---
permalink: sm-storage/actions-you-can-perform-on-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes 
summary: ボリュームに対しては、容量の拡張、削除、コピー、初期化、再配置、所有権の変更、キャッシュ設定の変更、メディアスキャン設定の変更など、さまざまな操作を実行できます。 
---
= ボリュームで実行できる操作
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームに対しては、容量の拡張、削除、コピー、初期化、再配置、所有権の変更、キャッシュ設定の変更、メディアスキャン設定の変更など、さまざまな操作を実行できます。



== 容量の拡張

ボリュームの容量は次の2つの方法で拡張できます。

* プールまたはボリュームグループの使用可能な空き容量を使用します。
+
ボリュームに容量を追加するには、メニューからStorage（Pool and Volume Groups）> Add Capacity（容量の追加）を選択します。

* ボリュームのプールまたはボリュームグループに未割り当て容量（未使用ドライブ）を追加します。このオプションは、プールまたはボリュームグループに空き容量がない場合に使用します。
+
プールまたはボリュームグループに未割り当て容量を追加するには、メニューからStorage（Pool and Volume Groups）> Add Capacity（容量の追加）を選択します。

+
プールまたはボリュームグループに使用可能な空き容量がない場合、ボリュームの容量を拡張することはできません。先にプールまたはボリュームグループのサイズを拡張するか、未使用のボリュームを削除する必要があります。



ボリュームの容量を拡張したら、それに応じてファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。



== 削除

ボリュームを削除する一般的な状況としては、作成したボリュームのパラメータや容量に誤りがあった場合、ストレージ構成のニーズを満たさなくなった場合、バックアップやアプリケーションのテストに必要なくなったSnapshotイメージがある場合などがあります。ボリュームを削除すると、プールまたはボリュームグループの空き容量が増えます。

ボリュームを削除すると、それらのボリューム上のすべてのデータが失われます。ボリュームを削除すると、関連付けられているSnapshotイメージ、スケジュール、Snapshotボリュームも削除され、ミラーリング関係も削除されます。



== コピー

ボリュームをコピーすると、ソースボリュームとターゲットボリュームの2つのボリュームのポイントインタイムコピーが同じストレージアレイ上に作成されます。ボリュームをコピーするには、メニューから「Storage [Volumes]> Copy Services > Copy volume」を選択します。



== 初期化

ボリュームを初期化すると、ボリュームからすべてのデータが消去されます。ボリュームは、最初に作成されたときに自動的に初期化されます。ただし、一定の障害状況からリカバリするために、ボリュームを手動で初期化するようRecovery Guruから指示される場合があります。ボリュームを初期化しても、ボリュームのWWN、ホストの割り当て、割り当て容量、およびリザーブ容量の設定は維持されます。Data Assurance（DA）設定とセキュリティ設定も同じままです。

ボリュームを初期化するには、メニューからStorage [Volumes]> More > Initialize volumesを選択します。



== 再配置

ボリュームの再配置は、ボリュームを優先コントローラ所有者に戻すために実行します。通常、ホストとストレージアレイの間のデータパスで問題が発生すると、マルチパスドライバによって優先コントローラ所有者からボリュームが移動されます。

ほとんどのホストマルチパスドライバは、優先コントローラ所有者へのパスで各ボリュームへのアクセスを試みます。ただし、この優先パスが使用できなくなった場合は、ホストのマルチパスドライバが代替パスにフェイルオーバーします。このフェイルオーバーによって、ボリューム所有権が代替コントローラに変更される可能性があります。フェイルオーバーの原因となった状況を解決すると、一部のホストではボリュームの所有権が優先コントローラ所有者に自動的に戻りますが、場合によっては手動でのボリュームの再配置が必要になります。

ボリュームを再配置するには、メニューを選択します。Storage [Volumes]>[More]> redistribute volumes ]



== ボリューム所有権の変更

ボリュームの所有権を変更すると、ボリュームの優先コントローラ所有権が変更されます。ボリュームの優先コントローラ所有者は、メニューの下に表示されます。Storage [Volumes]、[View/Edit Settings]、[Advanced]タブ

ボリュームの所有権を変更するには、メニューから次のいずれかを選択します。Storage [Volumes]、[More（その他）]、[Change ownership（所有権の変更）]。



=== ミラーリングとボリューム所有権

ミラーペアのプライマリボリュームがコントローラAに所有されている場合、セカンダリボリュームもリモートストレージアレイのコントローラAに所有されます。プライマリボリュームの所有者を変更すると、セカンダリボリュームの所有者が自動的に変更され、両方のボリュームが同じコントローラで所有されるようになります。プライマリ側で現在の所有権が変更されると、セカンダリ側の対応する所有権も自動的に変更されます。

ミラー整合性グループにローカルのセカンダリボリュームが含まれている場合にコントローラ所有権が変更されると、セカンダリボリュームは最初の書き込み処理時に自動的に元のコントローラ所有者に戻されます。所有権の変更*オプションを使用してセカンダリボリュームのコントローラ所有権を変更することはできません。



=== ボリュームのコピーとボリューム所有権

ボリュームのコピー処理では、ソースボリュームとターゲットボリュームの両方を同じコントローラが所有している必要があります。ボリュームコピー処理の開始時に、両方のボリュームの優先コントローラが同じでないことがあります。そのため、ターゲットボリュームの所有権がソースボリュームの優先コントローラに自動的に転送されます。ボリュームコピーが完了するか停止すると、ターゲットボリュームの所有権は優先コントローラにリストアされます。

ボリュームのコピー処理中にソースボリュームの所有権が変更された場合は、ターゲットボリュームの所有権も変更されます。特定のオペレーティングシステム環境では、I/Oパスを使用する前に、マルチパスホストドライバの再設定が必要になる場合があります。（一部のマルチパスドライバでは、I/Oパスを認識するために編集が必要です。詳細については、ドライバのマニュアルを参照してください）。



== キャッシュ設定の変更

キャッシュメモリは、ドライブメディアよりもアクセス時間が速い、コントローラ上の一時的な揮発性ストレージ（RAM）の領域です。キャッシュメモリを使用すると、次の理由により全体的なI/Oパフォーマンスを向上させることができます。

* 読み取り用にホストから要求されたデータは、以前の処理ですでにキャッシュに格納されている可能性があるため、ドライブにアクセスする必要はありません。
* 書き込みデータは最初にキャッシュに書き込まれるため、データがドライブに書き込まれるのを待つことなくアプリケーションが処理を続行できます。


メニューを選択します。Storage [Volumes]、[More（その他）]、[Change cache settings]（キャッシュ設定の変更）。次のキャッシュ設定を変更します。

* *読み取りキャッシュと書き込みキャッシュ*--読み取りキャッシュは'ドライブから読み取られたデータを格納するバッファです読み取り処理の対象となるデータが以前の処理ですでにキャッシュに格納されていれば、ドライブにアクセスする必要はありません。読み取りキャッシュのデータは、フラッシュされるまで保持されます。
+
書き込みキャッシュは、ドライブにまだ書き込まれていないホストからのデータを格納するバッファです。データは、ドライブに書き込まれるまで書き込みキャッシュに残ります。書き込みキャッシュにより、I/Oパフォーマンスを向上させることができます。

* *ミラーリングありの書き込みキャッシュ*--ミラーリングありの書き込みキャッシュは'一方のコントローラのキャッシュ・メモリに書き込まれたデータがもう一方のコントローラのキャッシュ・メモリにも書き込まれたときに発生しますそのため、一方のコントローラで障害が発生した場合、もう一方のコントローラで未処理の書き込み処理をすべて完了できます。書き込みキャッシュのミラーリングは、書き込みキャッシュが有効で、2台のコントローラが配置されている場合にのみ使用できます。ミラーリングありの書き込みキャッシュは、ボリュームの作成時にデフォルトで設定されます。
* *バッテリなしの書き込みキャッシュ*--バッテリなしの書き込みキャッシュ設定により、バッテリがない、故障している、完全に放電されている、またはフル充電されていない場合でも書き込みキャッシュを続行できます。バッテリなしの書き込みキャッシュを選択すると電源の喪失時にデータが失われる可能性があるため、一般には推奨されません。通常、書き込みキャッシュは、バッテリが充電されるか障害が発生したバッテリが交換されるまで、コントローラによって一時的にオフにされます。
+
この設定は、書き込みキャッシュを有効にしている場合にのみ使用できます。この設定はシンボリュームに対しては使用できません。

* *動的キャッシュ読み取りプリフェッチ*--動的キャッシュ読み取りプリフェッチにより'コントローラは'ドライブからキャッシュにデータ・ブロックを読み取っているときに'追加のシーケンシャル・データ・ブロックをキャッシュにコピーすることができますこのキャッシュにより、以降のデータ要求にキャッシュから対応できる可能性が高まります。動的キャッシュ読み取りプリフェッチは、シーケンシャルI/Oを使用するマルチメディアアプリケーションで重要です。データがキャッシュにプリフェッチされる速度と量は、ホスト読み取りの速度と要求サイズに基づいて自動で調整されます。ランダムアクセスでは、データがキャッシュにプリフェッチされることはありません。この機能は、読み取りキャッシュが無効になっている場合は適用されません。
+
動的キャッシュ読み取りプリフェッチはシンボリュームに対しては常に無効で、変更することはできません。





== メディアスキャン設定の変更

メディアスキャンは、アプリケーションで頻繁に読み取られないディスクブロック上のメディアエラーを検出して修復します。このスキャンを実行すると、プールまたはボリュームグループ内の他のドライブで障害が発生した場合に、障害ドライブのデータが冗長性情報とプールまたはボリュームグループ内の他のドライブのデータを使用して再構築されるため、データ損失が発生するのを防ぐことができます。

メディアスキャンは、スキャンする容量とスキャン期間に基づいて一定の速度で継続的に実行されます。優先度の高いバックグラウンドタスク（再構築など）によってバックグラウンドスキャンが一時的に中断されることはありますが、同じ速度で再開されます。

メディアスキャンの実行期間を有効にして設定するには、メニューを選択します。Storage [Volumes]、[More]、[Change media scan settings]の順に選択します。

ボリュームは、ストレージアレイとそのボリュームでメディアスキャンオプションが有効になっている場合にのみスキャンされます。そのボリュームに対して冗長性チェックも有効になっている場合、ボリュームに冗長性がある場合は、ボリューム内の冗長性情報がデータとの整合性がチェックされます。メディアスキャンと冗長性チェックは、ボリュームの作成時にデフォルトで有効になります。

スキャン中に回復不能なメディアエラーが発生した場合は、冗長性情報を使用してデータが修復されます（使用可能な場合）。たとえば、冗長性情報は、最適なRAID 5ボリューム、最適なRAID 6ボリューム、または1つのドライブだけで障害が発生したRAID 6ボリュームで確認できます。冗長性情報を使用してリカバリ不能なエラーを修復できない場合は、読み取り不能セクターのログにデータブロックが追加されます。イベントログには、修正可能なメディアエラーと修正不可能なメディアエラーの両方が記録されます。

冗長性チェックでデータと冗長性情報の間に不整合が検出されると、イベントログに報告されます。
