---
permalink: sm-storage/add-member-volumes-to-a-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, member, volume, snapshot consistency group 
summary: 既存のSnapshot整合性グループに新しいメンバーボリュームを追加できます。新しいメンバーボリュームを追加する場合は、そのメンバーボリュームの容量もリザーブする必要があります。 
---
= Snapshot整合性グループへのメンバーボリュームの追加
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のSnapshot整合性グループに新しいメンバーボリュームを追加できます。新しいメンバーボリュームを追加する場合は、そのメンバーボリュームの容量もリザーブする必要があります。

.開始する前に
* メンバーボリュームが最適lである必要があります。
* Snapshot整合性グループのボリューム数は、許容される最大ボリューム数（構成で定義）よりも少なくする必要があります。
* 各リザーブ容量ボリュームのData Assurance（DA）とセキュリティの設定は、関連付けられているメンバーボリュームと同じである必要があります。


.タスクの内容
Snapshot整合性グループには、標準ボリュームまたはシンボリュームを追加できます。ベースボリュームはプールまたはボリュームグループのいずれかに配置できます。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショット・コンシステンシ・グループ*タブを選択します
+
ストレージアレイに関連付けられているすべてのSnapshot整合性グループが表に表示されます。

. 変更するSnapshot整合性グループを選択し、*メンバーの追加*をクリックします。
+
メンバーの追加（Add Members）ダイアログボックスが表示されます。

. 追加するメンバーボリュームを選択し、*次へ*をクリックします。
+
[容量のリザーブ]手順が表示されます。[ボリューム候補]の表には、指定したリザーブ容量をサポートするボリュームだけが候補として表示されます。

. スピンボックスを使用して、メンバーボリュームにリザーブ容量を割り当てます。次のいずれかを実行します。
+
** *デフォルト設定を受け入れます。*
+
メンバーボリュームにデフォルトの設定でリザーブ容量を割り当てるには、このオプションを使用します（推奨）。

** *データストレージのニーズに合わせて独自の設定でリザーブ容量を割り当てることができます。*
+
デフォルトのリザーブ容量設定を変更した場合は、*候補の更新*をクリックして、指定したリザーブ容量の候補リストを更新します。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズ、およびSnapshotイメージを収集する数と期間によって異なります。




. [完了]をクリックして、メンバーボリュームを追加します。

