---
permalink: sm-storage/add-capacity-to-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, capacity, pool, volume, group 
summary: ドライブを追加して、既存のプールまたはボリュームグループの空き容量を拡張できます。 
---
= プールまたはボリュームグループへの容量の追加
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブを追加して、既存のプールまたはボリュームグループの空き容量を拡張できます。

拡張すると、プールまたはボリュームグループに追加の空き容量が含まれます。この空き容量を使用して、追加のボリュームを作成できます。この処理の実行中もボリューム内のデータには引き続きアクセスできます。

.開始する前に
* ドライブのステータスが最適lである必要があります。
* ドライブタイプ（HDDまたはSSD）が同じである必要があります。
* プールまたはボリュームグループのステータスが最適lである必要があります。
* ボリュームグループに含めることができるボリュームの最大数は256です。
* プールに含めることができるボリュームの最大数は、ストレージシステムのモデルによって異なります。
+
** 2、048ボリューム（EF600およびE5700シリーズ）
** 1、024ボリューム（EF300）
** 512（E2800シリーズ）


* プールまたはボリュームグループに含まれているドライブがすべてセキュリティ対応ドライブの場合は、セキュリティ対応ドライブの暗号化機能を引き続き使用するには、セキュリティ対応のドライブのみを追加してください。
+
セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。



.タスクの内容
プールに一度に追加できるドライブは最大60本です。ボリュームグループに一度に追加できるドライブは最大2本です。最大数を超えるドライブを追加する必要がある場合は、同じ手順を繰り返します。（プールにはストレージシステムの上限を超えるドライブを含めることはできません）。

[NOTE]
====
ドライブの追加に伴い、予約済み容量の引き上げが必要になる場合があります。拡張処理のあとにリザーブ容量を増やすことを検討してください。

====
[NOTE]
====
Data Assurance（DA）に対応していないプールまたはボリュームグループに容量を追加する場合は、DAに対応したドライブは使用しないでください。プールまたはボリュームグループでDA対応ドライブの機能を利用することはできません。DAに対応していないドライブの使用を検討してください。

====
.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. ドライブを追加するプールまたはボリュームグループを選択し、*容量の追加*をクリックします。
+
[容量の追加]ダイアログボックスが表示されます。プールまたはボリュームグループと互換性がある未割り当てのドライブのみが表示されます。

. ドライブの選択...*で、既存のプールまたはボリュームグループに追加するドライブを1つ以上選択します。
+
ドライブのリストは、より適した未割り当てのドライブから順に表示されます。プールまたはボリュームグループに追加された合計空き容量が、選択した合計容量*のリストの下に表示されます。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 製品説明 


 a| 
シェルフ
 a| 
ドライブのシェルフの場所を示します。



 a| 
ベイ
 a| 
ドライブのベイの場所を示します。



 a| 
容量（GiB）
 a| 
ドライブの容量を示します。

** 可能なかぎり、プールまたはボリュームグループ内の現在のドライブと同じ容量のドライブを選択してください。
** 容量が小さい未割り当てのドライブを追加する必要がある場合は、プールまたはボリュームグループに現在含まれている各ドライブの使用可能容量が削減されることに注意してください。したがって、ドライブ容量はプールまたはボリュームグループ全体で同じになります。
** 容量の大きい未割り当てドライブを追加する必要がある場合は、プールまたはボリュームグループ内のドライブの現在の容量に合わせて、追加する未割り当てドライブの使用可能容量が削減されることに注意してください。




 a| 
セキュリティ対応
 a| 
ドライブがセキュリティ対応かどうかを示します。

** プールまたはボリュームグループをドライブセキュリティ機能で保護するには、すべてのドライブがセキュリティ対応である必要があります。
** セキュリティ対応とセキュリティ対応でないドライブが混在したプールまたはボリュームグループを作成することは可能ですが、ドライブセキュリティ機能を有効にすることはできません。
** セキュリティ対応ドライブのみのプールまたはボリュームグループでは、暗号化機能を使用していなくても、スペアまたは拡張用にセキュリティ対応でないドライブを使用することはできません。
** セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。
** FIPSドライブにはレベル140-2または140-3を指定でき、レベル140-3が上位のセキュリティレベルです。140-2レベルと140-3レベルのドライブを混在させる場合、プールまたはボリュームグループは下位のセキュリティレベル（140-2）で動作します。




 a| 
DA 対応
 a| 
ドライブがData Assurance（DA）対応かどうかを示します。

** DAに対応していないドライブを使用してDAに対応したプールまたはボリュームグループに容量を追加することは推奨されません。プールまたはボリュームグループのDA機能は無効になり、プールまたはボリュームグループに新しく作成したボリュームでDAを有効にすることもできなくなります。
** Data Assurance（DA）対応のドライブを使用してDAに対応していないプールまたはボリュームグループに容量を追加することは推奨されません。プールまたはボリュームグループでDA対応ドライブの機能を利用できない（ドライブ属性が一致しない）ためです。DAに対応していないドライブの使用を検討してください。




 a| 
DULBE対応
 a| 
ドライブにDeallocated or Unwritten Logical Block Error（DULBE）に対応したオプションがあるかどうかを示します。DULBEはNVMeドライブのオプションです。このオプションを使用すると、EF300またはEF600ストレージアレイでリソースプロビジョニングボリュームをサポートできます。

|===
====
. [追加]*をクリックします。
+
プールまたはボリュームグループにドライブを追加する場合は、プールまたはボリュームグループの次の属性が無効になるドライブを選択すると、確認のダイアログボックスが表示されます。

+
** シェルフ損失の保護^*^
** ドロワー損失の保護^*^
** Full Disk Encryption機能
** Data Assurance機能
** DULBE機能





NOTE: ^*^現在、シェルフ損失の保護またはドロワー損失の保護が有効なプールにドライブを追加する場合、確認のダイアログボックスは表示されません。

. 続行するには、[はい]をクリックします。それ以外の場合は、[キャンセル]をクリックします。


.結果
プールまたはボリュームグループに未割り当てのドライブを追加すると、プールまたはボリュームグループの各ボリューム内のデータが再配置されて追加のドライブが追加されます。
