---
permalink: sm-storage/assign-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign volumes 
summary: I/O処理に使用できるように、ボリュームをホストまたはホストクラスタに割り当てる必要があります。これにより、ストレージアレイ内の1つ以上のボリュームへのアクセスがホストまたはホストクラスタに許可されます。 
---
= ホストへのボリュームの割り当て
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I/O処理に使用できるように、ボリュームをホストまたはホストクラスタに割り当てる必要があります。これにより、ストレージアレイ内の1つ以上のボリュームへのアクセスがホストまたはホストクラスタに許可されます。

.タスクの内容
ホストにボリュームを割り当てる際は、次のガイドラインに注意してください。

* ボリュームは一度に1つのホストまたはホストクラスタにのみ割り当てることができます。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* 1つのホストまたはホストクラスタが、同じ論理ユニット番号（LUN）を2回使用してボリュームにアクセスすることはできません。一意のLUNを使用する必要があります。
* 新しいボリュームグループの場合、すべてのボリュームが作成されて初期化されてからホストに割り当てると、ボリュームの初期化時間が短縮されます。ボリュームグループに関連付けられているボリュームをマッピングすると、_ALL_VOLUMESを使用すると、初期化の速度が遅くなります。初期化の進捗状況は、ホーム[処理実行中]メニューから確認できます。


次の場合、ボリュームの割り当ては失敗します。

* すべてのボリュームが割り当てられている。
* ボリュームはすでに別のホストまたはホストクラスタに割り当てられています。


次の場合、ボリュームを割り当てることはできません。

* 有効なホストまたはホストクラスタが存在しません。
* ホストにホストポート識別子が定義されていません。
* すべてのボリューム割り当てが定義されている。


このタスクでは未割り当てのボリュームがすべて表示されますが、ホストにData Assurance（DA）があるかどうかは次のようになります。

* DA対応ホストの場合は、DAが有効なボリュームとDAが有効でないボリュームを選択できます。
* DA対応でないホストでDAが有効なボリュームを選択すると、ボリュームをホストに割り当てる前にボリュームのDAを自動的にオフにする必要があることを示す警告が表示されます。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. ボリュームを割り当てるホストまたはホストクラスタを選択し、 * ボリュームの割り当て * をクリックします。
+
ダイアログボックスに、割り当て可能なすべてのボリュームが表示されます。任意の列をソートしたり、 * Filter * ボックスに何かを入力すると、特定のボリュームを簡単に見つけることができます。

. 割り当てる各ボリュームの横にあるチェックボックスを選択するか、テーブルヘッダーのチェックボックスを選択してすべてのボリュームを選択します。
. [*Assign*] をクリックして、操作を完了します。


.結果
ホストまたはホストクラスタへのボリュームの割り当てが完了すると、次の処理が実行されます。

* 割り当てられたボリュームに、次に使用可能なLUN番号が割り当てられます。ホストはこのLUN番号を使用してボリュームにアクセスします。
* ホストに関連付けられているボリュームの一覧にユーザが指定したボリューム名が表示されます。該当する場合は、ホストに関連付けられているボリュームの一覧に、工場出荷時に設定されたアクセスボリュームも表示されます。

