---
permalink: sm-storage/assign-hot-spares-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign hot spares 
summary: RAID 1、RAID 5、またはRAID 6のボリュームグループでは、ホットスペアを追加データ保護のスタンバイドライブとして割り当てることができます。これらのボリュームグループのいずれかでドライブに障害が発生すると、コントローラは障害が発生したドライブのデータをホットスペアに再構築します。 
---
= ホットスペアの割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RAID 1、RAID 5、またはRAID 6のボリュームグループでは、ホットスペアを追加データ保護のスタンバイドライブとして割り当てることができます。これらのボリュームグループのいずれかでドライブに障害が発生すると、コントローラは障害が発生したドライブのデータをホットスペアに再構築します。

.開始する前に
* RAID 1、RAID 5、またはRAID 6のボリュームグループを作成する必要があります。（ホットスペアはプールには使用できません。プールでは、データ保護用に各ドライブ内のスペア容量を使用します）。
* 次の条件を満たすドライブが使用可能な必要があります。
+
** 未割り当てで最適ステータス
** ボリュームグループ内のドライブと同じメディアタイプ（SSDなど）。
** ボリュームグループ内のドライブと同じインターフェイスタイプ（SASなど）。
** ボリュームグループ内のドライブの使用容量以上の容量。




.タスクの内容
このタスクでは、[ハードウェア]ページからホットスペアを手動で割り当てる方法について説明します。推奨されるカバレッジは、ドライブセットごとに2つのホットスペアです。

[CAUTION]
====
ホットスペアは初期セットアップウィザードから割り当てることもできます。ホットスペアがすでに割り当てられているかどうかは、[ハードウェア]ページでピンクで表示されるドライブベイで確認できます。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示された場合は、*[ドライブ]*タブをクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. ホットスペアとして使用する未割り当てのドライブ（グレーで表示）を選択します。
+
ドライブのコンテキストメニューが開きます。

. [ホットスペアの割り当て]を選択します。
+
ドライブがセキュリティ有効の場合は、* Secure Erase Drive *（ドライブのSecure Erase *）ダイアログボックスが開きます。セキュリティ有効ドライブをホットスペアとして使用するには、まず完全消去処理を実行してドライブのすべてのデータを削除し、セキュリティ属性をリセットする必要があります。

+
[CAUTION]
====
*データ損失の可能性*--正しいドライブを選択していることを確認してください完全消去処理が完了すると、どのデータもリカバリできなくなります。

====
+
ドライブが*セキュア有効でない場合は、ホットスペアドライブの割り当ての確認ダイアログボックスが開きます。

. ダイアログボックスのテキストを確認し、処理を確定します。
+
[ハードウェア]ページには、ホットスペアになったドライブがピンクで表示されます。





== 結果

RAID 1、RAID 5、またはRAID 6のボリュームグループ内のドライブで障害が発生した場合、コントローラは冗長性データを使用して、障害が発生したドライブからホットスペアにデータを自動的に再構築します。
