---
permalink: sm-storage/automatic-versus-manual-pool-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, pool 
summary: プールを自動または手動で作成して物理ストレージをグループ化し、必要に応じて動的に割り当てることができます。プールを作成すると、物理ドライブを追加できます。 
---
= プールの自動作成と手動作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールを自動または手動で作成して物理ストレージをグループ化し、必要に応じて動的に割り当てることができます。プールを作成すると、物理ドライブを追加できます。



== 自動作成

プールの自動作成は、System Managerがストレージアレイ内に未割り当て容量を検出すると開始されます。未割り当て容量が検出されると、プールを作成するか、未割り当て容量を既存のプールに追加するか、またはその両方を行うようにSystem Managerから自動的に要求されます。

プールの自動作成は、次のいずれかの条件に該当する場合に実行されます。

* プールがストレージアレイに存在せず、新しいプールを作成するのに十分な数のドライブがあります。
* 少なくとも1つのプールを含むストレージアレイに新しいドライブが追加される。


プール内の各ドライブは、ドライブタイプ（HDDまたはSSD）が同じで、容量がほぼ同じである必要があります。System Managerでは、次のタスクを実行するように求められます。

* 同じタイプの十分な数のドライブがある場合は、単一のプールを作成します。
* 未割り当て容量が異なるドライブタイプで構成されている場合は、複数のプールを作成します。
* ストレージアレイでプールが定義済みの場合は既存のプールにドライブを追加し、同じドライブタイプの新しいドライブをプールに追加します。
* ドライブタイプが同じドライブを既存のプールに追加します。新しいドライブタイプが異なる場合は、他のドライブタイプを使用して別のプールを作成します。




== 手動作成

最適な構成を自動作成で判断できない場合は、プールを手動で作成できます。この状況は、次のいずれかの理由で発生する可能性があります。

* 新しいドライブが複数のプールに追加される可能性があります。
* 1つ以上の新しいプールの候補で、シェルフ損失の保護またはドロワー損失の保護を使用できます。
* 1つ以上の現在のプールの候補で、シェルフ損失の保護またはドロワー損失の保護のステータスを維持できない。


ストレージアレイ上の複数のアプリケーションが同じドライブリソースを競合しないようにする場合は、プールを手動で作成することもできます。この場合は、1つ以上のアプリケーション用に小規模なプールを手動で作成することを検討してください。データを分散する多数のボリュームを含む大規模なプールにワークロードを割り当てる代わりに、1~2個のボリュームだけを割り当てることができます。特定のアプリケーションのワークロード専用の個別のプールを手動で作成すると、ストレージアレイの処理をより迅速に実行し、競合を軽減できます。
