---
permalink: sm-storage/cancel-snapshot-image-rollback.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cancel, snapshot, image, rollback 
summary: 進行中のアクティブなロールバック（データのアクティブなコピー）、保留中のロールバック（リソースの開始を待機している保留キュー内）、またはエラーによって一時停止されたロールバックをキャンセルできます。 
---
= Snapshotイメージのロールバックのキャンセル
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
進行中のアクティブなロールバック（データのアクティブなコピー）、保留中のロールバック（リソースの開始を待機している保留キュー内）、またはエラーによって一時停止されたロールバックをキャンセルできます。

.タスクの内容
実行中のロールバック処理をキャンセルすると、ベースボリュームは使用できない状態に戻り、「失敗」と表示されます。したがって、ベースボリュームの内容をリストアするためのリカバリオプションがある場合にのみロールバック処理をキャンセルすることを検討してください。

[NOTE]
====
Snapshotグループに含まれている1つ以上のSnapshotイメージが自動的にパージされた場合は、ロールバック処理に使用されるSnapshotイメージを今後のロールバックで使用できなくなる可能性があります。

====
.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットイメージ*タブをクリックします。
. アクティブまたは一時停止中のロールバックを選択し、メニューからロールバック[キャンセル]を選択します。
+
[ロールバックのキャンセルの確認]ダイアログボックスが表示されます。

. 「 * はい * 」をクリックして確定します。


.結果
System Managerがロールバック処理を停止します。ベースボリュームは使用可能ですが、データに整合性がないか完全でない可能性があります。

.終了後
ロールバック処理をキャンセルしたら、次のいずれかの操作を実行する必要があります。

* ベースボリュームの内容を再初期化します。
* 新しいロールバック処理を実行して、ロールバックのキャンセル処理と同じSnapshotイメージまたは別のSnapshotイメージを使用してベースボリュームをリストアします。

