---
permalink: sm-storage/capacity-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, volumes, 
summary: ストレージアレイ内のドライブは、データの物理ストレージ容量を提供します。データの格納を開始する前に、プールまたはボリュームグループと呼ばれる論理コンポーネントに割り当て容量を設定する必要があります。これらのストレージオブジェクトは、ストレージアレイのデータの設定、格納、保守、保持に使用します。 
---
= ボリュームの容量の割り当て方法
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ内のドライブは、データの物理ストレージ容量を提供します。データの格納を開始する前に、プールまたはボリュームグループと呼ばれる論理コンポーネントに割り当て容量を設定する必要があります。これらのストレージオブジェクトは、ストレージアレイのデータの設定、格納、保守、保持に使用します。



== 容量を使用したボリュームの作成と拡張

ボリュームは、プールまたはボリュームグループ内の未割り当て容量または空き容量から作成できます。

* 未割り当て容量からボリュームを作成する場合は、プールまたはボリュームグループとボリュームを同時に作成できます。
* 空き容量からボリュームを作成する場合は、既存のプールまたはボリュームグループに追加のボリュームを作成します。


ボリュームの容量を拡張したら、それに応じてファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。



== シックボリュームとシンボリュームの容量タイプ

シックボリュームまたはシンボリュームを作成できます。レポート容量と割り当て容量はシックボリュームでは同じですが、シンボリュームでは異なります。

* シックボリュームの場合、ボリュームのレポート容量は割り当てられている物理ストレージ容量と同じになります。物理ストレージ容量全体が存在している必要があります。物理的に割り当てられたスペースは、ホストに報告されるスペースと同じです。
+
通常、シックボリュームのレポート容量は、ボリュームが拡張されると予想される最大容量に設定します。シックボリュームは、予測可能な高パフォーマンスをアプリケーションに提供します。これは主に、すべてのユーザ容量が作成時に予約されて割り当てられるためです。

* シンボリュームの場合、レポート容量はホストに報告される容量であり、割り当て容量はデータの書き込み用に現在割り当てられているドライブスペースの量です。
+
レポート容量は、ストレージアレイで割り当てられた容量よりも大きくなることがあります。シンボリュームは、現在使用可能な資産に関係なく、拡張に応じてサイズを設定できます。



[NOTE]
====
SANtricity System Managerには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====


== シックボリュームの容量制限

シックボリュームの最小容量は1MiBで、最大容量はプールまたはボリュームグループ内のドライブの数と容量で決まります。

シックボリュームのレポート容量を拡張する場合は、次のガイドラインに注意してください。

* 小数点以下3桁まで指定できます（例：65.375GiB）。
* ボリュームグループで使用可能な最大容量以下の容量を指定する必要があります。
+
ボリュームを作成すると、セグメントサイズの動的変更（DSS）用に追加の容量が事前に割り当てられます。DSS移行は、ボリュームのセグメントサイズを変更できるソフトウェアの機能です。

* 一部のホストオペレーティングシステムでは2TiBを超えるボリュームがサポートされます（最大レポート容量はホストオペレーティングシステムで決定されます）。実際、一部のホストオペレーティングシステムでは、最大128TiBのボリュームがサポートされます。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。




== シンボリュームの容量制限

レポート容量が大きく、割り当て容量が比較的小さいシンボリュームを作成できます。これは、ストレージの利用率と効率を高めるのに役立ちます。シンボリュームを使用すると、アプリケーションの中断を伴わずにアプリケーションのニーズの変化に応じて割り当て容量を増やすことができるため、ストレージ管理が簡易化され、ストレージ利用率が向上します。

シンボリュームには、レポート容量と割り当て容量に加えて、書き込み済み容量も含まれます。書き込み済み容量は、シンボリュームに割り当てられたリザーブ容量のうちの書き込み済みの容量です。

次の表に、シンボリュームの容量制限を示します。

[cols="3*"]
|===
| 容量のタイプ | 最小サイズ | 最大サイズ 


 a| 
レポート済み
 a| 
32MiB
 a| 
256 TiB



 a| 
割り当て済み
 a| 
4MiB
 a| 
64TiB

|===
シンボリュームの場合、最大レポート容量の256TiBに達していると容量を拡張できません。シンボリュームのリザーブ容量が最大レポート容量よりも大きいサイズに設定されていることを確認してください。

割り当て容量は、割り当て容量の制限に基づいて自動的に拡張されます。割り当て容量の制限を使用すると、シンボリュームの自動拡張をレポート容量未満に制限できます。書き込まれるデータの量が割り当て容量に近付いたときは、割り当て容量の制限を変更することができます。

割り当て容量の制限を変更するには、メニューを選択します。Storage [Volumes]> Thin Volume Monitoringタブ> Change Limit]

System Managerでは、シンボリュームの作成時にフル容量を割り当てないため、プールの空き容量が不足する可能性があります。スペースが不足していると、シンボリュームだけでなく、プールの容量を必要とするその他の処理（SnapshotイメージやSnapshotボリュームなど）でもプールへの書き込みがブロックされる可能性があります。ただし、プールからの読み取り処理は引き続き実行できます。この状況が発生すると、アラートしきい値の警告が表示されます。
