---
permalink: sm-storage/change-the-settings-for-a-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, schedule 
summary: Snapshotスケジュールでは、自動収集時間または収集の頻度を変更できます。 
---
= Snapshotスケジュールの設定の変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotスケジュールでは、自動収集時間または収集の頻度を変更できます。

.タスクの内容
既存のSnapshotスケジュールから設定をインポートするか、必要に応じて設定を変更できます。

SnapshotスケジュールはSnapshotグループまたはSnapshot整合性グループに関連付けられているため、スケジュールの設定を変更するとリザーブ容量に影響を及ぼす場合があります。

.手順
. メニューを選択します。Storage [Snapshots]。
. [* Schedules *（スケジュール*）]タブをクリックします
. 変更するSnapshotスケジュールを選択し、* Edit *をクリックします。
+
Edit Snapshot Schedule（スナップショットスケジュールの編集）ダイアログボックスが表示されます。

. 次のいずれかを実行します。
+
** *別のスナップショットオブジェクトから以前に定義したスケジュールを使用する*--*スケジュールのインポート*をクリックし、インポートするスケジュールのあるオブジェクトを選択して、*インポート*をクリックします。
** *スケジュール設定を編集*--下記のフィールド詳細を参照してください。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
日/月
 a| 
次のいずれかのオプションを選択します。

*** *毎日/毎週*--同期スナップショットの個々の曜日を選択します日次スケジュールを設定する場合は、右上の[すべての日を選択]チェックボックスをオンにすることもできます。
*** *毎月/毎年*--同期スナップショットの個々の月を選択します[* on day(s)*]フィールドに、同期を実行する月の日を入力します。有効なエントリは* 1 ~* 31 *および* Last *です。複数の日にちをカンマまたはセミコロンで区切ることができます。日にちの範囲を入力するには、ハイフンを使用します。たとえば、「1、3、4」、「10-15」、「Last」のようになります。月単位のスケジュールを設定する場合は、右上の[すべての月を選択]チェックボックスをオンにすることもできます。




 a| 
開始時刻
 a| 
ドロップダウンリストから、日単位のSnapshotの新しい開始時刻を選択します。30分単位で選択できます。デフォルトでは、開始時刻は現在時刻の30分前に設定されます。



 a| 
タイムゾーン
 a| 
ドロップダウンリストから、ストレージアレイのタイムゾーンを選択します。



 a| 
1日あたりのSnapshot数

Snapshotの作成間隔
 a| 
1日に作成するSnapshotイメージの数を選択します。

複数を選択した場合は、復元ポイント間の時間も選択します。複数のリストアポイントを使用する場合は、十分なリザーブ容量があることを確認してください。



 a| 
開始日

終了日

終了日なし
 a| 
同期の開始日を入力します。終了日を入力するか、「*終了日なし*」を選択してください。

|===
====


. [ 保存（ Save ） ] をクリックします。

