---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: ボリュームの名前、ホストの割り当て、セグメントサイズ、変更の優先順位、キャッシュなど、ボリュームの設定を変更できます。 など。 
---
= ボリュームの設定の変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
名前、ホストの割り当て、セグメントサイズ、変更の優先順位、キャッシュなど、ボリュームの設定を変更できます。

.開始する前に
変更するボリュームのステータスは「最適」である必要があります。


NOTE: ボリューム設定の変更の実行中は、一部の処理を使用できない可能性があります

.手順
. 選択メニュー： Storage [Volumes]
. 変更するボリュームを選択し、*表示/設定の編集*を選択します。
+
[Volume Settings]ダイアログボックスが表示されます。選択したボリュームの設定がこのダイアログボックスに表示されます。

. ボリュームの名前とホストの割り当てを変更するには、* Basic *タブを選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
名前
 a| 
ボリュームの名前が表示されます。現在の名前が適切でない場合はボリュームの名前を変更します。



 a| 
容量
 a| 
選択したボリュームのレポート容量と割り当て容量が表示されます。

レポート容量と割り当て容量はシックボリュームでは同じですが、シンボリュームでは異なります。シックボリュームの場合、物理的に割り当てられたスペースは、ホストに報告されるスペースと同じになります。シンボリュームの場合、レポート容量はホストに報告される容量であり、割り当て容量はデータの書き込み用に現在割り当てられているドライブスペースの量です。



 a| 
プール/ボリュームグループ
 a| 
プールまたはボリュームグループの名前とRAIDレベルが表示されます。プールまたはボリュームグループがセキュリティ対応か、セキュリティ有効かを示します。



 a| 
ホスト
 a| 
ボリュームの割り当てが表示されます。I/O処理でボリュームにアクセスできるように、ボリュームをホストまたはホストクラスタに割り当てます。これにより、ストレージアレイ内の特定のボリュームまたは複数のボリュームへのアクセスがホストまたはホストクラスタに許可されます。

** *割り当て先*--選択したボリュームにアクセスできるホストまたはホストクラスタを指定します
** * lun *：ホストがボリュームへのアクセスに使用するアドレス・スペースに割り当てられる番号ボリュームは、LUNの形式で容量としてホストに提示されます。各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを異なるホストで使用して、異なるボリュームにアクセスできます。
+

NOTE: NVMeインターフェイスの場合、この列にはネームスペースIDが表示されます。ネームスペースは、ブロックアクセス用にフォーマットされたNVMストレージです。SCSIの論理ユニットに相当し、ストレージアレイ内のボリュームに関連します。ネームスペースIDは、NVMeコントローラのネームスペースに対する一意の識別子で、1~255の値を設定できます。SCSIの論理ユニット番号（LUN）に相当します。





 a| 
識別子
 a| 
選択したボリュームの識別子が表示されます。

** * World-Wide Identifier（WWID）*-ボリュームの一意な16進数の識別子。
** * Extended Unique Identifier（EUI）*--ボリュームの識別子EUI-64。
** *サブシステム識別子(SSID)*--ボリュームのストレージアレイサブシステム識別子。


|===
====
. プールまたはボリュームグループ内のボリュームの追加設定を変更するには、*詳細*タブを選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
アプリケーションとワークロードの情報
 a| 
ボリュームの作成時に、アプリケーション固有のワークロードまたはその他のワークロードを作成できます。該当する場合は、選択したボリュームのワークロード名、アプリケーションタイプ、およびボリュームタイプが表示されます。

ワークロード名は必要に応じて変更できます。



 a| 
サービス品質の設定
 a| 
* Data Assuranceを永続的に無効にする*-この設定は、ボリュームがData Assurance（DA）対応の場合にのみ表示されます。DAは、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。選択したボリュームのDAを完全に無効にする場合は、このオプションを使用します。DAを無効にすると、このボリュームで再度有効にすることはできません。

*読み取り前冗長性チェックを有効にする*--この設定は'ボリュームがシックボリュームの場合にのみ表示されます読み取り前冗長性チェックは、読み取りの実行時にボリュームのデータの整合性を確認する機能です。この機能が有効になっているボリュームでは、コントローラファームウェアでデータの整合性が確保されていないと判断されると、読み取りエラーが返されます。



 a| 
コントローラ所有権
 a| 
ボリュームを所有するプライマリコントローラを定義します。

コントローラ所有権は非常に重要であり、慎重に計画する必要があります。コントローラは、I/O全体でできるだけバランスよく配置する必要があります。



 a| 
セグメントサイジング
 a| 
セグメントサイジングの設定が表示されます。これは、ボリュームグループ内のボリュームについてのみ表示されます。セグメントサイズを変更してパフォーマンスを最適化できます。

*許容される変更後のセグメントサイズ*-許容される変更後のセグメントサイズがSystem Managerで判別されます。現在のセグメントサイズからの移行に適していないセグメントサイズは、ドロップダウンリストに表示されません。通常、許容されるトランジションは、現在のセグメントサイズの2倍または半分です。たとえば、ボリュームの現在のセグメントサイズが32KiBの場合は、16KiBまたは64KiBの新しいボリュームセグメントサイズが許可されます。

* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiBのセグメントサイズを選択するのは、SSDキャッシュが有効なボリュームで小さいブロックのI/O処理（I/Oブロックサイズが16KiB以下など）を処理する場合のみにしてください。SSDキャッシュが有効なボリュームで大容量ブロックのシーケンシャル処理を処理する場合、セグメントサイズとして4KiBを選択するとパフォーマンスが低下することがあります。

*セグメントサイズの変更にかかる時間*-ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

** ホストからのI/O負荷
** ボリュームの修正の優先順位
** ボリュームグループ内のドライブ数
** ドライブチャネルの数
** ストレージアレイコントローラの処理能力：ボリュームのセグメントサイズを変更すると、I/Oパフォーマンスに影響しますが、データの可用性は維持されます。




 a| 
修正の優先順位
 a| 
修正の優先度に関する設定が表示されます。この設定は、ボリュームグループ内のボリュームに対してのみ表示されます。

変更の優先度は、ボリューム変更処理に割り当てる処理時間を、システムパフォーマンスに対する相対的な割合で定義します。変更の優先度を上げることができますが、システムパフォーマンスに影響する可能性があります。

スライダバーを移動して優先度レベルを選択します。

*修正の優先順位率*--優先順位が最も低いとシステムのパフォーマンスは向上しますが、修正操作にかかる時間は長くなります。優先度を最も高くすると変更処理には影響しますが、システムパフォーマンスが低下する可能性があります。



 a| 
キャッシュ
 a| 
キャッシュ設定が表示されます。キャッシュ設定は、ボリュームの全体的なI/Oパフォーマンスに影響するように変更できます。



 a| 
SSD キャッシュ
 a| 
SSDキャッシュの設定が表示されます。互換性のあるボリュームでこの設定を有効にすると、読み取り専用のパフォーマンスが向上します。ドライブセキュリティとData Assuranceの設定が同じボリュームは互換性があります。

* SSDキャッシュ機能は、1つまたは複数のソリッドステートディスク（SSD）を使用して読み取りキャッシュ*を実装します。SSDの読み取り時間が短縮されるため、アプリケーションのパフォーマンスが向上します。読み取りキャッシュはストレージアレイにあるため、ストレージアレイを使用するすべてのアプリケーションでキャッシュが共有されます。キャッシュするボリュームを選択すると、あとは動的に自動でキャッシングが実行されます。

|===
====
. [ 保存（ Save ） ] をクリックします。
+
選択内容に基づいて、System Managerがボリュームの設定を変更します。



.終了後
選択したボリュームで現在実行されている変更処理の進捗状況を表示するには、[MENU]：[View Operations in Progress]を選択します。
