---
permalink: sm-storage/change-allocated-capacity-limit-for-a-thin-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, allocated capacity, thin volume 
summary: オンデマンドでスペースを割り当てることができるシンボリュームでは、シンボリュームを自動的に拡張できる割り当て容量の制限を変更できます。 
---
= シンボリュームの割り当て容量制限の変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オンデマンドでスペースを割り当てることができるシンボリュームでは、シンボリュームを自動的に拡張できる割り当て容量の制限を変更できます。

シンボリュームが割り当て容量の制限に近づいたときに[ホーム]ページの[通知]領域にアラート（警告しきい値の超過）が送信される割合を変更することもできます。このアラート通知を有効にするか無効にするかを選択できます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
割り当て容量は、割り当て容量の制限に基づいて自動的に拡張されます。割り当て容量の制限を使用すると、シンボリュームの自動拡張をレポート容量未満に制限できます。書き込まれるデータの量が割り当て容量に近付いたときは、割り当て容量の制限を変更することができます。

シンボリュームの割り当て容量の制限と警告しきい値を変更する場合は、ボリュームのユーザデータとコピーサービスデータの両方で消費されるスペースを考慮する必要があります。

.手順
. 選択メニュー： Storage [Volumes]
. [* Thin Volume Monitoring]タブを選択します。
+
シンボリュームの監視ビューが表示されます。

. 変更するシンボリュームを選択し、*制限の変更*を選択します。
+
[制限の変更]ダイアログボックスが表示されます。選択したシンボリュームの割り当て容量の制限と警告しきい値の設定がこのダイアログボックスに表示されます。

. 割り当て容量の制限と警告しきい値を必要に応じて変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
割り当て容量の制限を変更...
 a| 
書き込みが失敗し、シンボリュームが追加のリソースを消費しないようにするしきい値。このしきい値は、ボリュームのレポート容量サイズの割合です。



 a| 
アラートを受け取るタイミング...（警告しきい値）
 a| 
シンボリュームが割り当て容量の制限に近づいたときにシステムでアラートを生成する場合は、このチェックボックスを選択します。アラートが[ホーム]ページの[通知]領域に送信されます。このしきい値は、ボリュームのレポート容量サイズの割合です。

警告しきい値のアラート通知を無効にするには、このチェックボックスをオフにします。

|===
====
. [ 保存（ Save ） ] をクリックします。

