---
permalink: sm-storage/change-ssd-cache-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd, cache, settings 
summary: SSDキャッシュの名前を編集して、ステータス、最大容量と現在の容量、ドライブセキュリティとData Assuranceのステータス、および関連付けられているボリュームとドライブを確認できます。 
---
= SSDキャッシュ設定の変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュの名前を編集して、ステータス、最大容量と現在の容量、ドライブセキュリティとData Assuranceのステータス、および関連付けられているボリュームとドライブを確認できます。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 編集するSSDキャッシュを選択し、*表示/設定の編集*をクリックします。
+
[SSDキャッシュ設定]ダイアログボックスが表示されます。

. SSDキャッシュ設定を確認するか、必要に応じて編集します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
名前
 a| 
SSDキャッシュの名前が表示されます。この名前は変更できます。SSDキャッシュの名前は必須です。



 a| 
特性
 a| 
SSDキャッシュのステータスが表示されます。ステータスは次のいずれかです。

** 最適
** 不明
** デグレード
** 失敗（重大なMELイベントが生成されます）
** 中断




 a| 
容量
 a| 
SSDキャッシュの現在の容量と許容される最大容量が表示されます。

SSDキャッシュの最大容量は、コントローラのプライマリキャッシュサイズによって異なります。

** 1 GiB以下
** 1GiBから2GiB
** 2GiBから4GiB
** 4 GiB超




 a| 
セキュリティとDA
 a| 
SSDキャッシュのドライブセキュリティとData Assuranceのステータスが表示されます。

** *セキュリティ対応*-- SSDキャッシュがセキュリティ対応ドライブだけで構成されているかどうかを示しますセキュリティ対応ドライブは、データへの不正アクセスを防止できる自己暗号化ドライブです。
** * Secure-enabled *- SSDキャッシュでセキュリティが有効になっているかどうかを示します。
** *DA Capable *-- SSDキャッシュがDA対応ドライブだけで構成されているかどうかを示しますDA対応ドライブでは、ホストとストレージアレイの間でデータをやり取りするときに発生する可能性があるエラーをチェックして修正できます。




 a| 
関連付けられているオブジェクト
 a| 
SSDキャッシュに関連付けられているボリュームとドライブが表示されます。

|===
====
. [ 保存（ Save ） ] をクリックします。

