---
permalink: sm-storage/check-volume-redundancy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, check, volume, redundancy 
summary: テクニカルサポートから指示があった場合、またはRecovery Guruに記載されている場合は、プールまたはボリュームグループ内のボリュームの冗長性をチェックして、そのボリュームのデータに整合性があるかどうかを確認できます。冗長性データは、プールまたはボリュームグループ内のいずれかのドライブで障害が発生した場合に、交換用ドライブに迅速に情報を再構築するために使用されます。 
---
= ボリュームの冗長性チェック
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テクニカルサポートから指示があった場合、またはRecovery Guruに記載されている場合は、プールまたはボリュームグループ内のボリュームの冗長性をチェックして、そのボリュームのデータに整合性があるかどうかを確認できます。

冗長性データは、プールまたはボリュームグループ内のいずれかのドライブで障害が発生した場合に、交換用ドライブに迅速に情報を再構築するために使用されます。

.開始する前に
* プールまたはボリュームグループのステータスが最適である必要があります。
* プールまたはボリュームグループで実行中のボリューム変更処理がないことを確認します。
* RAID 0にはデータの冗長性がないため、RAID 0以外のどのRAIDレベルでも冗長性をチェックできます。


[NOTE]
====
ボリュームの冗長性チェックは、Recovery Guruに記載されている場合にのみ、テクニカルサポートの指示に従って実行してください。

====
.タスクの内容
このチェックは一度に1つのプールまたはボリュームグループでのみ実行できます。ボリュームの冗長性チェックでは、次の処理が実行されます。

* RAID 3ボリューム、RAID 5ボリューム、またはRAID 6ボリュームのデータブロックをスキャンし、各ブロックの冗長性情報をチェックします。（RAID 3をボリュームグループに割り当てるには、コマンドラインインターフェイスを使用する必要があります）。
* は、RAID 1ミラードライブ上のデータブロックを比較します。
* コントローラファームウェアがデータに整合性がないと判断した場合は、冗長性エラーを返します。


[NOTE]
====
同じプールまたはボリュームグループですぐに冗長性チェックを実行すると、エラーが発生することがあります。この問題を回避するには、同じプールまたはボリュームグループで別の冗長性チェックを実行する前に、1~2分待ってください。

====
.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニューから[一般的でないタスク]を選択します。[ボリュームの冗長性をチェック]。
+
[Check Redundancy]ダイアログボックスが表示されます。

. 確認するボリュームを選択し、と入力して `check`この処理を実行します。
. [*チェック（Check）]をクリックする。
+
ボリュームの冗長性チェック処理が開始されます。プールまたはボリュームグループ内のボリュームが、ダイアログボックスのテーブルの一番上から順番にスキャンされます。各ボリュームがスキャンされると、次の処理が実行されます。

+
** ボリュームテーブルでボリュームが選択されます。
** 冗長性チェックのステータスは、*Status*列に表示されます。
** メディアエラーまたはパリティエラーが発生すると、チェックが停止し、エラーが報告されます。
+
.冗長性チェックのステータスの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| ステータス | 製品説明 


 a| 
保留中
 a| 
これは最初にスキャンされるボリュームであり、冗長性チェックを開始するために[Start]をクリックしていません。

または

プールまたはボリュームグループ内の他のボリュームで冗長性チェック処理を実行中です。



 a| 
カクニン
 a| 
ボリュームは冗長性チェック中です。



 a| 
合格
 a| 
ボリュームは冗長性チェックにパスしました。冗長性情報に不整合は見つかりませんでした。



 a| 
失敗
 a| 
ボリュームは冗長性チェックに失敗しました。冗長性情報に不整合が見つかりました。



 a| 
メディアエラー
 a| 
ドライブメディアが故障しており、読み取りできません。Recovery Guruに表示される手順に従います。



 a| 
パリティエラー
 a| 
データの一部でパリティが想定される値ではありません。パリティエラーは重大な問題であり、データが永久に失われる可能性があります。

|===
====


. プールまたはボリュームグループ内の最後のボリュームをチェックした後、「* Done *」をクリックします。

