---
permalink: sm-storage/comparison-between-thick-volumes-and-thin-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, comparison, thick volumes, thin volumes 
summary: シックボリュームは常にフルプロビジョニングされます。つまり、ボリュームの作成時にすべての容量が割り当てられます。シンボリュームは常にシンプロビジョニングされます。つまり、ボリュームにデータが書き込まれるときに容量が割り当てられます。 
---
= シックボリュームとシンボリュームの比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シックボリュームは常にフルプロビジョニングされます。つまり、ボリュームの作成時にすべての容量が割り当てられます。シンボリュームは常にシンプロビジョニングされます。つまり、ボリュームにデータが書き込まれるときに容量が割り当てられます。

[NOTE]
====
System Managerには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====
[cols="25h,~"]
|===
| ボリュームタイプ | 製品説明 


 a| 
シックボリューム
 a| 
* シックボリュームは、プールまたはボリュームグループから作成されます。
* シックボリュームでは、将来のストレージニーズに備えて、大量のストレージスペースが事前に確保されます。
* シックボリュームは、ボリューム作成時に物理ストレージに事前に割り当てられたボリュームのサイズ全体を使用して作成されます。つまり、100GiBのボリュームを作成すると、ドライブ上で割り当てられた100GiBの容量が実際に消費されます。ただし、スペースが未使用のままになり、ストレージ容量の利用率が低下する可能性があります。
* シックボリュームを作成する場合は、1つのボリュームに容量を過剰に割り当てないようにしてください。1つのボリュームに容量を過剰に割り当てると、システム内の物理ストレージをすぐに使い果たしてしまう可能性があります。
* コピーサービス（Snapshotイメージ、Snapshotボリューム、ボリュームコピー、非同期ミラーリング）用のストレージ容量も必要なため、シックボリュームにすべての容量を割り当てないでください。スペースが不足していると、プールまたはボリュームグループへの書き込みがブロックされる可能性があります。この状況が発生すると、空き容量アラートしきい値の警告が表示されます。




 a| 
シンボリューム
 a| 
* シンボリュームはプールからのみ作成され、ボリュームグループからは作成されません。
* シンボリュームはRAID 6である必要があります。
* シンボリュームはEF600またはEF300ストレージシステムでは使用できません。
* シンボリュームを作成するにはCLIを使用する必要があります。
* シックボリュームとは異なり、シンボリュームに必要なスペースは作成時に割り当てられず、必要に応じてあとから提供されます。
* シンボリュームでは、サイズを過剰に割り当てることができます。つまり、ボリュームのサイズよりも大きいLUNサイズを割り当てることができます。その後、LUNのサイズを拡張することなく、ユーザを切断することなく、必要に応じてボリュームを拡張できます（必要に応じてドライブを追加します）。
* シンプロビジョニングブロックのスペース再生（UNMAP）を使用すると、ホストからSCSI UNMAPコマンドを実行して、ストレージアレイ上のシンプロビジョニングされたボリュームのブロックを再生できます。シンプロビジョニングをサポートするストレージアレイでは、再生されたスペースを同じストレージアレイ内の他のシンプロビジョニングされたボリュームの割り当て要求に使用できます。これにより、ディスクスペースの消費状況が適切にレポートされ、リソースがより効率的に使用されるようになります。


|===


== シンボリュームの制限事項

シンボリュームでは、次の例外を除き、シックボリュームとしてのすべての処理がサポートされます。

* シンボリュームのセグメントサイズは変更できません。
* シンボリュームに対して読み取り前冗長性チェックを有効にすることはできません。
* シンボリュームをボリュームコピー処理のターゲットボリュームとして使用することはできません。
* シンボリュームの割り当て容量制限と警告しきい値は、非同期ミラーペアのプライマリ側でのみ変更できます。プライマリ側でこれらのパラメータを変更すると、自動的にセカンダリ側に反映されます。

