---
permalink: sm-storage/consolidate-volume-group-free-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, consolidate, free capacity, volume group 
summary: '[空き容量の統合]オプションを使用して、選択したボリュームグループの既存の空きエクステントを統合します。この操作を実行すると、ボリュームグループ内の最大空き容量から追加ボリュームを作成できます。' 
---
= ボリュームグループの空き容量の統合
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[空き容量の統合]オプションを使用して、選択したボリュームグループの既存の空きエクステントを統合します。この操作を実行すると、ボリュームグループ内の最大空き容量から追加ボリュームを作成できます。

.開始する前に
* ボリュームグループに少なくとも1つの空き容量領域が含まれている必要があります。
* ボリュームグループ内のすべてのボリュームがオンラインで、ステータスが最適lである必要があります。
* ボリュームのセグメントサイズの変更など、実行中のボリューム変更処理がないようにする必要があります。


.タスクの内容
この処理は開始後にキャンセルすることはできません。データへのアクセスは、統合処理中も維持されます。

[空き容量の統合]ダイアログボックスは、次のいずれかの方法で起動できます。

* ボリュームグループで少なくとも1つの空き容量領域が検出されると、[ホーム]ページの[通知]領域に「空き容量の統合」という推奨事項が表示されます。[*空き容量の統合*（Consolidate free capacity）]リンクをクリックして、ダイアログボックスを起動します。
* 次のタスクで説明するように、[プールとボリュームグループ]ページから[空き容量の統合]ダイアログボックスを開くこともできます。


.空き容量領域について
[%collapsible]
====
空き容量領域は、ボリュームを削除した場合や、ボリュームの作成時に使用可能なすべての空き容量を使用しなかった場合に発生する空き容量です。1つ以上の空き容量領域があるボリュームグループでボリュームを作成する場合、ボリュームの容量はそのボリュームグループ内で最も大きい空き容量領域に制限されます。たとえば、ボリュームグループの合計空き容量が15GiBで、最も大きい空き容量領域が10GiBの場合、作成できるボリュームの最大サイズは10GiBです。

ボリュームグループの空き容量を統合すると、書き込みパフォーマンスが向上します。ボリュームグループの空き容量は、ホストがファイルを書き込み、変更、削除するにつれて徐 々 に断片化されます。最終的には、使用可能な容量は単一の連続するブロックに配置されるのではなく、小さなフラグメントに分割されてボリュームグループ全体に分散されます。これにより、ホストは新しいファイルを空きクラスタの利用可能な範囲に収まるようにフラグメントとして書き込む必要があるため、ファイルの断片化がさらに進みます。

選択したボリュームグループの空き容量を統合することで、ホストが新しいファイルを書き込む際のファイルシステムのパフォーマンスが向上します。統合プロセスは、将来的に新しいファイルが断片化されるのを防ぐのにも役立ちます。

====
.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 統合する空き容量があるボリュームグループを選択し、メニューから「Uncommon Tasks [ボリュームグループの空き容量を統合する]」を選択します。
+
[空き容量の統合]ダイアログボックスが表示されます。

. と入力して、 `consolidate`この処理を実行します。
. [*統合（Consolidate）]をクリックし
+
System Managerは、以降のストレージ設定タスクで使用できるように、ボリュームグループの空き容量領域の統合（デフラグ）を開始します。



.終了後
[MENU]：[Home（ホーム）][View Operations in Progress]（進行中の操作の表示）を選択して、[Consolidate Free Capacity（空き容量の統合）]操作のこの処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
