---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: 1つのボリュームから同じストレージアレイ内の別のボリュームにデータをコピーし、ソースボリュームのポイントインタイムの物理的な複製（クローン）を作成できます。 
---
= ボリュームコピー
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1つのボリュームから同じストレージアレイ内の別のボリュームにデータをコピーし、ソースボリュームのポイントインタイムの物理的な複製（クローン）を作成できます。

.開始する前に
* ソースボリュームとターゲットボリュームに対するすべてのI/Oアクティビティを停止する必要があります。
* ソースボリュームとターゲットボリュームのすべてのファイルシステムをアンマウントする必要があります。
* ターゲットボリュームを以前にボリュームコピー処理で使用したことがある場合は、そのデータが不要になるか、データをバックアップしておく必要があります。


.タスクの内容
ソースボリュームは、ホストI/Oを受け入れてアプリケーションデータを格納するボリュームです。ボリュームコピーを開始すると、ソースボリュームのデータ全体がターゲットボリュームにコピーされます。

ターゲットボリュームは、ソースボリュームのデータのコピーを保持する標準ボリュームです。ボリュームコピー処理の完了後、ターゲットボリュームはソースボリュームと同じになります。ターゲットボリュームの容量はソースボリュームと同じかそれ以上である必要がありますが、RAIDレベルは異なる場合があります。

.オンラインコピーとオフラインコピーの詳細
[%collapsible]
====
*オンラインコピー*

オンラインコピーでは、ストレージアレイ内の任意のボリュームのポイントインタイムコピーが作成されますが、コピーの実行中もボリュームへの書き込みは可能です。この機能は、ボリュームのSnapshotを作成し、そのSnapshotをコピーの実際のソースボリュームとして使用することで実現されます。ポイントインタイムイメージの作成対象となるボリュームはベースボリュームと呼ばれ、ストレージアレイ内の標準ボリュームまたはシンボリュームを使用できます。

*オフラインコピー*

オフラインコピーでは、ソースボリュームからデータを読み取り、ターゲットボリュームにコピーします。コピーの実行中は、ソースボリュームに対するすべての更新が一時停止されます。ソースボリュームに対するすべての更新は、時間的な不整合がターゲットボリュームで作成されるのを防ぐために中断されます。オフラインボリュームコピー関係は、ソースボリュームとターゲットボリュームの間の関係です。

====
[NOTE]
====
ボリュームコピー処理では、ターゲットボリュームのデータが上書きされ、ターゲットボリュームに関連付けられているSnapshotボリュームがある場合はすべて使用停止になります。

====
.手順
. 選択メニュー： Storage [Volumes]
. ボリュームコピー処理のソースとして使用するボリュームを選択し、メニューからコピーサービス[Copy Volume]を選択します。
+
Copy Volume - Select Target（ボリュームのコピー-ターゲットの選択）ダイアログボックスが表示されます。

. データのコピー先となるターゲットボリュームを選択します。
+
このダイアログボックスの表には、対応するターゲットボリュームがすべて表示されます。

. スライダバーを使用して、ボリュームコピー処理のコピー優先度を設定します。
+
コピー優先度は、I/O要求の処理と比較して、ボリュームコピー処理を完了するために使用されるシステムリソースの量を決定します。

+
.コピー優先度について
[%collapsible]
====
コピー優先度は5段階で設定できます。

** 最低
** 低
** 中
** 高
** 最高


[最低]に設定すると、I/Oアクティビティが優先され、ボリュームコピー処理にかかる時間が長くなります。[最高]に設定すると、ボリュームコピー処理が優先されますが、ストレージアレイのI/Oアクティビティに影響する可能性があります。

====
. オンラインコピーとオフラインコピーのどちらを作成するかを選択します。オンライン・コピーを作成するには'[**コピー・オペレーション中にソース・ボリュームをオンラインにしておく**]チェック・ボックスを選択します
. 次のいずれかを実行します。
+
** online_copy操作を実行するには、* Next *をクリックして、* Reserve Capacity *ダイアログボックスに進みます。
** _offline_copy操作を実行するには'[*終了*]をクリックしてオフライン・コピーを開始します


. オンラインコピーの作成を選択した場合は、オンラインコピーのデータおよびその他の情報を保存するために必要なリザーブ容量を設定し、[*Finish*]をクリックしてオンラインコピーを開始します。
+
[ボリューム候補]の表には、指定したリザーブ容量をサポートする候補のみが表示されます。リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
** ただし、リザーブ容量は元のデータに対する変更の回数によって異なります。ストレージオブジェクトがアクティブになっている時間が長いほど、リザーブ容量を大きくする必要があります。




.結果
System Managerにより、ソースボリュームのすべてのデータがターゲットボリュームにコピーされます。ボリュームコピー処理が完了すると、ターゲットボリュームは自動的にホストに対して読み取り専用になります。

.終了後
メニューHome（ホーム）[View Operations in Progress]（進行中の操作の表示）を選択して、ボリュームコピー操作の進行状況を表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
