---
permalink: sm-storage/copy-volume-function.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: ボリュームコピー機能を使用すると、ソースボリュームとターゲットボリュームという2つのボリュームを同じストレージアレイに作成して、ボリュームのポイントインタイムコピーを作成できます。 
---
= ボリュームコピーの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームコピー機能を使用すると、ソースボリュームとターゲットボリュームという2つのボリュームを同じストレージアレイに作成して、ボリュームのポイントインタイムコピーを作成できます。

ソースボリュームからターゲットボリュームへの1バイトずつコピーが実行され、ターゲットボリュームのデータがソースボリュームのデータと同一になります。



== データコピーによるアクセスの向上

ボリュームのストレージ要件の変化に応じて、ボリュームコピー機能を使用して、小容量のドライブを使用するプールまたはボリュームグループから大容量のドライブを使用するプールまたはボリュームグループにデータをコピーできます。たとえば、ボリュームコピー機能を使用して次の処理を実行できます。

* 大容量ドライブにデータを移動
* データ転送速度の高いドライブに変更します。
* パフォーマンスを向上させるために、新しいテクノロジを使用するドライブに変更してください。
* シンボリュームをシックボリュームに変更します。


コピーのソースボリュームとターゲットボリュームで、報告されるホストアドレス指定可能/論理ブロックサイズ（セクターサイズ）が同じである必要があります。

報告されるボリュームのブロックサイズは次のとおりです。

* *ネイティブブロックサイズ*–ボリュームのブロックサイズは、ドライブのブロックサイズ（512または4K）と同じです。
* *エミュレートされた512ブロックサイズ*-ドライブは4Kですが、報告されるブロックサイズは512です。




== シンボリュームからシックボリュームへの変更

シンボリュームをシックボリュームに変更する場合は、ボリュームコピー処理を使用してシンボリュームのコピーを作成します。ボリュームコピー処理のターゲットは常にシックボリュームです。

[NOTE]
====
System Managerには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====


== バックアップデータ

ボリュームコピー機能を使用すると、ボリュームのデータを同じストレージアレイ上の別のボリュームにコピーしてボリュームをバックアップできます。ターゲットボリュームは、ソースボリュームのバックアップ、システムのテスト、またはテープドライブなどの別のデバイスへのバックアップとして使用できます。



== Snapshotボリュームのデータをベースボリュームにリストア

ベースボリュームに関連付けられているSnapshotボリュームからデータをリストアする必要がある場合は、ボリュームコピー機能を使用してSnapshotボリュームからベースボリュームにデータをコピーできます。Snapshotボリューム上のデータのボリュームコピーを作成し、そのデータをベースボリュームにコピーできます。



== ソースボリュームとターゲットボリューム

次の表に、ボリュームコピー機能でソースボリュームとターゲットボリュームに使用できるボリュームのタイプを示します。

[cols="1a,1a,1a,1a"]
|===
| ボリュームタイプ | オフラインボリュームコピーのソースボリュームを指定します | オンラインボリュームコピーのソースボリューム | オンラインおよびオフラインのターゲットボリューム 


 a| 
プール内のシックボリューム
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ボリュームグループ内のシックボリューム
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
シンボリューム
 a| 
はい^1です
 a| 
はい
 a| 
いいえ



 a| 
Snapshotボリューム
 a| 
はい^2^
 a| 
いいえ
 a| 
いいえ



 a| 
Snapshotベースボリューム
 a| 
はい
 a| 
はい
 a| 
いいえ



 a| 
リモートミラープライマリボリューム
 a| 
はい^3^
 a| 
はい
 a| 
いいえ

|===
^1^ターゲットボリュームの容量はシンボリュームのレポート容量以上である必要があります。

^2^オンラインコピー処理が完了するまでは、Snapshotボリュームコピーを使用できません。

^3^ソースボリュームがプライマリボリュームの場合、ターゲットボリュームの容量はソースボリュームの使用可能容量以上である必要があります。
