---
permalink: sm-storage/create-snapshot-image.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, image 
summary: ベースボリュームまたはSnapshot整合性グループからSnapshotイメージを手動で作成できます。これは、インスタントSnapshotまたはインスタントイメージとも呼ばれます。 
---
= Snapshotイメージの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ベースボリュームまたはSnapshot整合性グループからSnapshotイメージを手動で作成できます。これは_インスタント・スナップショット_または_インスタント・イメージ_とも呼ばれます

.開始する前に
* ベースボリュームが最適lである必要があります。
* ドライブが最適lである必要があります。
* スナップショット・グループを予約済みとして指定することはできません
* リザーブ容量ボリュームのData Assurance（DA）設定は、関連付けられているSnapshotグループのベースボリュームと同じである必要があります。


.手順
. 次のいずれかの操作を実行してSnapshotイメージを作成します。
+
** 選択メニュー： Storage [Volumes]オブジェクト（ベースボリュームまたはSnapshot整合性グループ）を選択し、メニュー：コピーサービス[インスタントSnapshotの作成]を選択します。
** メニューを選択します。Storage [Snapshots]。「*スナップショットイメージ*」タブを選択し、メニューから「Create [Instant snapshot]」を選択します。
+
Create Snapshot Image（スナップショットイメージの作成）ダイアログボックスが表示されます。オブジェクト（ベースボリュームまたはSnapshot整合性グループ）を選択し、* Next *をクリックします。ボリュームまたはSnapshot整合性グループに対して以前にSnapshotイメージが作成されている場合は、インスタントSnapshotがただちに作成されます。それ以外の場合は、ボリュームまたはSnapshot整合性グループのSnapshotイメージが初めて作成されるときに、Confirm Snapshot Imageダイアログボックスが表示されます。



. Create *をクリックしてリザーブ容量が必要であることを通知し、Reserve Capacityステップに進みます。
+
Reserve Capacityダイアログボックスが表示されます。

. スピンボックスを使用して容量の割合を調整し、*次へ*をクリックして、テーブルで強調表示されている候補ボリュームを受け入れます。
+
設定の編集ダイアログボックスが表示されます。

. Snapshotイメージの設定を必要に応じて選択し、処理を確定します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
* Snapshotイメージの設定*



 a| 
Snapshotイメージの上限
 a| 
指定した上限を超えたSnapshotイメージを自動的に削除する場合は、チェックボックスをオンのままにします。上限を変更するには、スピンボックスを使用します。このチェックボックスをオフにすると、32個のイメージが作成された時点でSnapshotイメージの作成が停止します。



 a| 
*リザーブ容量の設定*



 a| 
アラートを受け取るタイミング...
 a| 
このスピンボックスを使用して、Snapshotグループのリザーブ容量が残り少なくなったときにシステムからアラート通知を送信する割合を調整します。

Snapshotグループのリザーブ容量が指定したしきい値を超えた場合は、事前通知を使用して、残りのスペースがなくなる前にリザーブ容量を増やしたり、不要なオブジェクトを削除したりします。



 a| 
リザーブ容量がフルになった場合のポリシー
 a| 
次のいずれかのポリシーを選択します。

** *最も古いSnapshotイメージをパージする*- Snapshotグループ内の最も古いSnapshotイメージが自動的にパージされ、そのSnapshotイメージのリザーブ容量が解放されてグループ内で再利用されます。
** *ベースボリュームへの書き込みを拒否*--リザーブ容量の割合が定義された上限に達すると'リザーブ容量へのアクセスをトリガーしたベースボリュームに対するI/O書き込み要求はすべて拒否されます


|===
====


.結果
* System ManagerのSnapshot Imagesテーブルに、新しいSnapshotイメージが表示されます。新しいイメージがタイムスタンプおよび関連付けられているベースボリュームまたはSnapshot整合性グループ別にリストされます。
* 次の状況に該当する場合は、Snapshotの作成が保留状態になることがあります。
+
** このSnapshotイメージを含むベースボリュームが非同期ミラーグループのメンバーである。
** ベースボリュームで同期処理を実行中です。同期処理が完了するとすぐにSnapshotイメージの作成が完了します。



