---
permalink: sm-storage/create-pool-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, manually 
summary: プールの自動構成機能でニーズに合ったプールが提供されない場合は、プールを（一連の候補から）手動で作成できます。 
---
= プールの手動作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールの自動構成機能でニーズに合ったプールが提供されない場合は、プールを（一連の候補から）手動で作成できます。

プールは必要な論理ストレージ容量を提供します。この容量から個々のボリュームを作成し、アプリケーションをホストすることができます。

.開始する前に
* ドライブタイプ（HDDまたはSSD）が同じドライブが11本以上必要です。
* シェルフ損失の保護を有効にするには、プールを構成するドライブが少なくとも6つのドライブシェルフに配置されていて、同じドライブシェルフのドライブが3本以下である必要があります。
* ドロワー損失の保護を有効にするには、プールを構成するドライブが少なくとも5つのドロワーに同じ数ずつ配置されている必要があります。
* EF600またはEF300ストレージアレイを構成する場合は、各コントローラが最初の12スロットの同数のドライブと最後の12スロットの同数のドライブにアクセスできることを確認してください。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。現在のところ、System Managerでは、ボリュームグループを作成するときに[アドバンスト]機能でドライブを選択できます。プールを作成する場合は、ストレージアレイ内のすべてのドライブを使用することを推奨します。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニュー：[Create Pool（プールの作成）]をクリックします。
+
[Create Pool]ダイアログボックスが表示されます。

. プールの名前を入力します。
. *オプション：ストレージアレイに複数のタイプのドライブがある場合、使用するドライブタイプを選択します。
+
作成可能なすべてのプールの候補が表示されます。

. 次の特性に基づいて使用するプール候補を選択し、*作成*をクリックします。
+
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
空き容量
 a| 
プール候補の空き容量（GiB）が表示されます。アプリケーションのストレージニーズに対応する容量を持つプール候補を選択します。

予約済み（スペア）容量もプール全体に分散され、空き容量には含まれません。



 a| 
合計ドライブ数
 a| 
プール候補で使用可能なドライブの数が表示されます。

System Managerは、できるだけ多くのドライブを予約済み容量として自動的に確保します（System Managerではプール内の6本につき1本のドライブを予約済み容量として確保します）。

ドライブ障害が発生すると、予約済み容量を使用して再構築されたデータが格納されます。



 a| 
ドライブブロックサイズ（EF300およびEF600のみ）
 a| 
プール内のドライブが書き込み可能なブロックサイズ（セクターサイズ）が表示されます。値は次のとおりです。

** 512 -- 512バイトのセクターサイズ。
** 4K -- 4、096バイトのセクターサイズ。




 a| 
セキュリティ対応
 a| 
プール候補がセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

** プールはドライブセキュリティを使用して保護できますが、この機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。
** FDEのみのプールを作成する場合は、SecureCapable列で「* Yes-fde」を検索してください。FIPSのみのプールを作成する場合は、「はい- FIPS *」または「はい- FIPS（混在）」を探します。「Mixed」 は 、140-2レベルドライブと140-3レベルドライブが混在していることを示します。これらのレベルを混合して使用する場合は、プールはより低いレベルのセキュリティ（140-2）で動作することに注意してください。
** セキュリティ対応かどうかがドライブによって異なるプールや、セキュリティレベルが異なるドライブが混在したプールを作成することもできます。プールにセキュリティ対応でないドライブが含まれている場合、プールをセキュリティ対応にすることはできません。




 a| 
セキュリティを有効化
 a| 
セキュリティ対応ドライブでドライブセキュリティ機能を有効にするオプションを提供します。プールがセキュリティ対応で、セキュリティキーを作成している場合は、チェックボックスを選択してセキュリティを有効にできます。

[NOTE]
====
一度有効にしたドライブセキュリティは、プールを削除してドライブを消去しないかぎり解除できません。

====


 a| 
DA 対応
 a| 
プール候補でData Assurance（DA）を使用できるかどうかを示します。DAは、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。

DAは、すべてのドライブがDA対応の場合は有効になります。DAは、ボリュームの作成後にメニューを選択して無効にすることができます。Storage [Volumes]、[View/Edit Settings]、[Advanced]、[Permanently disable Data Assurance（データ保護を完全に無効にする）]。DAが無効になっているボリュームでは、再度有効にすることはできません。



 a| 
リソースプロビジョニング対応（EF300およびEF600のみ）
 a| 
このプール候補でリソースプロビジョニングを使用できるかどうかを示します。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。



 a| 
シェルフ損失の保護
 a| 
シェルフ損失の保護が使用可能かどうかを示します。

シェルフ損失の保護が有効な場合、1台のドライブシェルフとの通信が完全に失われた場合でもプール内のボリューム上のデータへのアクセスが保証されます。



 a| 
ドロワー損失の保護
 a| 
ドロワー損失の保護を使用できるかどうかを示します。この保護は、使用しているドライブシェルフにドロワーが搭載されている場合にのみ提供されます。

ドロワー損失の保護が有効な場合、ドライブシェルフの1つのドロワーとの通信が完全に失われた場合でもプール内のボリューム上のデータへのアクセスが保証されます。



 a| 
サポートされるボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
に、プール内のボリュームに対して作成できるブロックサイズを示します。

** 512n -- 512バイトネイティブ。
** 512e -- 512バイトエミュレート。
** 4k -- 4,096バイト


|===

