---
permalink: sm-storage/create-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, ssd, cache 
summary: システムパフォーマンスを向上させるために、SSDキャッシュ機能を使用して、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることができます。SSDキャッシュは、ホスト読み取りにのみ使用されます。 
---
= SSDキャッシュの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムパフォーマンスを動的に高速化するには、SSDキャッシュ機能を使用して、アクセス頻度が最も高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュします。SSDキャッシュは、ホスト読み取りにのみ使用されます。

.開始する前に
ストレージアレイにSSDドライブが含まれている必要があります。

.タスクの内容
新しいSSDキャッシュを作成するときに、1つまたは複数のドライブを使用できます。読み取りキャッシュはストレージアレイにあるため、ストレージアレイを使用するすべてのアプリケーションでキャッシュが共有されます。キャッシュするボリュームを選択すると、あとは動的に自動でキャッシングが実行されます。

新しいSSDキャッシュを作成するときは、次のガイドラインに従ってください。

* SSDキャッシュのセキュリティを有効にできるのは作成時だけで、あとから有効にすることはできません。
* 1つのストレージアレイでサポートされるSSDキャッシュは1つだけです。
* SSDキャッシュが有効になっているボリュームが1つだけの場合は、SSDキャッシュ全体がそのボリュームを所有するコントローラに割り当てられます。
* ストレージアレイで使用可能なSSDキャッシュの最大容量は、コントローラのプライマリキャッシュ容量によって決まります。
* SSDキャッシュはSnapshotイメージではサポートされません。
* SSDキャッシュが有効または無効になっているボリュームをインポートまたはエクスポートした場合、キャッシュデータはインポートまたはエクスポートされません。
* コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシング転送の対象になりません。
* 関連するボリュームがセキュリティ有効の場合は、セキュリティ有効のSSDキャッシュを作成してください。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニューをクリックします：Create [SSD Cache]。
+
[SSDキャッシュの作成]ダイアログボックスが表示されます。

. SSDキャッシュの名前を入力します。
. 次の特性に基づいて使用するSSDキャッシュ候補を選択します。
+
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
容量
 a| 
使用可能な容量（GiB）を示します。アプリケーションのストレージニーズに応じて容量を選択します。

SSDキャッシュの最大容量は、コントローラのプライマリキャッシュ容量によって異なります。SSDキャッシュに最大容量を超える容量を割り当てた場合、超過した容量は使用できません。

SSDキャッシュの容量は、全体の割り当て容量にカウントされます。



 a| 
合計ドライブ数
 a| 
このSSDキャッシュで使用できるドライブの数が表示されます。必要なドライブ数のSSD候補を選択します。



 a| 
セキュリティ対応
 a| 
SSDキャッシュがセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

セキュリティ有効SSDキャッシュを作成する場合は、「セキュア対応」列で「はい- FDE *」または「はい- FIPS *」を探します。



 a| 
セキュリティを有効化
 a| 
セキュリティ対応ドライブでドライブセキュリティ機能を有効にするオプションを提供します。セキュリティ有効SSDキャッシュを作成する場合は、セキュリティの有効化チェックボックスをオンにします。

[NOTE]
====
いったん有効にすると、セキュリティを無効にすることはできません。SSDキャッシュのセキュリティを有効にできるのは作成時だけで、あとから有効にすることはできません。

====


 a| 
DA対応
 a| 
このSSDキャッシュ候補でData Assurance（DA）を使用できるかどうかを示します。Data Assurance（DA）は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。

DAを使用する場合は、DAに対応したSSDキャッシュ候補を選択します。このオプションはDA機能が有効になっている場合にのみ使用できます。

SSDキャッシュにはDAに対応したドライブとDAに対応していないドライブの両方を含めることができますが、DAを使用するためにはすべてのドライブがDAに対応している必要があります。

|===
. SSD読み取りキャッシュを実装するボリュームにSSDキャッシュを関連付けます。互換性のあるボリュームでSSDキャッシュをすぐに有効にするには、*ホストにマップされている既存の互換性のあるボリュームでSSDキャッシュを有効にする*チェックボックスをオンにします。
+
ドライブセキュリティとDAの機能が同じボリュームであれば互換性があります。

. [ 作成（ Create ） ] をクリックします。

