---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, automatically 
summary: プールの作成は、System Managerがストレージアレイ内に未割り当てのドライブを検出すると自動的に開始されます。プールの自動作成を使用すると、ストレージアレイ内のすべての未割り当てドライブを1つのプールに簡単に設定したり、既存のプールにドライブを追加したりできます。 
---
= プールの自動作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールの作成は、System Managerがストレージアレイ内に未割り当てのドライブを検出すると自動的に開始されます。プールの自動作成を使用すると、ストレージアレイ内のすべての未割り当てドライブを1つのプールに簡単に設定したり、既存のプールにドライブを追加したりできます。

.開始する前に
[プールの自動構成]ダイアログボックスは、次のいずれかの条件に該当する場合に起動できます。

* ドライブタイプが類似する既存のプールに追加できる未割り当てドライブが少なくとも1本検出されました。
* 新しいプールの作成に使用できる未割り当てドライブが11本以上検出されました（ドライブタイプが異なるために既存のプールに追加できない場合）。


.タスクの内容
次の点に注意してください。

* ストレージアレイにドライブを追加すると、System Managerでドライブが自動的に検出され、ドライブタイプと現在の構成に基づいて1つまたは複数のプールを作成するように求められます。
* プールがすでに定義されている場合は、互換性があるドライブを既存のプールに追加するかどうかを確認するプロンプトがSystem Managerで自動的に表示されます。新しいドライブが既存のプールに追加されると、System Managerによって新しい容量（追加した新しいドライブを含む）にデータが自動的に再配分されます。
* EF600またはEF300ストレージアレイを構成する場合は、各コントローラが最初の12スロットの同数のドライブと最後の12スロットの同数のドライブにアクセスできることを確認してください。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。


プールの自動構成（Pool Auto-Configuration）ダイアログボックスは、次のいずれかの方法で起動できます。

* 未割り当て容量が検出されると、通知領域のホームページにプールの自動構成に関する推奨事項が表示されます。View Pool Auto-Configuration *（プールの自動構成の表示）をクリックして、ダイアログボックスを起動します。
* プールとボリュームグループページからプールの自動構成ダイアログボックスを起動することもできます。これには次のタスクを実行します。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニューを選択します。More [Launch pool auto-configuration]。
+
新しいプール、ドライブが追加されている既存のプール、またはその両方が表示されます。新しいプールには、連番を付した名前がデフォルトで付けられます。

+
System Managerは次のタスクを実行します。

+
** ドライブタイプ（HDDまたはSSD）が同じで容量がほぼ同じ十分な数のドライブがある場合は、単一のプールを作成します。
** 未割り当て容量が異なるドライブタイプで構成されている場合は、複数のプールが作成されます。
** ストレージアレイでプールが定義済みの場合は、既存のプールにドライブを追加し、同じドライブタイプの新しいドライブをプールに追加します。
** ドライブタイプが同じドライブを既存のプールに追加します。新しいドライブタイプが異なる場合は、他のドライブタイプを使用して別のプールを作成します。


. 新しいプールの名前を変更するには、* Edit *アイコン（鉛筆）をクリックします。
. プールのその他の特性を表示するには、カーソルを合わせるか、* Details *アイコン（ページ）をタッチします。
+
ドライブタイプ、セキュリティ機能、Data Assurance（DA）機能、シェルフ損失の保護、ドロワー損失の保護に関する情報が表示されます。

+
EF600およびEF300ストレージアレイの場合は、リソースプロビジョニングとボリュームのブロックサイズの設定も表示されます。

. [* 同意する * ] をクリックします。

