---
permalink: sm-storage/create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, volume 
summary: ボリュームまたはSnapshot整合性グループのSnapshotイメージへのホストアクセスを提供するには、Snapshotボリュームを作成します。Snapshotボリュームは読み取り専用または読み取り/書き込みのいずれかに指定できます。 
---
= Snapshotボリュームの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームまたはSnapshot整合性グループのSnapshotイメージへのホストアクセスを提供するには、Snapshotボリュームを作成します。Snapshotボリュームは読み取り専用または読み取り/書き込みのいずれかに指定できます。

.タスクの内容
Snapshotボリュームの作成手順では、SnapshotイメージからSnapshotボリュームを作成し、ボリュームが読み取り/書き込みの場合にリザーブ容量を割り当てることができます。Snapshotボリュームは次のいずれかとして指定できます。

* 読み取り専用のSnapshotボリュームは、Snapshotイメージに格納されたデータへの読み取りアクセスをホストアプリケーションに提供しますが、Snapshotイメージを変更することはできません。読み取り専用のSnapshotボリュームには、関連付けられたリザーブ容量はありません。
* 読み書き可能なSnapshotボリュームは、Snapshotイメージに含まれているデータのコピーへの書き込みアクセスをホストアプリケーションに提供します。専用のリザーブ容量が割り当てられ、ホストアプリケーションがベースボリュームに対して行った以降の変更を、参照元のSnapshotイメージに影響を与えることなく保存するために使用されます。


Snapshotボリュームを作成するプロセスは複数の手順で構成されます。



== 手順1：Snapshotボリュームのメンバーを確認します

ベースボリュームまたはSnapshot整合性グループのSnapshotイメージを選択します。Snapshot整合性グループのSnapshotイメージを選択すると、確認用にSnapshot整合性グループのメンバーボリュームが表示されます。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットボリューム*タブを選択します。
. 「 * Create * 」を選択します。
+
Create Snapshot Volume（スナップショットボリュームの作成）ダイアログボックスが表示されます。

. Snapshotボリュームに変換するSnapshotイメージ（ボリュームまたはSnapshot整合性グループ）を選択し、* Next（次へ）*をクリックします。[*Filter*]フィールドのテキスト・エントリを使用して、リストを絞り込みます。
+
Snapshot整合性グループのSnapshotイメージを選択した場合は、[メンバーの確認]ダイアログボックスが表示されます。

+
[メンバーの確認]ダイアログ・ボックスで'スナップショット・ボリュームへの変換に選択したボリュームのリストを確認し'[次へ]をクリックします

. にアクセスします。




== 手順2：Snapshotボリュームをホストに割り当てる

特定のホストまたはホストクラスタを選択してSnapshotボリュームに割り当てます。これにより、Snapshotボリュームへのアクセスがホストまたはホストクラスタに許可されます。必要に応じて、あとでホストを割り当てることもできます。

.開始する前に
* 有効なホストまたはホストクラスタがHostsページに表示されています。
* ホストに対してホストポート識別子を定義しておく必要があります。
* DA対応ボリュームを作成する前に、予定しているホスト接続でData Assurance（DA）機能がサポートされていることを確認してください。ストレージアレイのコントローラのいずれかのホスト接続でDAがサポートされていない場合、関連付けられているホストはDA対応ボリュームのデータにアクセスできません。


.タスクの内容
ボリュームを割り当てる際は、次のガイドラインに注意してください。

* ホストのオペレーティングシステムには、ホストがアクセスできるボリュームの数に制限がある場合があります。
* ホスト割り当ては、ストレージアレイ内のSnapshotボリュームごとに1つずつ定義できます。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* 1つのホストまたはホストクラスタからSnapshotボリュームにアクセスする際に、同じ論理ユニット番号（LUN）を2回使用することはできません。一意のLUNを使用する必要があります。


[NOTE]
====
ホストクラスタにボリュームを割り当てようとすると、すでに確立されている割り当てと競合しているホストクラスタへのボリュームの割り当ては失敗します。

====
.手順
. [*ホストへの割り当て*]ダイアログ・ボックスで'新しいボリュームに割り当てるホストまたはホスト・クラスタを選択しますホストを割り当てずにボリュームを作成する場合は、ドロップダウンリストから* Assign later *を選択します。
. アクセスモードを選択します。次のいずれかを選択します。
+
** *読み取り/書き込み*-このオプションは、Snapshotボリュームへの読み取り/書き込みアクセスをホストに提供し、リザーブ容量を必要とします。
** *読み取り専用*-このオプションは、Snapshotボリュームへの読み取り専用アクセスをホストに提供し、リザーブ容量は不要です。


. 「*次へ*」をクリックして、次のいずれかの操作を行います。
+
** Snapshotボリュームが読み取り/書き込みの場合は、Review Capacity（容量の確認）ダイアログボックスが表示されます。にアクセスします。
** Snapshotボリュームが読み取り専用の場合は、Edit Priorityダイアログボックスが表示されます。にアクセスします。






== 手順3：Snapshotボリューム用の容量をリザーブする

読み取り/書き込みのSnapshotボリュームにリザーブ容量を関連付けます。ベースボリュームまたはSnapshot整合性グループのプロパティに基づいて、System Managerから推奨されるボリュームと容量が提示されます。推奨されるリザーブ容量の設定をそのまま使用することも、割り当てられたストレージをカスタマイズすることもできます。

.タスクの内容
Snapshotボリュームのリザーブ容量を必要に応じて増やしたり減らしたりできます。Snapshotのリザーブ容量が必要よりも多い場合は、サイズを縮小することで他の論理ボリュームに必要なスペースを解放できます。

.手順
. スピンボックスを使用して、Snapshotボリュームにリザーブ容量を割り当てます。
+
[ボリューム候補]の表には、指定したリザーブ容量をサポートするボリュームだけが候補として表示されます。

+
次のいずれかを実行します。

+
** *デフォルトの設定をそのまま使用します*。
+
Snapshotボリュームにデフォルトの設定でリザーブ容量を割り当てるには、このオプションを使用します（推奨）。

** *データストレージのニーズに合わせて、独自の設定でリザーブ容量を割り当てます。*
+
デフォルトのリザーブ容量設定を変更した場合は、*候補の更新*をクリックして、指定したリザーブ容量の候補リストを更新します。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズ、およびSnapshotイメージを収集する数と期間によって異なります。




. *オプション：Snapshot整合性グループのSnapshotボリュームを作成する場合は、「候補の変更」オプションがリザーブ容量候補の表に表示されます。[候補の変更]をクリックして、代替リザーブ容量候補を選択します。
. [次へ]*をクリックし、に進みます<<手順4：Snapshotボリュームの設定を編集する>>。




== 手順4：Snapshotボリュームの設定を編集する

名前、キャッシュ、リザーブ容量に関するアラートしきい値など、Snapshotボリュームの設定を変更します。

.タスクの内容
読み取り専用のパフォーマンスを向上させる方法として、ソリッドステートディスク（SSD）キャッシュにボリュームを追加することができます。SSDキャッシュは、ストレージアレイ内で論理的にグループ化した一連のSSDドライブで構成されます。

.手順
. Snapshotボリュームの設定をそのまま使用するか、必要に応じて変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
* Snapshotボリューム設定*



 a| 
名前
 a| 
Snapshotボリュームの名前を指定します。



 a| 
SSDキャッシュの有効化
 a| 
SSDで読み取り専用キャッシュを有効にする場合は、このオプションを選択します。



 a| 
*リザーブ容量の設定*



 a| 
アラートを受け取るタイミング...
 a| 
*読み取り/書き込みのSnapshotボリューム*にのみ表示されます。

このスピンボックスを使用して、Snapshotグループのリザーブ容量が残り少なくなったときにシステムからアラート通知を送信する割合を調整します。

Snapshotグループのリザーブ容量が指定したしきい値を超えた場合は、事前通知を使用して、残りのスペースがなくなる前にリザーブ容量を増やしたり、不要なオブジェクトを削除したりします。

|===
====
. Snapshotボリュームの設定を確認します。[戻る]をクリックして変更を行います。
. スナップショット・ボリュームの構成に問題がなければ'[*終了*]をクリックします

