---
permalink: sm-storage/create-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, cluster 
summary: 複数のホストが同じボリュームへのI/Oアクセスを必要とする場合は、ホストクラスタを作成します。 
---
= ホストクラスタの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
複数のホストが同じボリュームへのI/Oアクセスを必要とする場合は、ホストクラスタを作成します。

.タスクの内容
ホストクラスタを作成する際は、次のガイドラインに注意してください。

* クラスタの作成に使用できるホストが複数ない場合、この処理は開始されません。
* ホストクラスタ内のホストは、オペレーティングシステムが異なる場合があります（異機種混在）。
* ホストクラスタにNVMeホストとNVMe以外のホストを混在させることはできません。
* Data Assurance（DA）対応ボリュームを作成する場合は、使用するホスト接続でDAがサポートされている必要があります。
+
ストレージアレイのコントローラのいずれかのホスト接続でDAがサポートされていない場合、関連付けられているホストはDA対応ボリュームのデータにアクセスできません。

* 選択した名前がすでに使用されている場合、この処理は成功しません。
* 名前の最大文字数は30文字です。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. メニューから「Create [Host Cluster]」を選択します。
+
Create Host Cluster（ホストクラスタの作成）ダイアログボックスが表示されます。

. ホストクラスタの設定を必要に応じて選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
名前
 a| 
新しいホストクラスタの名前を入力します。



 a| 
ボリュームアクセスを共有するホストを選択
 a| 
ドロップダウンリストから2つ以上のホストを選択します。ホストクラスタにまだ含まれていないホストだけがリストに表示されます。

|===
====
. [ 作成（ Create ） ] をクリックします。
+
接続されているインターフェイスタイプのData Assurance（DA）機能が選択したホストで異なる場合は、ホストクラスタでDAを使用できなくなることを示すメッセージがダイアログに表示されます。この場合、DA対応ボリュームをホストクラスタに追加することはできません。続行するには「*はい」を選択し、キャンセルするには「*いいえ」を選択します。

+
DAを使用すると、ストレージシステム全体のデータ整合性が向上します。DAを使用すると、ホストとドライブの間でデータを移動するときに発生する可能性があるエラーがストレージアレイでチェックされます。新しいボリュームにDAを使用すると、エラーがすべて検出されます。



.結果
新しいホストクラスタがテーブルに表示され、その下の行に割り当てられたホストが表示されます。
