---
permalink: sm-storage/create-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volume, group 
summary: ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成します。ボリュームグループは、RAIDレベルや容量などの特性が共有されたボリュームのコンテナです。 
---
= ボリュームグループの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成します。ボリュームグループは、RAIDレベルや容量などの特性が共有されたボリュームのコンテナです。

大容量のドライブとコントローラ間でボリュームを分散できるので、ストレージ容量を活用してデータを保護するには、ボリュームグループごとに複数のボリュームを作成すると効果的です。

.開始する前に
ボリュームグループを作成する前に、次のガイドラインを確認してください。

* 未割り当てのドライブが少なくとも1本必要です。
* 1つのボリュームグループに含めることができるドライブ数には制限があります。これらの制限はRAIDレベルによって異なります。
* シェルフ/ドロワー損失の保護を有効にするには、少なくとも3台のシェルフまたはドロワーに配置されたドライブを使用するボリュームグループを作成する必要があります（RAID 1ではシェルフ/ドロワーが2台以上）。
* EF600またはEF300ストレージアレイを使用していて、ボリュームグループを手動で作成する場合は、各コントローラが最初の12スロットの同数のドライブと最後の12スロットの同数のドライブにアクセスできることを確認してください。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。現在のところ、System Managerでは、ボリュームグループを作成するときに[アドバンスト]機能でドライブを選択できます。
* 選択したRAIDレベルがボリュームグループの容量にどのように影響するかを確認します。
+
** RAID 1を選択した場合は、一度に2本のドライブを追加してミラーペアを選択する必要があります。ミラーリングとストライピング（RAID 10またはRAID 1+0）は、ドライブを4本以上選択した場合に実装されます。
** RAID 5を選択した場合は、少なくとも3本のドライブを追加してボリュームグループを作成する必要があります。
** RAID 6を選択した場合は、少なくとも5本のドライブを追加してボリュームグループを作成する必要があります。




.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニュー：Create [Volume group]（ボリュームグループの作成）をクリックします。
+
[Create Volume Group]ダイアログボックスが表示されます。

. ボリュームグループの名前を入力します。
. データストレージと保護の要件に最も適したRAIDレベルを選択します。
+
ボリュームグループ候補の表に、選択したRAIDレベルをサポートする候補のみが表示されます。

. *オプション：ストレージアレイに複数のタイプのドライブがある場合、使用するドライブタイプを選択します。
+
ボリュームグループ候補の表に、選択したドライブタイプとRAIDレベルをサポートする候補のみが表示されます。

. *オプション：*ボリュームグループで使用するドライブを自動で定義するか手動で定義するかを選択できます。デフォルトでは、[自動方式]が選択されています。
+
ドライブを手動で選択するには、ドライブを手動で選択する*（アドバンスト）リンクをクリックします。クリックすると、ドライブが自動的に選択されます（アドバンスト）*。

+
手動方式では、ボリュームグループを構成する特定のドライブを選択できます。未割り当ての特定のドライブを選択して必要な容量を確保することができます。メディアタイプやインターフェイスタイプが異なるドライブがストレージアレイに含まれている場合は、1つのドライブタイプに対して未設定の容量のみを選択して新しいボリュームグループを作成できます。

+
[NOTE]
====
手動方式を使用するのは、ドライブの冗長性と最適なドライブ構成を理解しているエキスパートだけです。

====
. 表示されたドライブ特性に基づいて、ボリュームグループで使用するドライブを選択し、*作成*をクリックします。
+
表示されるドライブ特性は、自動方式と手動方式のどちらを選択したかによって異なります。

+
.自動方式のドライブ特性
[%collapsible]
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
空き容量
 a| 
使用可能な容量（GiB）を示します。アプリケーションのストレージニーズに対応する容量を備えたボリュームグループ候補を選択してください。



 a| 
合計ドライブ数
 a| 
このボリュームグループで使用可能なドライブの数が表示されます。必要なドライブ数のボリュームグループ候補を選択します。



 a| 
ドライブブロックサイズ（EF300およびEF600のみ）
 a| 
グループ内のドライブが書き込み可能なブロックサイズ（セクターサイズ）が表示されます。値は次のとおりです。

** 512 -- 512バイトのセクターサイズ。
** 4K -- 4、096バイトのセクターサイズ。




 a| 
セキュリティ対応
 a| 
このボリュームグループ候補がセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

** ボリュームグループはドライブセキュリティを使用して保護できますが、この機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。
** FDEのみのボリュームグループを作成する場合は、SecureCapable列で「* Yes-fde」が検索されています。FIPSのみのボリュームグループを作成する場合は、「はい- FIPS *」または「はい- FIPS（混在）」を探します。「Mixed」 は 、140-2レベルドライブと140-3レベルドライブが混在していることを示します。これらのレベルが混在している場合は、ボリュームグループが下位のセキュリティレベル（140-2）で動作することに注意してください。
** セキュリティ対応かどうかがドライブによって異なるボリュームグループや、セキュリティレベルが異なるドライブが混在したボリュームグループを作成することもできます。ボリュームグループにセキュリティ対応でないドライブが含まれている場合、ボリュームグループをセキュリティ対応にすることはできません。




 a| 
セキュリティを有効化
 a| 
セキュリティ対応ドライブでドライブセキュリティ機能を有効にするオプションを提供します。ボリュームグループがセキュリティ対応で、セキュリティキーを設定している場合、チェックボックスを選択してドライブセキュリティを有効にできます。


NOTE: 一度有効にしたドライブセキュリティは、ボリュームグループを削除してドライブを消去しないかぎり解除できません。



 a| 
DA 対応
 a| 
このグループでData Assurance（DA）を使用できるかどうかを示します。Data Assurance（DA）は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。

DAを使用する場合は、DAに対応したボリュームグループを選択します。（DA対応ドライブの場合、プール内に作成されたボリュームではDAが自動的に有効になります）。

ボリュームグループにはDAに対応したドライブとDAに対応していないドライブを含めることができますが、DAを使用するためにはすべてのドライブがDAに対応している必要があります。



 a| 
リソースプロビジョニング対応（EF300およびEF600のみ）
 a| 
このグループでリソースプロビジョニングを使用できるかどうかを示します。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。



 a| 
シェルフ損失の保護
 a| 
シェルフ損失の保護が使用可能かどうかを示します。シェルフ損失の保護が有効な場合、シェルフとの通信が完全に失われた場合でもボリュームグループ内のボリューム上のデータへのアクセスが保証されます。



 a| 
ドロワー損失の保護
 a| 
ドロワー損失の保護を使用できるかどうかを示します。この保護は、使用しているドライブシェルフにドロワーが搭載されている場合にのみ提供されます。ドロワー損失の保護が有効な場合、ドライブシェルフの1台のドロワーとの通信が完全に失われた場合でもボリュームグループ内のボリューム上のデータへのアクセスが保証されます。



 a| 
サポートされるボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
グループ内のボリュームに対して作成できるブロックサイズが表示されます。

** 512n -- 512バイトネイティブ。
** 512e -- 512バイトエミュレート。
** 4k -- 4,096バイト


|===
====
+
.手動方式のドライブの特性
[%collapsible]
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
メディアタイプ
 a| 
メディアタイプを示します。次のメディアタイプがサポートされています。

** ハードドライブ
** ソリッドステートディスク（SSD）


ボリュームグループ内のすべてのドライブのメディアタイプ（すべてのSSDまたはすべてのハードドライブ）が同じである必要があります。ボリュームグループでメディアタイプやインターフェイスタイプを混在させることはできません。



 a| 
ドライブブロックサイズ（EF300およびEF600のみ）
 a| 
グループ内のドライブが書き込み可能なブロックサイズ（セクターサイズ）が表示されます。値は次のとおりです。

** 512 -- 512バイトのセクターサイズ。
** 4K -- 4、096バイトのセクターサイズ。




 a| 
ドライブ容量
 a| 
ドライブの容量を示します。

** ボリュームグループ内の既存のドライブと同じ容量のドライブを可能なかぎり選択してください。
** 容量が小さい未割り当てのドライブを追加する必要がある場合は、ボリュームグループに現在含まれている各ドライブの使用可能容量が削減されることに注意してください。したがって、ドライブ容量はボリュームグループ全体で同じになります。
** 容量が大きい未割り当てのドライブを追加する必要がある場合は、ボリュームグループに現在含まれているドライブの容量に合わせて、追加する未割り当てのドライブの使用可能容量が削減されることに注意してください。




 a| 
トレイ
 a| 
ドライブのトレイの場所を示します。



 a| 
スロット
 a| 
ドライブのスロットの場所を示します。



 a| 
速度（rpm）
 a| 
ドライブの速度を示します。



 a| 
論理セクターサイズ
 a| 
セクターサイズとフォーマットを示します。



 a| 
セキュリティ対応
 a| 
このボリュームグループ候補がセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

** ボリュームグループはドライブセキュリティを使用して保護できますが、この機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。
** FDEのみのボリュームグループを作成する場合は、SecureCapable列で「* Yes-fde」が検索されています。FIPSのみのボリュームグループを作成する場合は、「はい- FIPS *」または「はい- FIPS（混在）」を探します。「Mixed」 は 、140-2レベルドライブと140-3レベルドライブが混在していることを示します。これらのレベルが混在している場合は、ボリュームグループが下位のセキュリティレベル（140-2）で動作することに注意してください。
** セキュリティ対応かどうかがドライブによって異なるボリュームグループや、セキュリティレベルが異なるドライブが混在したボリュームグループを作成することもできます。ボリュームグループにセキュリティ対応でないドライブが含まれている場合、ボリュームグループをセキュリティ対応にすることはできません。




 a| 
DA 対応
 a| 
このグループでData Assurance（DA）を使用できるかどうかを示します。Data Assurance（DA）は、コントローラ経由でドライブとデータをやり取りするときに発生する可能性があるエラーをチェックして修正します。

DAを使用する場合は、DAに対応したボリュームグループを選択します。（DA対応ドライブの場合、プール内に作成されたボリュームではDAが自動的に有効になります）。

ボリュームグループにはDAに対応したドライブとDAに対応していないドライブを含めることができますが、DAを使用するためにはすべてのドライブがDAに対応している必要があります。



 a| 
サポートされるボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
グループ内のボリュームに対して作成できるブロックサイズが表示されます。

** 512n -- 512バイトネイティブ。
** 512e -- 512バイトエミュレート。
** 4k -- 4,096バイト




 a| 
リソースプロビジョニング対応（EF300およびEF600のみ）
 a| 
このグループでリソースプロビジョニングを使用できるかどうかを示します。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。

|===
====

