---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: ボリュームを作成して、アプリケーション固有のワークロードにストレージ容量を追加し、作成したボリュームが特定のホストまたはホストクラスタから認識されるようにします。また、ボリューム作成手順では、作成する各ボリュームに特定の容量を割り当てることもできます。 
---
= ボリュームの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを作成して、アプリケーション固有のワークロードにストレージ容量を追加し、作成したボリュームが特定のホストまたはホストクラスタから認識されるようにします。また、ボリューム作成手順では、作成する各ボリュームに特定の容量を割り当てることもできます。

.タスクの内容
ほとんどのアプリケーションタイプでは、ユーザ定義のボリューム構成がデフォルトで適用されます。一部のアプリケーションタイプでは、ボリュームの作成時にスマートな構成が適用されます。たとえば、Microsoft Exchangeアプリケーション用のボリュームを作成する場合は、必要なメールボックスの数、メールボックスに必要とされる平均容量、およびデータベースのコピーをいくつ作成するかについて設定します。System Managerでは、この情報に基づいてボリュームの構成を最適化します。この構成は、必要に応じて編集することもできます。

ボリュームを作成するプロセスは複数の手順で構成されます。



== 手順1：ボリュームのホストを選択する

ボリュームを作成して、アプリケーション固有のワークロードにストレージ容量を追加し、作成したボリュームが特定のホストまたはホストクラスタから認識されるようにします。また、ボリューム作成手順では、作成する各ボリュームに特定の容量を割り当てることもできます。

.開始する前に
* ホストタイルの下に、有効なホストまたはホストクラスタが存在します。
* ホストに対してホストポート識別子が定義されている。
* DA対応ボリュームを作成する場合は、使用するホスト接続でDAがサポートされている必要があります。ストレージアレイのコントローラのいずれかのホスト接続でDAがサポートされていない場合、関連付けられているホストはDA対応ボリュームのデータにアクセスできません。


.タスクの内容
ボリュームを割り当てる際は、次のガイドラインに注意してください。

* ホストのオペレーティングシステムには、ホストがアクセスできるボリュームの数に制限がある場合があります。特定のホストで使用するボリュームを作成するときは、この制限に注意してください。
* 割り当ては、ストレージアレイ内のボリュームごとに1つずつ定義できます。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* 1つのホストまたはホストクラスタが、同じ論理ユニット番号（LUN）を2回使用してボリュームにアクセスすることはできません。一意のLUNを使用する必要があります。
* ボリュームの作成にかかる時間を短縮するには、ホストの割り当て手順を省略して、新しく作成したボリュームをオフラインで初期化します。


[NOTE]
====
ホストクラスタにボリュームを割り当てようとすると、ホストクラスタ内のいずれかのホストに対して確立されている割り当てと競合している場合、割り当ては失敗します。

====
.手順
. 選択メニュー： Storage [Volumes]
. メニューから[ボリュームの作成]を選択します。
+
Create Volumes（ボリュームの作成）ダイアログボックスが表示されます。

. ドロップダウンリストから、ボリュームを割り当てるホストまたはホストクラスタを選択するか、ホストまたはホストクラスタをあとで割り当てるように選択します。
. 選択したホストまたはホストクラスタのボリューム作成手順を進めるには、*[次へ]*をクリックし、に進みます<<手順2：ボリュームのワークロードを選択する>>。
+
[ワークロードの選択]ダイアログボックスが表示されます。





== 手順2：ボリュームのワークロードを選択する

Microsoft SQL Server、Microsoft Exchange、ビデオ監視アプリケーション、VMwareなど、特定のアプリケーション用のワークロードを選択してストレージアレイの構成をカスタマイズします。このストレージアレイで使用するアプリケーションがリストに表示されない場合は、[その他のアプリケーション]を選択します。

.タスクの内容
このタスクでは、既存のワークロード用のボリュームを作成する方法について説明します。

* アプリケーション固有のワークロードを使用してボリュームを作成する場合_アプリケーションワークロードのI/Oとアプリケーションインスタンスからの他のトラフィックの競合が最小限になるように最適化されたボリューム構成が提示されることがあります。推奨されるボリューム構成を確認し、[ボリュームの追加/編集]ダイアログボックスを使用してシステム推奨のボリュームや特性を編集、追加、削除できます。
* _"other"_applications (または特定のボリューム作成サポートのないアプリケーション)を使用してボリュームを作成する場合は'ボリュームの追加/編集ダイアログ・ボックスを使用してボリューム構成を手動で指定します


.手順
. 次のいずれかを実行します。
+
** 既存のワークロード用のボリュームを作成する場合は、「*既存のワークロード用のボリュームを作成する」オプションを選択します。
** サポート対象のアプリケーションまたは「その他」のアプリケーションに対して新しいワークロードを定義するには、「新しいワークロードを作成」オプションを選択します。
+
*** ドロップダウンリストから、新しいワークロードを作成するアプリケーションの名前を選択します。
+
このストレージアレイで使用するアプリケーションが表示されない場合は、いずれかの[その他]エントリを選択します。

*** 作成するワークロードの名前を入力します。




. 「 * 次へ * 」をクリックします。
. ワークロードがサポート対象のアプリケーションタイプに関連付けられている場合は、必要な情報を入力します。関連付けられていない場合は、に進みます。<<手順3：ボリュームを追加または編集する>>




== 手順3：ボリュームを追加または編集する

選択したアプリケーションまたはワークロードに基づいて、推奨されるボリューム構成がSystem Managerから提示されることがあります。このボリューム構成は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されています。推奨されるボリューム構成をそのまま使用することも、必要に応じて編集することもできます。「その他」のいずれかのアプリケーションを選択した場合は、作成するボリュームと特性を手動で指定する必要があります。

.開始する前に
* プールまたはボリュームグループに十分な空き容量が必要です。
* ボリュームグループに含めることができるボリュームの最大数は256です。
* プールに含めることができるボリュームの最大数は、ストレージシステムのモデルによって異なります。
+
** 2、048ボリューム（EF600およびE5700シリーズ）
** 1、024ボリューム（EF300）
** 512（E2800シリーズ）


* Data Assurance（DA）対応ボリュームを作成する場合は、使用するホスト接続でDAがサポートされている必要があります。
+
.セキュリティ対応のプールまたはボリュームグループの選択
[%collapsible]
====
DA対応ボリュームを作成する場合は、DAに対応したプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルで「DA」の横にある「* Yes」を探します）。

System Managerでは、DA機能はプールおよびボリュームグループのレベルで提供されます。DA保護は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。新しいボリュームにDA対応のプールまたはボリュームグループを選択すると、エラーがあれば検出されて修正されます。

ストレージアレイのコントローラのいずれかのホスト接続でDAがサポートされていない場合、関連付けられているホストはDA対応ボリュームのデータにアクセスできません。

====
* セキュリティ有効ボリュームを作成するには、ストレージアレイのセキュリティキーを作成する必要があります。
+
.セキュリティ対応のプールまたはボリュームグループの選択
[%collapsible]
====
セキュリティ有効ボリュームを作成する場合は、セキュリティ対応のプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルで、「セキュリティ対応」の横にある「はい」*を探します）。

System Managerでは、ドライブセキュリティ機能はプールおよびボリュームグループのレベルで提供されます。セキュリティ対応ドライブは、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止します。セキュリティ有効ドライブでは、一意の暗号化キー_を使用して、書き込み時にデータが暗号化され、読み取り時に復号化されます。

プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でない両方のドライブを含めることができますが、暗号化機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。

====
* リソースプロビジョニングボリュームを作成するには、すべてのドライブがDeallocated or Unwritten Logical Block Error（DULBE）オプションが設定されたNVMeドライブである必要があります。


.タスクの内容
ボリュームはプールまたはボリュームグループから作成します。Add/Edit Volumes（ボリュームの追加/編集）ダイアログボックスには、ストレージアレイ上の使用可能なすべてのプールとボリュームグループが表示されます。対応する各プールおよびボリュームグループについて、使用可能なドライブの数と合計空き容量が表示されます。

一部のアプリケーション固有のワークロードについては、対象となる各プールまたはボリュームグループに、推奨されるボリューム構成に基づく容量が提示され、残りの空き容量（GiB）が表示されます。それ以外のワークロードの場合は、プールまたはボリュームグループにボリュームを追加してレポート容量を指定した時点で容量が提示されます。

.手順
. [その他]とアプリケーション固有のワークロードのどちらを選択したかに基づいて、次のいずれかの操作を実行します。
+
** *その他*：1つ以上のボリュームの作成に使用する各プールまたはボリュームグループで'新しいボリュームの追加をクリックします
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 製品説明 


 a| 
ボリューム名
 a| 
ボリュームには、作成時にSystem Managerによってデフォルトの名前が割り当てられます。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
レポート容量
 a| 
新しいボリュームの容量と使用する容量の単位（MiB、GiB、またはTiB）を定義します。シックボリュームの場合、最小容量は1MiBで、最大容量はプールまたはボリュームグループ内のドライブの数と容量で決まります。

コピーサービス（Snapshotイメージ、Snapshotボリューム、ボリュームコピー、リモートミラー）用のストレージ容量も必要であるため、標準ボリュームにすべての容量を割り当てないでください。

プール内の容量は、ドライブタイプに応じて4GiBまたは8GiB単位で割り当てられます。4GiBまたは8GiBの倍数でない容量は割り当てられていますが、使用できません。すべての容量を使用できるようにするには、4GiBまたは8GiB単位で容量を指定します。使用不可容量が存在する場合、その容量を使用するにはボリュームの容量を増やすしかありません。



 a| 
ボリュームブロックサイズ（EF300およびEF600のみ）
 a| 
ボリュームに対して作成できるブロックサイズが表示されます。

*** 512～512バイト
*** 4k -- 4,096バイト




 a| 
セグメントサイズ
 a| 
セグメントサイジングの設定が表示されます。これは、ボリュームグループ内のボリュームについてのみ表示されます。セグメントサイズを変更してパフォーマンスを最適化できます。

*許容される変更後のセグメントサイズ*-許容される変更後のセグメントサイズがSystem Managerで判別されます。現在のセグメントサイズからの移行に適していないセグメントサイズは、ドロップダウンリストに表示されません。通常、許容されるトランジションは、現在のセグメントサイズの2倍または半分です。たとえば、ボリュームの現在のセグメントサイズが32KiBの場合は、16KiBまたは64KiBの新しいボリュームセグメントサイズが許可されます。

* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiBのセグメントサイズを選択するのは、SSDキャッシュが有効なボリュームで小さいブロックのI/O処理（I/Oブロックサイズが16KiB以下など）を処理する場合のみにしてください。SSDキャッシュが有効なボリュームで大容量ブロックのシーケンシャル処理を処理する場合、セグメントサイズとして4KiBを選択するとパフォーマンスが低下することがあります。

*セグメントサイズの変更にかかる時間*-ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

*** ホストからのI/O負荷
*** ボリュームの修正の優先順位
*** ボリュームグループ内のドライブ数
*** ドライブチャネルの数
*** ストレージアレイコントローラの処理能力


ボリュームのセグメントサイズを変更するとI/Oパフォーマンスに影響しますが、データは引き続き使用できます。



 a| 
セキュリティ対応
 a| 
*「Secure Capable」の横には、プールまたはボリュームグループに属するドライブがセキュア対応である場合のみ「Secure Capable」と表示されます。

ドライブセキュリティを使用すると、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。このオプションは、ドライブセキュリティ機能が有効になっており、ストレージアレイのセキュリティキーが設定されている場合にのみ使用できます。

プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でない両方のドライブを含めることができますが、暗号化機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。



 a| 
DA
 a| 
* 「 DA 」の横には、プールまたはボリュームグループのドライブで Data Assurance （ DA ）がサポートされている場合にのみ「 Yes 」と表示されます。

DAを使用すると、ストレージシステム全体のデータ整合性が向上します。DAを使用すると、データがコントローラ経由でドライブに転送される際にストレージアレイで発生する可能性があるエラーをチェックできます。新しいボリュームにDAを使用すると、エラーがすべて検出されます。



 a| 
リソースプロビジョニング（EF300およびEF600のみ）
 a| 
*はい*ドライブがこのオプションをサポートしている場合にのみ、[リソースのプロビジョニング]の横に表示されます。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。

|===
====
** *アプリケーション固有のワークロード*--選択したワークロードのシステム推奨のボリュームと特性を受け入れるには、[次へ]をクリックします。選択したワークロードのシステム推奨のボリュームと特性を変更、追加、または削除するには、[ボリュームの編集]をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="1a,1a"]
|===
| フィールド | 製品説明 


 a| 
ボリューム名
 a| 
ボリュームには、作成時にSystem Managerによってデフォルトの名前が割り当てられます。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
レポート容量
 a| 
新しいボリュームの容量と使用する容量の単位（MiB、GiB、またはTiB）を定義します。シックボリュームの場合、最小容量は1MiBで、最大容量はプールまたはボリュームグループ内のドライブの数と容量で決まります。

コピーサービス（Snapshotイメージ、Snapshotボリューム、ボリュームコピー、リモートミラー）用のストレージ容量も必要であるため、標準ボリュームにすべての容量を割り当てないでください。

プール内の容量は、ドライブタイプに応じて4GiBまたは8GiB単位で割り当てられます。4GiBまたは8GiBの倍数でない容量は割り当てられていますが、使用できません。すべての容量を使用できるようにするには、4GiBまたは8GiB単位で容量を指定します。使用不可容量が存在する場合、その容量を使用するにはボリュームの容量を増やすしかありません。



 a| 
ボリュームタイプ
 a| 
アプリケーション固有のワークロード用に作成されたボリュームのタイプを示します。



 a| 
ボリュームブロックサイズ（EF300およびEF600のみ）
 a| 
ボリュームに対して作成できるブロックサイズが表示されます。

*** 512～512バイト
*** 4k -- 4,096バイト




 a| 
セグメントサイズ
 a| 
セグメントサイジングの設定が表示されます。これは、ボリュームグループ内のボリュームについてのみ表示されます。セグメントサイズを変更してパフォーマンスを最適化できます。

*許容される変更後のセグメントサイズ*-許容される変更後のセグメントサイズがSystem Managerで判別されます。現在のセグメントサイズからの移行に適していないセグメントサイズは、ドロップダウンリストに表示されません。通常、許容されるトランジションは、現在のセグメントサイズの2倍または半分です。たとえば、ボリュームの現在のセグメントサイズが32KiBの場合は、16KiBまたは64KiBの新しいボリュームセグメントサイズが許可されます。

* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiBのセグメントサイズを選択するのは、SSDキャッシュが有効なボリュームで小さいブロックのI/O処理（I/Oブロックサイズが16KiB以下など）を処理する場合のみにしてください。SSDキャッシュが有効なボリュームで大容量ブロックのシーケンシャル処理を処理する場合、セグメントサイズとして4KiBを選択するとパフォーマンスが低下することがあります。

*セグメントサイズの変更にかかる時間*-ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

*** ホストからのI/O負荷
*** ボリュームの修正の優先順位
*** ボリュームグループ内のドライブ数
*** ドライブチャネルの数
*** ストレージアレイコントローラの処理能力：ボリュームのセグメントサイズを変更すると、I/Oパフォーマンスに影響しますが、データの可用性は維持されます。




 a| 
セキュリティ対応
 a| 
*「Secure Capable」の横には、プールまたはボリュームグループに属するドライブがセキュア対応である場合のみ「Secure Capable」と表示されます。

ドライブセキュリティを使用すると、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。このオプションは、ドライブセキュリティ機能が有効になっていて、ストレージアレイのセキュリティキーが設定されている場合にのみ使用できます。

プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でない両方のドライブを含めることができますが、暗号化機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。



 a| 
DA
 a| 
* 「 DA 」の横には、プールまたはボリュームグループのドライブで Data Assurance （ DA ）がサポートされている場合にのみ「 Yes 」と表示されます。

DAを使用すると、ストレージシステム全体のデータ整合性が向上します。DAを使用すると、データがコントローラ経由でドライブに転送される際にストレージアレイで発生する可能性があるエラーをチェックできます。新しいボリュームにDAを使用すると、エラーがすべて検出されます。



 a| 
リソースプロビジョニング（EF300およびEF600のみ）
 a| 
*はい*ドライブがこのオプションをサポートしている場合にのみ、[リソースのプロビジョニング]の横に表示されます。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。

|===
====


. 選択したアプリケーションのボリューム作成手順を進めるには、*[次へ]*をクリックし、に進みます<<手順4：ボリュームの構成を確認する>>。




== 手順4：ボリュームの構成を確認する

作成するボリュームの概要を確認し、必要に応じて変更を加えます。

.手順
. 作成するボリュームを確認します。[戻る]をクリックして変更を行います。
. ボリューム構成に問題がなければ、「 * 完了 * 」をクリックします。


.結果
選択したプールとボリュームグループに新しいボリュームが作成され、All Volumes（すべてのボリューム）テーブルに新しいボリュームが表示されます。

.終了後
* アプリケーションがボリュームを使用できるように、アプリケーションホストで必要なオペレーティングシステムの変更を実行します。
* オペレーティングシステム固有のユーティリティ（サードパーティベンダーが提供）を実行してから、SMcliコマンドを実行し `-identifyDevices`てボリューム名をホストストレージアレイ名に関連付けます。
+
SMcliは、SANtricityシステムマネージャから直接使用できます。SMcliのダウンロード版は、EF600、EF300、E5700、EF570、E2800、EF280の各コントローラで使用できます。SANtricity システムマネージャからSMcliをダウンロードするには、* Settings *>* System * and * Add-ons *>* Command Line Interface *を選択します。


