---
permalink: sm-storage/create-host-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, manually 
summary: 自動で検出できないホストについては、手動で作成することができます。ホストの作成は、ストレージアレイに接続されているホストを認識させ、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。 
---
= ホストの手動作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動で検出できないホストについては、手動で作成することができます。ホストの作成は、ストレージアレイに接続されているホストを認識させ、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。

.タスクの内容
ホストを作成する際は、次のガイドラインに注意してください。

* ホストに関連付けられたホストポート識別子を定義する必要があります。
* ホストに割り当てられているシステム名と同じ名前を指定してください。
* 選択した名前がすでに使用されている場合、この処理は成功しません。
* 名前の最大文字数は30文字です。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. メニュー： Create [Host] をクリックします。
+
[ホストの作成]ダイアログボックスが表示されます。

. ホストの設定を必要に応じて選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
名前
 a| 
新しいホストの名前を入力します。



 a| 
ホストオペレーティングシステムタイプ
 a| 
新しいホストで実行しているオペレーティングシステムをドロップダウンリストから選択します。



 a| 
ホストインターフェイスタイプ
 a| 
（オプション）ストレージアレイで複数のタイプのホストインターフェイスがサポートされている場合は、使用するホストインターフェイスタイプを選択します。



 a| 
ホストポート
 a| 
次のいずれかを実行します。

** * I/O インターフェイス * を選択します
+
通常、ホストポートはログイン済みで、ドロップダウンリストに表示されます。リストからホストポート識別子を選択できます。

** * 手動で追加 *
+
ホスト ポート識別子がリストに表示されない場合は、ホスト ポートがログインしていません。HBAユーティリティまたはiSCSIイニシエータ ユーティリティを使用して、ホスト ポート識別子を検索してホストに関連付けることができます。

+
ホストポート識別子を手動で入力するか、ユーティリティ（一度に1つずつ）から* Host Ports *フィールドにコピーアンドペーストできます。

+
ホストポート識別子は一度に1つずつ選択してホストに関連付ける必要がありますが、ホストに関連付けられている識別子はいくつでも選択できます。各識別子は、 ［ * ホストポート * ］ フィールドに表示されます。必要に応じて、横の * X * を選択して識別子を削除することもできます。





 a| 
CHAPイニシエータ
 a| 
（オプション）iSCSI IQNを使用してホストポートを選択または手動で入力した場合、Challenge Handshake Authentication Protocol（CHAP）を使用して認証するためにストレージアレイへのアクセスを試みるホストが必要な場合は、* CHAP initiator *チェックボックスをオンにします。選択または手動で入力したiSCSIホストポートごとに、次の手順を実行します。

** CHAP認証用に各iSCSIホストイニシエータに設定したものと同じCHAPシークレットを入力します。双方向CHAP認証（ホストがストレージアレイに対して自身を検証し、ストレージアレイがホストに対して自身を検証できるようにする双方向認証）を使用する場合は、ストレージアレイの初期セットアップ時または設定の変更時にCHAPシークレットも設定する必要があります。
** ホスト認証が不要な場合は、このフィールドを空白のままにします。


現在のところ、System Managerで使用されるiSCSI認証方式はCHAPだけです。

|===
====
. [ 作成（ Create ） ] をクリックします。


.結果
ホストが正常に作成されると、ホストに設定された各ホストポートのデフォルト名（ユーザラベル）が作成されます。

デフォルトのエイリアスは<>``Hostname_Port Number``です。たとえば、用に作成された最初のポートのデフォルトエイリアス `host IPT is IPT_1`です。
