---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, pool, volume group 
summary: ボリュームはプールまたはボリュームグループを使用して作成できます。最適な選択は、主に、想定されるI/Oワークロードなどの主なストレージ要件、パフォーマンス要件、データ保護要件によって異なります。 
---
= プールとボリュームグループのどちらを使用するかを決定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームはプールまたはボリュームグループを使用して作成できます。最適な選択は、主に、想定されるI/Oワークロードなどの主なストレージ要件、パフォーマンス要件、データ保護要件によって異なります。



== プールまたはボリュームグループを選択する理由

*プールを選択*

* 高速なドライブリビルドやストレージ管理の簡易化が必要な場合、シンボリュームが必要な場合、大量のランダムワークロードを実行する場合。
* 各ボリュームのデータをプールを構成する一連のドライブにランダムに分散する場合。
+
プールまたはプール内のボリュームのRAIDレベルを設定または変更することはできません。プールではRAIDレベル6を使用します。



*ボリュームグループを選択*

* システム帯域幅の最大化、ストレージ設定の調整、大量のシーケンシャルワークロードが必要な場合。
* データをRAIDレベルに基づいてドライブに分散する場合。ボリュームグループの作成時にRAIDレベルを指定できます。
* 各ボリュームのデータを、ボリュームグループを構成する一連のドライブに順次書き込む場合。


[NOTE]
====
プールはボリュームグループと共存できるため、ストレージアレイにプールとボリュームグループの両方を含めることができます。

====


== プールとボリュームグループの機能の違い

次の表に、ボリュームグループとプールの機能の比較を示します。

[cols="1a,1a,1a"]
|===
| 使用 | プール | ボリュームグループ 


 a| 
ランダムワークロード
 a| 
より良い
 a| 
良い



 a| 
シーケンシャルワークロード
 a| 
良い
 a| 
より良い



 a| 
ドライブのリビルド時間
 a| 
高速化
 a| 
遅い



 a| 
パフォーマンス（最適モード）
 a| 
Good：小規模ブロックのランダムワークロードに最適です。
 a| 
良好：大規模ブロックのシーケンシャルワークロードに最適



 a| 
パフォーマンス（ドライブリビルドモード）
 a| 
優れている：通常はRAID 6よりも優れている
 a| 
デグレード：パフォーマンスが最大40%低下



 a| 
複数のドライブ障害
 a| 
データ保護機能に優れる：リビルドを優先し、高速に処理
 a| 
データ保護機能が劣る：リビルドが遅く、データ損失のリスクが大きい



 a| 
ドライブの追加
 a| 
高速：オンザフライでプールに追加
 a| 
低速：Dynamic Capacity Expansion処理が必要



 a| 
シンボリュームのサポート
 a| 
はい
 a| 
いいえ



 a| 
ソリッドステートディスク（SSD）のサポート
 a| 
はい
 a| 
はい



 a| 
管理の簡易化
 a| 
はい：構成するホットスペアやRAID設定はありません
 a| 
いいえ：ホットスペアを割り当て、RAIDを構成する必要がある



 a| 
パフォーマンスの調整
 a| 
いいえ
 a| 
はい

|===


== プールとボリュームグループの機能比較

プールとボリュームグループの機能と目的は同じです。どちらのオブジェクトも、ストレージアレイ内に論理的にグループ化された一連のドライブであり、ホストがアクセスできるボリュームの作成に使用されます。

次の表は、プールとボリュームグループのどちらがストレージのニーズに適しているかを判断する際に役立ちます。

[cols="1a,1a,1a"]
|===
| 機能 | プール | ボリュームグループ 


 a| 
異なるRAIDレベルのサポート
 a| 
×（System ManagerではRAID 6のみ）
 a| 
はい。RAID 0、1、10、5、6を使用可能



 a| 
シンボリュームのサポート
 a| 
はい
 a| 
いいえ



 a| 
Full Disk Encryption（FDE）のサポート
 a| 
はい
 a| 
はい



 a| 
Data Assurance（DA）のサポート
 a| 
はい
 a| 
はい



 a| 
シェルフ損失の保護のサポート
 a| 
はい
 a| 
はい



 a| 
ドロワー損失の保護のサポート
 a| 
はい
 a| 
はい



 a| 
ドライブ速度混在のサポート
 a| 
同じにすることをお勧めしますが、必須ではありません。一番低速のドライブにすべてのドライブの速度が合わせられます。
 a| 
同じにすることをお勧めしますが、必須ではありません。一番低速のドライブにすべてのドライブの速度が合わせられます。



 a| 
ドライブ容量混在のサポート
 a| 
同じにすることをお勧めしますが、必須ではありません。一番容量の少ないドライブにすべてのドライブの容量が合わせられます。
 a| 
同じにすることをお勧めしますが、必須ではありません。一番容量の少ないドライブにすべてのドライブの容量が合わせられます。



 a| 
最小ドライブ数
 a| 
11
 a| 
RAIDレベルによって異なります。RAID 0には1が必要です。RAID 1または10には2本（偶数）必要。RAID 5の最小構成は3です。RAID 6の最小構成は5です。



 a| 
最大ドライブ数
 a| 
ストレージアレイの上限まで
 a| 
RAID 1および10：ストレージアレイの上限までRAID 5、6～30ドライブ



 a| 
ボリューム作成時にドライブを個別に選択可能
 a| 
いいえ
 a| 
はい



 a| 
ボリューム作成時にセグメントサイズを指定可能
 a| 
はい。128Kをサポート。
 a| 
はい



 a| 
ボリューム作成時にI/O特性を指定可能
 a| 
いいえ
 a| 
はい。ファイルシステム、データベース、マルチメディア、カスタムをサポート。



 a| 
ドライブ障害からの保護
 a| 
プール内の各ドライブの予約済み容量を使用し、再構築にかかる時間を短縮。
 a| 
ホットスペアドライブを使用します。再構築はドライブのIOPSによって制限されます。



 a| 
容量制限に達したときの警告
 a| 
はい。使用済み容量が最大容量の割合に達したときにアラートを設定できます。
 a| 
いいえ



 a| 
別のストレージアレイへの移行のサポート
 a| 
×（まずボリューム グループに移行する必要がある）
 a| 
はい



 a| 
動的セグメントサイズ（DSS）
 a| 
いいえ
 a| 
はい



 a| 
RAIDレベルを変更可能
 a| 
いいえ
 a| 
はい



 a| 
ボリュームの拡張（容量の拡張）
 a| 
はい
 a| 
はい



 a| 
容量の拡張（容量の追加）
 a| 
はい
 a| 
はい



 a| 
容量の削減
 a| 
はい
 a| 
いいえ

|===
[NOTE]
====
プールまたはボリュームグループでは、ドライブタイプ（HDD、SSD）の混在はサポートされていません。

====