---
permalink: sm-storage/decrease-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, decrease, reserved, capacity 
summary: 容量の削減オプションを使用して、Snapshotグループ、Snapshotボリューム、整合性グループのメンバーボリュームなど、次のストレージオブジェクトのリザーブ容量を削減します。リザーブ容量は、拡張に使用した量だけ削減できます。 
---
= リザーブ容量の削減
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[容量の削減]オプションを使用して、Snapshotグループ、Snapshotボリューム、および整合性グループのメンバーボリュームのリザーブ容量を削減します。リザーブ容量は、拡張に使用した量だけ削減できます。

.開始する前に
* ストレージオブジェクトに複数のリザーブ容量ボリュームが含まれている必要があります。
* ストレージオブジェクトがミラーペアボリュームでないことを確認してください。
* ストレージオブジェクトがSnapshotボリュームの場合は、無効になっているSnapshotボリュームである必要があります。
* ストレージオブジェクトがSnapshotグループの場合は、関連付けられているSnapshotイメージが含まれていないことを確認してください。


.タスクの内容
次のガイドラインを確認してください。

* リザーブ容量ボリュームは、追加したときと逆の順序でのみ削除できます。
* 読み取り専用のSnapshotボリュームについては、関連付けられたリザーブ容量がないため、リザーブ容量を削減することはできません。リザーブ容量が必要なのは、読み取り/書き込みのSnapshotボリュームだけです。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 予約容量*タブをクリックします。
. リザーブ容量を削減するストレージオブジェクトを選択し、*容量の削減*をクリックします。
+
リザーブ容量の削減ダイアログボックスが表示されます。

. リザーブ容量を削減する容量を選択し、*削減*をクリックします。


.結果
System Managerは次の処理を実行します。

* ストレージオブジェクトの容量を更新します。
* ストレージオブジェクトの更新された新しいリザーブ容量が表示されます。
* Snapshotボリュームの容量を削減すると、System ManagerはSnapshotボリュームを自動的に無効状態に移行します。無効は、Snapshotボリュームが現在Snapshotイメージに関連付けられていないため、I/O処理でホストに割り当てることができないことを意味します。

