---
permalink: sm-storage/delete-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, volume 
summary: バックアップまたはソフトウェアアプリケーションのテストに不要になったSnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームを削除できます。 
---
= Snapshotボリュームの削除
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップまたはソフトウェアアプリケーションのテストに不要になったSnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームを削除できます。

Snapshotボリュームに関連付けられているSnapshotリザーブ容量ボリュームを削除するか、またはSnapshotリザーブ容量ボリュームを未割り当てボリュームとして残すかを指定することもできます `read-write`。

.タスクの内容
ベースボリュームを削除すると、関連付けられているSnapshotボリュームまたは整合性グループのSnapshotボリュームが自動的に削除されます。ステータスが「実行中」のボリュームコピーの対象になっているSnapshotボリュームは削除できません。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットボリューム*タブを選択します。
+
ストレージアレイに関連付けられているすべてのSnapshotボリュームが表示されます。

. 削除するSnapshotボリュームを選択し、メニューから「一般的でないタスク」「削除」を選択します。
. 処理を実行することを確認し、* Delete *をクリックします。


.結果
System Managerは次の処理を実行します。

* メンバーであるSnapshotボリュームをすべて削除します（Snapshot整合性グループのSnapshotボリュームの場合）。
* 関連付けられているホスト割り当てをすべて削除します。

