---
permalink: sm-storage/delete-host-or-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, host, host cluster 
summary: ホストまたはホストクラスタを削除できます。 
---
= ホストまたはホストクラスタの削除
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストまたはホストクラスタを削除できます。

.タスクの内容
ホストまたはホストクラスタを削除する際は、次のガイドラインに注意してください。

* ボリュームの割り当てはすべて削除され、関連付けられたボリュームを新しい割り当てに使用できるようになります。
* ホストが属しているホストクラスタに固有の割り当てがある場合、ホストクラスタは影響を受けません。ただし、ホストが属しているホストクラスタに他の割り当てがない場合は、ホストクラスタと他の関連付けられたホストまたはホストポート識別子にデフォルトの割り当てが継承されます。
* ホストに関連付けられていたホストポート識別子は未定義になります。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. 削除するホストまたはホストクラスタを選択し、* Delete *をクリックします。
+
確認のダイアログボックスが表示されます。

. 処理を実行することを確認し、* Delete *をクリックします。


.結果
ホストを削除すると、システムは次の処理を実行します。

* ホストを削除し、該当する場合はホストクラスタから削除します。
* 割り当てられているボリュームへのアクセスを削除します。
* 関連付けられているボリュームの割り当てを解除します。
* ホストに関連付けられているホストポート識別子の関連付けを解除します。


ホストクラスタを削除すると、システムによって次の処理が実行されます。

* ホストクラスタとそれに関連付けられているホスト（存在する場合）を削除します。
* 割り当てられているボリュームへのアクセスを削除します。
* 関連付けられているボリュームの割り当てを解除します。
* ホストに関連付けられているホストポート識別子の関連付けを解除します。

