---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: 既存のプールまたはボリュームグループでリソースのプロビジョニングを有効または無効にすることができます。 
---
= 既存のボリュームグループおよびプールでリソースプロビジョニングを有効または無効にする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DULBE対応ドライブについては、プールまたはボリュームグループ内の既存のボリュームでリソースプロビジョニングを有効または無効にすることができます。

リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。ボリュームに割り当てられているドライブブロックはすべて割り当て解除（マッピング解除）されるため、SSDの摩耗度が向上し、最大書き込みパフォーマンスが向上します。

デフォルトでは、ドライブがDULBEをサポートするシステムでリソースプロビジョニングが有効になっています。以前にリソースプロビジョニングを無効にしていないかぎり、リソースプロビジョニングを有効にする必要はありません。

.開始する前に
* EF300またはEF600ストレージアレイが必要です。
* NVMeのDeallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能がすべてのドライブでサポートされているSSDボリュームグループまたはプールが必要です。そうしないと、リソースプロビジョニングオプションは使用できません。


.タスクの内容
既存のボリュームグループおよびプールに対してリソースプロビジョニングを有効にすると、選択したボリュームグループまたはプール内のすべてのボリュームが変更されてブロックの割り当てが解除されます。このプロセスには、UNMAPの粒度で一貫した割り当てを確保するためのバックグラウンド処理が含まれる場合があります。この処理では、スペースのマッピングは解除されません。バックグラウンド処理が完了したら、オペレーティングシステムは未使用のブロックのマッピングを解除して空きスペースを確保する必要があります。

既存のボリュームグループまたはプールのリソースプロビジョニングを無効にすると、バックグラウンド処理によってすべてのボリューム内のすべての論理ブロックが書き換えられます。既存のデータはそのまま維持されます。書き込みでは、ボリュームグループまたはプールに関連付けられたドライブのブロックがマッピングまたはプロビジョニングされます。


NOTE: 新しいボリュームグループおよびプールについては、メニューからリソースのプロビジョニングを有効または無効にできます。設定[システム]、[追加設定]、[リソースプロビジョニングボリュームの有効化/無効化]の順に選択します。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. リストからプールまたはボリュームグループを1つ選択します。
+
プールまたはボリュームグループは一度に1つだけ選択できます。リストを下にスクロールして、他のプールまたはボリュームグループを確認します。

. [一般的でないタスク]を選択し、[リソースプロビジョニングを有効にする]または[リソースプロビジョニングを無効にする]のいずれかを選択します。
. ダイアログボックスで、処理を確認します。



NOTE: *DULBEを再度有効にした場合--バックグラウンド処理が完了した後'ホストを再起動してDULBE設定の変更を検出し'すべてのファイルシステムを再マウントする必要がある場合があります
