---
permalink: sm-storage/disable-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, snapshot, volume 
summary: Snapshotボリューム、またはSnapshot整合性グループのSnapshotボリュームが不要になった場合や一時的に使用を停止する場合は、それらのボリュームを無効にすることができます。 
---
= Snapshotボリュームの無効化
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotボリューム、またはSnapshot整合性グループのSnapshotボリュームが不要になった場合や一時的に使用を停止する場合は、それらのボリュームを無効にすることができます。

.タスクの内容
次のいずれかの条件に該当する場合は、[Disable]オプションを使用します。

* SnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームをしばらく使用しない。
* あとでSnapshotボリュームまたはSnapshot整合性グループのSnapshotボリューム（読み取り/書き込み用）を再作成する予定があり、再度作成する必要がないように関連付けられているリザーブ容量を残したい。
* 読み書き可能なSnapshotボリュームへの書き込みアクティビティを停止して、ストレージアレイのパフォーマンスを向上させたい。


SnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームが読み取り/書き込みの場合、このオプションを使用すると、関連付けられているリザーブ容量ボリュームへの以降の書き込みアクティビティも停止できます。SnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームを再作成する場合は、同じベースボリュームからSnapshotイメージを選択する必要があります。

[NOTE]
====
SnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームがオンラインコピー関係の一部である場合、[無効化]オプションは実行できません。

====
.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットボリューム*タブを選択します。
+
ストレージアレイに関連付けられているすべてのSnapshotボリュームが表示されます。

. 無効にするSnapshotボリュームを選択し、メニューから「一般的でないタスク」「無効」を選択します。
. 操作を実行することを確認し、[*Disable*]をクリックします。


.結果
* Snapshotボリュームのベースボリュームへの関連付けは維持されます。
* SnapshotボリュームのWorld Wide Name（WWN；ワールドワイド名）は保持されます。
* 読み取り/書き込みの場合、Snapshotボリュームに関連付けられているリザーブ容量は保持されます。
* Snapshotボリュームのホストの割り当てとアクセスは保持されます。ただし、読み取り/書き込み要求は失敗します。
* SnapshotボリュームのSnapshotイメージとの関連付けは解除されます。

