---
permalink: sm-storage/enable-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, security, pool, volume group 
summary: プールまたはボリュームグループに対してドライブセキュリティを有効にすると、プールまたはボリュームグループに含まれているドライブ上のデータへの不正アクセスを防止できます。ドライブの読み取り/書き込みアクセスは、セキュリティキーが設定されたコントローラからのみ使用できます。 
---
= プールまたはボリュームグループのセキュリティを有効にする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールまたはボリュームグループに対してドライブセキュリティを有効にすると、プールまたはボリュームグループに含まれているドライブ上のデータへの不正アクセスを防止できます。ドライブの読み取り/書き込みアクセスは、セキュリティキーが設定されたコントローラからのみ使用できます。

.開始する前に
* ドライブセキュリティ機能が有効になっている必要があります。
* セキュリティキーを作成する必要があります。
* プールまたはボリュームグループの状態が最適lである必要があります。
* プールまたはボリュームグループ内のすべてのドライブがセキュリティ対応ドライブである必要があります。


.タスクの内容
ドライブセキュリティを使用する場合は、セキュリティ対応のプールまたはボリュームグループを選択します。プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でない両方のドライブを含めることができますが、暗号化機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。

セキュリティを有効にしたあとに削除するには、プールまたはボリュームグループを削除してからドライブを消去する必要があります。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. セキュリティを有効にするプールまたはボリュームグループを選択し、[メニュー:その他のセキュリティの有効化]をクリックします。
+
[Confirm Enable Security]ダイアログボックスが表示されます。

. 選択したプールまたはボリュームグループのセキュリティを有効にすることを確認し、*有効*をクリックします。

