---
permalink: sm-storage/host-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, terms 
summary: ストレージアレイに関連するホストの用語を次に示します。 
---
= ホストの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するホストの用語を次に示します。

[cols="25h,~"]
|===
| コンポーネント | 定義 


 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
ホスト名
 a| 
ホスト名は、ホストのシステム名に相当します。



 a| 
ホストクラスタ
 a| 
ホストクラスタはホストのグループです。ホストクラスタを作成すると、同じボリュームを複数のホストに簡単に割り当てることができます。



 a| 
ホストインターフェイスプロトコル
 a| 
ホストインターフェイスプロトコルは、コントローラとホストの間の接続（Fibre ChannelやiSCSIなど）です。



 a| 
HBAまたはネットワークインターフェイスカード（NIC）
 a| 
ホストバスアダプタ（HBA）はホストに搭載されるボードで、1つ以上のホストポートが搭載されています。



 a| 
ホストポート
 a| 
ホストポートは、コントローラに物理的に接続されるホストバスアダプタ（HBA）のポートで、I/O処理に使用されます。



 a| 
ホストポート識別子
 a| 
ホストポート識別子は、ホストバスアダプタ（HBA）上の各ホストポートに関連付けられた一意のワールドワイド名です。

* Internet Small Computer System Interface（iSCSI）ホストポート識別子は、1 ~ 233文字で指定する必要があります。iSCSIホストポート識別子は、標準のIQN形式（など）で表示されます。 `iqn.xxx.com.xxx:8b3ad`
* Fibre ChannelやSerial Attached SCSI（SAS；シリアル接続SCSI）など、iSCSI以外のホストポート識別子は、2文字ごとにコロンで区切って表示されます（など） `xx:yy:zz`。Fibre Channelのホストポート識別子は16文字にする必要があります。




 a| 
ホストオペレーティングシステムタイプ
 a| 
ホストオペレーティングシステムタイプは、ホストのオペレーティングシステム（またはそのバージョン）に応じて、ストレージアレイ内のコントローラによるI/Oの処理方法を定義する設定です。これは、_host type_for shortとも呼ばれます。



 a| 
コントローラのホストポート
 a| 
コントローラホストポートは、ホストに物理的に接続されるコントローラのポートで、I/O処理に使用されます。



 a| 
LUN
 a| 
Logical Unit Number（LUN；論理ユニット番号）は、ホストがボリュームへのアクセスに使用する番号で、アドレススペースに割り当てられます。ボリュームは、LUNの形式で容量としてホストに提示されます。

各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを異なるホストで使用して、異なるボリュームにアクセスできます。

|===