---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: ボリュームは、ストレージアレイ上のストレージスペースを管理および編成するデータコンテナです。 
---
= ボリュームの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームは、ストレージアレイ上のストレージスペースを管理および編成するデータコンテナです。

ストレージアレイで使用可能なストレージ容量からボリュームを作成し、システムのリソースを簡単に整理して使用できます。この概念は、コンピュータ上のフォルダ/ディレクトリを使用してファイルを整理し、簡単かつ迅速にアクセスできるようにするのと似ています。

ボリュームは、ホストから認識できる唯一のデータレイヤです。SAN環境では、論理ユニット番号（LUN）にマッピングされたボリュームをホストから認識できます。LUNには、ストレージアレイでサポートされている1つ以上のホストアクセスプロトコル（FC、iSCSI、SASなど）を使用してアクセス可能なユーザデータが格納されます。



== プールおよびボリュームグループから作成できるボリュームタイプ

ボリュームは、プールまたはボリュームグループから容量を取得します。ストレージアレイ上のプールまたはボリュームグループから次のタイプのボリュームを作成できます。

* *プールから*--プールからは、_フルプロビジョニング（シック）ボリューム_または_シンプロビジョニング（シン）ボリュームとしてボリュームを作成できます。_
+
[NOTE]
====
System Managerインターフェイスには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====
* *ボリュームグループから*--ボリュームグループからボリュームを作成できるのは_完全にプロビジョニングされた（シック）ボリューム_のみです。


シックボリュームとシンボリュームは、次の方法でストレージアレイから容量を取得します。

* シックボリュームの容量は、ボリュームの作成時に割り当てられます。
* シンボリュームの容量は、ボリュームへの書き込み時にデータとして割り当てられます。


シンプロビジョニングを使用すると、容量の無駄な割り当てを回避し、ストレージの先行投資を抑えることができます。ただし、シックボリュームの作成時にすべてのストレージが一度に割り当てられるため、フルプロビジョニングの場合はレイテンシが低減されます。

[NOTE]
====
EF600およびEF300ストレージシステムでは、シンプロビジョニングはサポートされません。

====


== ボリュームの特性

プールまたはボリュームグループ内の各ボリュームには、格納するデータのタイプに基づいた独自の特性があります。次のような特徴があります。

* *セグメントサイズ*-セグメントは、あるドライブに格納されるデータの量（KiB）です。この量に達すると、ストライプ（RAIDグループ）内の次のドライブへと進みます。セグメントサイズがボリュームグループの容量以下である。プールのセグメントサイズは固定であり、変更することはできません。
* *容量*-プールまたはボリュームグループの空き容量からボリュームを作成します。ボリュームを作成するには、プールまたはボリュームグループがすでに存在していて、ボリュームを作成するための十分な空き容量がプールまたはボリュームグループにある必要があります。
* *コントローラ所有権*--すべてのストレージアレイは'1台または2台のコントローラを持つことができますシングルコントローラアレイでは、ボリュームのワークロードが1台のコントローラで管理されます。デュアル・コントローラ・アレイでは'ボリュームを「所有」する優先コントローラ（AまたはB）がボリュームに割り当てられますデュアルコントローラ構成では、自動ロードバランシング機能を使用してボリューム所有権が自動的に調整され、コントローラ間でワークロードが移動する際の負荷分散の問題が修正されます。自動ロードバランシングは、I/Oワークロードを自動で分散し、ホストからの受信I/Oトラフィックを動的に管理して両方のコントローラに分散します。
* *ボリューム割り当て*--ボリュームの作成時または後で、ホストにボリュームへのアクセス権を与えることができます。すべてのホストアクセスは、Logical Unit Number（LUN；論理ユニット番号）を使用して管理されます。ホストは、ボリュームに割り当てられているLUNを検出します。ボリュームを複数のホストに割り当てる場合は、クラスタリングソフトウェアを使用して、すべてのホストでボリュームを使用できるようにします。
+
ホストタイプでは、ホストがアクセスできるボリュームの数を制限できます。特定のホストで使用するボリュームを作成するときは、この制限に注意してください。

* *わかりやすい名前*--ボリュームに任意の名前を付けることができますが、わかりやすい名前にすることをお勧めします。


ボリュームの作成時には、各ボリュームに容量が割り当てられ、名前、セグメントサイズ（ボリュームグループのみ）、コントローラ所有権、およびボリュームとホストの割り当てが割り当てられます。ボリュームデータは、必要に応じてコントローラ間で自動的に負荷分散されます。
