---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: リザーブ容量は、Snapshotや非同期ミラーリング処理などのコピーサービス処理がボリュームに提供されている場合に自動的に作成されます。 
---
= リザーブ容量の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リザーブ容量は、Snapshotや非同期ミラーリング処理などのコピーサービス処理がボリュームに提供されている場合に自動的に作成されます。

リザーブ容量の目的は、何らかの不具合が発生した場合に備えて、これらのボリューム上のデータ変更を保存することです。ボリュームと同様に、リザーブ容量はプールまたはボリュームグループから作成されます。



== リザーブ容量を使用するコピーサービスオブジェクト

リザーブ容量は、次のコピーサービスオブジェクトで使用される基盤となるストレージメカニズムです。

* Snapshotクルウフ
* 読み取り/書き込みSnapshotボリューム
* 整合性グループメンバーボリューム
* ミラアヘアホリユウム


これらのコピーサービスオブジェクトを作成または拡張するときは、プールまたはボリュームグループから新しいリザーブ容量を作成する必要があります。リザーブ容量は、通常、Snapshot処理の場合はベースボリュームの40%、非同期ミラーリング処理の場合はベースボリュームの20%です。ただし、リザーブ容量は元のデータに対する変更の回数によって異なります。



== シンボリュームとリザーブ容量

シンボリュームの場合、最大レポート容量の256TiBに達していると容量を拡張できません。シンボリュームのリザーブ容量が最大レポート容量よりも大きいサイズに設定されていることを確認してください。（シンボリュームは常にシンプロビジョニングされます。つまり、ボリュームにデータが書き込まれるときに容量が割り当てられます）。

プール内のシンボリュームを使用してリザーブ容量を作成する場合は、リザーブ容量に関する次の操作と結果を確認してください。

* シンボリュームのリザーブ容量に障害が発生した場合、シンボリューム自体は自動的に失敗状態に移行しません。ただし、シンボリュームに対するI/O処理はすべてリザーブ容量ボリュームにアクセスする必要があるため、I/O処理では常にCheck Conditionが要求元ホストに返されます。リザーブ容量ボリュームの根本的な問題を解決できる場合は、リザーブ容量ボリュームが最適な状態に戻り、シンボリュームが再び機能するようになります。
* 既存のシンボリュームを使用して非同期ミラーペアを作成する場合、そのシンボリュームは新しいリザーブ容量ボリュームで再初期化されます。初期同期プロセス中は、プライマリ側のプロビジョニングされたブロックのみが転送されます。




== 容量のアラート

コピーサービスオブジェクトには、容量の警告とアラートのしきい値を設定できるほか、リザーブ容量がフルになったときの応答も設定できます。

コピーサービスオブジェクトボリュームのリザーブ容量が上限に近づくと、ユーザにアラートが発行されます。デフォルトでは、リザーブ容量ボリュームの使用率が75%に達したときにこのアラートが生成されますが、必要に応じて増減できます。このアラートを受け取った場合は、その時点でリザーブ容量ボリュームの容量を増やすことができます。この点で、各コピーサービスオブジェクトは個別に設定できます。



== 孤立したリザーブ容量ボリューム

孤立したリザーブ容量ボリュームは、関連付けられているコピーサービスオブジェクトが削除されたため、コピーサービス処理のデータを格納しなくなったボリュームです。コピーサービスオブジェクトが削除されたときにリザーブ容量ボリュームも削除されている必要があります。ただし、リザーブ容量ボリュームを削除できませんでした。

孤立したリザーブ容量ボリュームは、どのホストからもアクセスできないため、再生候補となります。孤立したリザーブ容量ボリュームを手動で削除して、その容量を他の処理で使用できるようにします。

System Managerは、[ホーム]ページの[通知]領域に「未使用容量の再生」というメッセージを表示して、孤立したリザーブ容量ボリュームについて警告します。未使用容量を再利用する*をクリックすると、未使用容量の再生ダイアログボックスが表示され、孤立したリザーブ容量ボリュームを削除できます。



== リザーブ容量の特性

* 十分な空き容量を保持するために、ボリュームの作成時にはリザーブ容量に割り当てられる容量を考慮する必要があります。
* リザーブ容量はベースボリュームよりも小さくすることができます（最小サイズは8MiB）。
* 一部のスペースはメタデータによって消費されますが、ごくわずか（192KiB）なので、リザーブ容量ボリュームのサイズを特定する際に考慮する必要はありません。
* リザーブ容量は、ホストから直接読み取りまたは書き込みすることはできません。
* リザーブ容量は、読み取り/書き込みSnapshotボリューム、Snapshotグループ、整合性グループメンバーボリューム、ミラーペアボリュームごとに確保されます。

