---
permalink: sm-storage/how-volumes-are-assigned-to-hosts-and-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, assigned, hosts, clusters 
summary: ホストまたはホストクラスタからボリュームにI/Oを送信するには、ボリュームをホストまたはホストクラスタに割り当てる必要があります。 
---
= ホストおよびホストクラスタへのボリュームの割り当て方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストまたはホストクラスタからボリュームにI/Oを送信するには、ボリュームをホストまたはホストクラスタに割り当てる必要があります。

ボリュームの作成時にホストまたはホストクラスタを選択するか、あとでホストまたはホストクラスタにボリュームを割り当てることができます。ホストクラスタはホストのグループです。ホストクラスタを作成すると、同じボリュームを複数のホストに簡単に割り当てることができます。

ホストへのボリュームの割り当ては柔軟性が高く、ストレージの特定のニーズを満たすことができます。

* *ホストクラスタの一部ではなく、スタンドアロンホスト*--ボリュームを個々のホストに割り当てることができます。ボリュームにアクセスできるのは1つのホストだけです。
* *ホストクラスタ*--ボリュームをホストクラスタに割り当てることができますこのボリュームには、ホストクラスタ内のすべてのホストからアクセスできます。
* *ホストクラスタ内のホスト*--ホストクラスタの一部である個別のホストにボリュームを割り当てることができますホストはホストクラスタの一部ですが、ボリュームにアクセスできるのは個 々 のホストだけで、ホストクラスタ内の他のホストからはアクセスできません。


ボリュームの作成時に、論理ユニット番号（LUN）が自動的に割り当てられます。LUNは、I/O処理中のホストとコントローラの間の「アドレス」の役割を果たします。LUNはボリュームが作成されたあとに変更できます。
