---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: SSDキャッシュ機能は、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることでシステムのパフォーマンスを動的に向上させるコントローラベースの解決策 です。SSDキャッシュは、ホスト読み取りにのみ使用されます。 
---
= SSDキャッシュの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュ機能は、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることでシステムのパフォーマンスを動的に向上させるコントローラベースの解決策 です。SSDキャッシュは、ホスト読み取りにのみ使用されます。



== SSDキャッシュとプライマリキャッシュ

SSDキャッシュはセカンダリキャッシュであり、コントローラの動的ランダムアクセスメモリ（DRAM）にあるプライマリキャッシュと組み合わせて使用されます。

SSDキャッシュはプライマリキャッシュとは動作が異なります。

* プライマリキャッシュの場合、I/O処理ごとにキャッシュを介してデータをステージングする必要があります。
+
プライマリキャッシュでは、ホスト読み取り後にデータがDRAMに格納されます。

* SSDキャッシュは、データをキャッシュに配置してシステムの全体的なパフォーマンスを向上できる場合にのみ使用されます。
+
SSDキャッシュでは、データはボリュームからコピーされて2つの内部RAIDボリューム（コントローラごとに1つ）に格納されます。RAIDボリュームはSSDキャッシュの作成時に自動的に作成されます。



内部RAIDボリュームは、内部的なキャッシュ処理に使用されます。これらのボリュームにはアクセスできず、ユーザインターフェイスにも表示されません。ただし、ストレージアレイで許可されるボリュームの総数には、これら2つのボリュームが含まれます。



== SSDキャッシュの使用方法

インテリジェントキャッシングは、低レイテンシのドライブにデータを配置するため、そのデータに対する以降の要求への応答時間を大幅に短縮できます。キャッシュ内のデータをプログラムが要求すると(キャッシュヒットと呼ばれます)'低遅延ドライブはそのトランザクションを処理できますそれ以外の場合は「キャッシュミス」が発生し、元の低速ドライブからデータにアクセスする必要があります。キャッシュヒット数が増えると、全体的なパフォーマンスが向上します。

ホストプログラムがストレージアレイのドライブにアクセスすると、データはSSDキャッシュに格納されます。ホストプログラムが再度同じデータにアクセスすると、そのデータはハードドライブではなくSSDキャッシュから読み取られます。よくアクセスされるデータはSSDキャッシュに格納されます。ハードドライブは、SSDキャッシュからデータを読み取ることができない場合にのみアクセスされます。

SSDキャッシュは、データをキャッシュに配置して全体的なシステムパフォーマンスを向上できる場合にのみ使用されます。

CPUが読み取りデータを処理する必要がある場合は、次の手順に従います。

. DRAMキャッシュをチェックします。
. DRAMキャッシュで検出されない場合は、SSDキャッシュをチェックします。
. SSDキャッシュで見つからない場合は、ハードドライブから取得します。データをキャッシュする価値があると判断された場合は、SSDキャッシュにコピーします。




== パフォーマンスの向上

最もアクセス頻度の高いデータ（ホットスポット）をSSDキャッシュにコピーすることで、ハードディスクの処理効率が向上し、レイテンシが低減され、読み取りと書き込みの速度が向上します。ハイパフォーマンスのSSDを使用してHDDボリュームのデータをキャッシュすると、I/Oパフォーマンスと応答時間が向上します。

SSDキャッシュとの間のデータの移動には、単純なボリュームI/Oのメカニズムが使用されます。データがキャッシュされてSSDに格納されると、そのデータの以降の読み取りはSSDキャッシュで実行されるため、HDDボリュームにアクセスする必要はありません。



== SSDキャッシュとドライブセキュリティ機能

ドライブセキュリティを使用している（セキュリティ有効）ボリュームでSSDキャッシュを使用する場合は、そのボリュームとSSDキャッシュのドライブセキュリティ機能が同じである必要があります。同じでない場合、ボリュームはセキュリティ有効になりません。



== SSDキャッシュの実装

SSDキャッシュを実装するには、次の手順を実行します。

. SSDキャッシュを作成します。
. SSD読み取りキャッシュを実装するボリュームにSSDキャッシュを関連付けます。


[NOTE]
====
コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシング転送の対象になりません。

====