---
permalink: sm-storage/how-does-my-selected-workload-impact-volume-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workload, impact, volume, 
summary: ボリュームの作成時に、ワークロードの用途に関する情報を入力するように求められます。この情報に基づいてボリュームの最適な構成が作成され、必要に応じて編集することもできます。必要に応じて、ボリューム作成のこの手順を省略できます。 
---
= 選択したワークロードはボリュームの作成にどのように影響しますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームの作成時に、ワークロードの用途に関する情報を入力するように求められます。この情報に基づいてボリュームの最適な構成が作成され、必要に応じて編集することもできます。必要に応じて、ボリューム作成のこの手順を省略できます。

ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロード（インスタンス）を定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

* *アプリケーション固有*--アプリケーション固有のワークロードを使用してボリュームを作成する場合、アプリケーションワークロードのI/Oとアプリケーションインスタンスからの他のトラフィックの競合を最小限に抑えるために最適化されたボリューム構成が推奨される場合があります。I/Oタイプ、セグメントサイズ、コントローラ所有権、読み取りキャッシュと書き込みキャッシュなどのボリューム特性が自動的に推奨され、次のアプリケーションタイプ用に作成されるワークロードに合わせて最適化されます。
+
** Microsoft®SQL Server™
** Microsoft®Exchange Server™
** ビデオ監視アプリケーション
** VMware ESXi™（仮想マシンファイルシステムで使用するボリューム用）
+
推奨されるボリューム構成を確認し、[ボリュームの追加/編集]ダイアログボックスを使用してシステム推奨のボリュームや特性を編集、追加、削除できます。



* *その他*（または特定のボリューム作成サポートのないアプリケーション）- 特定のアプリケーションに関連付けられていないワークロードを作成する場合や、ストレージアレイで使用する予定のアプリケーションに対する最適化が組み込まれていない場合は、その他のワークロードではボリューム構成を手動で指定する必要があります。[ボリュームの追加/編集]ダイアログボックスを使用して、ボリューム構成を手動で指定する必要があります。

