---
permalink: sm-storage/how-do-i-know-which-host-operating-system-type-is-correct.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host operating system, type, 
summary: '[Host Operating System Type]フィールドには、ホストのオペレーティングシステムが表示されます。推奨されるホストタイプをドロップダウンリストから選択できます。' 
---
= 正しいホストオペレーティングシステムタイプを確認するにはどうすればよいですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Host Operating System Type]フィールドには、ホストのオペレーティングシステムが表示されます。推奨されるホストタイプをドロップダウンリストから選択できます。

ドロップダウンリストに表示されるホストタイプは、ストレージアレイのモデルとファームウェアバージョンによって異なります。最新バージョンでは、最も一般的なオプションが最初に表示されます。最も適切なオプションが表示されます。このリストの表示は、このオプションが完全にサポートされていることを意味するものではありません。

[NOTE]
====
ホストサポートの詳細については、を参照して https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^]ください。

====
次のホストタイプの一部がリストに表示されます。

[cols="35h,~"]
|===
| ホストオペレーティングシステムタイプ | オペレーティングシステム（OS）とマルチパスドライバ 


 a| 
Linux DM-MP（カーネル3.10以降）
 a| 
Device Mapperマルチパスフェイルオーバーソリューションと3.10以降のカーネルを使用するLinuxオペレーティングシステムをサポートします。



 a| 
VMware ESXi
 a| 
VMwareビルトインのストレージアレイタイプポリシーモジュールSATP_ALUAを使用してNative Multipathing Plug-in（NMP）アーキテクチャを実行するVMware ESXiオペレーティングシステムをサポートします。



 a| 
Windows（クラスタまたは非クラスタ）
 a| 
ATTOマルチパスドライバを実行しないWindowsクラスタ構成または非クラスタ構成をサポートします。



 a| 
ATTOクラスタ（すべてのオペレーティングシステム）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するすべてのクラスタ構成をサポートします。



 a| 
Linux（Veritas DMP）
 a| 
Veritas DMPマルチパスソリューションを使用するLinuxオペレーティングシステムをサポートします。



 a| 
Linux（ATTO）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するLinuxオペレーティングシステムをサポートします。



 a| 
Mac OS（ATTO）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するMac OSバージョンをサポートします。



 a| 
Windows（ATTO）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するWindowsオペレーティングシステムをサポートします。



 a| 
FlexArray（ALUA）
 a| 
マルチパスにALUAを使用するNetApp FlexArrayシステムをサポートします。



 a| 
IBM SVC
 a| 
IBM SAN Volume Controller構成をサポートします。



 a| 
工場出荷時のデフォルト
 a| 
ストレージアレイの初期起動用に予約されています。ホストオペレーティングシステムタイプが[工場出荷時のデフォルト]に設定されている場合は、接続されているホストで実行されているホストオペレーティングシステムとマルチパスドライバに合わせて変更します。



 a| 
Linux DM-MP（カーネル3.9以前）
 a| 
Device Mapperマルチパスフェイルオーバーソリューションと3.9以前のカーネルを使用するLinuxオペレーティングシステムをサポートします。



 a| 
Windowsクラスタ（廃止）
 a| 
ホストオペレーティングシステムタイプがこの値に設定されている場合は、代わりにWindows（クラスタまたは非クラスタ）設定を使用します。

|===