---
permalink: sm-storage/how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, statistics 
summary: SSDキャッシュについては、一般統計と詳細統計を表示できます。一般統計は詳細統計のサブセットです。 
---
= SSDキャッシュのすべての統計を表示および表示するにはどうすればよいですか？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュについては、一般統計と詳細統計を表示できます。一般統計は詳細統計のサブセットです。

詳細統計は、すべてのSSD統計をファイルにエクスポートした場合にのみ表示でき `.csv`ます。統計を確認および解釈する際には、複数の統計を組み合わせることで見えてくる情報もあることに注意してください。



== 一般統計

SSDキャッシュの統計を表示するには、次のメニューを選択します。Storage [Pools & Volume Groups]統計を表示するSSDキャッシュを選択し、メニューを選択します。More [View Statistics]一般統計は[SSDキャッシュの統計を表示]ダイアログに表示されます。

次に、詳細統計のサブセットである一般統計を示します。

[cols="25h,~"]
|===
| 一般統計 | 製品説明 


 a| 
読み取り/書き込み
 a| 
SSDキャッシュが有効なボリュームに対するホストの読み取りと書き込みの合計数。読み取り数を書き込み数と比較します。効率的なSSDキャッシュ処理には、読み取り数が書き込み数より多いことが必要です。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
キャッシュヒット
 a| 
キャッシュヒットの数。



 a| 
キャッシュヒット(%)
 a| 
キャッシュヒット数を読み取り+書き込み数で割った値。効果的なSSDキャッシュ処理には、キャッシュヒットの割合が50%以上である必要があります。数値が小さい場合は、次のような場合があります。

* 書き込みに対する読み取りの比率が小さすぎる
* 読み取りが繰り返されない
* キャッシュ容量が小さすぎる




 a| 
キャッシュ割り当て率（%）
 a| 
割り当てられているSSDキャッシュストレージの量。このコントローラで使用可能なSSDキャッシュストレージの割合として表されます。割り当てられたバイト数を使用可能なバイト数で割った値。キャッシュ割り当ての割合は、通常は100%と表示されます。この数値が100%未満の場合は、キャッシュがウォームアップされていないか、アクセスされているすべてのデータよりもSSDキャッシュ容量が大きいことを意味します。後者の場合は、SSDキャッシュ容量を小さくしても同じレベルのパフォーマンスを提供できます。この値は、キャッシュされたデータがSSDキャッシュに配置されたことを示しているわけではなく、SSDキャッシュにデータを配置可能となる前の準備手順にすぎません。



 a| 
キャッシュ使用率（%）
 a| 
有効なボリュームのデータが格納されているSSDキャッシュストレージの量。割り当てられているSSDキャッシュストレージの割合として表されます。この値はSSDキャッシュの利用率または密度を表し、ユーザデータのバイト数を割り当てられているバイト数で割った値です。キャッシュ使用率のパーセンテージは通常100%より低く、おそらくはるかに低くなります。この数値は、SSDキャッシュ容量のうち、キャッシュデータが書き込まれている割合を示します。SSDキャッシュの各割り当て単位（SSDキャッシュブロック）はサブブロックと呼ばれる小さい単位に分割され、サブブロックにはある程度独立してデータが格納されるため、この数値は100%未満です。数値が大きいほど一般的には優れていますが、数値が小さい場合でもパフォーマンスが大幅に向上する可能性があります。

|===


== 詳細統計

詳細統計は、一般統計とその他の統計で構成されます。これらの追加の統計は一般統計と一緒に保存されますが、一般統計とは異なり、[SSDキャッシュの統計を表示]ダイアログには表示されません。詳細統計を表示するには、統計をファイルにエクスポートする `.csv`必要があります。

ファイルを表示する `.csv`と、一般統計のあとに詳細統計が表示されます。

[cols="25h,~"]
|===
| 詳細統計 | 製品説明 


 a| 
読み取りブロック
 a| 
ホスト読み取りのブロック数。



 a| 
書き込みブロック
 a| 
ホスト書き込みのブロック数。



 a| 
フルヒットブロック
 a| 
キャッシュヒットのブロック数。フルヒットブロックは、SSDキャッシュから完全に読み取られたブロックの数を示します。SSDキャッシュのパフォーマンスが向上するのは、フルキャッシュヒットの処理に対してのみです。



 a| 
部分ヒット
 a| 
すべてのブロックではなく、少なくとも1つのブロックがSSDキャッシュ内にあったホスト読み取りの数。部分ヒットはSSDキャッシュ*ミス*で、読み取りはベースボリュームから行われています。



 a| 
部分ヒット-ブロック
 a| 
[部分ヒット]のブロック数。部分キャッシュヒットと部分キャッシュヒットブロックは、SSDキャッシュにデータの一部しかない処理の結果として発生します。この場合、キャッシュされたハードディスクドライブ（HDD）ボリュームからデータを取得する必要があります。このタイプのヒットの場合、SSDキャッシュから得られるパフォーマンス上のメリットはありません。部分キャッシュヒットブロック数が完全キャッシュヒットブロック数よりも多い場合は、別のI/O特性タイプ（ファイルシステム、データベース、またはWebサーバ）を使用するとパフォーマンスが向上する可能性があります。SSDキャッシュのウォームアップ中は、[キャッシュヒット]と比較して[部分キャッシュヒット]と[キャッシュミス]の数が多くなることが想定されます。



 a| 
ミス
 a| 
SSDキャッシュ内にブロックがなかったホスト読み取りの数。SSDキャッシュミスは、ベースボリュームから読み取りが行われた場合に発生します。SSDキャッシュのウォームアップ中は、[キャッシュヒット]と比較して[部分キャッシュヒット]と[キャッシュミス]の数が多くなることが想定されます。



 a| 
ミス-ブロック
 a| 
[キャッシュミス]のブロック数。



 a| 
取り込み処理（ホスト読み取り）
 a| 
ベースボリュームからSSDキャッシュにデータがコピーされたホスト読み取りの数。



 a| 
取り込み処理（ホスト読み取り）-ブロック
 a| 
[取り込み処理（ホスト読み取り）]のブロック数。



 a| 
取り込み処理（ホスト書き込み）
 a| 
ベースボリュームからSSDキャッシュにデータがコピーされたホスト書き込みの数。書き込みI/O処理でキャッシュに書き込まないキャッシュ設定の場合、[取り込み処理（ホスト書き込み）]の数がゼロになることがあります。



 a| 
取り込み処理（ホスト書き込み）-ブロック
 a| 
[取り込み処理（ホスト書き込み）]のブロック数。



 a| 
無効化処理
 a| 
データが無効化された、またはSSDキャッシュから削除された回数。キャッシュの無効化処理は、各ホスト書き込み要求、Forced Unit Access（FUA）によるホスト読み取り要求、確認要求、およびその他一部の状況で実行されます。



 a| 
リサイクル処理
 a| 
別のベースボリュームや別の論理ブロックアドレス（LBA）範囲にSSDキャッシュブロックが再利用された回数。キャッシュ処理を効果的に行うには、読み取り処理と書き込み処理の合計数と比較して、再利用の数を少なくする必要があります。[リサイクル処理]の数が読み取りと書き込みの合計数に近い場合は、SSDキャッシュでスラッシングが発生しています。キャッシュ容量を増やす必要があります。または、ワークロードがSSDキャッシュの使用に適していません。



 a| 
使用可能バイト数
 a| 
SSDキャッシュ内でこのコントローラによって使用可能なバイト数。



 a| 
割り当てバイト数
 a| 
このコントローラによってSSDキャッシュから割り当てられたバイト数。SSDキャッシュから割り当てられたバイトは、空の場合もあれば、ベースボリュームのデータが含まれている場合もあります。



 a| 
ユーザデータバイト数
 a| 
SSDキャッシュ内の、ベースボリュームのデータを含む割り当て済みバイト数。[Available Bytes]、[Allocated Bytes]、および[User Data Bytes]を使用して、キャッシュ割り当ての割合とキャッシュ使用率が計算されます。

|===