---
permalink: sm-storage/increase-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, reserved, capacity 
summary: リザーブ容量を増やすことができます。リザーブ容量は、ストレージオブジェクトに対する任意のコピーサービス処理に使用される物理的に割り当てられた容量です。 
---
= リザーブ容量の拡張
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リザーブ容量を増やすことができます。リザーブ容量は、ストレージオブジェクトに対する任意のコピーサービス処理に使用される物理的に割り当てられた容量です。

Snapshot処理の場合は、通常はベースボリュームの40%、非同期ミラーリング処理の場合は通常はベースボリュームの20%です。一般に、ストレージオブジェクトのリザーブ容量がフルに近づいているという警告が表示されたときにリザーブ容量を拡張します。

.開始する前に
* プールまたはボリュームグループ内のボリュームのステータスが最適で、変更処理の実行中でないことを確認してください。
* プールまたはボリュームグループに容量の拡張に使用する空き容量が必要です。
+
プールまたはボリュームグループに空き容量がない場合は、未割り当て容量を未使用ドライブの形式でプールまたはボリュームグループに追加できます。



.タスクの内容
次のストレージオブジェクトのリザーブ容量は8GiB単位でのみ拡張できます。

* Snapshotグループ
* Snapshotボリューム
* 整合性グループメンバーボリューム
* ミラーペアボリューム


プライマリボリュームで多数の変更が行われる可能性がある場合や、特定のコピーサービス処理の寿命が非常に長い場合は、割合を高くします。

[NOTE]
====
読み取り専用のSnapshotボリュームのリザーブ容量は増やすことはできません。リザーブ容量が必要なのは、読み取り/書き込みのSnapshotボリュームだけです。

====
.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 予約容量*タブを選択します。
. リザーブ容量を増やすストレージオブジェクトを選択し、*容量の拡張*をクリックします。
+
リザーブ容量の拡張ダイアログボックスが表示されます。

. スピンボックスを使用して容量の割合を調整します。
+
選択したストレージオブジェクトを含むプールまたはボリュームグループに空き容量がなく、ストレージアレイに未割り当て容量がある場合は、新しいプールまたはボリュームグループを作成できます。その後、そのプールまたはボリュームグループの新しい空き容量を使用してこの処理を再試行できます。

. [* 拡大（ * ） ] をクリックします


.結果
System Managerは次の処理を実行します。

* ストレージオブジェクトのリザーブ容量を拡張します。
* 新たに追加したリザーブ容量を表示します。

