---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: プールまたはボリュームグループ内の使用可能な空き容量を使用して、ボリュームのレポート容量（ホストに報告される容量）を拡張できます。 
---
= ボリュームの容量の拡張
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールまたはボリュームグループ内の使用可能な空き容量を使用して、ボリュームのレポート容量（ホストに報告される容量）を拡張できます。

.開始する前に
* ボリュームの関連付けられたプールまたはボリュームグループに十分な空き容量がある。
* ボリュームが最適な状態であり、変更中の状態ではありません。
* シンボリュームの最大レポート容量である256TiBに達していません。
* ボリュームでホットスペアドライブが使用されていません。（ボリュームグループ内のボリュームにのみ適用されます）。



NOTE: ボリューム容量は一度に最大128TiBまで拡張できます。

.タスクの内容
このプールまたはボリュームグループ内の他のボリュームに対する今後の容量要件に注意してください。Snapshotイメージ、Snapshotボリューム、またはリモートミラーを作成するための十分な空き容量を確保してください。

[NOTE]
====
ボリュームの容量の拡張は、特定のオペレーティングシステムでのみサポートされます。サポート対象外のホストオペレーティングシステムでボリューム容量を拡張すると、拡張した容量は使用できなくなり、元のボリューム容量をリストアすることはできません。

====
.手順
. 選択メニュー： Storage [Volumes]
. 容量を拡張するボリュームを選択し、 * 容量を拡張 * を選択します。
+
[容量の拡張の確認]ダイアログボックスが表示されます。

. 続行するには、 * はい * を選択します。
+
[レポート容量の拡張]ダイアログボックスが表示されます。

+
このダイアログボックスには、ボリュームの現在のレポート容量と、ボリュームの関連付けられたプールまたはボリュームグループで使用可能な空き容量が表示されます。

. レポート容量の拡張に使用できるレポート容量を追加するには、 * ボックスを使用します。メビバイト（MiB）、ギビバイト（GiB）、テビバイト（TiB）のいずれかで表示するように容量の値を変更できます。
. [* 拡大（ * ） ] をクリックします


.結果
* System Managerは、選択に基づいてボリュームの容量を拡張します。
* メニューを選択します。Home [View Operations in Progress]は、選択したボリュームで現在実行中の容量増加処理の進捗状況を表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。


.終了後
ボリュームの容量を拡張したら、それに応じてファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。
