---
permalink: sm-storage/interpret-performance-data.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, performance data 
summary: パフォーマンスデータは、ストレージアレイのパフォーマンスの調整に役立ちます。 
---
= パフォーマンスデータの解釈
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスデータは、ストレージアレイのパフォーマンスの調整に役立ちます。

パフォーマンスデータを解釈するときは、いくつかの要因がストレージアレイのパフォーマンスに影響することに注意してください。次の表に、考慮すべき主な領域を示します。

[cols="25h,~"]
|===
| パフォーマンスデータ | パフォーマンス調整の関連事項 


 a| 
レイテンシ（ミリ秒、ms）
 a| 
特定のオブジェクトのI/Oアクティビティを監視します。

ボトルネックになっているオブジェクトを特定できる可能性があります。

* ボリュームグループを複数のボリュームで共有する場合は、ドライブのシーケンシャルパフォーマンスを向上させてレイテンシを低減するために、個 々 のボリュームに独自のボリュームグループが必要になることがあります。
* プールではレイテンシが大きくなり、ドライブ間でワークロードが不均一な場合があるため、レイテンシの値はあまり意味がなく、一般的に高くなります。
* ドライブのタイプと速度はレイテンシに影響します。ランダムI/Oを使用すると、回転式ドライブが高速であるため、ディスク上のさまざまな場所への移動にかかる時間が短縮されます。
* ドライブの数が少なすぎると、キューに登録されるコマンドが多くなり、ドライブがコマンドを処理する時間が長くなり、システムの一般的なレイテンシが増加します。
* I/Oが大きいほど、データ転送にかかる時間が長くなるため、レイテンシが大きくなります。
* レイテンシが高い場合は、I/Oパターンが本質的にランダムである可能性があります。ランダムI/Oのドライブは、シーケンシャルストリームのドライブよりもレイテンシが高くなります。
* 共通のボリュームグループのドライブ間またはボリューム間でレイテンシが異なる場合は、ドライブが低速であることを示している可能性があります。




 a| 
IOPS
 a| 
1秒あたりの入出力処理（IOPSまたはIO/秒）に影響する要因には、次の項目があります。

* アクセスパターン（ランダムまたはシーケンシャル）
* I/Oサイズ
* RAIDレベル
* キャッシュブロックサイズ
* 読み取りキャッシュが有効かどうか
* 書き込みキャッシュが有効かどうか
* 動的キャッシュ読み取りプリフェッチ
* セグメントサイズ
* ボリュームグループまたはストレージアレイ内のドライブ数


キャッシュヒット率が高いほど、I/O速度は高くなります。書き込みキャッシュが有効な場合の方が、無効な場合に比べて書き込みI/O速度が高くなります。個々のボリュームの書き込みキャッシュを有効にするかどうかを判断するときは、現在のIOPSと最大IOPSを確認します。シーケンシャルI/Oパターンの方が、ランダムI/Oパターンよりも高速です。I/Oパターンに関係なく、書き込みキャッシュを有効にしてI/O速度を最大化し、アプリケーションの応答時間を短縮します。

ボリュームのIOPS統計では、セグメントサイズの変更によるパフォーマンスの向上を確認できます。実験して最適なセグメントサイズを決定するか、ファイルシステムサイズまたはデータベースブロックサイズを使用します。



 a| 
MiB/秒
 a| 
転送またはスループットの速度は、アプリケーションのI/OサイズとI/O速度によって決まります。一般に、アプリケーションのI/O要求が小さいと転送速度は低下しますが、I/O速度は速く、応答時間は短くなります。アプリケーションのI/O要求のサイズが大きい場合は、スループットが高速になる可能性があります。

一般的なアプリケーションのI/Oパターンを理解しておくと、特定のストレージアレイの最大I/O転送速度を決定するのに役立ちます。



 a| 
CPU
 a| 
使用中の処理能力の割合を示します。

同じタイプのオブジェクトのCPU使用率に差異がある場合があります。たとえば、一方のコントローラのCPU使用率が高いか、時間の経過とともに増加している一方で、もう一方のコントローラのCPU使用率は低く安定しています。この場合、1つ以上のボリュームのコントローラ所有権を、CPU使用率の低いコントローラに変更できます。

ストレージアレイ全体でCPUを監視できます。時間の経過とともにアプリケーションのパフォーマンスが低下する場合は、ストレージアレイの追加が必要になることがあります。ストレージアレイを企業に追加することで、許容可能なパフォーマンスレベルでアプリケーションのニーズを引き続き満たすことができます。



 a| 
ヘッドルーム
 a| 
ヘッドルームとは、コントローラ、コントローラホストチャネル、およびコントローラドライブチャネルの残りのパフォーマンス容量のことです。この値はパーセンテージで表され、これらのオブジェクトが提供できる最大パフォーマンスと現在のパフォーマンスレベルの差を表します。

* コントローラの場合、ヘッドルームは最大限可能なIOPSの割合です。
* チャネルの場合、ヘッドルームは最大スループット（MiB/秒）の割合です。計算には、読み取りスループット、書き込みスループット、双方向スループットが含まれています。


|===