---
permalink: sm-storage/overview-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage 
summary: リモートストレージ機能を使用している場合は、リモートストレージシステムからデータをインポートできます。 
---
= リモートストレージ機能の概要
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージ機能が搭載されている場合は、リモートストレージシステムからストレージアレイにデータをインポートできます。



== リモートストレージ機能とは何ですか？

リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステムにデータをインポートできます。リモートシステムには、別のEシリーズシステムを使用することも、別のベンダーのシステムを使用することもできます。この機能は、機器のアップグレード時など、ダウンタイムを最小限に抑えながらデータ移行を合理化したい場合に役立ちます。


NOTE: リモートストレージを使用するには、サブモデルID（SMID）でこの機能を有効にする必要があります。

詳細：

* link:rtv-how-remote-storage-works.html["リモートストレージの仕組み"]
* link:rtv-terminology.html["リモートストレージの用語"]
* link:rtv-remote-storage-requirements.html["リモートストレージの要件"]
* link:rtv-remote-storage-volume-requirements.html["リモートストレージボリュームの要件"]




== この機能を使用してデータをインポートする方法を教えてください。

リモートストレージウィザードを使用して、リモートストレージデバイス（データのインポート元）をEシリーズシステム上のターゲットボリュームにマッピングします。このウィザードは、ストレージ[リモートストレージ]メニューから使用できます。

詳細：

* link:rtv-import-remote-storage.html["リモートストレージのインポート"]
* link:rtv-manage-progress-of-remote-volume-import.html["データインポートの進行状況を管理します。"]

