---
permalink: sm-storage/overview-pools-volume-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, pools, volume groups 
summary: ストレージアレイ内の未割り当てドライブのサブセットから論理ストレージ容量を作成できます。この論理容量は、環境のニーズに応じてプールまたはボリュームグループのどちらかになります。 
---
= プールとボリュームグループの概要
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ内の未割り当てドライブのサブセットから論理ストレージ容量を作成できます。この論理容量は、環境のニーズに応じてプールまたはボリュームグループのどちらかになります。



== プールとボリュームグループとは

a_pool_は、論理的にグループ化されたドライブのセットです。a_volume group_は、特性が共有されているボリュームのコンテナです。プールまたはボリュームグループを使用して、ホストにアクセスできるボリュームを作成できます。

詳細：

* link:how-pools-and-volume-groups-work.html["プールとボリュームグループの機能"]
* link:capacity-terminology.html["容量に関する用語"]
* link:decide-to-use-a-pool-or-volume-group.html["プールとボリュームグループのどちらを使用するかを決定する"]




== プールはどのように作成しますか？

System Managerでストレージアレイ内に未割り当て容量が検出されたときにプールを自動的に作成することができます。最適な構成を自動作成で判断できない場合は、ストレージ[プールとボリュームグループ]メニューからプールを手動で作成することもできます。

詳細：

* link:automatic-versus-manual-pool-creation.html["プールの自動作成と手動作成"]
* link:create-pool-automatically.html["プールの自動作成"]
* link:create-pool-manually.html["プールの手動作成"]
* link:add-capacity-to-a-pool-or-volume-group.html["プールまたはボリュームグループへの容量の追加"]




== ボリュームグループはどのようにして作成しますか？

メニューからボリュームグループを作成できます。Storage [Pools & Volume Groups]

詳細：

* link:create-volume-group.html["ボリュームグループの作成"]
* link:add-capacity-to-a-pool-or-volume-group.html["プールまたはボリュームグループへの容量の追加"]




== 関連情報

プールとボリュームグループに関連する概念については、以下を参照してください。

* link:how-reserved-capacity-works.html["リザーブ容量の仕組み"]
* link:how-ssd-cache-works.html["SSDキャッシュの仕組み"]

