---
permalink: sm-storage/requirements-and-guidelines-for-snapshots.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, guidelines, snapshots 
summary: スナップショットを作成して使用する場合は、次の要件とガイドラインを確認してください。 
---
= Snapshotの要件とガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スナップショットを作成して使用する場合は、次の要件とガイドラインを確認してください。



== SnapshotイメージとSnapshotグループ

* 各Snapshotイメージは1つのSnapshotグループに関連付けられます。
* Snapshotグループは、関連オブジェクトのスケジュールされたSnapshotイメージまたはインスタントSnapshotイメージを初めて作成したときに作成されます。これにより、リザーブ容量が作成されます。
+
Snapshotグループは、Pools & Volume Groupsページで表示できます。

* スケジュールされたSnapshotイメージは、ストレージアレイがオフラインのときや電源がオフのときは作成されません。
* Snapshotスケジュールが設定されたSnapshotグループを削除すると、Snapshotスケジュールも削除されます。
* 不要になったSnapshotボリュームは、削除する代わりに、関連付けられているリザーブ容量とともに再利用できます。これにより、同じベースボリュームの別のSnapshotボリュームが作成されます。Snapshotイメージが同じベースボリューム内にあるかぎり、SnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームを同じSnapshotイメージまたは別のSnapshotイメージに再度関連付けることができます。




== Snapshot整合性グループ

* Snapshot整合性グループには、Snapshot整合性グループのメンバーであるボリュームごとにSnapshotグループが1つ含まれます。
* Snapshot整合性グループは1つのスケジュールにのみ関連付けることができます。
* Snapshotスケジュールが設定されたSnapshot整合性グループを削除すると、Snapshotスケジュールも削除されます。
* Snapshot整合性グループに関連付けられているSnapshotグループを個別に管理することはできません。管理処理（Snapshotイメージの作成、SnapshotイメージまたはSnapshotグループの削除、Snapshotイメージのロールバック）は、Snapshot整合性グループレベルで実行する必要があります。




== ベースボリューム

* SnapshotボリュームのData Assurance（DA）とセキュリティ設定は、関連付けられているベースボリュームと同じである必要があります。
* 障害が発生したベースボリュームのSnapshotボリュームは作成できません。
* ベースボリュームがボリュームグループに含まれている場合は、関連付けられているSnapshot整合性グループのメンバーボリュームをプールまたはボリュームグループに配置できます。
* ベースボリュームがプールに含まれている場合は、関連付けられているSnapshot整合性グループのすべてのメンバーボリュームをベースボリュームと同じプールに配置する必要があります。




== リザーブ容量

* リザーブ容量は1つのベースボリュームにのみ関連付けられます。
* スケジュールを使用すると、Snapshotイメージが大量に作成される可能性があります。スケジュールされたSnapshot用の十分なリザーブ容量があることを確認してください。
* Snapshot整合性グループのリザーブ容量ボリュームのData Assurance（DA）とセキュリティの設定は、Snapshot整合性グループのメンバーボリュームの関連付けられているベースボリュームと同じである必要があります。




== 保留中のSnapshotイメージ

次の状況では、Snapshotイメージの作成が保留状態のままになることがあります。

* このSnapshotイメージを含むベースボリュームが非同期ミラーグループのメンバーである。
* ベースボリュームで同期処理を実行中です。同期処理が完了するとすぐにSnapshotイメージの作成が完了します。




== Snapshotイメージの最大数

* ボリュームがSnapshot整合性グループのメンバーである場合、System ManagerはそのメンバーボリュームのSnapshotグループを作成します。このSnapshotグループは、ベースボリュームあたりのSnapshotグループの許容最大数にカウントされます。
* SnapshotグループまたはSnapshot整合性グループにSnapshotイメージを作成しようとしていて、関連付けられているグループがSnapshotイメージの最大数に達している場合は、次の2つのオプションがあります。
+
** SnapshotグループまたはSnapshot整合性グループの自動削除を有効にします。
** SnapshotグループまたはSnapshot整合性グループから1つ以上のSnapshotイメージを手動で削除し、処理を再試行します。






== 自動削除

SnapshotグループまたはSnapshot整合性グループで自動削除が有効になっている場合、グループに新しいSnapshotイメージが作成されると、最も古いSnapshotイメージがSystem Managerによって削除されます。



== ロールバック処理

* ロールバック処理の実行中は、次の操作を実行できません。
+
** ロールバックに使用されているSnapshotイメージを削除します。
** ロールバック処理の対象となるベースボリュームの新しいSnapshotイメージを作成します。
** 関連付けられているSnapshotグループのRepository-Fullポリシーの変更


* 次のいずれかの処理が実行中の場合は、ロールバック処理を開始できません。
+
** 容量の拡張（プールまたはボリュームグループへの容量の追加）
** ボリュームの拡張（ボリュームの容量の拡張）
** ボリュームグループのRAIDレベルの変更
** ボリュームのセグメントサイズの変更


* ベースボリュームがボリュームコピーに含まれている場合は、ロールバック処理を開始できません。
* ベースボリュームがリモートミラーのセカンダリボリュームである場合は、ロールバック処理を開始できません。
* 関連付けられているSnapshotリポジトリボリュームの使用済み容量に読み取り不能セクターがある場合、ロールバック処理は失敗します。

