---
permalink: sm-storage/rtv-how-remote-storage-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage 
summary: リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステムにデータをインポートできます。この機能は、機器のアップグレード時など、ダウンタイムを最小限に抑えながらデータ移行を合理化したい場合に役立ちます。 
---
= リモートストレージの仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステムにデータをインポートできます。この機能は、機器のアップグレード時など、ダウンタイムを最小限に抑えながらデータ移行を合理化したい場合に役立ちます。

リモートストレージ機能を設定するには、ハードウェアをセットアップし、System Managerを使用してリモートストレージオブジェクトを作成する必要があります。この設定が完了すると、インポートプロセスが開始されます。



== ハードウェアのセットアップ

次のワークフローを使用して、ハードウェア接続を準備します。

これらの手順の詳細については、リモートストレージ機能のユーザガイドを参照してください。このユーザガイドは、EシリーズおよびSANtricityのドキュメントセンター、およびで https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]入手でき https://docs.netapp.com/us-en/e-series/remote-storage-volumes/index.html["Remote Storage Volumesの概要"^]ます。

ローカルのEシリーズストレージシステムで、次の手順を実行します。

. 各コントローラからリモートストレージシステムへのiSCSI接続が確立されていることを確認します。この接続では、ローカルのEシリーズシステムがiSCSIイニシエータとして機能し、リモートシステムでホストとしてセットアップできます。
. インポート処理のデスティネーションボリュームを作成します。ボリュームの容量がリモートストレージシステムのソースボリューム以上で、ブロックサイズが同じで、マッピングされていないことを確認してください。を参照して link:create-volumes.html["ボリュームの作成"]
. System Managerインターフェイスから、ローカルのEシリーズシステムのiSCSI Qualified Name（IQN）を収集します。このIQNは、あとでローカルのEシリーズシステムをリモートストレージシステムのホストとしてセットアップする際に使用します。System Managerで、次のメニューに移動します。Settings（システム）> iSCSI settings（iSCSI設定）> Target IQN（ターゲットIQN）の順に選択します。


リモート・ストレージ・システム：

. IQNを使用して、ローカルのEシリーズシステムをリモートシステムのホストとしてセットアップします。適切なホストタイプを次のように設定してください。
+
** リモートシステムがEシリーズモデルの場合は、を参照してくださいlink:overview-hosts.html["ホストおよびホストクラスタの概要"]。「工場出荷時のデフォルト」のホストタイプを使用します。
** リモートシステムが別のベンダーのものである場合は、使用可能なオプションに基づいて適切なホストタイプを選択します。


. ソースボリュームのすべてのI/Oを停止し、ファイルシステムをアンマウントし、ホストまたはアプリケーションへの割り当てをすべて削除します。
. 新しく作成したローカルのEシリーズストレージシステムホストにボリュームを割り当てます。
. 選択したソースボリュームについて、インポートを作成できるように、リモートストレージシステムから次の情報を収集します。
+
** iSCSI Qualified Name（IQN）
** iSCSI IPアドレス
** ソースボリュームのLUN番号






== System Managerのセットアップ

インポート用のリモートストレージオブジェクトを作成するには、次のワークフローを使用します。

. System Managerインターフェイスのリモートストレージウィザードを使用して、リモートストレージデバイス（データのインポート元）をEシリーズシステム上のターゲットボリュームにマッピングします。「完了」を選択すると、インポート処理が開始されます。
. [処理を表示]ダイアログまたは[実行中の処理]パネルからインポートを監視します。必要に応じて、プロセスを一時停止および再開することもできます。
. 必要に応じて、インポートの完了時にソースボリュームとターゲットボリュームの間の接続を切断するか、以降のインポート用に接続を維持します。

