---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: リモートシステムからローカルのEシリーズストレージシステムへのストレージのインポートを開始するには、リモートストレージのインポートウィザードを使用します。 
---
= リモートストレージのインポート
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートシステムからローカルのEシリーズストレージシステムへのストレージのインポートを開始するには、リモートストレージのインポートウィザードを使用します。

.開始する前に
* Eシリーズストレージシステムがリモートストレージシステムと通信するように設定されている必要があります。
+
[NOTE]
====
ハードウェア構成については、リモートストレージ機能のユーザガイドを参照してください。このユーザガイドは、EシリーズおよびSANtricityのドキュメントセンター、およびで https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]入手でき https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["ハードウェアの設定"^]ます。

====
* リモートストレージシステムについて、次の情報を収集します。
+
** iSCSI IQN
** iSCSI IPアドレス
** リモートストレージデバイス（ソースボリューム）のLUN番号


* ローカルのEシリーズストレージシステムの場合、データのインポートに使用するボリュームを作成または選択します。を参照して link:create-volumes.html["ボリュームの作成"]ターゲットボリュームは次の要件を満たしている必要があります。
+
** リモートストレージデバイス（ソースボリューム）のブロックサイズと一致します。
** リモートストレージデバイスと同等以上の容量がある。
** は最適な状態で使用可能です。




要件の完全なリストについては、を参照してくださいlink:rtv-remote-storage-volume-requirements.html["リモートストレージボリュームの要件"]。

* *推奨：*インポート処理を開始する前に、リモートストレージシステムのボリュームをバックアップしてください。


.タスクの内容
このタスクでは、リモートストレージデバイスとローカルのEシリーズストレージシステム上のボリュームの間にマッピングを作成します。設定が完了すると、インポートが開始されます。

[NOTE]
====
多くの変数がインポート操作とその完了時間に影響を与える可能性があるため、最初に小さい「テスト」インポートを実行することをお勧めします。これらのテストを使用して、すべての接続が想定どおりに機能し、インポート処理が適切な時間で完了することを確認します。

====
.手順
. 「ストレージ[リモートストレージ]」メニューを選択します。
. [ リモートストレージのインポート ] をクリックします。
+
リモートストレージをインポートするためのウィザードが表示されます。

. ソースの設定パネルの*手順1a *で、接続情報を入力します。別のiSCSI接続を追加する場合は、*別のIPアドレスを追加*をクリックして、リモートストレージのIPアドレスを追加します。完了したら、 * 次へ * をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
名前
 a| 
System Managerインターフェイスでリモートストレージデバイスを識別するための名前を入力します。

名前には最大30文字を使用できます。使用できる文字は、アルファベット、数字、およびアンダースコア（_）、ダッシュ（-）、ハッシュ記号（#）のみです。名前にスペースを含めることはできません。



 a| 
iSCSI接続プロパティ
 a| 
リモートストレージデバイスの接続プロパティを入力します。

** * iSCSI Qualified Name（IQN）*：iSCSI IQNを入力します。
** *IPアドレス*: IPv4アドレスを入力します。
** *ポート*：ソース・デバイスとターゲット・デバイス間の通信に使用するポート番号を入力します。デフォルトでは、ポート番号は3260です。


|===
====
+
「*次へ*」をクリックすると、ソースの設定パネルの*ステップ1b *が表示されます。

. [*LUN*]フィールドで'ソースとして使用するリモート・ストレージ・デバイスのLUN番号を選択し'[次へ]をクリックします
+
[ターゲットの設定]パネルが開き、インポートのターゲットとして使用するボリューム候補が表示されます。ブロックサイズ、容量、またはボリュームの可用性が原因で、一部のボリュームが候補のリストに表示されません。

. テーブルから、Eシリーズストレージシステム上のターゲットボリュームを選択します。必要に応じて、スライダを使用してインポートの優先度を変更します。「 * 次へ * 」をクリックします。次のダイアログボックスでと入力し、* Continue *をクリックして操作を確定します `continue`。
+
ターゲットボリュームの容量がソースボリュームよりも大きい場合、その追加容量はEシリーズシステムに接続されたホストには報告されません。新しい容量を使用するには、インポート処理が完了して切断されたあとに、ホストでファイルシステムの拡張処理を実行する必要があります。

+
ダイアログで構成を確認すると、[Review]パネルが表示されます。

. [レビュー]パネルで、設定が正しいことを確認し、[完了]をクリックしてインポートを開始します。
+
別のインポートを開始するかどうかを確認するダイアログボックスが表示されます。

. 必要に応じて、 * はい * をクリックして別のリモートストレージインポートを作成します。[ソースの設定]パネルの[はい]をクリックすると、[手順1a*]に戻ります。ここで、既存の構成を選択するか、新しい構成を追加できます。別のインポートを作成しない場合は、[*いいえ*（* No *）]をクリックしてダイアログボックスを終了します。
+
インポートプロセスが開始されると、コピーしたデータでターゲットボリューム全体が上書きされます。このプロセス中にホストがターゲットボリュームに新しいデータを書き込むと、その新しいデータはリモートデバイス（ソースボリューム）に伝播されます。

. 処理の進捗状況は、[リモートストレージ]パネルの[処理の表示]ダイアログで確認します。


.結果
インポート処理が完了するまでの時間は、リモートストレージシステムのサイズ、インポートの優先度設定、およびストレージシステムと関連ボリュームの両方のI/O負荷によって異なります。

インポートが完了すると、ローカルボリュームはリモートストレージデバイスの複製になります。

.終了後
2つのボリューム間の関係を解除する準備ができたら、インポートオブジェクトの「処理を実行中」ビューで「*切断」を選択します。関係を切断すると、ローカルボリュームのパフォーマンスは正常に戻り、リモート接続による影響はなくなります。
