---
permalink: sm-storage/rtv-remote-storage-volume-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, volume, requirements 
summary: インポートに使用するボリュームは、サイズ、ステータス、その他の条件を満たしている必要があります。 
---
= リモートストレージボリュームの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インポートに使用するボリュームは、サイズ、ステータス、その他の条件を満たしている必要があります。



== リモートストレージボリューム

インポートのソース ボリュームは「リモート ストレージ ボリューム」と呼ばれます。このボリュームは次の基準を満たす必要があります。

* 別のインポートに含めることはできません
* オンラインステータスである必要があります


インポートが開始されると、コントローラファームウェアはバックグラウンドでリモートストレージボリュームを作成します。そのため、リモートストレージボリュームはSystem Managerで管理できず、インポート処理にのみ使用できます。

作成されたリモートストレージボリュームは、次の例外を除き、Eシリーズシステム上の他の標準ボリュームと同様に扱われます。

* リモートストレージデバイスのプロキシとして使用できます。
* 他のボリュームコピーまたはSnapshotの候補として使用することはできません。
* インポートの実行中はData Assurance設定を変更することはできません。
* はどのホストにもマッピングできません。インポート処理用にのみ予約されています。


各リモートストレージボリュームは1つのリモートストレージオブジェクトにのみ関連付けられますが、1つのリモートストレージオブジェクトを複数のリモートストレージボリュームに関連付けることができます。リモートストレージボリュームは、次の組み合わせを使用して一意に識別されます。

* リモートストレージオブジェクトID
* リモートストレージデバイスのLUN番号




== ターゲットボリューム候補

ターゲットボリュームは、ローカルのEシリーズシステムのデスティネーションボリュームです。デスティネーションボリュームは次の条件を満たしている必要があります。

* RAID / DDPボリュームである必要があります。
* リモートストレージボリューム以上の容量が必要です。
* ブロックサイズがリモートストレージボリュームと同じである必要があります。
* 有効な状態（最適）である必要があります。
* ボリュームコピー、Snapshotコピー、非同期ミラーリング、同期ミラーリングのいずれの関係も確立できません。
* 再設定処理を実行できません：動的ボリューム拡張、動的容量拡張、動的セグメントサイズ、動的 RAID 移行、動的な容量削減、 最適化。
* インポートの開始前にホストにマッピングすることはできません（ただし、インポートの完了後にマッピングすることはできます）。
* Flash Read Cached（FRC）を有効にできません。


これらの要件は、System Managerのリモートストレージインポートウィザードで自動的に確認されます。デスティネーションボリュームの選択には、すべての要件を満たすボリュームのみが表示されます。
