---
permalink: sm-storage/rtv-what-do-i-need-to-know-before-starting-a-remote-storage-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, import 
summary: リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステム上のボリュームにデータをコピーできます。この機能を使用する前に、次のガイドラインを確認してください。 
---
= リモートストレージのインポートを開始するときは、どのような点に注意する必要がありますか？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステム上のボリュームにデータをコピーできます。この機能を使用する前に、次のガイドラインを確認してください。



== 構成

リモートストレージインポートを作成する前に、次の操作を完了し、次の条件を確認する必要があります。

* ローカルのEシリーズストレージシステムの各コントローラにリモートストレージシステムへのiSCSI接続が確立されていることを確認します。
* ローカルのEシリーズストレージシステムで、インポート処理のターゲットボリュームを作成します。ボリュームの容量がソースボリューム以上で、ブロックサイズがソースボリュームと同じで、マッピングされていないことを確認してください。を参照して link:create-volumes.html["ボリュームの作成"]
* iSCSI Qualified Name（IQN）を使用して、ローカルのEシリーズストレージシステムをリモートシステムのホストとしてセットアップします。IQNは次のメニューから確認できます。Settings（システム）> iSCSI settings（iSCSI設定）> Target IQN（ターゲットIQN）。また、使用するシステムに基づいて適切なホストタイプを設定してください。
* リモートストレージシステム上の選択したボリュームについて、すべてのI/Oを停止し、ファイルシステムをアンマウントし、ホストまたはアプリケーションへの割り当てをすべて削除します。
* 新しく作成したローカルのEシリーズストレージシステムホストにボリュームを割り当てます。
* インポートを作成できるように、リモートストレージシステムから次の情報を収集します。
+
** iSCSI Qualified Name（IQN）
** iSCSI IPアドレス
** ソースデータの発信元であるリモートストレージデバイスのLUN番号


* インポートプロセスが開始されると、ローカルデスティネーションボリューム全体がコピーされたデータで上書きされます。インポートの作成後、ローカルデスティネーションボリュームに新たに書き込まれたデータは、リモートストレージデバイス上のボリュームに伝播されます。そのため、インポートプロセスを開始する前に、リモートストレージシステム上のボリュームをバックアップすることを推奨します。




== インポートプロセス

次の手順では、インポートプロセスの概要を説明します。

. System Managerインターフェイスにアクセスし、* Remote Storage *ページに移動します。「*読み込み*」を選択して、新しいインポートの作成を開始します。詳細については、を参照してくださいlink:rtv-import-remote-storage.html["リモートストレージのインポート"]。
+
オフラインインポートを実行する場合は、インポートが完了するまでデスティネーションボリュームをマッピングしないでください。

. インポートの進捗状況を監視します。
+
インポートが開始されたら、ターゲットボリュームをマッピングできます。インポート処理が完了するまでの時間は、リモートストレージデバイス（ソースボリューム）のサイズ、インポートの優先度の設定、ストレージシステムと関連付けられたボリュームの両方のI/O負荷によって異なります。

+
インポートが完了すると、ターゲットボリュームはソースと同じボリュームになります。

. マッピング関係を解除する準備ができたら、インポートオブジェクトに対して*操作実行中*パネルから*切断*を実行します。


インポートが切断されると、ローカルデスティネーションのパフォーマンスは通常の状態に戻り、リモート接続による影響はなくなります。



== 制限事項

リモートストレージ機能には、次の制限事項があります。

* ミラーリングを無効にする必要があります。
* EシリーズシステムのデスティネーションボリュームにSnapshotを含めることはできません。
* インポートを開始する前に、Eシリーズシステム上のデスティネーションボリュームをホストにマッピングしないでください。
* Eシリーズシステムのデスティネーションボリュームで、リソースプロビジョニングを無効にする必要があります。
* リモートストレージボリュームを1つのホストまたは複数のホストに直接マッピングすることはできません。
* Web Services Proxyはサポートされません。
* iSCSI CHAPシークレットはサポートされません。
* SMcliはサポートされていません。
* VMwareデータストアはサポートされません。
* インポートペアが存在する場合、関係/インポートペアに含まれるストレージシステムは一度に1つだけアップグレードできます。




== 追加情報

リモートストレージ機能の詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]。
