---
permalink: sm-storage/rtv-remote-storage-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, requirements 
summary: リモートストレージ機能を使用する前に、次の要件および制限事項を確認してください。 
---
= リモートストレージ機能の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージ機能を使用する前に、次の要件および制限事項を確認してください。



== サポートされるプロトコル

サポートされるプロトコルは次のとおりです。

* iSCSI
* IPv4


Eシリーズの最新のサポートおよび設定情報については、を参照してください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^]。



== ハードウェア要件

Eシリーズストレージシステムには次のものが含まれている必要があります。

* コントローラ×2（デュプレックスモード）
* 両方のEシリーズコントローラのiSCSI接続（1つ以上のiSCSI接続を介してリモートストレージシステムと通信する場合）
* SANtricity OS 11.71以降
* サブモデルID（SMID）でリモートストレージ機能が有効になっている


リモートシステムには、Eシリーズストレージシステムを使用することも、別のベンダーのシステムを使用することもできます。以下を含む必要があります。

* iSCSI対応インターフェイス




== 制限事項

リモートストレージ機能には、次の制限事項があります。

* ミラーリングを無効にする必要があります。
* EシリーズシステムのデスティネーションボリュームにSnapshotを含めることはできません。
* インポートを開始する前に、Eシリーズシステム上のデスティネーションボリュームをホストにマッピングしないでください。
* Eシリーズシステムのデスティネーションボリュームで、リソースプロビジョニングを無効にする必要があります。
* リモートストレージボリュームを1つのホストまたは複数のホストに直接マッピングすることはできません。
* Web Services Proxyはサポートされません。
* iSCSI CHAPシークレットはサポートされません。
* SMcliはサポートされていません。
* VMwareデータストアはサポートされません。
* インポートペアが存在する場合、関係/インポートペアに含まれるストレージシステムは一度に1つだけアップグレードできます。

