---
permalink: sm-storage/ssd-cache-and-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd, cache, volumes 
summary: 読み取り専用のパフォーマンスを向上させる方法として、SSDキャッシュにボリュームを追加できます。SSDキャッシュは、ストレージアレイ内で論理的にグループ化した一連のソリッドステートディスク（SSD）ドライブで構成されます。 
---
= SSDキャッシュとボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
読み取り専用のパフォーマンスを向上させる方法として、SSDキャッシュにボリュームを追加できます。SSDキャッシュは、ストレージアレイ内で論理的にグループ化した一連のソリッドステートディスク（SSD）ドライブで構成されます。



== ボリューム

SSDキャッシュとの間のデータの移動には、単純なボリュームI/Oのメカニズムが使用されます。データがキャッシュされてSSDに格納されると、そのデータの以降の読み取りはSSDキャッシュで実行されるため、HDDボリュームにアクセスする必要はありません。

SSDキャッシュはセカンダリキャッシュであり、コントローラの動的ランダムアクセスメモリ（DRAM）にあるプライマリキャッシュと組み合わせて使用されます。

* プライマリキャッシュでは、ホスト読み取り後にデータがDRAMに格納されます。
* SSDキャッシュでは、データはボリュームからコピーされて2つの内部RAIDボリューム（コントローラごとに1つ）に格納されます。RAIDボリュームはSSDキャッシュの作成時に自動的に作成されます。


内部RAIDボリュームは、内部的なキャッシュ処理に使用されます。これらのボリュームにはアクセスできず、ユーザインターフェイスにも表示されません。ただし、ストレージアレイで許可されるボリュームの総数には、これら2つのボリュームが含まれます。

[NOTE]
====
コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシング転送の対象になりません。

====


== ドライブセキュリティ機能

ドライブセキュリティを使用している（セキュリティ有効）ボリュームでSSDキャッシュを使用する場合は、そのボリュームとSSDキャッシュのドライブセキュリティ機能が同じである必要があります。同じでない場合、ボリュームはセキュリティ有効になりません。
