---
permalink: sm-storage/start-snapshot-image-rollback-for-base-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, base, volume 
summary: ロールバック処理を実行して、Snapshotイメージに保存されている内容と一致するようにベースボリュームの内容を変更できます。ロールバック処理では、ベースボリュームに関連付けられているSnapshotイメージの内容は変更されません。 
---
= ベースボリュームのSnapshotイメージのロールバックの開始
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロールバック処理を実行して、Snapshotイメージに保存されている内容と一致するようにベースボリュームの内容を変更できます。

ロールバック処理では、ベースボリュームに関連付けられているSnapshotイメージの内容は変更されません。

.開始する前に
* ロールバック処理を開始するための十分なリザーブ容量があります。
* 選択したSnapshotイメージとボリュームがどちらも最適な状態である必要があります。
* 選択したボリュームですでに実行中のロールバック処理がないことを確認します。


.タスクの内容
ロールバックの開始手順では、ベースボリュームのSnapshotイメージに対してロールバックを開始すると同時に、ストレージ容量を追加することもできます。1つのベースボリュームに対して複数のロールバック処理を同時に開始することはできません。

[NOTE]
====
ホストはロールバックされた新しいベースボリュームにすぐにアクセスできますが、ロールバックの開始後は既存のベースボリュームに読み取り/書き込みアクセスできません。リカバリ用にロールバック前のベースボリュームを保持するには、ロールバックを開始する直前にベースボリュームのSnapshotを作成します。

====
.手順
. メニューを選択します。Storage [Snapshots]。
. 「* Snapshot Images *」タブを選択します。
. Snapshotイメージを選択し、メニューからロールバック[開始]を選択します。
+
ロールバックの開始の確認ダイアログボックスが表示されます。

. *オプション：*必要に応じて、*容量を増やす*オプションを選択します。
+
リザーブ容量の拡張ダイアログボックスが表示されます。

+
.. スピンボックスを使用して容量の割合を調整します。
+
選択したストレージオブジェクトを含むプールまたはボリュームグループに空き容量がなく、ストレージアレイに未割り当て容量がある場合は、容量を追加できます。新しいプールまたはボリュームグループを作成し、そのプールまたはボリュームグループの新しい空き容量を使用してこの処理を再試行できます。

.. [* 拡大（ * ） ] をクリックします


. この処理を実行することを確認し、*ロールバック*をクリックします。


.結果
System Managerは次の処理を実行します。

* 選択したSnapshotイメージに保存された内容を使用してボリュームをリストアします。
* ホストからロールバックされたボリュームにすぐにアクセスできるようにします。ロールバック処理が完了するまで待つ必要はありません。


.終了後
ロールバック処理の進捗状況を表示するには、MENU（ホーム）：[View Operations in Progress]（進行中の処理の表示）を選択します。

ロールバック処理が失敗すると、処理は一時停止します。一時停止した処理を再開できます。それでも失敗する場合は、Recovery Guruの手順に従って問題を解決するか、テクニカルサポートにお問い合わせください。
