---
permalink: sm-storage/types-of-copy-volume-operations.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: オフラインとオンラインのどちらかのボリュームコピー処理を実行できます。オフライン処理では、ソースボリュームからデータを読み取り、ターゲットボリュームにコピーします。オンライン処理では、Snapshotボリュームをソースとして使用し、そのデータをターゲットボリュームにコピーします。 
---
= ボリュームコピー処理のタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オフラインの_ボリュームコピー操作または_オンラインの_ボリュームコピー操作のいずれかを実行できます。オフライン処理では、ソースボリュームからデータを読み取り、ターゲットボリュームにコピーします。オンライン処理では、Snapshotボリュームをソースとして使用し、そのデータをターゲットボリュームにコピーします。

データの整合性を確保するために、どちらのタイプのボリュームコピー処理でも、ターゲットボリュームに対するすべてのI/Oアクティビティが中断されます。この一時停止は、手順が完了するまでターゲットボリューム上のデータの状態が不整合であるために発生します。

以下に、オフラインとオンラインのボリュームコピー処理について説明します。



== オフラインノボリュームコヒイシヨリ

オフラインのボリュームコピー関係は、ソースボリュームとターゲットボリュームの間の関係です。オフラインコピーでは、ソースボリュームからデータを読み取り、ターゲットボリュームにコピーします。コピーの実行中は、ソースボリュームに対するすべての更新が一時停止されます。ソースボリュームに対するすべての更新は、時間的な不整合がターゲットボリュームで作成されるのを防ぐために中断されます。

[cols="25h,~"]
|===
2+| オフラインコピー処理に関する重要なポイント 


 a| 
読み取り要求と書き込み要求
 a| 
* ボリュームコピー処理のステータスが実行中または保留の間は、オフラインコピーに参加しているソースボリュームを読み取り専用のI/Oアクティビティに使用できます。
* 書き込み要求はオフラインコピーの完了後に許可されます。
* 書き込み禁止のエラーメッセージが表示されないようにするには、ステータスが実行中のボリュームコピー処理に参加しているソースボリュームにはアクセスしないでください。




 a| 
ジャーナリングファイルシステム
 a| 
* ソースボリュームがジャーナリングファイルシステムでフォーマットされている場合、ソースボリュームに対する読み取り要求を発行しようとすると、ストレージアレイコントローラによって拒否され、エラーメッセージが表示されることがあります。
* ジャーナリングファイルシステムドライバは、読み取り要求の発行を試行する前に書き込み要求を発行します。コントローラは書き込み要求を拒否します。書き込み要求が拒否されたために、読み取り要求が発行されない可能性があります。その場合、ソースボリュームが書き込み禁止になっていることを示すエラーメッセージが表示されることがあります。
* この問題が発生しないようにするには、ボリュームコピー処理のステータスが実行中である間は、オフラインコピーに参加しているソースボリュームにはアクセスしないでください。


|===


== オンラインのボリュームコピー処理

オンラインのボリュームコピー関係は、Snapshotボリュームとターゲットボリュームの間の関係です。ソースボリュームがオンラインでデータの書き込みに使用できる状態で、ボリュームコピー処理を開始できます。この機能は、ボリュームのSnapshotを作成し、そのSnapshotをコピーの実際のソースボリュームとして使用することで実現されます。

ソースボリュームに対してボリュームコピー処理を開始すると、System ManagerはベースボリュームのSnapshotイメージおよびベースボリュームとターゲットボリュームのSnapshotイメージ間のコピー関係を作成します。Snapshotイメージをソースボリュームとして使用すると、ストレージアレイはコピーの実行中もソースボリュームへの書き込みを継続できます。

オンラインコピー処理では、copy-on-write手順が原因でパフォーマンスが低下します。オンラインコピーが完了すると、ベースボリュームのパフォーマンスが元に戻ります。

[cols="25h,~"]
|===
2+| オンラインコピー処理に関する重要なポイント 


 a| 
どのような種類のボリュームを使用できますか？
 a| 
* ポイントインタイムイメージの作成対象となるボリュームはベースボリュームと呼ばれ、ストレージアレイ上の標準ボリュームまたはシンボリュームである必要があります。
* ターゲットボリュームは、ボリュームグループ内の標準ボリュームまたはプール内の標準ボリュームです。ターゲットボリュームをシンボリュームやSnapshotグループ内のベースボリュームにすることはできません。
* オンラインのボリュームコピー機能を使用して、シンボリュームから同じストレージアレイ内のプール内の標準ボリュームにデータをコピーできます。ただし、ボリュームコピー機能を使用して標準ボリュームからシンボリュームにデータをコピーすることはできません。




 a| 
ベースボリュームのパフォーマンス
 a| 
* コピーソースとして使用されるSnapshotボリュームがアクティブな場合は、copy-on-write処理が原因でベースボリュームのパフォーマンスが低下します。コピーが完了すると、Snapshotは無効になり、ベースボリュームのパフォーマンスがリストアされます。Snapshotは無効ですが、リザーブ容量ボリュームとコピー関係はそのまま残ります。




 a| 
作成されるボリュームのタイプ
 a| 
* Snapshotボリュームとリザーブ容量ボリュームは、オンラインコピー処理中に作成されます。
* Snapshotボリュームは、データを格納する実際のボリュームではなく、特定の時点でボリュームに格納されていたデータへの参照です。
* 作成されるSnapshotごとに、そのSnapshotのデータを保持するためのリザーブ容量ボリュームが作成されます。リザーブ容量ボリュームは、Snapshotイメージの管理にのみ使用されます。




 a| 
リザーブ容量ボリューム
 a| 
* ソースボリューム上のデータブロックが変更される前に、変更対象のブロックの内容が保護用のリザーブ容量ボリュームにコピーされます。
* リザーブ容量ボリュームには元のデータブロックのコピーが格納されるため、これらのデータブロックに対する以降の変更はソースボリュームにのみ書き込まれます。
* リザーブ容量ボリュームに格納されるのはSnapshotの作成後に変更されたデータブロックだけであるため、オンラインコピー処理で使用されるディスクスペースは完全な物理コピーよりも少なくなります。


|===