---
permalink: sm-storage/view-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, ssd cache, statistics 
summary: SSDキャッシュの統計（読み取り、書き込み、キャッシュヒット、キャッシュ割り当ての割合、キャッシュ利用率など）を表示できます。 
---
= SSDキャッシュの統計の表示
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュの統計（読み取り、書き込み、キャッシュヒット、キャッシュ割り当ての割合、キャッシュ利用率など）を表示できます。

詳細統計のサブセットである一般統計は、[SSDキャッシュの統計を表示]ダイアログボックスに表示されます。SSDキャッシュの詳細統計は、すべてのSSD統計をファイルにエクスポートした場合にのみ表示できます `.csv`。

統計を確認および解釈する際には、複数の統計を組み合わせることで見えてくる情報もあることに注意してください。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 統計を表示するSSDキャッシュを選択し、メニューをクリックします。More [SSD Cache statistics（SSDキャッシュ統計の表示）]
+
[SSDキャッシュの統計を表示]ダイアログボックスが表示され、選択したSSDキャッシュの一般統計が表示されます。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 製品説明 


 a| 
読み取り
 a| 
SSDキャッシュが有効なボリュームに対するホストの読み取りの合計数が表示されます。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
書き込み
 a| 
SSDキャッシュが有効なボリュームに対するホストの書き込みの総数。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
キャッシュヒット
 a| 
キャッシュヒット数を表示します。



 a| 
キャッシュヒット率
 a| 
キャッシュヒットの割合が表示されます。この値は、キャッシュヒット数/（読み取り+書き込み）から算出されます。効果的なSSDキャッシュ処理には、キャッシュヒットの割合が50%以上である必要があります。



 a| 
キャッシュ割り当て率
 a| 
割り当てられているSSDキャッシュストレージの割合が表示されます。この値は、このコントローラで使用可能なSSDキャッシュストレージの割合で表され、割り当て済みバイト数/使用可能バイト数から算出されます。



 a| 
キャッシュ使用率
 a| 
有効なボリュームのデータが格納されているSSDキャッシュストレージの割合が表示されます。割り当てられているSSDキャッシュストレージの割合として表されます。この量は、SSDキャッシュの利用率または密度を表します。割り当てられたバイト数を使用可能なバイト数で割った値。



 a| 
すべてエクスポート
 a| 
SSDキャッシュのすべての統計をCSV形式にエクスポートします。エクスポートされたファイルには、SSDキャッシュの使用可能なすべての統計（一般統計と詳細統計の両方）が含まれます。

|===
====
. 「*キャンセル*」をクリックして、ダイアログボックスを閉じます。

