---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: ストレージアレイに関連するボリュームの用語を次に示します。 
---
= ボリュームに関する用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するボリュームの用語を次に示します。



== すべてのボリュームタイプ

[cols="25h,~"]
|===
| 期間 | 製品説明 


 a| 
割り当て容量
 a| 
割り当て容量は、ボリュームの作成やコピーサービス処理に使用します。

割り当て容量とレポート容量はシックボリュームでは同じですが、シンボリュームでは異なります。シックボリュームの場合、物理的に割り当てられたスペースは、ホストに報告されるスペースと同じになります。シンボリュームの場合、レポート容量はホストに報告される容量であり、割り当て容量はデータの書き込み用に現在割り当てられているドライブスペースの量です。



 a| 
アプリケーション
 a| 
アプリケーションとは、SQL ServerやExchangeなどのソフトウェアのことです。アプリケーションごとに、サポートするワークロードを1つ以上定義します。一部のアプリケーションについては、ストレージを最適化するボリューム構成が自動的に提示されます。ボリューム構成には、I/Oタイプ、セグメントサイズ、コントローラ所有権、読み取りキャッシュと書き込みキャッシュなどの特性が含まれます。



 a| 
容量
 a| 
容量は、ボリュームに格納できるデータの量です。



 a| 
コントローラ所有権
 a| 
コントローラ所有権は、ボリュームを所有するプライマリコントローラを定義します。ボリュームは'ボリュームを所有する優先コントローラ（AまたはB）を持つことができますボリューム所有権は、自動ロードバランシング機能を使用して自動的に調整され、コントローラ間でワークロードが移動する際の負荷分散の問題が修正されます。自動ロードバランシングは、I/Oワークロードを自動的に分散し、ホストからの受信I/Oトラフィックを動的に管理して両方のコントローラに分散します。



 a| 
動的キャッシュ読み取りプリフェッチ
 a| 
動的キャッシュ読み取りプリフェッチでは、コントローラは、ドライブからキャッシュにデータブロックを読み取っているときに、連続する追加のデータブロックをキャッシュにコピーすることができます。このキャッシュにより、以降のデータ要求にキャッシュから対応できる可能性が高まります。動的キャッシュ読み取りプリフェッチは、シーケンシャルI/Oを使用するマルチメディアアプリケーションで重要です。データがキャッシュにプリフェッチされる速度と量は、ホスト読み取りの速度と要求サイズに基づいて自動で調整されます。ランダムアクセスでは、データがキャッシュにプリフェッチされることはありません。この機能は、読み取りキャッシュが無効になっている場合は適用されません。

動的キャッシュ読み取りプリフェッチはシンボリュームに対しては常に無効で、変更することはできません。



 a| 
空き容量領域
 a| 
空き容量領域は、ボリュームを削除した場合や、ボリュームの作成時に使用可能なすべての空き容量を使用しなかった場合に発生する空き容量です。1つ以上の空き容量領域があるボリュームグループでボリュームを作成する場合、ボリュームの容量はそのボリュームグループ内で最も大きい空き容量領域に制限されます。たとえば、ボリュームグループの合計空き容量が15GiBで、最も大きい空き容量領域が10GiBの場合、作成できるボリュームの最大サイズは10GiBです。

空き容量を統合することで、ボリュームグループ内の空き容量を最大限に増やして追加ボリュームを作成できます。



 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
ホストクラスタ
 a| 
ホストクラスタはホストのグループです。ホストクラスタを作成すると、同じボリュームを複数のホストに簡単に割り当てることができます。



 a| 
ホットスペアドライブ
 a| 
ホットスペアドライブはボリュームグループでのみサポートされます。ホットスペアドライブにはデータは格納されておらず、ボリュームグループに含まれるRAID 1、RAID 3、RAID 5、またはRAID 6のボリュームでドライブに障害が発生した場合のスタンバイとして機能します。ホットスペアドライブを使用すると、ストレージアレイの冗長性が向上します。



 a| 
LUN
 a| 
Logical Unit Number（LUN；論理ユニット番号）は、ホストがボリュームへのアクセスに使用する番号で、アドレススペースに割り当てられます。ボリュームは、LUNの形式で容量としてホストに提示されます。

各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを異なるホストで使用して、異なるボリュームにアクセスできます。



 a| 
メテイアスキヤン
 a| 
メディアスキャンは、ドライブに対する通常の読み取り/書き込みの際に、ドライブメディアのエラーが検出される前に検出する機能です。メディアスキャンはバックグラウンド処理として実行され、定義されたユーザボリューム内のすべてのデータと冗長性情報がスキャンされます。



 a| 
ネームスペース
 a| 
ネームスペースは、ブロックアクセス用にフォーマットされたNVMストレージです。SCSIの論理ユニットに相当し、ストレージアレイ内のボリュームに関連します。



 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセスできる1つ以上のボリュームを作成できます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
プールまたはボリュームグループの容量
 a| 
プール、ボリューム、またはボリュームグループの容量は、プールまたはボリュームグループに割り当てられているストレージアレイ内の容量です。この容量は、ボリュームを作成し、コピーサービス処理やストレージオブジェクトで必要とされるさまざまな容量に対応するために使用されます。



 a| 
読み取りキャッシュ
 a| 
読み取りキャッシュは、ドライブから読み取られたデータを格納するバッファです。読み取り処理の対象となるデータが以前の処理ですでにキャッシュに格納されていれば、ドライブにアクセスする必要はありません。読み取りキャッシュのデータは、フラッシュされるまで保持されます。



 a| 
レポート容量
 a| 
レポート容量は、ホストに報告され、ホストからアクセスできる容量です。

レポート容量と割り当て容量はシックボリュームでは同じですが、シンボリュームでは異なります。シックボリュームの場合、物理的に割り当てられたスペースは、ホストに報告されるスペースと同じになります。シンボリュームの場合、レポート容量はホストに報告される容量であり、割り当て容量はデータの書き込み用に現在割り当てられているドライブスペースの量です。



 a| 
セグメントサイズ
 a| 
セグメントは、あるドライブに格納されるデータの量（KiB）です。この量に達すると、ストライプ（RAIDグループ）内の次のドライブへと進みます。セグメントサイズがボリュームグループの容量以下である。プールのセグメントサイズは固定であり、変更することはできません。



 a| 
ストライピング
 a| 
ストライピングは、ストレージアレイにデータを格納する方法の1つです。ストライピングでは、データフローが特定のサイズ（「ブロックサイズ」）のブロックに分割され、それらのブロックがドライブに1つずつ書き込まれます。このデータ格納方法は、複数の物理ドライブにデータを分散して格納する場合に使用されます。ストライピングはRAID 0と同義で、パリティを使用せずにRAIDグループ内のすべてのドライブにデータを分散します。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。



 a| 
ボリュームの割り当て
 a| 
ボリューム割り当てとは、ホストLUNのボリュームへの割り当てです。



 a| 
ボリューム名
 a| 
ボリューム名は、ボリュームの作成時に割り当てられる文字列です。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループには容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセスできる1つ以上のボリュームを作成できます。（ボリュームはボリュームグループまたはプールから作成します）。



 a| 
ワークロード
 a| 
ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロード（インスタンス）を定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。



 a| 
書き込みキャッシュ
 a| 
書き込みキャッシュは、ドライブにまだ書き込まれていないホストからのデータを格納するバッファです。データは、ドライブに書き込まれるまで書き込みキャッシュに残ります。書き込みキャッシュにより、I/Oパフォーマンスを向上させることができます。



 a| 
ミラーリングありの書き込みキャッシュ
 a| 
ミラーリングありの書き込みキャッシュは、一方のコントローラのキャッシュメモリに書き込まれたデータがもう一方のコントローラのキャッシュメモリにも書き込まれる場合に発生します。そのため、一方のコントローラで障害が発生した場合、もう一方のコントローラで未処理の書き込み処理をすべて完了できます。書き込みキャッシュのミラーリングは、書き込みキャッシュが有効で、2台のコントローラが配置されている場合にのみ使用できます。ミラーリングありの書き込みキャッシュは、ボリュームの作成時にデフォルトで設定されます。



 a| 
バッテリなしの書き込みキャッシュ
 a| 
バッテリなしの書き込みキャッシュを設定すると、バッテリがない、障害が発生している、完全に放電されている、フル充電されていないなどの状況でも書き込みキャッシュが継続されます。バッテリなしの書き込みキャッシュを選択すると電源の喪失時にデータが失われる可能性があるため、一般には推奨されません。通常、書き込みキャッシュは、バッテリが充電されるか障害が発生したバッテリが交換されるまで、コントローラによって一時的にオフにされます。

|===


== シンボリューム固有

[NOTE]
====
System Managerには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用してください。

====
[NOTE]
====
シンボリュームはEF600またはEF300ストレージシステムでは使用できません。

====
[cols="25h,~"]
|===
| 期間 | 製品説明 


 a| 
割り当て容量の制限
 a| 
割り当て容量の制限は、シンボリュームの拡張時に割り当てることができる物理容量の上限です。



 a| 
書き込み済み容量
 a| 
書き込み済み容量は、シンボリュームに割り当てられたリザーブ容量のうちの書き込み済みの容量です。



 a| 
警告しきい値
 a| 
警告しきい値アラートは、シンボリュームの割り当て容量がしきい値に達したときに発行されるように設定できます（警告しきい値）。

|===