---
permalink: sm-storage/what-is-segment-sizing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, segment, size, storage, raid 
summary: セグメントは、あるドライブに格納されるデータの量（KiB）です。この量に達すると、ストライプ（RAIDグループ）内の次のドライブへと進みます。セグメントサイズはボリュームグループにのみ適用され、プールには適用されません。 
---
= セグメントサイズとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セグメントは、あるドライブに格納されるデータの量（KiB）です。この量に達すると、ストライプ（RAIDグループ）内の次のドライブへと進みます。セグメントサイズはボリュームグループにのみ適用され、プールには適用されません。

セグメントサイズは、セグメントに含まれるデータブロックの数で定義されます。セグメントサイズを決定するときは、ボリュームに格納するデータのタイプを把握しておく必要があります。アプリケーションが一般にスモールランダムリードとスモールランダムライト（IOPS）を使用する場合は、一般に小さいセグメントサイズが適しています。また、アプリケーションが大容量のシーケンシャルリード/ライト（スループット）を実行している場合は、一般に大きなセグメントサイズの方が適しています。

アプリケーションがスモールランダムリード/ライトを使用する場合でも、ラージシーケンシャルリード/ライトを使用する場合でも、セグメントサイズが一般的なデータブロックのチャンクサイズよりも大きいと、ストレージアレイのパフォーマンスが向上します。これにより、ドライブからのデータへのアクセスがより簡単かつ高速になります。これは、ストレージアレイのパフォーマンスを向上させるために重要です。



== IOPSパフォーマンスが重視される環境

IOPS（1秒あたりのI/O処理数）環境では、ドライブに対して読み書きされる標準的なデータブロックサイズ（「チャンク」）よりもセグメントサイズを大きくすると、ストレージアレイのパフォーマンスが向上します。こうすることで、各チャンクが確実に1つのドライブに書き込まれます。



== スループットが重視される環境

スループット環境では、セグメントサイズは、データ用ドライブの総数および一般的なデータチャンクサイズ（I/Oサイズ）の偶数になります。これにより、データが単一のストライプとしてボリュームグループ内のドライブに分散されるため、読み取りと書き込みが高速になります。
