---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, default, cluster, 
summary: デフォルトクラスタはシステム定義のエンティティで、ストレージアレイにログインしたホストポート識別子が関連付けられていない場合に、デフォルトクラスタに割り当てられているボリュームへのアクセスを許可します。関連付けられていないホストポート識別子は、特定のホストに論理的に関連付けられていないが、ホストに物理的に設置されてストレージアレイにログインしているホストポートです。 
---
= デフォルトクラスタとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトクラスタはシステム定義のエンティティで、ストレージアレイにログインしたホストポート識別子が関連付けられていない場合に、デフォルトクラスタに割り当てられているボリュームへのアクセスを許可します。関連付けられていないホストポート識別子は、特定のホストに論理的に関連付けられていないが、ホストに物理的に設置されてストレージアレイにログインしているホストポートです。

[NOTE]
====
ホストがストレージアレイ内の特定のボリュームにアクセスできるようにする場合は、デフォルトクラスタを使用する_は_しない_選択します。代わりに、ホストポート識別子を対応するホストに関連付ける必要があります。このタスクは、ホスト作成処理中に手動で実行できます。次に、個 々 のホストまたはホストクラスタにボリュームを割り当てます。

====
デフォルトクラスタは、すべてのホストとストレージアレイに接続されたすべてのログイン済みホストポート識別子がすべてのボリュームにアクセスできるようにするための外部ストレージ環境を構築する場合にのみ使用してください（フルアクセスモード） 特にストレージアレイやユーザインターフェイスでホストが認識されないようにする必要があります。

最初にボリュームをデフォルトクラスタに割り当てるには、コマンドラインインターフェイス（CLI）を使用する必要があります。ただし、ボリュームを少なくとも1つデフォルトクラスタに割り当てると、ユーザインターフェイスに表示されて管理できるようになります。
