---
permalink: sm-storage/what-raid-level-is-best-for-my-application.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, raid, level, application, performance, 
summary: 'ボリュームグループのパフォーマンスを最大限に高めるには、適切なRAIDレベルを選択する必要があります。適切なRAIDレベルを判断するには、ボリュームグループにアクセスしているアプリケーションの読み取りと書き込みの割合を把握します。これらの割合は、[Performance]ページで確認できます。' 
---
= アプリケーションに最適なRAIDレベルを教えてください。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームグループのパフォーマンスを最大限に高めるには、適切なRAIDレベルを選択する必要があります。適切なRAIDレベルを判断するには、ボリュームグループにアクセスしているアプリケーションの読み取りと書き込みの割合を把握します。これらの割合は、[Performance]ページで確認できます。



== RAIDレベルとアプリケーションパフォーマンス

RAIDには、_levels _という一連の構成が採用されており、ユーザデータと冗長性データのドライブに対する書き込み/読み出し方法が決定されます。RAIDレベルごとに異なるパフォーマンス機能が提供されます。読み取り率が高いアプリケーションでは、RAID 5ボリュームまたはRAID 6ボリュームを使用すると、RAID 5およびRAID 6構成の読み取りパフォーマンスが優れているため、パフォーマンスが向上します。

読み取り比率が低い（書き込み中心の）アプリケーションの場合、RAID 5ボリュームまたはRAID 6ボリュームでは同様のパフォーマンスを実現できません。パフォーマンスの低下は、コントローラがデータと冗長性データをRAID 5ボリュームグループまたはRAID 6ボリュームグループのドライブに書き込む方法が原因です。

次の情報に基づいてRAIDレベルを選択します。

* RAID 0*

* * 概要 *
+
** 非冗長、ストライピングモード。


* *どのように機能するか*
+
** RAID 0は、ボリュームグループ内のすべてのドライブにわたってデータをストライピングします。


* *データ保護機能*
+
** 高可用性が求められる場合、RAID 0は推奨されません。RAID 0は重要度の低いデータに適しています。
** ボリュームグループ内の1本のドライブで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。


* *必要なドライブ数*
+
** RAIDレベル0には少なくとも1本のドライブが必要です。
** RAID 0ボリュームグループには30本を超えるドライブを含めることができます。
** ストレージアレイ内のすべてのドライブを含むボリュームグループを作成できます。




* RAID 1またはRAID 10 *

* * 概要 *
+
** ストライピング/ミラーモード。


* *どのように機能するか*
+
** RAID 1は、ディスクミラーリングを使用して、2つの重複ディスクに同時にデータを書き込みます。
** RAID 10は、ドライブストライピングを使用して、ミラーリングされた一連のドライブペアにデータをストライピングします。


* *データ保護機能*
+
** RAID 1とRAID 10は、高いパフォーマンスと最高のデータ可用性を提供します。
** RAID 1およびRAID 10では、ドライブミラーリングを使用して、あるドライブから別のドライブに完全なコピーを作成します。
** ドライブペアの一方のドライブで障害が発生しても、ストレージアレイはデータやサービスを失うことなく、もう一方のドライブに即座に切り替えることができます。
** 単一ドライブ障害が発生すると、関連付けられているボリュームがデグレード状態になります。ミラードライブはデータへのアクセスを許可します。
** ボリュームグループのドライブペアで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、データが失われる可能性があります。


* *必要なドライブ数*
+
** RAID 1には少なくとも2つのドライブが必要です。1つはユーザデータ用、もう1つはミラーリングされたデータ用です。
** 4本以上のドライブを選択すると、ボリュームグループ全体（ユーザデータ用に2本、ミラーリングされたデータ用に2本）でRAID 10が自動的に設定されます。
** ボリュームグループには偶数個のドライブが必要です。ドライブ数が偶数ではなく未割り当てのドライブが残っている場合は、「* Pools & Volume Groups」に移動してボリュームグループにドライブを追加し、処理を再試行します。
** RAID 1とRAID 10のボリュームグループには30本を超えるドライブを含めることができます。ストレージアレイ内のすべてのドライブを含むボリュームグループを作成できます。




* RAID 5*

* * 概要 *
+
** 高I/Oモード。


* *どのように機能するか*
+
** ユーザデータと冗長情報（パリティ）が複数のドライブにストライピングされます。
** 冗長性情報を格納するために、ドライブ1本分の容量が使用されます。


* *データ保護機能*
+
** RAID 5ボリュームグループの1本のドライブで障害が発生すると、関連付けられているすべてのボリュームがデグレード状態になります。冗長な情報により、データに引き続きアクセスできます。
** RAID 5ボリュームグループで複数のドライブに障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。


* *必要なドライブ数*
+
** ボリュームグループには少なくとも3本のドライブが必要です。
** 通常、ボリュームグループ内のドライブ数は最大30本に制限されます。




* RAID 6*

* * 概要 *
+
** 高I/Oモード。


* *どのように機能するか*
+
** ユーザデータと冗長情報（デュアルパリティ）が複数のドライブにストライピングされます。
** 冗長性情報を格納するために、ドライブ2本分の容量が使用されます。


* *データ保護機能*
+
** RAID 6ボリュームグループで1本または2本のドライブに障害が発生すると、関連付けられているすべてのボリュームがデグレード状態になりますが、冗長性情報を使用することで引き続きデータにアクセスできます。
** RAID 6ボリュームグループで3本以上のドライブで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。


* *必要なドライブ数*
+
** ボリュームグループには少なくとも5本のドライブが必要です。
** 通常、ボリュームグループ内のドライブ数は最大30本に制限されます。




[NOTE]
====
プールのRAIDレベルは変更できません。プールは、ユーザインターフェイスによって自動的にRAID 6として構成されます。

====


== RAIDレベルとデータ保護

RAID 1、RAID 5、およびRAID 6は、フォールトトレランスのために冗長性データをドライブメディアに書き込みます。冗長性データには、データのコピー（ミラーリング）や、データから導き出されたエラー修正コードなどがあります。ドライブで障害が発生した場合に、冗長性データを使用して交換用ドライブに迅速に情報を再構築できます。

単一のボリュームグループ全体で単一のRAIDレベルを設定します。そのボリュームグループの冗長性データはすべてボリュームグループ内に格納されます。ボリュームグループの容量は、メンバードライブのアグリゲート容量から冗長性データ用に確保されている容量を引いたものです。冗長性を確保するために必要な容量は、使用するRAIDレベルによって異なります。
