---
permalink: sm-storage/what-do-i-need-to-know-about-host-block-size-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, block size, 
summary: EF300およびEF600システムでは、ボリュームを設定して512バイトまたは4KiBのブロックサイズ（「コレクタサイズ」とも呼ばれます）をサポートすることができます。ボリュームの作成時に正しい値を設定する必要があります。可能な場合は、適切なデフォルト値が提示されます。 
---
= ホストのブロックサイズの要件について、どのような点に注意する必要がありますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF300およびEF600システムでは、ボリュームのブロックサイズ（「セクターサイズ」とも呼ばれます）を512バイトまたは4KiBに設定できます。ボリュームの作成時に正しい値を設定する必要があります。可能な場合は、適切なデフォルト値が提示されます。

ボリュームのブロックサイズを設定する前に、次の制限事項とガイドラインを確認してください。

* 一部のオペレーティングシステムおよび仮想マシン（現時点ではVMwareなど）では512バイトのブロックサイズが必要であり、4KiBをサポートしていないため、ボリュームを作成する前にホストの要件を確認してください。通常、最適なパフォーマンスを実現するには、ボリュームを4KiBのブロックサイズに設定します。ただし、ホストで4KiB（または「4Kn`」）のブロックを使用できることを確認します。
* サポートされるボリュームのブロックサイズは、次のように、プールまたはボリュームグループに対して選択するドライブのタイプによっても決まります。
+
** 512バイトのブロックに書き込むドライブを使用してボリュームグループを作成する場合、512バイトのブロックを含むボリュームのみを作成できます。
** 4KiBブロックに書き込むドライブを使用してボリュームグループを作成する場合は、512バイトブロックまたは4KiBブロックのボリュームを作成できます。


* アレイにiSCSIホストインターフェイスカードが搭載されている場合、ボリュームグループのブロックサイズに関係なく、すべてのボリュームのブロック数が512バイトに制限されます。これは、特定のハードウェアの実装によるものです。
* 一度設定したブロックサイズは変更できません。ブロックサイズを変更する必要がある場合は、ボリュームを削除して再作成する必要があります。

