---
permalink: sm-storage/why-are-some-drives-not-showing-up.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drives, Add Capacity 
summary: '[容量の追加]ダイアログで、すべてのドライブを既存のプールまたはボリュームグループに容量を追加できるわけではありません。' 
---
= 一部のドライブが表示されないのはなぜですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[容量の追加]ダイアログで、すべてのドライブを既存のプールまたはボリュームグループに容量を追加できるわけではありません。

ドライブを追加できない理由は次のとおりです。

* 未割り当ての、セキュリティ有効でないドライブを指定する必要があります。すでに別のプールまたはボリュームグループに属しているドライブ、またはホットスペアとして設定されているドライブは使用できません。未割り当てだが、セキュリティ有効なドライブは、手動で消去すると使用可能になります。
* 最適な状態でないドライブは使用できません。
* 容量が小さすぎるドライブは使用できません。
* プールまたはボリュームグループ内でドライブのメディアタイプが一致している必要があります。次のものを混在させることはできません。
+
** ソリッドステートディスク（SSD）搭載ハードディスクドライブ（HDD）
** SASドライブ搭載のNVMe
** 512バイトおよび4KiBのボリュームブロックサイズのドライブ


* プールまたはボリュームグループに含まれているドライブがすべてセキュリティ対応ドライブの場合、セキュリティ対応でないドライブは表示されません。
* プールまたはボリュームグループに含まれているドライブがすべて連邦情報処理標準（FIPS）ドライブの場合、FIPS以外のドライブは表示されません。
* プールまたはボリュームグループにData Assurance（DA）対応ドライブが含まれていて、プールまたはボリュームグループにDA対応ボリュームが1つ以上ある場合は、DA対応でないドライブは使用できないため、そのプールまたはボリュームグループに追加することはできません。ただし、プールまたはボリュームグループにDA対応ボリュームがない場合は、DA対応でないドライブをプールまたはボリュームグループに追加できます。これらのドライブを混在させる場合は、DA対応ボリュームは作成できないことに注意してください。


[NOTE]
====
ストレージアレイの容量は、新しいドライブを追加するか、プールまたはボリュームグループを削除して増やすことができます。

====