---
permalink: sm-storage/why-am-i-seeing-a-capacity-over-allocation-error-when-i-have-enough-free-capacity-in-a-volume-group-to-create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, over-allocation, error, 
summary: 選択したボリュームグループには1つ以上の空き容量領域がある可能性があります。空き容量領域は、ボリュームを削除した場合や、ボリュームの作成時に使用可能なすべての空き容量を使用しなかった場合に発生する空き容量です。 
---
= ボリュームグループにボリュームの作成に十分な空き容量があると、容量の過剰割り当てエラーが表示されるのはなぜですか？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
選択したボリュームグループには1つ以上の空き容量領域がある可能性があります。空き容量領域は、ボリュームを削除した場合や、ボリュームの作成時に使用可能なすべての空き容量を使用しなかった場合に発生する空き容量です。

1つ以上の空き容量領域があるボリュームグループでボリュームを作成する場合、ボリュームの容量はそのボリュームグループ内で最も大きい空き容量領域に制限されます。たとえば、ボリュームグループの合計空き容量が15GiBで、最も大きい空き容量領域が10GiBの場合、作成できるボリュームの最大サイズは10GiBです。

ボリュームグループに空き容量領域がある場合は、ボリュームグループのグラフに、既存の空き容量領域の数を示すリンクが表示されます。リンクを選択すると、各領域の容量を示すポップアップが表示されます。

空き容量を統合することで、ボリュームグループ内の空き容量を最大限に増やして追加ボリュームを作成できます。次のいずれかの方法を使用して、選択したボリュームグループの既存の空き容量を統合できます。

* ボリュームグループで少なくとも1つの空き容量領域が検出されると、[ホーム]ページの[通知]領域に「空き容量の統合」という推奨事項が表示されます。[*空き容量の統合*（Consolidate free capacity）]リンクをクリックして、ダイアログボックスを起動します。
* メニューから[プールとボリュームグループ[一般的でないタスク]>[ボリュームグループの空き容量の統合]を選択して、ダイアログボックスを起動することもできます。


最大の空き容量領域ではなく特定の空き容量領域を使用する場合は、コマンドラインインターフェイス（CLI）を使用してください。
