---
permalink: sm-mirroring/asynchronous-mirror-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirror, status, consistency, group, 
summary: ミラーステータスは、ミラー整合性グループとミラーボリュームペアの状態を定義します。 
---
= 非同期ミラーのステータス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーステータスは、ミラー整合性グループとミラーボリュームペアの状態を定義します。



== ミラー整合性グループのステータス

[cols="25h,~"]
|===
| ステータス | 製品説明 


 a| 
同期（初期同期）
 a| 
ミラーボリュームペア間で完了した初期データ同期の進捗状況。

初期同期中に、ボリュームは、デグレード/失敗/最適/不明の各状態に移行できます。



 a| 
同期（間隔同期）
 a| 
ミラーボリュームペア間で完了した定期的なデータ同期の進捗状況。



 a| 
システム中断
 a| 
ミラー整合性グループレベルで、すべてのミラーペアについて、データの同期がストレージシステムによって一時停止された状態。

ミラー整合性グループ内の少なくとも1つのミラーペアが停止または障害状態です。



 a| 
ユーザによる中断
 a| 
ミラー整合性グループレベルで、すべてのミラーペアについて、データの同期がユーザによって一時停止されました。

この状態は、ホストアプリケーションのパフォーマンスへの影響（ローカルストレージアレイで変更されたデータがリモートストレージアレイにコピーされるときに発生する可能性があります）を削減するのに役立ちます。



 a| 
一時停止
 a| 
リモートストレージアレイへのアクセス中にエラーが発生したため、データ同期プロセスが一時停止しました。



 a| 
孤立
 a| 
孤立したミラーペアボリュームは、整合性ミラーグループの一方（プライマリまたはセカンダリ）で整合性ミラーグループのメンバーボリュームが削除され、もう一方では削除されていない場合に発生します。

孤立したミラーペアボリュームは、アレイ間の通信がリストアされ、ミラー構成の両サイドでミラーパラメータが調整されたときに検出されます。

ミラーペアを削除すると、孤立したミラーペアの状態を修正できます。



 a| 
ロール変更を保留中/実行中
 a| 
ミラー整合性グループ間のロールの変更が保留中または進行中です。

ロールを（プライマリロールまたはセカンダリロールに）反転すると、選択したミラー整合性グループ内のすべての非同期ミラーペアに反映されます。

保留中のロール変更はキャンセルできますが、進行中のロール変更はキャンセルできません。



 a| 
ロールの競合
 a| 
ロール変更処理中にローカルストレージアレイとリモートストレージアレイの間の通信に問題が発生したため、ミラー整合性グループ間でロールの競合が発生しました。

通信の問題が解決されると、ロールの競合が発生します。Recovery Guruを使用してこのエラーを解決してください。

ロールの競合を解決する場合、強制昇格は許可されません。

|===


== ミラアヘアノステエタス

ミラーペアのステータスは、プライマリボリュームとセカンダリボリュームのデータが同期されているかどうかを示します。

[cols="25h,~"]
|===
| ステータス | 製品説明 


 a| 
トウキ
 a| 
ミラーペア間で完了した初期または定期的なデータ同期の進捗状況。

同期には、初期同期と定期的同期の2種類があります。初期同期の進捗状況は、[Long Running Operations]ダイアログボックスにも表示されます。



 a| 
最適
 a| 
ミラーペア内のボリュームが同期されています。これは、ストレージアレイ間の接続が動作していて、各ボリュームが適切な動作状態にあることを示しています。



 a| 
不完全
 a| 
System Managerでサポートされていないストレージアレイでミラーペアの作成手順が開始され、セカンダリでミラーペアが完了していないため、リモートストレージアレイ上の非同期ミラーペアが不完全です。

ミラーペアの作成プロセスは、リモートストレージアレイ上のミラー整合性グループにボリュームを追加すると完了します。このボリュームが非同期ミラーペアのセカンダリボリュームになります。

リモートストレージアレイがSystem Managerで管理されている場合、ミラーペアは自動的に完了します。



 a| 
失敗
 a| 
プライマリボリューム、セカンダリボリューム、またはミラーのリザーブ容量で障害が発生したため、非同期ミラーリング処理を正常に実行できません。



 a| 
孤立
 a| 
孤立したミラーペアボリュームは、整合性ミラーグループの一方（プライマリまたはセカンダリ）で整合性ミラーグループのメンバーボリュームが削除され、もう一方では削除されていない場合に発生します。

孤立したミラーペアボリュームは、2つのストレージアレイ間の通信がリストアされ、ミラー構成の両側でミラーパラメータが調整されると検出されます。

ミラーペアを削除すると、孤立したミラーペアの状態を修正できます。



 a| 
停止
 a| 
ミラー整合性グループがシステムによって中断された状態であるため、ミラーペアは停止状態です。

|===