---
permalink: sm-mirroring/change-synchronization-settings-for-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, synchronization, settings, mirror, consistency, group, 
summary: ローカルストレージアレイ上のミラー整合性グループが、データが最初に同期されたときや非同期ミラーリング処理中にデータが再同期されたときに使用する同期設定と警告しきい値を変更できます。 
---
= ミラー整合性グループの同期設定の変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルストレージアレイ上のミラー整合性グループが、データが最初に同期されたときや非同期ミラーリング処理中にデータが再同期されたときに使用する同期設定と警告しきい値を変更できます。

.タスクの内容
同期設定を変更すると、ミラー整合性グループ内のすべてのミラーペアの同期処理に反映されます。

.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラー整合性グループ*（Mirror Consistency Groups *）]タブを選択します。
+
[ミラー整合性グループ]の表に、ストレージアレイに関連付けられているすべてのミラー整合性グループが表示されます。

. 編集するミラー整合性グループを選択し、メニューから[More（詳細）][Edit Settings（設定の編集）]を選択します。
+
[設定の編集]ダイアログボックスが表示されます。

. 必要に応じて同期とアラートの設定を編集し、*保存*をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 製品説明 


 a| 
ミラーペアを同期...
 a| 
リモートストレージアレイのミラーペアの同期を手動で行うか自動で行うかを指定します。

** **手動**–リモートストレージアレイ上のミラーペアを手動で同期する場合に選択します
** **自動、**–リモートストレージアレイのミラーペアを自動的に同期する場合は、前の更新の開始から次の更新の開始までの間隔を指定します。デフォルトの間隔は10分です。




 a| 
アラートを受け取る条件を選択...
 a| 
同期方法を自動的に実行するように設定した場合は、次のアラートを設定します。

** **同期**–同期が完了していないというアラートがSystem Managerから送信されるまでの時間を設定します。
** **リモートリカバリポイント**–リモートストレージアレイのリカバリポイントデータが指定した制限時間より古くなったことを示すアラートがSystem Managerから送信されるまでの時間制限を設定します。期限は、前回の更新の終了時点からの経過時間で定義します。
** **リザーブ容量のしきい値**–リザーブ容量が指定した値を超えるとSystem Managerからアラートが送信され、リザーブ容量のしきい値に近づいていることが通知されます。しきい値は残りの容量の割合で定義します。


|===
====


.結果
System Managerによって、ミラー整合性グループ内のすべてのミラーペアの同期設定が変更されます。
