---
permalink: sm-mirroring/change-mirror-consistency-group-role-to-primary-or-secondary.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, mirror, consistency group, primary, secondary 
summary: 管理目的で、またはローカルストレージアレイで災害が発生した場合に、ミラー整合性グループ間でロールを変更できます。 
---
= ミラー整合性グループのロール変更（プライマリまたはセカンダリ）
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理目的で、またはローカルストレージアレイで災害が発生した場合に、ミラー整合性グループ間でロールを変更できます。

.タスクの内容
ローカルストレージアレイに作成されたミラー整合性グループには、プライマリロールが割り当てられます。リモートストレージアレイに作成されたミラー整合性グループには、セカンダリロールが割り当てられます。ローカルのミラー整合性グループのロールをセカンダリに降格するか、リモートのミラー整合性グループのロールをプライマリに昇格することができます。

.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラー整合性グループ*（Mirror Consistency Groups *）]タブを選択します。
+
[ミラー整合性グループ]の表に、ストレージアレイに関連付けられているすべてのミラー整合性グループが表示されます。

. ロールを変更するミラー整合性グループを選択し、メニューを選択します。More [Change role to <Primary | Secondary]*>>*。
+
確認メッセージが表示されます。

. ミラー整合性グループのロールを変更することを確認し、* Change Role *をクリックします。
+
[NOTE]
====
ロールの変更が要求されてもリモートストレージアレイに接続できない場合、[ストレージアレイに接続できません]ダイアログボックスが表示されます。[はい]をクリックして、強制的にロールを変更します。

====


.結果
System Managerは次の処理を実行します。

* [ミラー整合性グループ]テーブルで、ロール変更を実行中のミラー整合性グループの横にステータスが「保留」または「実行中」と表示されます。テーブルセル内にある*Cancel*リンクをクリックすると、保留中のロール変更操作をキャンセルできます。
* 関連付けられたミラー整合性グループにアクセスできる場合は、ミラー整合性グループ間でロールが変更されます。選択した内容に応じて、System Managerはセカンダリミラー整合性グループのロールをプライマリに昇格するか、プライマリミラー整合性グループのロールをセカンダリに降格します。ロール変更は、選択したミラー整合性グループ内のすべてのミラーペアに反映されます。

