---
permalink: sm-mirroring/change-role-between-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, role, volumes, mirrored, pair, 
summary: 管理目的またはローカルストレージアレイで災害が発生した場合に、同期ミラーリングに参加しているミラーペア内の2つのボリューム間でロールを交換することができます。 
---
= ミラーペア内のボリューム間でのロールの変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期ミラーリングに参加しているミラーペア内の2つのボリューム間でロール反転を実行できます。このタスクは、管理目的やローカルストレージアレイで災害が発生した場合に必要になることがあります。

.タスクの内容
プライマリボリュームをセカンダリロールに降格するか、セカンダリボリュームをプライマリロールに昇格できます。プライマリボリュームにアクセスしているホストには、そのボリュームに対する読み取り/書き込みアクセス権があります。プライマリボリュームがセカンダリボリュームになると、プライマリコントローラによって開始されたリモート書き込みだけがボリュームに書き込まれます。

.手順
. 選択メニュー：Storage [Synchronous Mirroring]
. ロールを変更するボリュームが含まれているミラーペアを選択し、メニューから[More]（その他）[Change Role]（ロールの変更）を選択します。
+
確認メッセージが表示されます。

. ボリュームのロールを変更することを確認し、*ロールの変更*を選択します。
+
[NOTE]
====
ローカルストレージアレイがリモートストレージアレイと通信できない場合、ロールの変更が要求されたときにシステムに[ストレージアレイにアクセスできません]ダイアログボックスが表示されますが、リモートストレージアレイにアクセスできません。[はい]をクリックして、強制的にロールを変更します。

====


.結果
System Managerは次の処理を実行します。

* ミラーペア内の関連付けられているボリュームにアクセスできる場合は、ボリューム間でロールが変更されます。選択内容に応じて、ミラーペアのセカンダリボリュームのロールがプライマリに昇格されるか、プライマリボリュームのロールがセカンダリに降格されます。

