---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: SANtricity System Managerで管理できない従来のストレージアレイにプライマリボリュームを作成した場合は、System Managerを使用してそのアレイにセカンダリボリュームを作成できます。 
---
= 従来型システムで作成されたプライマリボリュームのミラーペアの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Managerで管理できない従来型ストレージアレイにプライマリボリュームを作成した場合は、System Managerでこのアレイにセカンダリボリュームを作成できます。

.タスクの内容
別のインターフェイスを使用する従来のアレイとSystem Managerで管理可能な新しいアレイの間で、非同期ミラーリングを実行できます。

* System Managerを使用する2つのストレージアレイをミラーリングする場合は、ミラーペア作成手順ですでにミラーペアの作成が完了しているため、このタスクはスキップできます。
* このタスクはリモートストレージアレイで実行します。


.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラーペア*（Mirrored Pair *）]タブを選択します。
+
[ミラーペア]の表に、ストレージアレイに関連付けられているすべてのミラーペアが表示されます。

. ステータスが「Incomplete」のミラーペアボリュームを探し、ミラーペアの列に表示された「* Complete Mirrored pair *」リンクをクリックします。
. 次のいずれかのラジオボタンを選択して、ミラーペア作成手順を自動で実行するか手動で実行するかを選択します。
+
** *自動*--新しいセカンダリボリュームを作成します
+
セカンダリボリュームを作成する既存のプールまたはボリュームグループを選択して、ミラーペアのリモート側のデフォルト設定を受け入れます。セカンダリボリュームにデフォルトの設定でリザーブ容量を割り当てるには、このオプションを使用します（推奨）。

** *手動*--既存のボリュームを選択します
+
セカンダリボリュームのパラメータを独自に定義します。

+
... Next（次へ）*をクリックして、セカンダリボリュームを選択します。
... セカンダリボリュームとして使用する既存のボリュームを選択し、* Next *をクリックしてリザーブ容量を割り当てます。
... リザーブ容量を割り当てます。次のいずれかを実行します。
+
**** デフォルト設定をそのまま使用します。
+
リザーブ容量のデフォルト設定はベースボリュームの容量の20%で、通常はこの容量で十分です。

**** 非同期ミラーリングに関連するデータストレージのニーズに合わせて、独自の設定でリザーブ容量を割り当てます。
+
必要な容量は、プライマリボリュームに対するI/O書き込みの頻度とサイズ、およびその容量を維持する必要がある期間によって異なります。一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。

+
***** ミラーペアを長期間保持する場合。
***** 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。








. [*Complete]を選択します。


.結果
System Managerは次の処理を実行します。

* リモートストレージアレイにセカンダリボリュームを作成し、ミラーペアのリモート側にリザーブ容量を割り当てます。
* ローカルストレージアレイとリモートストレージアレイの間の初期同期を開始します。
* ミラーリング対象のボリュームがシンボリュームの場合、初期同期では割り当てられたブロックのみがセカンダリボリュームに転送されます。この転送により、初期同期を完了するために転送する必要のあるデータ量が削減されます。
* ローカルストレージアレイとリモートストレージアレイにミラーペア用のリザーブ容量を作成します。

