---
permalink: sm-mirroring/how-does-asynchronous-mirroring-differ-from-synchronous-mirroring-async.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asysnchronous, mirroring, differ, synchronous, mirroring, 
summary: 非同期ミラーリング機能と同期ミラーリング機能の重要な点は、非同期ミラーリング機能がソースボリュームの特定の時点の状態をキャプチャし、前回のイメージキャプチャ以降に変更されたデータのみをコピーするという点です。 
---
= 非同期ミラーリングと同期ミラーリングの違いは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非同期ミラーリング機能と同期ミラーリング機能の重要な点は、非同期ミラーリング機能がソースボリュームの特定の時点の状態をキャプチャし、前回のイメージキャプチャ以降に変更されたデータのみをコピーするという点です。

同期ミラーリングでは、プライマリボリュームの状態はある時点でキャプチャされるのではなく、プライマリボリュームで行われたすべての変更がセカンダリボリュームに反映されます。このタイプのミラーでは、プライマリボリュームへの書き込みが行われるたびにセカンダリボリュームへの書き込みが行われるため、セカンダリボリュームは常にプライマリボリュームと同一です。プライマリボリュームで行われた変更でセカンダリボリュームが更新されるまで、ホストは書き込みが成功したという確認応答を受信しません。

非同期ミラーリングでは、リモートストレージアレイはローカルストレージアレイと完全に同期されません。そのため、ローカルストレージアレイの損失によってアプリケーションをリモートストレージアレイに移行する必要がある場合、一部のトランザクションが失われる可能性があります。

ミラーリングフィーチャー間の比較：

[cols="1a,1a"]
|===
| 非同期ミラーリング | 同期ミラーリング 


 a| 
*レプリケーション方法*



 a| 
* *ポイントインタイム*
+
ミラーリングはオンデマンドで、またはユーザ定義のスケジュールに従って自動的に行われます。スケジュールは分単位で定義できます。同期の最小間隔は10分です。


 a| 
* *連続*
+
ミラーリングは継続して自動的に実行され、ホストに書き込みがあるたびにデータがコピーされます。





 a| 
*リザーブ容量*



 a| 
* *複数*
+
ミラーペアごとにリザーブ容量ボリュームが1つ必要です。


 a| 
* * シングル *
+
すべてのミラーボリュームにリザーブ容量ボリュームが1つ必要です。





 a| 
*通信*



 a| 
* * iSCSIおよびファイバ・チャネル*
+
ストレージアレイ間でiSCSIインターフェイスとFibre Channelインターフェイスをサポートします。


 a| 
* *ファイバ・チャネル*
+
ストレージアレイ間でFibre Channelインターフェイスのみがサポートされます。





 a| 
*距離*



 a| 
* *無制限*
+
ローカルストレージアレイとリモートストレージアレイの間でサポートされる距離は事実上無制限で、通常はネットワークとチャネル拡張テクノロジの機能によってのみ距離が制限されます。


 a| 
* *制限付き*
+
レイテンシとアプリケーションパフォーマンスの要件を満たすために、通常はローカルストレージアレイから約10km（6.2マイル）以内である必要があります。



|===