---
permalink: sm-mirroring/role-change-of-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, mirror, consistency, group, secondary, mirror, consistency, group, 
summary: ミラー整合性グループ内のミラーペア間でロールを変更できます。そのためには、プライマリミラー整合性グループをセカンダリロールに降格するか、セカンダリミラー整合性グループをプライマリロールに昇格します。 
---
= ミラー整合性グループのロール変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラー整合性グループ内のミラーペア間でロールを変更できます。そのためには、プライマリミラー整合性グループをセカンダリロールに降格するか、セカンダリミラー整合性グループをプライマリロールに昇格します。

ロール変更処理に関する次の情報を確認してください。

* ロール変更は、選択したミラー整合性グループ内のすべてのミラーペアに反映されます。
* ミラー整合性グループがセカンダリロールに降格されると、そのミラー整合性グループ内のすべてのミラーペアもセカンダリロールに降格されます。その逆も同様です。
* プライマリミラー整合性グループがセカンダリロールに降格されると、そのグループ内のメンバーボリュームに割り当てられているホストはそのグループに書き込みアクセスできなくなります。
* ミラー整合性グループがプライマリロールに昇格されると、そのグループ内のメンバーボリュームにアクセスしているホストがそのグループに書き込むことができるようになります。
* ローカルストレージアレイがリモートストレージアレイと通信できない場合は、ローカルストレージアレイで強制的にロールを変更できます。




== 強制的なロール変更

ローカルストレージアレイとリモートストレージアレイ間の通信の問題により、セカンダリミラー整合性グループ内のメンバーボリュームの昇格やプライマリミラー整合性グループ内のメンバーボリュームの降格を実行できない場合は、ミラー整合性グループ間で強制的にロールを変更できます。

セカンダリ側のミラー整合性グループを強制的にプライマリロールに移行できます。これで、リカバリホストはそのミラー整合性グループ内で新しく昇格されたメンバーボリュームにアクセスできるようになり、業務を続行できます。



== 強制昇格が許可される場合と許可されない場合

ミラー整合性グループの強制昇格は、ミラー整合性グループのすべてのメンバーボリュームが同期され、整合性のあるリカバリポイントがある場合にのみ許可されます。

次の状況では、ミラー整合性グループの強制昇格が許可されません。

* ミラー整合性グループのいずれかのメンバーボリュームが初期同期中です。
* ミラー整合性グループのメンバーボリュームにリカバリポイントのポイントインタイムイメージがない（リザーブ容量のフルエラーなどが原因）。
* ミラー整合性グループにメンバーボリュームが含まれていません。
* ミラー整合性グループが失敗、Role-Change-Pending、Role-Change-In-Progressのいずれかの状態であるか、関連付けられているいずれかのメンバーボリュームまたはリザーブ容量ボリュームで障害が発生している。




== ミラーグループロールの競合

ローカルストレージアレイとリモートストレージアレイ間の通信の問題が解決すると、Mirror Group Role Conflict状態が発生します。Recovery Guruを使用してこのエラーを解決してください。二重ロールの競合の解決時に、強制昇格は許可されません。

Mirror Group Role Conflict状態とそれ以降のリカバリ手順を回避するには、ストレージアレイ間の接続が確立されてから強制的にロールを変更してください。



== ロール変更実行中の状態

ミラーリング構成内の2つのストレージアレイが切断され、ミラー整合性グループのプライマリ側が強制的にセカンダリロールに降格され、ミラー整合性グループのセカンダリ側が強制的にプライマリロールに昇格されると、通信が回復すると、両方のストレージアレイのミラー整合性グループがRole-Change-In-Progress状態になります。

システムでは、変更ログを転送し、再同期を実行し、ミラー整合性グループを通常の動作状態に戻して、定期的な同期を続行することで、ロール変更プロセスを完了します。
