---
permalink: sm-mirroring/role-change-of-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, between, volume, mirrored, pair, 
summary: ミラーペア内のボリューム間でロールを変更できます。そのためには、プライマリボリュームをセカンダリロールに降格するか、セカンダリボリュームをプライマリロールに昇格します。 
---
= ミラーペア内のボリューム間でのロール変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペア内のボリューム間でロールを変更できます。そのためには、プライマリボリュームをセカンダリロールに降格するか、セカンダリボリュームをプライマリロールに昇格します。

[NOTE]
====
同期ミラーリングは、EF600またはEF300ストレージシステムでは使用できません。

====
ロール変更処理に関する次の情報を確認してください。

* プライマリボリュームがセカンダリロールに降格されると、そのミラーペアのセカンダリボリュームがプライマリロールに昇格されます。その逆も同様です。
* プライマリボリュームがセカンダリロールに降格されると、そのボリュームに割り当てられているホストはボリュームに書き込みアクセスできなくなります。
* セカンダリボリュームがプライマリロールに昇格されると、そのボリュームにアクセスしているすべてのホストがボリュームに書き込むことができるようになります。
* ローカルストレージアレイがリモートストレージアレイと通信できない場合は、ローカルストレージアレイで強制的にロールを変更できます。




== 強制的なロール変更

ローカルストレージアレイとリモートストレージアレイ間の通信の問題によってセカンダリボリュームの昇格またはプライマリボリュームの降格を実行できない場合は、ミラーペアのボリューム間で強制的にロールを変更できます。

セカンダリ側のボリュームを強制的にプライマリロールに移行できます。これで、新しく昇格されたボリュームにリカバリホストがアクセスできるようになり、業務を続行できます。

[NOTE]
====
リモートストレージアレイがリカバリされ、通信の問題が解決されると、「同期ミラーリング-プライマリボリュームが競合しています」状態が発生します。リカバリ手順にはボリュームの再同期が含まれます。Recovery Guruを使用してこのエラーを解決してください。

====


== 強制昇格が許可される場合と許可されない場合

次の状況では、ミラーペアのボリュームの強制昇格は許可されません。

* ミラーペア内のいずれかのボリュームで初期同期中です。
* ミラーペアが失敗、Role-Change-Pending、Role-Change-In-Progressのいずれかの状態であるか、関連付けられているいずれかのリザーブ容量ボリュームで障害が発生している。




== ロール変更実行中の状態

ミラーリング構成の2つのストレージアレイが切断され、ミラーペアのプライマリボリュームが強制的にセカンダリロールに降格され、ミラーペアのセカンダリボリュームが強制的にプライマリロールに昇格された場合、通信が回復すると、両方のストレージアレイのボリュームがRole-Change-In-Progress状態になります。

システムは、変更ログを転送し、再同期し、ミラーペアを通常の動作状態に戻し、同期を続行することで、ロール変更プロセスを完了します。
