---
permalink: sm-mirroring/suspend-or-resume-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, suspend, resume, synchronization, mirror, consistency, group, 
summary: ミラー整合性グループ内のすべてのミラーペアでデータの同期を中断または再開できます。これは、個 々 のミラーペアで同期を中断または再開するよりも効率的です。 
---
= ミラー整合性グループの同期の中断または再開
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラー整合性グループ内のすべてのミラーペアでデータの同期を中断または再開できます。これは、個 々 のミラーペアで同期を中断または再開するよりも効率的です。

.タスクの内容
グループに対する同期の一時停止と再開は、ホストアプリケーションのパフォーマンスへの影響（ローカルストレージアレイで変更されたデータがリモートストレージアレイにコピーされるときに発生する可能性があります）を軽減するのに役立ちます。

ミラー整合性グループとそのミラーペアの状態は、[再開]オプションを使用して同期アクティビティを再開するまで中断されたままです。

.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラー整合性グループ*（Mirror Consistency Groups *）]タブを選択します。
+
[ミラー整合性グループ]の表に、ストレージアレイに関連付けられているすべてのミラー整合性グループが表示されます。

. 中断または再開するミラー整合性グループを選択し、メニュー：その他[中断]またはメニュー：その他[再開]を選択します。
+
確認メッセージが表示されます。

. 「*はい*」を選択して確定します。


.結果
System Managerは次の処理を実行します。

* ミラー関係を削除せずに、ミラー整合性グループ内のすべてのミラーペア間のデータ転送を中断または再開します。
* ミラーグループの中断中にミラー整合性グループのプライマリ側に書き込まれたデータをログに記録し、ミラーグループが再開されるとミラー整合性グループのセカンダリ側にデータを自動的に書き込みます。完全同期は必要ありません。
* a_suspended_mirror整合性グループの場合、Mirror Consistency Groupsテーブルに* user-suspended *が表示されます。
* 再開されたミラー整合性グループでは、ミラー整合性グループの中断中にプライマリボリュームに書き込まれたデータがセカンダリボリュームにただちに書き込まれます。自動同期間隔が設定されている場合は、定期的な同期が再開されます。

