---
permalink: sm-mirroring/test-communication-for-mirror-consistency-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, test, communication, mirror, consistency, groups, 
summary: 通信リンクをテストして、ミラー整合性グループに関連付けられているローカルストレージアレイとリモートストレージアレイの間の通信の問題を診断できます。 
---
= ミラー整合性グループの通信のテスト
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通信リンクをテストして、ミラー整合性グループに関連付けられているローカルストレージアレイとリモートストレージアレイの間の通信の問題を診断できます。

.開始する前に
テストするミラー整合性グループがローカルとリモートのストレージアレイに存在している必要があります。

.タスクの内容
次の4つのテストを実行できます。

* *接続*-- 2台のコントローラに通信パスがあることを確認します接続テストでは、ストレージアレイ間でメッセージを送信し、リモートストレージアレイに対応するミラー整合性グループが存在するかどうかを検証します。また、リモートストレージアレイ上のミラー整合性グループのメンバーボリュームがローカルストレージアレイ上のミラー整合性グループのメンバーボリュームと一致するかどうかも検証されます。
* * Latency *--ミラー整合性グループに関連付けられたリモートストレージアレイ上の各ミラーボリュームにSCSI Test Unitコマンドを送信して、最小、平均、最大のレイテンシをテストします。
* *bandwidth*-- 2つのアレイ間メッセージをリモートストレージアレイに送信して、最小、平均、最大の帯域幅、およびテストを実行しているアレイ上のポートのネゴシエートされたリンク速度をテストします。
* *ポート接続*--ローカルストレージアレイ上のミラーリングに使用されているポート'およびリモートストレージアレイ上のミラーデータを受信しているポートを表示します


.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. ミラー整合性グループ*タブを選択し、テストするミラー整合性グループを選択します。
. [*通信のテスト*]を選択します。
+
[Test Communication]ダイアログボックスが表示されます。

. 選択したミラー整合性グループに関連付けられているローカルとリモートのストレージアレイ間で実行する通信テストを1つ以上選択し、* Test *をクリックします。
. [結果]ウィンドウに表示される情報を確認します。
+
[cols="35h,~"]
|===
| 通信テストのステータス | 製品説明 


 a| 
正常（エラーなし）
 a| 
ミラー整合性グループが正常に通信しています。



 a| 
合格（ただし、正常ではない）
 a| 
考えられるネットワークまたは接続の問題を確認してから、テストを再試行してください。



 a| 
失敗ステータス
 a| 
エラーの理由が示されます。問題を修正するには、Recovery Guruを参照してください。



 a| 
ポート接続エラー
 a| 
ローカルストレージアレイが接続されていないか、リモートストレージアレイに接続できない可能性があります。問題を修正するには、Recovery Guruを参照してください。

|===


.結果
通信テストが完了すると、このダイアログボックスにNormal、Passed、Failedのいずれかのステータスが表示されます。

通信テストから失敗ステータスが返された場合は、このダイアログボックスを閉じたあと、ミラー整合性グループ間の通信が回復するまでテストが続行されます。
