---
permalink: sm-mirroring/volume-ownership-sync.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, ownership, sync, change, preferred, controller, owner, mirrored, pair, 
summary: ミラーペアの優先コントローラ所有者を変更できます。 
---
= ボリューム所有権
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペアの優先コントローラ所有者を変更できます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムの同期ミラーリングでは使用できません。

====
ミラーペアのプライマリボリュームがコントローラAに所有されている場合、セカンダリボリュームもリモートストレージアレイのコントローラAに所有されます。プライマリボリュームの所有者を変更すると、セカンダリボリュームの所有者が自動的に変更され、両方のボリュームが同じコントローラで所有されるようになります。プライマリ側で現在の所有権が変更されると、セカンダリ側の対応する所有権も自動的に変更されます。

たとえば、コントローラAが所有するプライマリ ボリュームの所有者をコントローラBに変更したとします。この場合、次回のリモート書き込み時に、セカンダリ ボリュームの所有者がコントローラAからコントローラBに切り替わります。セカンダリ側のコントローラ所有権の切り替えはプライマリ側で制御されるため、ストレージ管理者による特別な対応は必要ありません。



== コントローラのリセット

コントローラをリセットすると、プライマリ側でボリューム所有権が優先コントローラ所有者からストレージアレイ内の代替コントローラに変更されます。

セカンダリボリュームへの書き込み前に、コントローラのリセットやストレージアレイの電源の再投入によってリモート書き込みが中断されることがあります。この場合、コントローラでミラーペアの完全同期を実行する必要はありません。

コントローラのリセット中にリモートの書き込みが中断されると、プライマリ側の新しいコントローラ所有者は、優先コントローラ所有者のリザーブ容量ボリューム内のログファイルに格納されている情報を読み取ります。その後、新しいコントローラ所有者は、影響を受けたデータブロックをプライマリボリュームからセカンダリボリュームにコピーします。これにより、ミラーボリュームの完全な同期が不要になります。
