---
permalink: sm-mirroring/what-impact-does-synchronization-priority-have-on-synchronization-rates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronization, priority, rates, 
summary: 同期優先度は、システムパフォーマンスに対する同期アクティビティに割り当てる処理時間を定義します。 
---
= 同期優先度は同期速度にどのような影響を与えますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期優先度は、システムパフォーマンスに対する同期アクティビティに割り当てる処理時間を定義します。

プライマリボリュームのコントローラ所有者はこの処理をバックグラウンドで実行します。同時にコントローラ所有者は、プライマリボリュームへのローカルのI/O書き込みと、対応するセカンダリボリュームへのリモートの書き込みを処理します。再同期には、I/Oアクティビティに使用されるはずのコントローラの処理リソースが使用されるため、再同期がホストアプリケーションのパフォーマンスに影響する可能性があります。

同期優先度に応じた所要時間や、同期優先度がシステムパフォーマンスに与える影響を特定する際には、次のガイドラインに注意してください。

.同期優先度について
[%collapsible]
====
次のプライオリティレートを使用できます。

* 最低
* 低
* 中
* 高
* 最高


優先度が最低の場合はシステムパフォーマンスがサポートされますが、再同期にかかる時間は長くなります。最も優先度が高い場合は再同期がサポートされますが、システムパフォーマンスが低下する可能性があります。

====
これらのガイドラインは、優先度の大まかな違いを示しています。

[cols="35h,~"]
|===
| 完全同期の優先度 | 最高の同期速度と比較した経過時間 


 a| 
最低
 a| 
最高プライオリティレートの約8倍の長さになります。



 a| 
低
 a| 
最高プライオリティレートの約6倍の長さになります。



 a| 
中
 a| 
最高プライオリティレートの約3.5倍の長さになります。



 a| 
高
 a| 
最高プライオリティレートの約2倍の時間がかかります。

|===
同期の所要時間には、ボリュームサイズとホストのI/O速度が影響します。
