---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: ストレージアレイには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。 
---
= パスワード保護の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
不正なアクセスから保護するために、ストレージアレイにパスワードを設定する必要があります。



== パスワードの設定と変更

System Managerの初回起動時に、管理者パスワードを設定するように求められます。adminパスワードを持つユーザは、オブジェクトや設定の追加、変更、削除など、ストレージアレイの設定を変更できます。初回起動時にadminパスワードを設定するには、を参照してくださいlink:../san-getstarted/access-sam.html["System Managerへのアクセス"]。

セキュリティ上の理由から、パスワードの入力を試行できるのは5回までです。この回数を超えると、ストレージアレイは「ロックアウト」状態になります。この状態の場合、ストレージアレイは以降のパスワードの入力を拒否します。パスワードをもう一度入力するには、ストレージアレイが「通常」の状態にリセットされるまで10分待つ必要があります。

ストレージアレイには、adminパスワードに加えて、1つ以上のロールがマッピングされた事前定義されたユーザプロファイルが含まれています。詳細については、を参照してください link:../sm-settings/permissions-for-mapped-roles.html["マッピングされたロールの権限"]。ユーザプロファイルとマッピングは変更できません。変更できるのはパスワードのみです。adminパスワードまたはその他のユーザパスワードを変更する場合は、を参照してくださいlink:../sm-settings/change-passwords.html["パスワードの変更"]。



== セッションタイムアウト後のパスワードの再入力

パスワードの入力を求めるプロンプトは、1つの管理セッションで1回だけ表示されます。ただし、30分間操作を行わないとセッションはタイムアウトし、その時点でパスワードを再入力する必要があります。セッションの実行中に別の管理クライアントから同じストレージアレイを管理している別のユーザがパスワードを変更した場合は、次回の設定処理または表示処理でパスワードの入力を求められます。

セッションタイムアウトを調整することも、セッションタイムアウトを完全に無効にすることもできます。を参照して link:../sm-settings/manage-session-timeouts-sam.html["セッションタイムアウトの管理"]



== ドライブまたはパスワードによる保護の解除

パスワードで保護されたドライブを取り外す場合、またはパスワード保護を無効にする場合は、次の点に注意してください。

* *パスワード保護が設定されたドライブを取り外すと、パスワードはストレージアレイの各ドライブの予約領域に保存されます。ストレージアレイからすべてのドライブを取り外すと、そのパスワードは機能しなくなります。この状況を修正するには、元のドライブの1つをストレージアレイに再取り付けします。
* *パスワード保護を解除する場合*--コマンドのパスワード保護を解除する場合は'現在の管理者パスワードを入力し'新しいパスワードのテキストボックスを空白のままにします


[CAUTION]
====
ストレージアレイで設定コマンドを実行すると、データ損失などの重大な損傷が発生する可能性があります。そのため、ストレージアレイには管理者パスワードを常に設定する必要があります。セキュリティを強化するために、英数字15文字以上の長い管理者パスワードを使用してください。

====