---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: メインインターフェイスのストレージ階層には、ストレージアレイで管理されているさまざまなハードウェアコンポーネントやストレージオブジェクトがまとめて表示されます。 
---
= ストレージ階層の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メインインターフェイスのストレージ階層には、ストレージアレイで管理されているさまざまなハードウェアコンポーネントやストレージオブジェクトがまとめて表示されます。

ストレージ階層を表示するには、[ホーム]ページに移動し、ストレージアレイコンポーネントまたはストレージオブジェクトのドロップダウン矢印をクリックします。ストレージアレイは、物理コンポーネントと論理コンポーネントの両方の集合で構成されます。



== 物理コンポーネント

この表では、ストレージアレイの物理コンポーネントについて説明します。

[cols="25h,~"]
|===
| コンポーネント | 製品説明 


 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、System Managerの機能を実装します。



 a| 
シェルフ
 a| 
シェルフは、キャビネットまたはラックに設置されるエンクロージャです。ストレージアレイのハードウェアコンポーネントが含まれています。シェルフには、コントローラシェルフとドライブシェルフの2種類があります。コントローラシェルフにはコントローラとドライブが搭載されます。ドライブシェルフには、入出力モジュール（IOM）とドライブが搭載されています。

[NOTE]
====
ストレージアレイのメディアタイプやインターフェイスタイプが異なる場合は、ドライブタイプごとにドライブシェルフが表示されます。

====


 a| 
ドライブ
 a| 
ドライブは、データの物理ストレージメディアとして使用される、電磁的な機械デバイスまたはソリッドステートメモリデバイスです。



 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
ホストバスアダプタ（HBA）
 a| 
ホストバスアダプタ（HBA）はホストに搭載されるボードで、1つ以上のホストポートが搭載されています。



 a| 
ホストポート
 a| 
ホストポートは、コントローラに物理的に接続されるホストバスアダプタ（HBA）のポートで、I/O処理に使用されます。



 a| 
管理クライアント
 a| 
管理クライアントは、System Managerにアクセスするためのブラウザがインストールされたコンピュータです。

|===


== 論理コンポーネント

ストレージアレイ内のドライブは、データ用の物理ストレージ容量を提供します。System Managerを使用して、物理容量をプール、ボリュームグループ、ボリュームなどの論理コンポーネントに設定します。これらのコンポーネントは、ストレージアレイのデータの設定、格納、保守、保持に使用するツールです。次の表では、ストレージアレイの論理コンポーネントについて説明します。

[cols="25h,~"]
|===
| コンポーネント | 製品説明 


 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセスできる1つ以上のボリュームを作成できます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループには容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセスできる1つ以上のボリュームを作成できます。（ボリュームはボリュームグループまたはプールから作成します）。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。



 a| 
論理ユニット番号（LUN）
 a| 
Logical Unit Number（LUN；論理ユニット番号）は、ホストがボリュームへのアクセスに使用する番号で、アドレススペースに割り当てられます。ボリュームは、LUNの形式で容量としてホストに提示されます。

各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを異なるホストで使用して、異なるボリュームにアクセスできます。

|===