---
permalink: sm-hardware/configure-dns-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, dns, server, addresses, 
summary: ドメインネームシステム（DNS）は、コントローラとネットワークタイムプロトコル（NTP）サーバの完全修飾ドメイン名を解決するために使用します。ストレージアレイの管理ポートでは、IPv4プロトコルとIPv6プロトコルを同時にサポートできます。 
---
= DNSサーバアドレスの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドメインネームシステム（DNS）は、コントローラとネットワークタイムプロトコル（NTP）サーバの完全修飾ドメイン名を解決するために使用します。ストレージアレイの管理ポートでは、IPv4プロトコルとIPv6プロトコルを同時にサポートできます。

.開始する前に
* ネットワークにDNSサーバをインストールし、設定する必要があります。
* プライマリDNSサーバとオプションのバックアップDNSサーバのアドレスを確認しておきます。IPv4アドレスまたはIPv6アドレスを指定できます。


.タスクの内容
この手順では、プライマリおよびバックアップのDNSサーバアドレスを指定する方法について説明します。バックアップDNSサーバは、プライマリDNSサーバに障害が発生した場合に使用するようにオプションで設定できます。

[NOTE]
====
ストレージアレイの管理ポートを動的ホスト構成プロトコル（DHCP）ですでに設定していて、1つ以上のDNSサーバまたはNTPサーバをDHCPセットアップに関連付けている場合は、DNSまたはNTPを手動で設定する必要はありません。この場合、DNS / NTPサーバのアドレスはストレージアレイですでに自動的に取得されているはずです。ただし、以下の手順に従ってダイアログボックスを開き、正しいアドレスが検出されていることを確認する必要があります。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示された場合は、*[コントローラとコンポーネント]*タブをクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. 設定するコントローラを選択します。
+
コントローラのコンテキストメニューが表示されます。

. [Configure DNS server*]を選択します。
+
ドメインネームシステム（DNS）サーバの設定ダイアログボックスが開きます。

. 次のいずれかのオプションを選択します。
+
** *DHCPサーバから自動的にDNSサーバアドレスを取得*--検出されたDNSサーバアドレスが表示されます
+
[NOTE]
====
静的DNSアドレスを使用するようにストレージアレイが設定されている場合、DNSサーバは表示されません。

====
** *DNSサーバアドレスを手動で指定する*--プライマリDNSサーバのアドレスとバックアップDNSサーバのアドレスを入力しますバックアップサーバはオプションです。（アドレス フィールドはラジオ ボタンを選択すると表示されます）。IPv4アドレスまたはIPv6アドレスを指定できます。


. [ 保存（ Save ） ] をクリックします。
. もう一方のコントローラに対して上記の手順を繰り返します。


.結果
DNS設定は、コントローラ設定の* DNS/NTP *タブに表示されます。
