---
permalink: sm-hardware/configure-management-ports.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, management, port, 
summary: コントローラには、システム管理に使用するイーサネットポートが搭載されています。必要に応じて、送信パラメータとIPアドレスを変更できます。 
---
= 管理ポートを設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラには、システム管理に使用するイーサネットポートが搭載されています。必要に応じて、送信パラメータとIPアドレスを変更できます。

.タスクの内容
この手順では、ポート1を選択し、速度とポートアドレス指定方法を決定します。ポート1は、管理クライアントがコントローラとSystem Managerにアクセスできるネットワークに接続します。

[NOTE]
====
どちらのコントローラでもポート2は使用しないでください。ポート2はテクニカルサポート用に予約されています。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示された場合は、*[コントローラとコンポーネント]*タブをクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. 管理ポートを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. ［*管理ポートの設定*］を選択します。
+
Configure Management Portsダイアログボックスが開きます。

. ポート1が表示されていることを確認し、*次へ*をクリックします。
. 構成ポートの設定を選択し、 * 次へ * をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 製品説明 


 a| 
速度と二重モード
 a| 
System Managerでストレージアレイとネットワークの間の転送パラメータを決定する場合、またはネットワークの速度とモードを確認したい場合は、自動ネゴシエーション設定を維持します。ネットワークのパラメータをドロップダウンリストから選択することもできます。有効な速度とデュプレックスの組み合わせだけがリストに表示されます。



 a| 
IPv4を有効にする/ IPv6を有効にする
 a| 
IPv4およびIPv6ネットワークのサポートを有効にするには、一方または両方のオプションを選択します。

|===
====
+
「* IPv4を有効にする*」を選択すると、「*次へ*」をクリックした後でIPv4設定を選択するためのダイアログボックスが開きます。「* IPv6を有効にする*」を選択すると、「*次へ*」をクリックした後でIPv6設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、IPv4設定のダイアログボックスが最初に開き、*次へ*をクリックすると、IPv6設定のダイアログボックスが開きます。

. IPv4 / IPv6を自動または手動で設定します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 製品説明 


 a| 
DHCPサーバから自動的に設定を取得
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的設定を手動で指定する
 a| 
このオプションを選択し、コントローラのIPアドレスを入力します。（必要に応じて、カット アンド ペーストでアドレスをフィールドに貼り付けることもできます）。IPv4の場合は、ネットワークのサブネットマスクとゲートウェイを指定します。IPv6の場合は、ルーティング可能なIPアドレスとルータのIPアドレスを指定します。


NOTE: IPアドレスの設定を変更すると、ストレージアレイへの管理パスが失われます。SANtricity Unified Managerを使用してネットワーク内のアレイをグローバルに管理する場合は、ユーザインターフェイスを開き、メニューから「Manage [Discover]」に移動します。SANtricity Storage Managerを使用している場合は、Enterprise Management Window（EMW）からデバイスを削除し、メニューのEdit [Add Storage Array]を選択してEMWに再び追加し、新しいIPアドレスを入力する必要があります。

|===
====
. [ 完了 ] をクリックします。


.結果
管理ポートの設定は、コントローラの設定の管理ポートタブに表示されます。
