---
permalink: sm-hardware/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, over, roce, ports 
summary: 'コントローラにNVMe over RoCE（RDMA over Converged Ethernet）の接続が搭載されている場合は、[ハードウェア]ページからNVMeポートを設定できます。' 
---
= NVMe over RoCEポートの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラにNVMe over RoCE（RDMA over Converged Ethernet）の接続が搭載されている場合は、[ハードウェア]ページからNVMeポートを設定できます。

.開始する前に
* コントローラにNVMe over RoCEホストポートが搭載されている必要があります。そうでないと、System ManagerでNVMe over RoCE設定を使用できません。
* ホスト接続のIPアドレスを確認しておく必要があります。


.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示された場合は、*[コントローラとコンポーネント]*タブをクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. NVMe over RoCEポートを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. NVMe over RoCE ポートの設定 * を選択します。
+
[NVMe over RoCEポートの設定]ダイアログボックスが開きます。

. ドロップダウンリストで、設定するHICポートを選択します。
. 「 * 次へ * 」をクリックします。
+
すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more port settings * リンクをクリックします。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| ポート設定 | 製品説明 


 a| 
設定されたイーサネットポート速度
 a| 
ポートのSFPの速度と同じ速度を選択します。



 a| 
IPv4を有効にする/ IPv6を有効にする
 a| 
IPv4およびIPv6ネットワークのサポートを有効にするには、一方または両方のオプションを選択します。


NOTE: ポートアクセスをディセーブルにする場合は、両方のチェックボックスをオフにします。



 a| 
MTU サイズ（ * Show more port settings* をクリックすると使用可能）
 a| 
必要に応じて、Maximum Transmission Unit（MTU；最大転送単位）の新しいサイズをバイト単位で入力します。

デフォルトのMaximum Transmission Unit（MTU；最大伝送ユニット）サイズは1500バイト/フレームです。1500 ~ 9000の値を入力する必要があります。

|===
====
+
[*IPv4 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv4 設定を選択するためのダイアログボックスが開きます。[*IPv6 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv6 設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、 IPv4 設定のダイアログボックスが最初に開き、 * 次へ * をクリックすると、 IPv6 設定のダイアログボックスが開きます。

. IPv4 / IPv6を自動または手動で設定します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| ポート設定 | 製品説明 


 a| 
設定を自動的に取得
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的設定を手動で指定する
 a| 
このオプションを選択し、フィールドに静的アドレスを入力します。（必要に応じて、カット アンド ペーストでアドレスをフィールドに貼り付けることもできます）。IPv4の場合は、ネットワークのサブネットマスクとゲートウェイを指定します。IPv6の場合は、ルーティング可能なIPアドレスとルータのIPアドレスを指定します。200Gb対応のHICを使用してEF600ストレージアレイを設定する場合、このダイアログボックスには、ネットワークパラメータの2セットのフィールドが表示されます。1つは物理ポート（外部）用のフィールドで、もう1つは仮想ポート（内部）用のフィールドです。両方のポートに一意のパラメータを割り当てる必要があります。これらの設定を使用すると、ホストで各ポート間のパスを確立し、HICのパフォーマンスを最大限に高めることができます。仮想ポートにIPアドレスを割り当てない場合、HICの実行速度は約半分になります。

|===
====
. [ 完了 ] をクリックします。

