---
permalink: sm-hardware/considerations-for-assigning-ip-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, considerations, assigning, ip, addresses 
summary: デフォルトでは、コントローラは両方のネットワークポートでDHCPを有効にした状態で出荷されます。静的IPアドレスを割り当てるか、デフォルトの静的IPアドレスを使用するか、またはDHCPによって割り当てられたIPアドレスを使用できます。IPv6のステートレス自動設定を使用することもできます。 
---
= IPアドレスの割り当てに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、コントローラは両方のネットワークポートでDHCPを有効にした状態で出荷されます。静的IPアドレスを割り当てるか、デフォルトの静的IPアドレスを使用するか、またはDHCPによって割り当てられたIPアドレスを使用できます。IPv6のステートレス自動設定を使用することもできます。

[NOTE]
====
IPv6は新しいコントローラではデフォルトで無効になっていますが、別の方法で管理ポートのIPアドレスを設定し、System Managerを使用して管理ポートでIPv6を有効にすることができます。

====
ネットワークポートが「リンク停止」状態、つまりLANから切断されている場合、システムは設定を静的として報告するか（以前のリリース）、DHCPが有効でIPアドレスが報告されないか（以降のリリース）と報告します。ネットワークポートが「リンクアップ」状態（LANに接続）になると、DHCP経由でIPアドレスを取得しようとします。

コントローラの特定のネットワークポートでDHCPアドレスを取得できない場合はデフォルトのIPアドレスに戻りますが、これには3分ほどかかることがあります。デフォルトのIPアドレスは次のとおりです。

[listing]
----
Controller 1 (port 1): IP Address: 192.168.128.101
----
[listing]
----
Controller 1 (port 2): IP Address: 192.168.129.101
----
[listing]
----
Controller 2 (port 1): IP Address: 192.168.128.102
----
[listing]
----
Controller 2 (port 2): IP Address: 192.168.129.102
----
IPアドレスを割り当てる場合：

* コントローラのポート2をカスタマーサポート用に予約します。デフォルトのネットワーク設定（DHCPが有効な状態）を変更しないでください。
* E2800およびE5700のコントローラに静的IPアドレスを設定するには、SANtricity System Managerを使用します。E2700およびE5600のコントローラに静的IPアドレスを設定するには、SANtricity Storage Managerを使用します。静的IPアドレスを設定すると、リンクの停止/停止イベントが発生しても設定されたままになります。
* DHCPを使用してコントローラのIPアドレスを割り当てるには、DHCP要求を処理できるネットワークにコントローラを接続します。永続的なDHCPリースを使用してください。
+
[NOTE]
====
デフォルトアドレスは、リンク停止イベントが発生しても維持されません。コントローラのネットワークポートでDHCPを使用するように設定されている場合、ケーブルの挿入、リブート、電源の再投入など、リンク稼働イベントのたびにDHCPアドレスの取得が試行されます。DHCPの試行に失敗すると、そのポートのデフォルトの静的IPアドレスが使用されます。

====

