---
permalink: sm-hardware/controller-states.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, states, 
summary: コントローラは、オンライン、オフライン、およびサービスモードの3つの状態に切り替えることができます。 
---
= コントローラの状態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラは、オンライン、オフライン、およびサービスモードの3つの状態に切り替えることができます。



== オンライン状態

オンライン状態は、コントローラの通常動作時の状態です。コントローラが正常に動作しており、I/O処理に使用できることを意味します。

コントローラをオンラインにすると、ステータスが最適になります。



== オフライン状態

オフライン状態は、通常、ストレージアレイにコントローラが2台ある場合にコントローラを交換する準備に使用します。コントローラは、明示的なコマンドを実行した場合とコントローラで障害が発生した場合の2つの方法でオフライン状態になります。コントローラのオフライン状態は、別の明示的なコマンドを実行するか、障害が発生したコントローラを交換するまで解消されません。コントローラをオフラインにできるのは、ストレージアレイにコントローラが2台ある場合だけです。

コントローラがオフライン状態のときは次の状況になります。

* コントローラをI/Oに使用できません。
* そのコントローラでストレージアレイを管理することはできません。
* そのコントローラが現在所有しているボリュームは、もう一方のコントローラに移動されます。
* キャッシュミラーリングが無効になり、すべてのボリュームがライトスルーキャッシュモードに変更されます。




== サービスモード

サービスモードは通常、テクニカルサポートのみが使用し、ストレージアレイのすべてのボリュームを一方のコントローラに移動して、もう一方のコントローラを診断できるようにします。コントローラは手動でサービスモードにする必要があり、サービス処理の完了後に手動でオンラインに戻す必要があります。

コントローラがサービスモードの場合は、次の状況になります。

* コントローラをI/Oに使用できません。
* テクニカルサポートは、シリアルポートまたはネットワーク接続経由でコントローラにアクセスし、潜在的な問題を分析できます。
* そのコントローラが現在所有しているボリュームは、もう一方のコントローラに移動されます。
* キャッシュミラーリングが無効になり、すべてのボリュームがライトスルーキャッシュモードに変更されます。

