---
permalink: sm-hardware/drive-states.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, states, 
summary: System Managerでは、ドライブについてさまざまな状態が報告されます。 
---
= ドライブの状態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Managerでは、ドライブについてさまざまな状態が報告されます。



== アクセスの状態

[cols="25h,~"]
|===
| 都道府県 | 定義 


 a| 
バイパス
 a| 
ドライブは物理的に存在しますが、コントローラがどちらのポートでもドライブと通信できません。



 a| 
互換性なし
 a| 
次のいずれかの状況に該当します。

* ドライブはストレージアレイでの使用が認定されていません。
* ドライブのセクターサイズが異なります。
* ドライブに古いバージョンまたは新しいバージョンのファームウェアから使用できない構成データがあります。




 a| 
削除済み
 a| 
ドライブがストレージアレイから適切に取り外されていません。



 a| 
現在
 a| 
コントローラは両方のポートでドライブと通信できます。



 a| 
応答なし
 a| 
ドライブがコマンドに応答していません。

|===


== ロールの状態

[cols="25h,~"]
|===
| 都道府県 | 定義 


 a| 
割り当て済み
 a| 
プールまたはボリュームグループのメンバーである。



 a| 
使用中のホットスペア
 a| 
障害が発生したドライブの交換用ドライブとして使用中です。ホットスペアはボリュームグループでのみ使用され、プールでは使用されません。



 a| 
スタンバイのホットスペア
 a| 
障害が発生したドライブの交換用ドライブとして使用可能な状態です。ホットスペアはボリュームグループでのみ使用され、プールでは使用されません。



 a| 
未割り当て
 a| 
プールまたはボリュームグループのメンバーではありません。

|===


== 可用性の状態

[cols="25h,~"]
|===
| 都道府県 | 定義 


 a| 
失敗
 a| 
ドライブは動作していません。ドライブ上のデータを使用できません。



 a| 
障害の兆候
 a| 
ドライブで障害の前兆が検出されています。ドライブ上のデータはまだ使用できます。



 a| 
オフライン
 a| 
ドライブをデータの格納に使用できません。通常、ドライブがエクスポート中のボリュームグループに属しているか、ファームウェアのアップグレード中です。



 a| 
最適
 a| 
ドライブは正常に動作しています。

|===