---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, erase, drives, removal, 
summary: '[消去]オプションを使用すると、未割り当てのドライブをシステムから取り外す準備をすることができます。この手順では、データが永久に削除され、データが再度読み取れないようにします。' 
---
= ドライブの消去
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[消去]オプションを使用すると、未割り当てのドライブをシステムから取り外す準備をすることができます。この手順では、データが永久に削除され、データが再度読み取れないようにします。

.開始する前に
ドライブは未割り当て状態である必要があります。

.タスクの内容
[消去]オプションは、ドライブ上のすべてのデータを完全に削除する場合にのみ使用してください。セキュリティ有効ドライブの場合、[消去]オプションを使用すると暗号化データが消去され、セキュリティ属性がセキュリティ対応にリセットされます。

[NOTE]
====
消去機能は、一部の古いドライブモデルをサポートしていません。これらの古いモデルのいずれかを消去しようとすると、エラーメッセージが表示されます。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示された場合は、*[ドライブ]*タブをクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. 必要に応じて、フィルタフィールドを使用してシェルフ内の未割り当てのドライブをすべて表示できます。[Show drives that are ...*]ドロップダウンリストから、[*Unassigned *]を選択します。
+
シェルフビューには未割り当てのドライブのみが表示され、それ以外のドライブはすべてグレー表示になります。

. ドライブのコンテキストメニューを開くには、消去するドライブをクリックします。（複数のドライブを選択する場合は、[ドライブを消去]ダイアログボックスで選択できます）。
+
[CAUTION]
====
*データ損失の可能性*--消去操作は取り消せません。手順の実行中に正しいドライブを選択していることを確認してください。

====
. コンテキストメニューから*消去*を選択します。
+
[ドライブを消去]ダイアログボックスが開き、消去処理の対象となるすべてのドライブが表示されます。

. 必要に応じて、表から追加のドライブを選択します。_all_drivesを選択することはできません。1つのドライブの選択が解除されたままになっていることを
. と入力して処理を確認し `erase`、*[消去]*をクリックします。
+
[CAUTION]
====
この処理を続行することを確認してください。次のダイアログで[はい（Yes）]をクリックすると、操作を中止できません。

====
. 推定完了時間（Estimated Completion Time）ダイアログボックスで、*はい*（* Yes）をクリックして消去操作を続行します。


.結果
消去処理には数分から数時間かかることがあります。ステータスは、ホーム[進行中の処理を表示]メニューで確認できます。消去処理が完了すると、ドライブは別のボリュームグループまたはディスクプール、または別のストレージアレイで使用できるようになります。

.終了後
ドライブを再度使用する場合は、最初に初期化する必要があります。これを行うには、ドライブのコンテキストメニューから* Initialize *（初期化）を選択します。
