---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: ホットスペアは、System ManagerのRAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。 
---
= ホットスペアドライブの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットスペアは、System ManagerのRAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。

問題なく動作するドライブですが、データは格納されていません。ボリュームグループ内のドライブに障害が発生すると、障害が発生したドライブのデータがホットスペアとして割り当てられたドライブに自動的に再構築されます。

ホットスペアは、特定のボリュームグループ専用ではありません。ホットスペアとドライブで次の属性が共有されていれば、ストレージアレイ内の障害が発生したドライブに使用できます。

* 容量が等しい（またはホットスペアの容量が大きい）
* 同じメディアタイプ（HDD、SSDなど）
* インターフェイスタイプが同じ（SASなど）




== ホットスペアの特定方法

ホットスペアは、初期セットアップウィザードまたは[ハードウェア]ページから割り当てることができます。ホットスペアが割り当てられているかどうかを確認するには、[ハードウェア]ページに移動して、ピンクで表示されているドライブベイを探します。



== ホットスペアの適用方法

ホットスペアのカバレッジは次のように機能します。

* RAID 1、RAID 5、またはRAID 6のボリュームグループのホットスペアとして未割り当てのドライブを予約します。
+
[NOTE]
====
データ保護の方法が異なるプールにはホットスペアを使用できません。プールでは、追加のドライブを予約する代わりに、プール内の各ドライブにスペア容量（_予約済み容量_）を予約します。プール内のドライブに障害が発生した場合、コントローラはそのスペア容量内にデータを再構築します。

====
* RAID 1、RAID 5、またはRAID 6のボリュームグループ内のドライブで障害が発生した場合、コントローラは冗長性データを使用して障害が発生したドライブのデータを自動的に再構築します。障害が発生したドライブの代わりにホットスペアが自動的に使用され、物理的に交換する必要はありません。
* 障害が発生したドライブを物理的に交換すると、ホットスペアドライブから交換したドライブへのコピーバック処理が実行されます。ホットスペアドライブをボリュームグループの永続的メンバーとして指定している場合は、コピーバック処理は必要ありません。
* ボリュームグループのトレイ損失の保護およびドロワー損失の保護が可能かどうかは、ボリュームグループを構成するドライブの場所によって異なります。ドライブの障害とホットスペアドライブの場所が原因で、トレイ損失の保護とドロワー損失の保護が失われることがあります。トレイ損失の保護とドロワー損失の保護が影響を受けないようにするには、障害が発生したドライブを交換してコピーバックプロセスを開始する必要があります。
* 障害が発生したドライブの代わりにホットスペアドライブが自動的に使用されるため、障害が発生したドライブの交換中もストレージアレイボリュームはオンラインのままでアクセス可能です。




== ホットスペアドライブの容量に関する考慮事項

保護するドライブの合計容量以上の容量のドライブを選択してください。たとえば、容量が8GiBの18GiBドライブがある場合、9GiB以上のドライブをホットスペアとして使用できます。通常、ドライブの容量がストレージアレイ内の最大ドライブの容量以上でないかぎり、ドライブをホットスペアとして割り当てないでください。

[NOTE]
====
物理容量が同じホットスペアを使用できない場合、ドライブの「使用容量」がホットスペアドライブの容量と同じかそれよりも小さい場合は、容量が小さいドライブをホットスペアとして使用できます。

====


== メディアおよびインターフェイスタイプに関する考慮事項

ホットスペアとして使用するドライブは、保護対象のドライブと同じメディアタイプおよびインターフェイスタイプである必要があります。たとえば、HDDドライブをSSDドライブのホットスペアとして使用することはできません。



== セキュリティ対応ドライブに関する考慮事項

セキュリティ対応ドライブ（FDEやFIPSなど）は、セキュリティ機能の有無にかかわらず、ドライブのホットスペアとして使用できます。ただし、セキュリティ対応でないドライブは、セキュリティ機能を備えたドライブのホットスペアとして使用することはできません。

セキュリティ有効ドライブをホットスペアとして使用するよう選択すると、完全消去を実行してから続行するようにSystem Managerから求められます。完全消去では、ドライブのセキュリティ属性はセキュリティ有効ではなくセキュリティ対応にリセットされます。

[NOTE]
====
ドライブセキュリティ機能を有効にし、セキュリティ対応ドライブで構成されるプールまたはボリュームグループを作成すると、ドライブは_secure-enabled _になります。読み取り/書き込みアクセスは、正しいセキュリティキーが設定されたコントローラからのみ実行できます。この追加のセキュリティ機能により、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。

====


== 推奨されるホットスペアドライブの数

初期セットアップウィザードを使用してホットスペアを自動的に作成した場合、System Managerでは、特定のメディアタイプおよびインターフェイスタイプのドライブ30本ごとに1つのホットスペアが作成されます。それ以外の場合は、ストレージアレイ内のボリュームグループ間にホットスペアドライブを手動で作成できます。
