---
permalink: sm-hardware/limit-the-drive-view.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, limit, drive, view, 
summary: '物理属性と論理属性のタイプが異なるドライブがストレージアレイに含まれている場合、[ハードウェア]ページのフィルタフィールドを使用して、ドライブの表示を制限したり特定のドライブを特定したりできます。' 
---
= ドライブ表示の制限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
物理属性と論理属性のタイプが異なるドライブがストレージアレイに含まれている場合、[ハードウェア]ページのフィルタフィールドを使用して、ドライブの表示を制限したり特定のドライブを特定したりできます。

.タスクの内容
ドライブフィルタを使用すると、特定のセキュリティ属性（セキュリティ対応など）を備えた特定の論理的な場所（ボリュームグループ1など）にある特定のタイプの物理ドライブ（すべてのSASなど）のみに表示を制限できます。これらのフィルタは一緒に使用することも別 々 に使用することもできます

[NOTE]
====
すべてのドライブが同じ物理属性を共有している場合、*次のドライブを表示する*フィルタフィールドは表示されません。すべてのドライブが同じ論理属性を共有している場合'ストレージ・アレイ*フィルタ・フィールドの* Anywhereは表示されません

====
.手順
. 「 * ハードウェア * 」を選択します。
. 最初のフィルタフィールド（* Show drives that are ...*）で、ドロップダウン矢印をクリックして、使用可能なドライブタイプとセキュリティ属性を表示します。
+
ドライブタイプには次のものがあります。

+
** ドライブのメディアタイプ（SSD、HDD）
** ドライブインターフェイスタイプ
** ドライブの容量（最大から最小）
** セキュリティ属性には次のようなものがあります（ドライブ速度（最大から最小）。
** セキュリティ対応
** セキュリティ有効
** DA（Data Assurance）対応
** FIPS に準拠している
** FIPS準拠（FIPS 140-2）
** FIPS準拠（FIPS 140-3）
+
これらの属性のいずれかがすべてのドライブで同じ場合、ドロップダウンリストには表示されません。たとえば、ストレージアレイにSASインターフェイスと速度15000rpmのSSDドライブがすべて含まれていて、一部のSSDの容量が異なる場合、ドロップダウンリストには容量のみがフィルタリングの選択肢として表示されます。

+
フィールドからオプションを選択すると、フィルタ条件に一致しないドライブはグラフィックビューでグレー表示されます。



. 2番目のフィルタボックスで、ドロップダウン矢印をクリックしてドライブに使用できる論理的な場所を表示します。
+
[NOTE]
====
フィルタ条件をクリアする必要がある場合は、フィルタボックスの右端にある[*Clear*]を選択します。

====
+
論理的な場所は次のとおりです。

+
** プール
** ボリュームグループ
** ホットスペア
** SSD キャッシュ
** 未割り当て
+
フィールドからオプションを選択すると、フィルタ条件に一致しないドライブはグラフィックビューでグレー表示されます。



. 必要に応じて、フィルタフィールドの右端で「*ロケーターライトを点灯」を選択し、表示されたドライブのロケーターライトを点灯できます。
+
この操作は、ストレージアレイ内のドライブの物理的な場所を特定するのに役立ちます。


