---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: ロックされたNVMeまたはFIPSドライブをストレージアレイに挿入する場合は、ドライブに関連付けられたセキュリティキーファイルを追加することでドライブデータのロックを解除できます。セキュリティキーがない場合は、ドライブの物理セキュリティID（PSID）を入力してロックされた各ドライブでリセットを実行し、セキュリティ属性をリセットしてドライブデータを消去できます。 
---
= ロックされたNVMe / FIPSドライブのロック解除またはリセット
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロックされたNVMeまたはFIPSドライブをストレージアレイに挿入する場合は、ドライブに関連付けられたセキュリティキーファイルを追加することでドライブデータのロックを解除できます。セキュリティキーがない場合は、ドライブの物理セキュリティID（PSID）を入力してロックされた各ドライブでリセットを実行し、セキュリティ属性をリセットしてドライブデータを消去できます。

.開始する前に
* ロックを解除する場合は、セキュリティキーファイル（拡張子）が管理クライアント（System Managerへのアクセスに使用するブラウザを備えたシステム）にあることを確認します `.slk`。キーに関連付けられているパスフレーズも確認しておく必要があります。
* リセットする場合は、リセットする各ドライブのPSIDを確認する必要があります。PSIDを確認するには、ドライブを物理的に取り外し、ドライブのラベルに記載されているPSID（最大32文字）を確認してから、ドライブを再度取り付けます。


.タスクの内容
このタスクでは、セキュリティキーファイルをストレージアレイにインポートして、NVMeドライブまたはFIPSドライブのデータのロックを解除する方法について説明します。セキュリティキーを使用できない状況では、ロックされたドライブでリセットを実行する方法についても説明します。

[NOTE]
====
外部キー管理サーバを使用してドライブがロックされている場合は、System Managerでメニュー：設定（System）>セキュリティキー管理（Security key management）を選択して、外部キー管理を設定し、ドライブのロックを解除します。

====
ロック解除機能には、[ハードウェア]ページまたはメニューからアクセスできます。[設定][システム]>[セキュリティキー管理]。次のタスクでは、[ハードウェア]ページからの手順を説明します。

.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示された場合は、*[ドライブ]*タブをクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. ロックを解除またはリセットするNVMeドライブまたはFIPSドライブを選択します。
+
ドライブのコンテキストメニューが開きます。

. セキュリティー・キー・ファイルを適用するには、*ロック解除*を選択します。セキュリティー・キー・ファイルがない場合は、*リセット*を選択します。
+
これらのオプションは、ロックされたNVMeドライブまたはFIPSドライブを選択した場合にのみ表示されます。

+
[CAUTION]
====
リセット処理を実行すると、すべてのデータが消去されます。リセットは、セキュリティキーがない場合にのみ実行してください。ロックされたドライブをリセットすると、ドライブ上のすべてのデータが完全に削除され、ドライブのセキュリティ属性がセキュリティ対応（ただし有効ではない）にリセットされます。*この操作は元に戻せません。*

====
. 次のいずれかを実行します。
+
.. *ロック解除*：［*セキュアドライブのロック解除*］ダイアログボックスで、［*参照*］をクリックし、ロック解除するドライブに対応するセキュリティキーファイルを選択します。次に、パスフレーズを入力し、*ロック解除*をクリックします。
.. *リセット*：*ロックされたドライブのリセット*ダイアログボックスで、フィールドにPSID文字列を入力し、と入力し `RESET`て確認します。[*リセット*]をクリックします。
+
ロック解除の場合、1回の処理ですべてのNVMeドライブまたはFIPSドライブのロックを解除できます。リセット処理では、リセットするドライブを個別に選択する必要があります。





.結果
これで、別のボリュームグループまたはディスクプール、または別のストレージアレイでドライブを使用できるようになります。
