---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: コントローラに関する情報（ホストインターフェイス、ドライブインターフェイス、管理ポートのステータスなど）を表示できます。 
---
= コントローラ設定の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラに関する情報（ホストインターフェイス、ドライブインターフェイス、管理ポートのステータスなど）を表示できます。

.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示された場合は、*[コントローラとコンポーネント]*タブをクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. 次のいずれかの操作を実行して、コントローラの設定を表示します。
+
** コントローラをクリックしてコンテキストメニューを表示し、*設定の表示*を選択します。
** コントローラアイコン（「* Shelf *」ドロップダウン・リストの横）を選択します。デュプレックス構成の場合は、ダイアログボックスから* Controller A*または* Controller B*を選択し、* Next *をクリックします。
+
Controller Settings（コントローラ設定）ダイアログボックスが開きます。



. プロパティ設定間を移動するタブを選択します。
+
一部のタブには、右上に[詳細設定を表示]*のリンクがあります。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| タブ | 製品説明 


 a| 
ベース
 a| 
コントローラのステータス、モデル名、交換パーツ番号、現在のファームウェアバージョン、および不揮発性静的ランダムアクセスメモリ（NVSRAM）のバージョンが表示されます。



 a| 
キャッシュ
 a| 
コントローラのキャッシュ設定が表示されます。これには、データキャッシュ、プロセッサキャッシュ、およびキャッシュバックアップデバイスが含まれます。キャッシュバックアップデバイスは、コントローラへの電源が失われた場合にキャッシュ内のデータをバックアップするために使用されます。ステータスは、最適、失敗、削除、不明、書き込み禁止、互換性なしのいずれかです。



 a| 
ホストインターフェイス
 a| 
ホストインターフェイスの情報と各ポートのリンクステータスが表示されます。ホストインターフェイスは、コントローラとホスト間の接続（Fibre ChannelやiSCSIなど）です。


NOTE: ホストインターフェイスカード（HIC）の場所は、ベースボード内またはスロット（ベイ）内です。「Baseboard」は、HICポートがコントローラに組み込まれていることを示します。「Slot」ポートはオプションのHICに搭載されています。



 a| 
ドライブインターフェイス
 a| 
ドライブインターフェイス情報と各ポートのリンクステータスが表示されます。ドライブインターフェイスは、コントローラとドライブ（SASなど）の間の接続です。



 a| 
管理ポート
 a| 
管理ポートの詳細（コントローラへのアクセスに使用するホスト名、リモートログインが有効になっているかどうかなど）が表示されます。管理ポートは、コントローラと管理クライアントを接続します。このポートには、System Managerにアクセスするためのブラウザがインストールされています。



 a| 
DNS / NTP
 a| 
は、DNSサーバとNTPサーバがSystem Managerで設定されている場合のアドレス指定方法とIPアドレスを示しています。

Domain Name System（DNS；ドメインネームシステム）は、インターネットまたはプライベートネットワークに接続されたデバイスの命名システムです。DNSサーバはドメイン名のディレクトリを維持し、インターネットプロトコル（IP）アドレスに変換します。

Network Time Protocol（NTP；ネットワークタイムプロトコル）は、データネットワーク内のコンピュータシステム間でクロック同期を行うためのネットワークプロトコルです。

|===
====
. [* 閉じる * ] をクリックします。

