---
permalink: sm-hardware/what-is-shelf-loss-protection-and-drawer-loss-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, shelf, loss, protection, drawer, 
summary: シェルフ損失の保護とドロワー損失の保護は、1つのシェルフまたはドロワーに障害が発生した場合にデータアクセスを維持できるプールおよびボリュームグループの属性です。 
---
= シェルフ損失の保護とドロワー損失の保護とは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シェルフ損失の保護とドロワー損失の保護は、1つのシェルフまたはドロワーに障害が発生した場合にデータアクセスを維持できるプールおよびボリュームグループの属性です。



== シェルフ損失の保護

シェルフは、ドライブまたはドライブとコントローラを格納するエンクロージャです。シェルフ損失の保護が有効な場合、1台のドライブシェルフとの通信が完全に失われた場合でもプールまたはボリュームグループ内のボリューム上のデータへのアクセスが保証されます。通信が完全に失われる例としては、ドライブシェルフへの電力供給の停止や、両方のI/Oモジュール（IOM）の障害などがあります。

[NOTE]
====
プールまたはボリュームグループですでにドライブに障害が発生している場合は、シェルフ損失の保護は保証されません。この場合、ドライブシェルフにアクセスできなくなり、その結果プールまたはボリュームグループ内の別のドライブにアクセスできなくなると、データが失われます。

====
シェルフ損失の保護の条件は、次の表で説明するように、保護の手法によって異なります。

[cols="1a,1a,1a"]
|===
| レベル | シェルフ損失の保護の条件 | 必要なシェルフの最小数 


 a| 
プール
 a| 
プールには5台以上のシェルフのドライブが含まれ、各シェルフに同数のドライブが含まれている必要があります。シェルフ損失の保護は大容量シェルフには適用されません。大容量シェルフがあるシステムの場合は、ドロワー損失の保護を参照してください。
 a| 
5



 a| 
RAID 6
 a| 
ボリュームグループに同じシェルフのドライブが3本以上含まれない。
 a| 
3



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがそれぞれ別 々 のシェルフに配置されている。
 a| 
3



 a| 
RAID 1
 a| 
RAID 1ペアのドライブがそれぞれ別のシェルフに配置されている。
 a| 
2



 a| 
RAID 0
 a| 
シェルフ損失の保護は実現できない。
 a| 
該当なし

|===


== ドロワー損失の保護

ドロワーはシェルフのコンパートメントの1つで、引き出してドライブを設置します。ドロワーを備えているのは大容量のシェルフだけです。ドロワー損失の保護が有効な場合、1つのドロワーとの通信が完全に失われた場合でもプールまたはボリュームグループ内のボリューム上のデータへのアクセスが保証されます。通信が完全に失われるケースには、ドロワーの電源喪失や、ドロワー内のコンポーネント障害などがあります。

[NOTE]
====
プールまたはボリュームグループですでにドライブに障害が発生している場合は、ドロワー損失の保護は保証されません。この場合、ドロワーへのアクセス（その結果、プールまたはボリュームグループ内の別のドライブ）を失うと、データが失われます。

====
ドロワー損失の保護の条件は、次の表で説明するように、保護の手法によって異なります。

[cols="1a,1a,1a"]
|===
| レベル | ドロワー損失の保護の基準 | 必要なドロワーの最小数 


 a| 
プール
 a| 
プール候補にはすべてのドロワーのドライブが含まれ、各ドロワーに同じ数のドライブが必要です。

プールに少なくとも5つのドロワーのドライブが含まれており、各ドロワーに同じ数のドライブが含まれている必要があります。

60ドライブシェルフでは、プールに含まれるドライブが15、20、25、30、35、40、45、50、55、または60本の場合にドロワー損失の保護を実現できます。最初の作成後に、5の倍数の増分をプールに追加できます。
 a| 
5



 a| 
RAID 6
 a| 
ボリュームグループに同じドロワーのドライブが3本以上含まれない。
 a| 
3



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがそれぞれ別 々 のドロワーに配置されている。
 a| 
3



 a| 
RAID 1
 a| 
ミラーペアの各ドライブが別 々 のドロワーに配置されている必要があります。
 a| 
2



 a| 
RAID 0
 a| 
ドロワー損失の保護は実現できない。
 a| 
該当なし

|===