---
permalink: sm-hardware/what-is-ipv6-stateless-address-auto-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ipv6, stateless, address, auto, configuration, 
summary: ステートレス自動設定を使用すると、ホストはアドレスやその他の設定情報をサーバから取得しません。 
---
= IPv6ステートレスアドレス自動設定とは何ですか。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ステートレス自動設定を使用すると、ホストはアドレスやその他の設定情報をサーバから取得しません。

IPv6のステートレス自動設定には、リンクローカルアドレス、マルチキャスト、およびNeighbor Discovery（ND）プロトコルがあります。IPv6では、基盤となるデータリンク層アドレスからアドレスのインターフェイスIDを生成できます。

ステートレス自動設定とステートフル自動設定は、相互に補完しあう機能です。たとえば、ホストはステートレス自動設定を使用して自身のアドレスを設定できますが、ステートフル自動設定を使用してその他の情報を取得できます。ステートフル自動設定を使用すると、ホストはサーバからアドレスやその他の設定情報を取得できます。インターネットプロトコルバージョン6（IPv6）では、ネットワーク上のすべてのIPアドレスを一度に再番号付けできる方法も定義されています。IPv6は、ネットワーク上のデバイスがサーバを必要とせずにIPアドレスやその他のパラメータを自動的に設定する方法を定義します。

ステートレス自動設定を使用する場合、デバイスは次の手順を実行します。

. *リンクローカルアドレスを生成*--デバイスは10ビットのリンクローカルアドレスを生成し、その後に54個のゼロと64ビットのインターフェイスIDを生成します。
. *リンクローカルアドレスの一意性をテスト*--生成されるリンクローカルアドレスがローカルネットワークでまだ使用されていないことをテストしますデバイスがNDプロトコルを使用して近接要求メッセージを送信します。これに応答して、ローカルネットワークはネイバーアドバタイズメントメッセージをリッスンします。これは、別のデバイスがすでにリンクローカルアドレスを使用していることを示します。その場合は、新しいリンクローカルアドレスを生成するか、自動設定が失敗し、別の方法を使用する必要があります。
. *リンクローカルアドレスの割り当て*--一意性テストに合格すると、デバイスは自身のIPインタフェースにリンクローカルアドレスを割り当てます。リンクローカルアドレスは、ローカルネットワーク上での通信には使用できますが、インターネット経由では使用できません。
. *ルータに連絡*--ノードは、設定の続行の詳細についてローカルルータへの接続を試みます。この連絡先は、ルータから定期的に送信されるルータアドバタイズメントメッセージをリスンするか、またはルータに次の処理についての情報を要求する特定のルータ要求メッセージを送信することによって実行されます。
. *ノードへの指示*--ルーターは自動設定の続行方法をノードに指示します。または、ルータは、グローバルインターネットアドレスの決定方法をホストに通知します。
. *グローバルアドレスを設定*--ホストは、グローバルに一意なインターネットアドレスを自身に設定します。このアドレスは、通常、ルータによってホストに提供されるネットワークプレフィックスから形成されます。

