---
permalink: um-manage/activate-pending-firmware.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, activate, staged, os, software 
summary: ソフトウェアファイルはすぐにアクティブ化することも、都合の良いタイミングでアクティブ化することもできます。この手順では、ソフトウェアファイルをあとでアクティブ化するように選択したことを前提としています。 
---
= ステージング済みOSソフトウェアのアクティブ化
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェアファイルはすぐにアクティブ化することも、都合の良いタイミングでアクティブ化することもできます。この手順では、ソフトウェアファイルをあとでアクティブ化するように選択したことを前提としています。

.タスクの内容
ファームウェアファイルはアクティブ化せずに転送できます。あとでアクティブ化する理由は次のとおりです。

* * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがリブートしてフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


[NOTE]
====
起動後にアクティブ化プロセスを停止することはできません。

====
.手順
. メインビューで、* Manage *（管理）を選択します。必要に応じて、ページ上部の[ステータス]列をクリックしてソートし、ステータスが「OSアップグレード（アクティブ化待ち）」のすべてのストレージアレイを表示します。
. ソフトウェアをアクティブ化するストレージアレイを 1 つ以上選択し、メニューから [Upgrade Center] [Activate Staged OS Software] を選択します。
+
アップグレード処理では、次の処理が実行されます。

+
** アップグレード前の健常性チェックは、アクティブ化プロセスの一環として実行されます。アップグレード前の健常性チェックでは、ストレージアレイのすべてのコンポーネントについて、アクティブ化を続行できるかどうかがチェックされます。
** ストレージアレイの健全性チェックに失敗すると、アクティブ化は停止します。省略符号 (...) をクリックして * ログを保存 * を選択すると、エラーを確認できます。ヘルスチェックエラーを無視して、 [* Continue （続行） ] をクリックしてアクティブ化を続行することもできます。
** アップグレード前の健常性チェックのあとにアクティブ化処理をキャンセルできます。アップグレード前の健常性チェックが正常に完了すると、アクティブ化が実行されます。アクティブ化にかかる時間は、ストレージアレイの構成とアクティブ化するコンポーネントによって異なります。


. *オプション：*アクティブ化が完了すると、省略記号（...）をクリックし、「ログを保存」を選択することにより、特定のストレージアレイに対してアクティブ化された内容のリストが表示されます。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `activate_log-<date>.json`。


