---
permalink: um-manage/discover-single-array.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, single, array 
summary: 単一ストレージアレイの追加/検出オプションを使用して、組織のネットワークを手動で検出して追加します。 
---
= 単一のアレイの検出
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
単一のストレージアレイを手動で検出して組織のネットワークに追加するには、[単一のストレージアレイの追加/検出]オプションを使用します。

.開始する前に
* ストレージアレイが正しくセットアップおよび設定されている必要があります。
* ストレージアレイのパスワードは、System Managerの[アクセス管理]タイルを使用して設定する必要があります。


.手順
. [ 管理 ] ページで、 [ * 追加 / 検出 * ] を選択します。
+
[Add/Discover]ダイアログボックスが表示されます。

. [Discover a single storage array]オプションボタンを選択します。
. ストレージアレイ内のいずれかのコントローラのIPアドレスを入力し、*検出の開始*をクリックします。
+
指定したストレージアレイへのUnified Managerの接続には数分かかることがあります。

+
[NOTE]
====
指定したIPアドレスでコントローラに接続できない場合、「ストレージアレイにアクセスできません」というメッセージが表示されます。

====
. プロンプトが表示されたら、自己署名証明書を解決します。
+
検出プロセスでは、検出されたストレージアレイに信頼できるソースからの証明書があるかどうかが確認されます。ストレージアレイのデジタル証明書が見つからない場合は、認識された認証局（CA）によって署名されていない証明書を解決するためにセキュリティ例外を追加するように求められます。

. 信頼されていない証明書があれば解決します。
+
信頼されていない証明書は、ストレージアレイからUnified Managerへのセキュアな接続を確立しようとしたときに、接続がセキュアであることを確認できない場合に発生します。信頼されていない証明書を解決するには、信頼できる第三者機関から発行された認証局（CA）証明書をインポートします。

. 「 * 次へ * 」をクリックします。
. *オプション：*検出されたストレージアレイをグループに関連付けます。ドロップダウンリストから、ストレージアレイを関連付ける目的のグループを選択します。
+
デフォルトでは「All」グループが選択されています。

. 管理ドメインに追加するストレージアレイの管理者パスワードを入力し、* OK *をクリックします。


.終了後
ストレージアレイがUnified Managerに追加され、指定した場合は選択したグループにも追加されます。

サポートデータの自動収集が有効になっている場合は、追加したストレージアレイのサポートデータが自動的に収集されます。
