---
permalink: um-manage/how-upgrades-work.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrades, 
summary: Unified Managerを使用して、同じタイプの複数のストレージアレイのSANtricity OSソフトウェアを新しいバージョンにアップグレードできます。 
---
= アップグレードの仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを使用して、同じタイプの複数のストレージアレイのSANtricity OSソフトウェアを新しいバージョンにアップグレードできます。



== アップグレードワークフロー

次の手順は、ソフトウェアのアップグレードを実行するための大まかなワークフローを示しています。

. 最新のSANtricity OSソフトウェアファイルをサポートサイトからダウンロードします（サポート*ページのUnified Managerからリンクできます）。管理ホストシステム（ブラウザでUnified Managerにアクセスするホスト）にファイルを保存し、ファイルを解凍します。
. Unified Managerで、SANtricity OSソフトウェアファイルとNVSRAMファイルをリポジトリ（Webサービスプロキシサーバのファイルが格納されている領域）にロードします。ファイルは、メニューから追加できます。[Upgrade SANtricity OS Software]または[Upgrade Center]>[Manage Software Repository]から選択します。
. ファイルがリポジトリにロードされたら、アップグレードで使用するファイルを選択できます。SANtricity OSソフトウェアのアップグレードページ（メニュー：アップグレードセンター[Upgrade SANtricity OS software]）から、SANtricity OSソフトウェアファイルとNVSRAMファイルを選択します。ソフトウェアファイルを選択すると、互換性があるストレージアレイのリストがこのページに表示されます。次に、新しいソフトウェアにアップグレードするストレージアレイを選択します。（互換性のないアレイは選択できません）。
. その後、ソフトウェアの転送とアクティブ化をすぐに開始することも、後でアクティブ化するためにファイルをステージングすることもできます。アップグレードプロセスを実行すると、Unified Managerで次の処理が実行されます。
+
.. ストレージアレイの健全性チェックが実行され、アップグレードの完了を妨げる可能性のある状況がないかどうかが確認されます。いずれかのアレイが健全性チェックで不合格になった場合は、そのアレイをスキップして他のアレイのアップグレードを続行するか、プロセス全体を停止して合格しなかったアレイのトラブルシューティングを行うことができます。
.. アップグレードファイルを各コントローラに転送します。
.. コントローラが一度に1台ずつリブートされ、新しいSANtricity OSソフトウェアがアクティブ化されます。アクティブ化では、既存のSANtricity OSファイルが新しいファイルに置き換えられます。
+
[NOTE]
====
ソフトウェアをあとでアクティブ化するように指定することもできます。

====






== 即時アップグレードまたは段階的アップグレード

アップグレードはただちにアクティブ化することも、ステージングしてあとでアクティブ化することもできます。あとでアクティブ化する理由は次のとおりです。

* * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。I/O負荷とキャッシュサイズによっては、コントローラのアップグレードが完了するまでに通常15~25分かかることがあります。アクティブ化の際にはコントローラがリブートしてフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


ステージング済みソフトウェアをアクティブにするには、メニューサポート[Upgrade Center]に移動し、SANtricity OSコントローラソフトウェアのアップグレードというラベルの付いた領域で[Activate *（有効化*）]をクリックします。



== 健全性チェック

健全性チェックはアップグレードプロセスの一環として実行されますが、開始する前に別途実行することもできます（メニュー：Upgrade Center [Pre-Upgrade Health Check]に移動）。

健全性チェックでは、ストレージシステムのすべてのコンポーネントについて、アップグレードを実行できるかどうかがチェックされます。アップグレードを実行できない状況は次のとおりです。

* 割り当て済みドライブで障害が発生
* ホットスペアを使用中です
* ボリュームグループに不備がある
* 同時に実行できない処理
* ボリュームが見つからない
* コントローラのステータスが最適でない
* イベントログイベントの数が多すぎる
* 構成データベースの検証エラー
* 古いバージョンのDACstoreを搭載したドライブ

