---
permalink: um-manage/import-storage-configuration-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, storage, configuration, settings 
summary: ストレージアレイから別のストレージアレイにストレージ構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= ストレージ構成のインポート
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにストレージ構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.開始する前に
* ソースとして使用するストレージアレイのストレージをSANtricity System Managerで設定しておきます。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。
* ソースアレイとターゲットアレイが次の要件を満たしている必要があります。
+
** コントローラが配置されているシェルフが同じである必要があります。
** シェルフIDが同じである必要があります。
** 拡張シェルフには、同じドライブタイプの同じスロットが搭載されている必要があります。
** RBODエンクロージャタイプは同一である必要があります。
** HICが、ホストのData Assurance機能を含めて同一である。
** ターゲットアレイのステータスが最適である必要があります。
** ターゲットアレイのボリューム容量がソースアレイの容量よりも大きい。


* 次の制限事項に注意してください。
+
** デュプレックス構成からシンプレックス構成へのインポートはサポートされていませんが、シンプレックス構成からデュプレックス構成へのインポートは可能です。
** ソースアレイのディスクプールボリュームが64TB以上の場合、ターゲットでインポートプロセスを実行できません。
** シンボリュームはインポートプロセスに含まれません。




.タスクの内容
インポートされる設定には、設定済みのボリューム（リポジトリボリュームでないシックボリュームのみ）、ボリュームグループ、プール、およびホットスペアドライブの割り当てが含まれます。

.手順
. [管理]ページで、[設定のインポート*]をクリックします。
+
設定のインポートウィザードが開きます。

. [設定の選択]ダイアログボックスで、[ストレージ構成*]を選択し、[次へ*]をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログボックスで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. [Select Targets]ダイアログボックスで、新しい設定を適用するアレイを1つ以上選択します。
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイ、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログボックスに表示されません。

====
. [ 完了 ] をクリックします。
+
[Operations]ページにインポート処理の結果が表示されます。処理に失敗した場合は、その行をクリックすると詳細が表示されます。



.結果
ターゲットストレージアレイのストレージ構成がソースアレイと同じに設定されます。
