---
permalink: um-manage/import-directory-services-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, directory, services, settings 
summary: ストレージアレイから別のストレージアレイにディレクトリサービス設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= ディレクトリサービス設定のインポート
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにディレクトリサービス設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.開始する前に
* ディレクトリサービスは、ソースとして使用するストレージアレイのSystem Managerで設定されます（メニュー：設定[アクセス管理]）。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。


.タスクの内容
インポートされる設定には、LDAP（Lightweight Directory Access Protocol）サーバのドメイン名とURL、およびLDAPサーバのユーザグループとストレージアレイの事前定義されたロールのマッピングが含まれます。

.手順
. [管理]ページで、[設定のインポート*]をクリックします。
+
設定のインポートウィザードが開きます。

. [設定の選択]ダイアログボックスで、[*ディレクトリサービス*]を選択し、[次へ*]をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログボックスで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. [Select Targets]ダイアログボックスで、新しい設定を適用するアレイを1つ以上選択します。
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイ、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログボックスに表示されません。

====
. [ 完了 ] をクリックします。
+
[Operations]ページにインポート処理の結果が表示されます。処理に失敗した場合は、その行をクリックすると詳細が表示されます。





== 結果

ターゲットストレージアレイにソースアレイと同じディレクトリサービスが設定されます。
