---
permalink: um-manage/manage-repository.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, manage, software, repository 
summary: ソフトウェアリポジトリには、Web Services Proxyに関連付けられているすべてのソフトウェアファイルが表示されます。 
---
= ソフトウェアリポジトリの管理
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェアリポジトリには、Web Services Proxyに関連付けられているすべてのソフトウェアファイルが表示されます。

使用するファイルが表示されない場合は、ソフトウェアリポジトリの管理オプションを使用して、WebサービスプロキシとUnified Managerが実行されているホストシステムに1つ以上のSANtricity OSファイルをインポートできます。ソフトウェアリポジトリにあるSANtricity OSファイルを削除することもできます。

.開始する前に
SANtricity OSファイルを追加する場合は、ローカルシステム上にOSファイルがあることを確認します。

.手順
. メインビューから* Manage *を選択し、メニューからUpgrade Center [Manage Software Repository]を選択します。
+
[Manage Software Repository]ダイアログボックスが表示されます。

. 次のいずれかを実行します。
+
[cols="25h,~"]
|===
| オプション | これをしなさい… 


 a| 
インポート
 a| 
.. [*インポート.*]をクリックします
.. [*参照]をクリックし、追加するOSファイルが保存されている場所に移動します。
+
OSファイルのファイル名は、のようになり `N2800-830000-000.dlp`ます。

.. 追加するOSファイルを1つ以上選択し、*インポート*をクリックします。




 a| 
削除
 a| 
.. ソフトウェアリポジトリから削除するOSファイルを1つ以上選択します。
.. [ 削除（ Delete ） ] をクリックします。


|===


.結果
インポートを選択した場合は、ファイルがアップロードされて検証されます。[Delete]を選択すると、ファイルがソフトウェアリポジトリから削除されます。
