---
permalink: um-manage/mirroring-terminology.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, terminology 
summary: ストレージアレイに関連するミラーリングの用語を次に示します。 
---
= ミラーリングに関する用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するミラーリングの用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 製品説明 


 a| 
ローカルストレージアレイ
 a| 
ローカルストレージアレイは、操作の対象となるストレージアレイです。



 a| 
ミラー整合性グループ
 a| 
ミラー整合性グループは、1つ以上のミラーペアのコンテナです。非同期ミラーリング処理では、ミラー整合性グループを作成する必要があります。グループ内のすべてのミラーペアが同時に再同期されるため、整合性のあるリカバリポイントが維持されます。

同期ミラーリングではミラー整合性グループを使用しません。



 a| 
ミラーペア
 a| 
ミラーペアは、プライマリボリュームとセカンダリボリュームの2つのボリュームで構成されます。

非同期ミラーリングでは、ミラーペアは常にミラー整合性グループに属します。書き込み処理は最初にプライマリボリュームに対して実行され、次にセカンダリボリュームにレプリケートされます。ミラー整合性グループ内の各ミラーペアでは、同じ同期設定が共有されます。



 a| 
プライマリボリューム
 a| 
ミラーペアのプライマリボリュームは、ミラーリングするソースボリュームです。



 a| 
リモートストレージアレイ
 a| 
通常、リモートストレージアレイはセカンダリサイトとして指定され、セカンダリサイトにはミラーリング構成のデータのレプリカが格納されます。



 a| 
リザーブ容量
 a| 
リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。

ミラーリングの動作状態を維持するために必要な情報をコントローラが永続的に保存できるようにするには、これらのボリュームが必要です。これらのボリュームには、差分ログやcopy-on-writeデータなどの情報が格納されます。



 a| 
セカンダリボリューム
 a| 
ミラーペアのセカンダリボリュームは、通常はセカンダリサイトに配置され、データのレプリカが格納されます。



 a| 
同期
 a| 
同期は、ローカルストレージアレイとリモートストレージアレイの間の初期同期で実行されます。同期は、通信の中断後にプライマリボリュームとセカンダリボリュームが同期されていない状態になった場合にも実行されます。通信リンクの動作が再開されると、レプリケートされていないデータがセカンダリボリュームのストレージアレイに同期されます。

|===