---
permalink: um-manage/mirroring-overview.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, 
summary: Unified ManagerにはSANtricity ミラーリング機能の設定オプションが用意されており、管理者は2つのストレージアレイ間でデータをレプリケートしてデータを保護できます。 
---
= ミラーリングの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified ManagerにはSANtricity ミラーリング機能の設定オプションが用意されており、管理者は2つのストレージアレイ間でデータをレプリケートしてデータを保護できます。

[NOTE]
====
同期ミラーリングは、EF600またはEF300ストレージシステムでは使用できません。

====


== ミラーリングのタイプ

SANtricityアプリケーションには、非同期と同期の2種類のミラーリングがあります。

非同期ミラーリングでは、データボリュームがオンデマンドまたはスケジュールに基づいてコピーされるため、データの破損や損失が原因で発生するダウンタイムを最小限または回避できます。非同期ミラーリングでは、特定の時点におけるプライマリボリュームの状態がキャプチャされ、前回のイメージキャプチャ以降に変更されたデータだけがコピーされます。プライマリサイトはただちに更新でき、セカンダリサイトは帯域幅の許す限り更新できます。情報はキャッシュされ、あとでネットワークリソースが利用可能になると送信されます。このタイプのミラーリングは、バックアップやアーカイブなどの定期的なプロセスに最適です。

同期ミラーリングでは、データボリュームがリアルタイムでレプリケートされるため、継続的な可用性が確保されます。目的は、2つのストレージアレイのいずれかで災害が発生した場合に重要なデータのコピーを確保しておくことで、データ損失ゼロの目標復旧時点（RPO）を達成することです。プライマリボリュームに書き込みが行われるたびにセカンダリボリュームにも書き込みが行われるため、コピーは常に本番環境のデータと同じです。プライマリボリュームで行われた変更でセカンダリボリュームが更新されるまで、ホストは書き込みが成功したことを示す確認応答を受信しません。このタイプのミラーリングは、ディザスタリカバリなどのビジネス継続性の目的に最適です。



== ミラーリングのタイプの違い

次の表に、2種類のミラーリングの主な違いを示します。

[cols="1a,1a,1a"]
|===
| 属性 | 非同期 | 同期 


 a| 
レプリケーション方法
 a| 
ポイントインタイム--ミラーリングはオンデマンドで、またはユーザー定義のスケジュールに従って自動的に実行されます。
 a| 
continuous --ミラーリングは自動的に継続的に実行され'ホストの書き込みごとにデータがコピーされます



 a| 
距離
 a| 
アレイ間の長距離をサポートします。通常、距離はネットワークとチャネル拡張テクノロジーの機能によってのみ制限されます。
 a| 
アレイ間の距離は短くしてください。レイテンシとアプリケーションパフォーマンスの要件を満たすために、通常はローカルストレージアレイから約10km（6.2マイル）以内の距離にする必要があります。



 a| 
通信方法
 a| 
標準のIPまたはFibre Channelネットワーク。
 a| 
Fibre Channelネットワークのみ。



 a| 
ボリュームタイプ
 a| 
標準またはシン。
 a| 
標準のみ。

|===