---
permalink: um-manage/overview-upgrade-center-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, center 
summary: アップグレードセンターでは、複数のストレージアレイのSANtricity OSソフトウェアとNVSRAMのアップグレードを管理できます。 
---
= アップグレードセンターの概要
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードセンターでは、複数のストレージアレイのSANtricity OSソフトウェアとNVSRAMのアップグレードを管理できます。



== アップグレードの仕組み

最新のOSソフトウェアをダウンロードしてから、1つ以上のアレイをアップグレードします。



=== アップグレードワークフロー

次の手順では、ソフトウェアのアップグレードを実行するための大まかなワークフローを示します。

. 最新のSANtricity OSソフトウェアファイルをサポートサイトからダウンロードします（サポートページのUnified Managerからリンクできます）。管理ホストシステム（ブラウザでUnified Managerにアクセスするホスト）にファイルを保存し、ファイルを解凍します。
. Unified Managerで、SANtricity OSソフトウェアファイルとNVSRAMファイルをリポジトリ（Webサービスプロキシサーバのファイルが格納されている領域）にロードします。ファイルは、メニューから追加できます。[Upgrade SANtricity OS Software]または[Upgrade Center]>[Manage Software Repository]から選択します。
. ファイルがリポジトリにロードされたら、アップグレードで使用するファイルを選択できます。SANtricity OSソフトウェアのアップグレードページ（メニュー：アップグレードセンター[Upgrade SANtricity OS software]）から、SANtricity OSソフトウェアファイルとNVSRAMファイルを選択します。ソフトウェアファイルを選択すると、互換性があるストレージアレイのリストがこのページに表示されます。次に、新しいソフトウェアにアップグレードするストレージアレイを選択します。（互換性のないアレイは選択できません）。
. その後、ソフトウェアの転送とアクティブ化をすぐに開始することも、後でアクティブ化するためにファイルをステージングすることもできます。アップグレードプロセスを実行すると、Unified Managerで次の処理が実行されます。
+
.. ストレージアレイの健全性チェックが実行され、アップグレードの完了を妨げる可能性のある状況がないかどうかが確認されます。いずれかのアレイが健全性チェックで不合格になった場合は、そのアレイをスキップして他のアレイのアップグレードを続行するか、プロセス全体を停止して合格しなかったアレイのトラブルシューティングを行うことができます。
.. アップグレードファイルを各コントローラに転送します。
.. コントローラが一度に1台ずつリブートされ、新しいSANtricity OSソフトウェアがアクティブ化されます。アクティブ化では、既存のSANtricity OSファイルが新しいファイルに置き換えられます。
+
[NOTE]
====
ソフトウェアをあとでアクティブ化するように指定することもできます。

====






=== 即時アップグレードまたは段階的アップグレード

アップグレードはただちにアクティブ化することも、ステージングしてあとでアクティブ化することもできます。あとでアクティブ化する理由は次のとおりです。

* * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。I/O負荷とキャッシュサイズによっては、コントローラのアップグレードが完了するまでに通常15~25分かかることがあります。アクティブ化の際にはコントローラがリブートしてフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


ステージング済みソフトウェアをアクティブにするには、メニューサポート[Upgrade Center]に移動し、SANtricity OSコントローラソフトウェアのアップグレードというラベルの付いた領域で[Activate *（有効化*）]をクリックします。



=== 健全性チェック

健全性チェックはアップグレードプロセスの一環として実行されますが、開始する前に別途実行することもできます（メニュー：Upgrade Center [Pre-Upgrade Health Check]に移動）。

健全性チェックでは、ストレージシステムのすべてのコンポーネントについて、アップグレードを実行できるかどうかがチェックされます。アップグレードを実行できない状況は次のとおりです。

* 割り当て済みドライブで障害が発生
* ホットスペアを使用中です
* ボリュームグループに不備がある
* 同時に実行できない処理
* ボリュームが見つからない
* コントローラのステータスが最適でない
* イベントログイベントの数が多すぎる
* 構成データベースの検証エラー
* 古いバージョンのDACstoreを搭載したドライブ




== アップグレードするときは、どのような点に注意する必要がありますか？

複数のストレージアレイをアップグレードする前に、計画の一環として重要な考慮事項を確認してください。



=== 現在のバージョン

検出された各ストレージアレイについて、Unified Managerの管理ページからSANtricity OSの現在のソフトウェアバージョンを表示できます。バージョンは、SANtricity OSソフトウェアの列に表示されます。各行の SANtricity OS のバージョンをクリックするとポップアップダイアログボックスが表示され、コントローラのファームウェアと NVSRAM の情報を確認できます。



=== アップグレードが必要なその他のコンポーネント

アップグレードプロセスの一環として、ホストがコントローラと正しく連携できるように、ホストのマルチパス/フェイルオーバードライバまたはHBAドライバのアップグレードも必要になる場合があります。

互換性については、を参照して https://imt.netapp.com/matrix/#welcome["NetAppのInteroperability Matrix"^]ください。手順については、使用しているオペレーティングシステムに対応したエクスプレスガイドを参照してください。エクスプレスガイドはから入手でき https://docs.netapp.com/us-en/e-series/index.html["E シリーズおよび SANtricity に関するドキュメント"^]ます。



=== デュアルコントローラ

ストレージアレイにコントローラが2台あり、マルチパスドライバがインストールされている場合は、アップグレードの実行中もストレージアレイでI/Oの処理を続行できます。アップグレード中に、次のプロセスが実行されます。

. コントローラAのすべてのLUNがコントローラBにフェイルオーバーされます。
. コントローラAでアップグレードが実行されます。
. コントローラAが自身のLUNとコントローラBのすべてのLUNをテイクバックします。
. コントローラBでアップグレードが実行されます。


アップグレードの完了後、所有権のある正しいコントローラにボリュームが配置されるように、コントローラ間で手動でのボリュームの再配置が必要になることがあります。
