---
permalink: um-manage/overview-mirroring-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring 
summary: ミラーリング機能を使用して、ローカルストレージアレイとリモートストレージアレイの間でデータを非同期または同期的にレプリケートします。 
---
= ミラーリングの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーリング機能を使用して、ローカルストレージアレイとリモートストレージアレイの間でデータを非同期または同期的にレプリケートします。

[NOTE]
====
同期ミラーリングは、EF600またはEF300ストレージシステムでは使用できません。

====


== ミラーリングとは

SANtricityアプリケーションには、非同期と同期の2種類のミラーリングがあります。非同期ミラーリングでは、データボリュームがオンデマンドまたはスケジュールに基づいてコピーされるため、データの破損や損失が原因で発生するダウンタイムを最小限または回避できます。同期ミラーリングでは、データボリュームがリアルタイムでレプリケートされるため、継続的な可用性が確保されます。

詳細：

* link:mirroring-overview.html["ミラーリングの仕組み"]
* link:mirroring-terminology.html["ミラーリングに関する用語"]




== ミラーリングの設定方法

Unified Managerで非同期ミラーリングまたは同期ミラーリングを設定し、System Managerを使用して同期を管理します。

詳細：

* link:mirroring-configuration-workflow.html["ミラーリングの設定ワークフロー"]
* link:requirements-for-using-mirroring.html["ミラーリングを使用するための要件"]
* link:create-asynchronous-mirrored-pair-um.html["非同期ミラーペアの作成"]
* link:create-synchronous-mirrored-pair-um.html["同期ミラーペアの作成"]

