---
permalink: um-manage/overview-import-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, settings 
summary: アラート、AutoSupport 、ディレクトリサービスなどの設定をストレージアレイから別のストレージアレイにインポートできます。 
---
= 設定のインポートの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定のインポート機能を使用すると、1つのアレイから複数のアレイに設定をインポートするバッチ処理を実行できます。この機能により、ネットワーク内で複数のアレイを構成する必要がある場合に時間を節約できます。



== どのような設定をインポートできますか？

アラート方法、AutoSupport設定、ディレクトリサービス設定、ストレージ設定（ボリュームグループやプールなど）、およびシステム設定（自動ロードバランシングなど）をインポートできます。

詳細：

* link:how-import-settings-works.html["設定のインポートの仕組み"]
* link:requirements-for-replicating-storage-configurations.html["ストレージ構成のレプリケートに関する要件"]




== バッチインポートの実行方法を教えてください。

ソースとして使用するストレージアレイで、System Managerを開き、必要な設定を行います。そのあと、Unified Managerの[管理]ページに移動し、1つ以上のアレイに設定をインポートします。

詳細：

* link:import-alert-settings.html["アラート設定のインポート"]
* link:import-autosupport-settings.html["AutoSupport設定のインポート"]
* link:import-directory-services-settings.html["ディレクトリサービス設定のインポート"]
* link:import-storage-configuration-settings.html["ストレージ構成のインポート"]
* link:import-system-settings.html["システム設定のインポート"]

