---
permalink: um-manage/requirements-for-replicating-storage-configurations.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, requirements, replicating, storage, configurations 
summary: ストレージアレイ間でストレージ構成をインポートする前に、要件とガイドラインを確認してください。 
---
= ストレージ構成のレプリケートに関する要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ間でストレージ構成をインポートする前に、要件とガイドラインを確認してください。



== シェルフ

* コントローラが配置されているシェルフがソースとターゲットのアレイで同一である。
* シェルフIDがソースアレイとターゲットアレイで同一である必要があります。
* 拡張シェルフは、同じドライブタイプの同じスロットに搭載する必要があります（ドライブが構成で使用されている場合は、未使用ドライブの場所は関係ありません）。




== コントローラ

* コントローラのタイプはソースアレイとターゲットアレイで異なる場合があり（E2800からE5700にインポートする場合など）、RBODエンクロージャのタイプは同じである必要があります。
* HIC（ホストのDA機能を含む）がソースアレイとターゲットアレイで同一である必要があります。
* デュプレックス構成からシンプレックス構成へのインポートはサポートされていませんが、シンプレックス構成からデュプレックス構成へのインポートは可能です。
* FDE設定はインポートプロセスに含まれません。




== ステータス

* ターゲットアレイのステータスが最適である必要があります。
* ソースアレイのステータスが最適である必要はありません。




== ストレージ

* ターゲットのボリューム容量がソースよりも大きいかぎり、ソースアレイとターゲットアレイでドライブ容量が異なる場合があります。（ターゲットアレイには、より新しい大容量のドライブが搭載されている場合がありますが、このドライブはレプリケーション処理によってボリュームに完全に構成されません）。
* ソースアレイのディスクプールボリュームが64TB以上の場合、ターゲットでインポートプロセスを実行できません。
* シンボリュームはインポートプロセスに含まれません。

