---
permalink: um-manage/upgrade-controller-firmware.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, os, operating system 
summary: 1つ以上のストレージアレイを最新のソフトウェアとNVSRAMでアップグレードして、最新の機能とバグ修正をすべて適用します。コントローラNVSRAMは、コントローラのデフォルト設定を指定するコントローラファイルです。 
---
= SANtricity OSのアップグレード
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1つ以上のストレージアレイを最新のソフトウェアとNVSRAMでアップグレードして、最新の機能とバグ修正をすべて適用します。コントローラNVSRAMは、コントローラのデフォルト設定を指定するコントローラファイルです。

.開始する前に
* 最新のSANtricity OSファイルは、SANtricity WebサービスプロキシとUnified Managerが実行されているホストシステムにあります。
* ソフトウェアアップグレードを今すぐアクティブ化するかあとでアクティブ化するかを決めておきます。
+
あとでアクティブ化する理由は次のとおりです。

+
** * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ *-- 他のストレージアレイのファイルをアップグレードする前に ' 新しい OS ソフトウェアを 1 つのストレージアレイでテストすることをお勧めします





IMPORTANT: システムを11.80.x以降にアップグレードするには、SANtricity OS 11.70.5が実行されている必要があります。

.タスクの内容
+++++

[NOTE]
====
データ損失またはストレージアレイの破損のリスク-アップグレードの実行中はストレージアレイを変更しないでください。ストレージアレイへの電源を維持します。

====
.手順
. ストレージアレイにコントローラが1台しかない場合、またはマルチパスドライバを使用していない場合は、アプリケーションエラーを回避するためにストレージアレイへのI/Oアクティビティを停止します。ストレージアレイにコントローラが2台あり、マルチパスドライバがインストールされている場合は、I/Oアクティビティを停止する必要はありません。
. メイン・ビューから* Manage *を選択し、アップグレードするストレージ・アレイを1つ以上選択します。
. メニューからアップグレードセンター [Upgrade SANtricity OS Software] を選択します。
+
[Upgrade SANtricity OS software]ページが表示されます。

. 最新のSANtricity OSソフトウェアパッケージをNetAppサポートサイトからローカルマシンにダウンロードします。
+
.. [ 新しいファイルをソフトウェアリポジトリに追加する *] をクリックします。
.. 最新の * SANtricity OS ダウンロード * を検索するためのリンクをクリックします。
.. [Download Latest Release] リンクをクリックします。
.. 以降の手順に従って、 SANtricity OS ファイルと NVSRAM ファイルをローカルマシンにダウンロードします。


+
[NOTE]
====
バージョン8.42以降では、デジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。

====
. コントローラのアップグレードに使用するOSソフトウェアファイルとNVSRAMファイルを選択します。
+
.. [Select a SANtricity OS software file*] ドロップダウンから、ローカルマシンにダウンロードした OS ファイルを選択します。
+
使用可能なファイルが複数ある場合は、日付が新しい順にファイルがソートされます。

+
[NOTE]
====
ソフトウェアリポジトリには、Web Services Proxyに関連付けられているすべてのソフトウェアファイルが表示されます。使用するファイルが表示されない場合は、リンク * ソフトウェアリポジトリに新しいファイルを追加 * をクリックして、追加する OS ファイルが保存されている場所を参照します。

====
.. Select an NVSRAM file * ドロップダウンから、使用するコントローラファイルを選択します。
+
ファイルが複数ある場合は、日付が新しい順にファイルがソートされます。



. [互換性があるストレージアレイ]の表で、選択したOSソフトウェアファイルと互換性があるストレージアレイを確認し、アップグレードするアレイを選択します。
+
** [互換性があるストレージアレイ]の表では、[管理]ビューで選択したストレージアレイのうち、選択したファームウェアファイルと互換性があるストレージアレイがデフォルトで選択されます。
** 選択したファームウェアファイルで更新できないストレージアレイは、ステータス * incompatible * と表示される互換性があるストレージアレイテーブルで選択できません。


. *オプション：*ソフトウェアファイルをアクティブ化せずにストレージアレイに転送するには、* OSソフトウェアをストレージアレイに転送し、ステージング済みとしてマークし、後でアクティブ化*チェックボックスをオンにします。
. [ スタート ] ボタンをクリックします。
. すぐにアクティブ化するかあとでアクティブ化するかに応じて、次のいずれかを実行します。
+
** 「 * transfer * 」と入力して、アップグレード対象として選択したアレイの OS ソフトウェアのバージョンを転送することを確認し、「 * Transfer * 」をクリックします。
+
転送されたソフトウェアをアクティブにするには、メニューから [Upgrade Center] [Activate Staged OS Software] を選択します。

** アップグレード対象として選択したアレイ上の OS ソフトウェアのバージョンを転送してアクティブ化することを確認するには、 * upgrade * と入力し、 * Upgrade * をクリックします。
+
アップグレード対象として選択した各ストレージアレイにソフトウェアファイルが転送され、リブートが開始されてファイルがアクティブ化されます。



+
アップグレード処理では、次の処理が実行されます。

+
** アップグレード前の健常性チェックは、アップグレードプロセスの一環として実行されます。アップグレード前の健常性チェックでは、ストレージアレイのすべてのコンポーネントについて、アップグレードを実行できるかどうかがチェックされます。
** ストレージアレイの健全性チェックに失敗すると、アップグレードは停止します。省略符号 (...) をクリックして * ログを保存 * を選択すると、エラーを確認できます。ヘルスチェックエラーを無視するように選択し、 * Continue * をクリックしてアップグレードを続行することもできます。
** アップグレード前の健常性チェックのあとに、アップグレード処理をキャンセルできます。


. *オプション：*アップグレードが完了したら、省略記号（...）をクリックし、*ログの保存*を選択すると、特定のストレージ・アレイのアップグレード内容のリストが表示されます。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `upgrade_log-<date>.json`。


