---
permalink: um-manage/upgrade-considerations.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, considerations 
summary: Unified Managerを使用して複数のストレージアレイをアップグレードする前に、計画の一環として重要な考慮事項を確認しておいてください。 
---
= アップグレード時の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを使用して複数のストレージアレイをアップグレードする前に、計画の一環として重要な考慮事項を確認しておいてください。



== 現在のバージョン

検出された各ストレージアレイについて、Unified Managerの管理ページからSANtricity OSの現在のソフトウェアバージョンを表示できます。バージョンは、SANtricity OSソフトウェアの列に表示されます。各行の SANtricity OS のバージョンをクリックするとポップアップダイアログボックスが表示され、コントローラのファームウェアと NVSRAM の情報を確認できます。



== アップグレードが必要なその他のコンポーネント

アップグレードプロセスの一環として、ホストがコントローラと正しく連携できるように、ホストのマルチパス/フェイルオーバードライバまたはHBAドライバのアップグレードも必要になる場合があります。

互換性については、を参照して https://imt.netapp.com/matrix/#welcome["NetAppのInteroperability Matrix"^]ください。手順については、使用しているオペレーティングシステムに対応したエクスプレスガイドを参照してください。エクスプレスガイドはから入手でき https://docs.netapp.com/us-en/e-series/index.html["E シリーズおよび SANtricity に関するドキュメント"^]ます。



== デュアルコントローラ

ストレージアレイにコントローラが2台あり、マルチパスドライバがインストールされている場合は、アップグレードの実行中もストレージアレイでI/Oの処理を続行できます。アップグレード中に、次のプロセスが実行されます。

. コントローラAのすべてのLUNがコントローラBにフェイルオーバーされます。
. コントローラAでアップグレードが実行されます。
. コントローラAが自身のLUNとコントローラBのすべてのLUNをテイクバックします。
. コントローラBでアップグレードが実行されます。


アップグレードの完了後、所有権のある正しいコントローラにボリュームが配置されるように、コントローラ間で手動でのボリュームの再配置が必要になることがあります。
