---
permalink: sm-settings/access-management-with-directory-services.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, directory services, 
summary: 管理者は、LDAP（Lightweight Directory Access Protocol）サーバとディレクトリサービス（MicrosoftのActive Directoryなど）をアクセス管理に使用できます。 
---
= ディレクトリサービスを使用したアクセス管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理者は、Lightweight Directory Access Protocol（LDAP）サーバとディレクトリサービス（MicrosoftのActive Directoryなど）をアクセス管理に使用できます。



== 設定ワークフロー

ネットワークでLDAPサーバとディレクトリサービスが使用されている場合、設定は次のように機能します。

. Security Adminの権限を含むユーザプロファイルでSystem Managerにログインします。
+
[NOTE]
====
 `admin`ユーザには、システム内のすべての機能へのフルアクセス権が付与されます。

====
. LDAPサーバの設定を入力します。設定には、ドメイン名、URL、バインドアカウント情報が含まれます。
. LDAPサーバでセキュアなプロトコル（LDAPS）を使用している場合は、LDAPサーバとストレージアレイの間の認証に使用する認証局（CA）証明書チェーンをアップロードします。
. サーバ接続が確立されると、ユーザグループをストレージアレイのロールにマッピングします。これらのロールは事前定義されており、変更することはできません。
. LDAPサーバとストレージアレイの間の接続をテストします。
. ユーザは、自分に割り当てられたLDAP /ディレクトリサービスのクレデンシャルを使用してシステムにログインします。




== 管理

認証にディレクトリサービスを使用する場合、管理者は次の管理タスクを実行できます。

* ディレクトリサーバを追加します。
* ディレクトリサーバの設定を編集します。
* LDAPユーザをローカルユーザロールにマッピングします。
* ディレクトリサーバを削除します。

