---
permalink: sm-settings/access-management-tokens-create.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, create tokens 
summary: ユーザ名とパスワードの代わりに、REST APIまたはコマンドラインインターフェイスでの認証に使用するアクセストークンを作成できます。 
---
= アクセストークンの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザ名とパスワードの代わりにREST APIまたはコマンドラインインターフェイス（CLI）で認証するアクセストークンを作成できます。


NOTE: トークンにはパスワードがないため、慎重に管理する必要があります。

.手順
. メニューを選択します。Settings [Access Management]。
. ［* Access Tokens *］タブを選択します。
. [アクセストークン設定の表示/編集]を選択します。ダイアログボックスで、*アクセストークンを有効にする*チェックボックスが選択されていることを確認します。[保存（Save）]をクリックして、ダイアログボックスを閉じます。
. [アクセストークンの作成*]を選択します。
. ダイアログボックスで、トークンの有効期間を選択します。
+

NOTE: トークンの有効期限が切れると、ユーザーの認証は失敗します。

. [* 作成 .*] をクリックします
. ダイアログボックスで、次のいずれかを選択します。
+
** *コピー*をクリックしてトークンテキストをクリップボードに保存します。
** *ダウンロード*：トークンテキストをファイルに保存します。
+

NOTE: トークンテキストは必ず保存してください。これは、ダイアログを閉じる前にテキストを表示する唯一の機会です。



. [* 閉じる * ] をクリックします。
. トークンは次のように使用します。
+
** * REST API *：REST API要求でトークンを使用するには、要求にHTTPヘッダーを追加します。例：
`Authorization: Bearer _<access-token-value>_`
** * Secure CLI *：CLIでトークンを使用するには、コマンドラインでトークン値を追加するか、トークン値を含むファイルへのパスを使用します。例：
+
*** コマンドラインのトークン値： `-t _access-token-value_`
*** トークン値を含むファイルへのパス： `-T _access-token-file_`
+

NOTE: ユーザ名、パスワード、またはトークンが指定されていない場合、CLIはコマンドラインでアクセストークン値の入力をユーザに要求します。






