---
permalink: sm-settings/automatic-load-balancing-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, load, balancing, 
summary: 自動ロードバランシングでは、時間の経過に伴う負荷の変化に動的に対応し、ボリュームのコントローラ所有権が自動的に調整されて、コントローラ間でワークロードが移動する際の負荷の不均衡が解消されるため、I/Oリソースの管理が強化されます。 
---
= 自動ロードバランシングの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動ロードバランシングでは、時間の経過に伴う負荷の変化に動的に対応し、ボリュームのコントローラ所有権が自動的に調整されて、コントローラ間でワークロードが移動する際の負荷の不均衡が解消されるため、I/Oリソースの管理が強化されます。

各コントローラのワークロードは継続的に監視され、ホストにインストールされたマルチパスドライバとの連携により、必要に応じて自動的に負荷を分散できます。コントローラ間でワークロードが自動的にリバランシングされるため、ストレージアレイの負荷の変化に合わせてボリュームのコントローラ所有権を手動で調整する負担が軽減されます。

自動ロードバランシングを有効にすると、次の機能が実行されます。

* コントローラのリソース使用率を自動的に監視してバランスを調整します。
* ボリュームのコントローラ所有権が必要に応じて自動的に調整され、ホストとストレージアレイの間のI/O帯域幅が最適化されます。




== 自動ロードバランシングの有効化と無効化

自動ロードバランシングは、すべてのストレージアレイでデフォルトで有効になっています。

自動ロードバランシングは、次のような理由でストレージアレイで無効にすることができます。

* 特定のボリュームのコントローラ所有権を自動的に変更してワークロードを分散させたくない場合
* 高度に調整された環境で、コントローラ間の負荷分散が特定の要件を満たすように意図的に設定されている。




== 自動ロードバランシング機能をサポートするホストタイプ

自動ロードバランシングはストレージアレイレベルで有効になっていますが、ホストまたはホストクラスタに対して選択するホストタイプは機能の動作に直接影響します。

ストレージアレイのワークロードをコントローラ間で分散する場合、自動ロードバランシング機能は、両方のコントローラからアクセス可能で、自動ロードバランシング機能に対応したホストまたはホストクラスタにのみマッピングされたボリュームの移動を試みます。

これにより、ロードバランシングプロセスが原因でホストがボリュームにアクセスできなくなるのを防ぐことができます。ただし、自動ロードバランシングをサポートしていないホストにマッピングされたボリュームがあると、ストレージアレイのワークロードを分散できなくなります。自動ロードバランシングでワークロードを分散するには、マルチパスドライバがTPGSをサポートし、ホストタイプが次の表に含まれている必要があります。

[NOTE]
====
ホストクラスタが自動ロードバランシングに対応しているとみなされるには、そのグループ内のすべてのホストが自動ロードバランシングをサポートしている必要があります。

====
[cols="1a,1a"]
|===
| 自動ロードバランシングをサポートするホストタイプ | マルチパスドライバ 


 a| 
WindowsまたはWindowsクラスタ
 a| 
MPIOとNetApp EシリーズDSM



 a| 
Linux DM-MP（カーネル3.10以降）
 a| 
DM-MPと `scsi_dh_alua`デバイスハンドラ



 a| 
VMware
 a| 
Native Multipathing Plugin（NMP）と `VMW_SATP_ALUA Storage Array Type`プラグイン

|===
[NOTE]
====
一部の例外を除き、自動ロードバランシング機能が有効になっているかどうかに関係なく、自動ロードバランシングをサポートしないホストタイプは引き続き正常に動作します。例外の1つは、システムでフェイルオーバーが発生した場合、データパスが戻った時点で、マッピングされていないボリュームまたは割り当てられていないボリュームがストレージアレイによって所有権を持つコントローラに戻されます。自動ロードバランシング以外のホストにマッピングまたは割り当てられているボリュームは移動されません。

====
特定のマルチパスドライバ、OSレベル、およびコントローラドライブトレイのサポートに関する互換性情報については、を参照してください https://mysupport.netapp.com/matrix["Interoperability Matrix Tool"^]。



== 自動ロードバランシング機能とOSの互換性の確認

新しいシステムをセットアップ（または既存のシステムを移行）する前に、自動ロードバランシング機能とOSの互換性を確認してください。

. にアクセスし https://mysupport.netapp.com/matrix["Interoperability Matrix Tool"^]てソリューションを検索し、サポートを確認します。
+
システムでRed Hat Enterprise Linux 6またはSUSE Linux Enterprise Server 11を実行している場合は、テクニカルサポートにお問い合わせください。

. を更新して設定し `/etc/multipath.conf file`ます。
. 該当するベンダーと製品に対してとの `detect_prio`両方がに設定されている `yes`ことを確認する `retain_attached_device_handler`か、デフォルト設定を使用します。

