---
permalink: sm-settings/back-up-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, backup, security, key, 
summary: セキュリティキーを作成または変更したら、元のキーファイルが破損した場合に備えて、キーファイルのバックアップコピーを作成できます。 
---
= セキュリティキーのバックアップ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティキーを作成または変更したら、元のキーファイルが破損した場合に備えて、キーファイルのバックアップコピーを作成できます。

.タスクの内容
このタスクでは、以前に作成したセキュリティキーをバックアップする方法について説明します。この手順では、バックアップ用の新しいパスフレーズを作成します。このパスフレーズは、元のキーの作成時または最後の変更時に使用されたパスフレーズと一致する必要はありません。このパスフレーズは、作成するバックアップにのみ適用されます。

.手順
. メニューを選択します。[設定][システム]。
. セキュリティキー管理*で、*バックアップキー*を選択します。
+
[セキュリティキーのバックアップ]ダイアログボックスが開きます。

. [*パスフレーズを定義/パスフレーズを再入力*]フィールドに、このバックアップのパスフレーズを入力して確認します。
+
値は8~32文字で、次の文字をそれぞれ含める必要があります。

+
** 大文字（1文字以上）
** 数字（1文字以上）
** 英数字以外の文字（！、*、@など）（1文字以上）


+
[CAUTION]
====
*後で使用するためには、必ず入力を記録してください*。このセキュリティキーのバックアップにアクセスするには、パスフレーズが必要です。

====
. [バックアップ]をクリックします。
+
セキュリティキーのバックアップがローカルホストにダウンロードされ、[*Confirm/Record Security Key Backup*]ダイアログボックスが開きます。

+
[NOTE]
====
ダウンロードしたセキュリティキーファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。

====
. パスフレーズを安全な場所に記録し、*閉じる*をクリックします。


.終了後
バックアップセキュリティキーを検証する必要があります。
