---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: アクセス管理で各ユーザプロファイルのユーザパスワードを変更できます。 
---
= パスワードの変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセス管理で各ユーザプロファイルのユーザパスワードを変更できます。

.開始する前に
* Root Adminの権限が割り当てられたローカル管理者としてログインする必要があります。
* ローカル管理者のパスワードを確認しておく必要があります。


.タスクの内容
パスワードを選択する際は、次のガイドラインに注意してください。

* 新しいローカルユーザパスワードは、最小パスワードの現在の設定（[設定の表示/編集]）以上にする必要があります。
* パスワードは大文字と小文字が区別されます。
* パスワードの末尾のスペースは削除されません。パスワードにスペースが含まれている場合は、スペースを含めるように注意してください。
* セキュリティを強化するために、15文字以上の英数字を使用し、パスワードを頻繁に変更してください。


[NOTE]
====
System Managerでパスワードを変更すると、コマンドラインインターフェイス（CLI）のパスワードも変更されます。また、パスワードを変更すると、ユーザーのアクティブなセッションが終了します。

====
.手順
. メニューを選択します。Settings [Access Management]。
. [ローカルユーザー役割*（Local User Roles *）]タブを選択します。
. 表からユーザを選択します。
+
[パスワードの変更]ボタンが使用可能になります。

. [ パスワードの変更 *] を選択します。
+
[パスワードの変更]ダイアログボックスが開きます。

. ローカルユーザパスワードの最小文字数が設定されていない場合は、選択したユーザがストレージアレイにアクセスする際にパスワードの入力を必須にするチェックボックスをオンにして、選択したユーザの新しいパスワードを入力できます。
. ローカル管理者パスワードを入力し、* Change *をクリックします。


.結果
ユーザが現在ログインしている場合、パスワードを変更するとユーザのアクティブなセッションが終了します。
