---
permalink: sm-settings/change-default-host-type.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, default, host, type, 
summary: 'ストレージアレイレベルでデフォルトのホストタイプを変更するには、[デフォルトのホストオペレーティングシステムの変更]設定を使用します。通常、デフォルトのホストタイプは、ホストをストレージアレイに接続する前、または追加のホストを接続するときに変更します。' 
---
= デフォルトのホストタイプの変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイレベルでデフォルトのホストタイプを変更するには、[デフォルトのホストオペレーティングシステムの変更]設定を使用します。通常、デフォルトのホストタイプは、ホストをストレージアレイに接続する前、または追加のホストを接続するときに変更します。

.タスクの内容
次のガイドラインに注意してください。

* ストレージアレイに接続するすべてのホストのオペレーティングシステムが同じ場合（同種のホスト環境）は、オペレーティングシステムに合わせてホストタイプを変更します。
* ストレージアレイに接続するホストに異なるオペレーティングシステムのホストが混在している場合は（異機種ホスト環境）、ホストのオペレーティングシステムの大部分に一致するホストタイプに変更します。
+
たとえば、8つの異なるホストをストレージアレイに接続し、そのうち6つでWindowsオペレーティングシステムを実行している場合は、Windowsをデフォルトのホストオペレーティングシステムタイプとして選択する必要があります。

* 接続されているホストの大部分でオペレーティングシステムが異なる場合は、ホストタイプを[工場出荷時のデフォルト]に変更します。
+
たとえば、8つの異なるホストをストレージアレイに接続し、そのうち2つでWindowsオペレーティングシステムを実行している場合、3つでVMwareオペレーティングシステムを実行しています。 さらに、別の3つのOSでLinuxオペレーティングシステムを実行している場合は、デフォルトのホストオペレーティングシステムタイプとしてFactory Defaultを選択する必要があります。



.手順
. メニューを選択します。[設定][システム]。
. 下にスクロールして「その他の設定」を選択し、「デフォルトのホストOSタイプの変更」をクリックします。
. デフォルトとして使用するホストオペレーティングシステムタイプを選択します。
. [ 変更（ Change ） ] をクリックします。

