---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: ストレージアレイ上のすべての新規または更新されるローカルユーザパスワードに必要な最小文字数を設定できます。また、ローカルユーザにパスワードを入力せずにストレージアレイへのアクセスを許可することもできます。 
---
= ローカルユーザのパスワード設定の変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ上のすべての新規または更新されるローカルユーザパスワードに必要な最小文字数を設定できます。また、ローカルユーザにパスワードを入力せずにストレージアレイへのアクセスを許可することもできます。

.開始する前に
Root Adminの権限が割り当てられたローカル管理者としてログインする必要があります。

.タスクの内容
ローカルユーザパスワードの最小文字数を設定する際は、次のガイドラインに注意してください。

* 設定を変更しても、既存のローカルユーザパスワードには影響しません。
* ローカルユーザパスワードの最小文字数は0~30文字に設定する必要があります。
* 新しいローカルユーザパスワードは、現在の最小文字数の設定以上にする必要があります。
* ローカルユーザがパスワードを入力せずにストレージアレイにアクセスできるようにする場合は、パスワードの最小文字数を設定しないでください。


.手順
. メニューを選択します。Settings [Access Management]。
. [ローカルユーザー役割*（Local User Roles *）]タブを選択します。
. 「*表示/設定の編集*」ボタンを選択します。
+
[ローカルユーザーパスワードの設定]ダイアログボックスが開きます。

. 次のいずれかを実行します。
+
** ローカルユーザがパスワードを入力せずにストレージアレイにアクセスできるようにするには、「すべてのローカルユーザパスワードを少なくとも必要とする」チェックボックスをオフにします。
** すべてのローカルユーザパスワードに対してパスワードの最小文字数を設定するには、[Require all local user passwords to be at least]チェックボックスをオンにし、スピンボックスですべてのローカルユーザパスワードの最小文字数を設定します。
+
新しいローカルユーザパスワードは現在の設定以上にする必要があります。



. [ 保存（ Save ） ] をクリックします。

