---
permalink: sm-settings/clear-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, storage, array, configuration, 
summary: ストレージアレイからすべてのプール、ボリュームグループ、ボリューム、ホスト定義、およびホスト割り当てを削除する場合は、構成のクリア処理を使用します。 
---
= ストレージアレイ構成のクリア
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイからすべてのプール、ボリュームグループ、ボリューム、ホスト定義、およびホスト割り当てを削除する場合は、構成のクリア処理を使用します。

.開始する前に
ストレージアレイ構成をクリアする前に、データをバックアップしてください。

.タスクの内容
ストレージアレイ構成のクリアには2つのオプションがあります。

* *ボリューム*--通常、テスト用ストレージアレイを本番ストレージアレイとして再構成するために、ボリュームオプションを使用します。たとえば、テスト用にストレージアレイを構成し、テストが完了したらテスト構成を削除して、本番環境用にストレージアレイをセットアップすることができます。
* *ストレージ・アレイ*--通常'ストレージ・アレイを別の部門またはグループに移動するには'ストレージ・アレイ・オプションを使用しますたとえば、エンジニアリング部門でストレージアレイを使用していて、エンジニアリング部門が新しいストレージアレイを入手したために、現在のストレージアレイを再設定する管理部門に移動するとします。
+
[ストレージアレイ]オプションでは、いくつかの追加設定が削除されます。



[cols="1a,1a,1a"]
|===
|  | ボリューム | ストレージアレイ 


 a| 
ARVMを非アクティブ化
 a| 
X
 a| 
X



 a| 
プールとボリュームグループを削除
 a| 
X
 a| 
X



 a| 
ボリュームを削除
 a| 
X
 a| 
X



 a| 
ホストとホストクラスタを削除
 a| 
X
 a| 
X



 a| 
ホスト割り当てを削除
 a| 
X
 a| 
X



 a| 
ストレージアレイ名を削除
 a| 
 a| 
X



 a| 
ストレージアレイのキャッシュ設定をデフォルトにリセット
 a| 
 a| 
X

|===
[CAUTION]
====
*データ損失のリスク*-この処理を実行すると、ストレージアレイからすべてのデータが削除されます。（完全消去は実行されません）。この処理は開始後にキャンセルすることはできません。この処理は、テクニカルサポートから指示があった場合にのみ実行してください。

====
.手順
. メニューを選択します。[設定][システム]。
. 「ストレージアレイ構成のクリア」を選択します。
. ドロップダウンリストで、* Volume *または* Storage Array *のいずれかを選択します。
. *オプション：*（データではなく）設定を保存する場合は、ダイアログボックス内のリンクを使用します。
. 処理を確定します。


.結果
* 現在の構成が削除され、ストレージアレイ上の既存のデータがすべて削除されます。
* すべてのドライブの割り当てが解除されます。

