---
permalink: sm-settings/configure-iscsi-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iSCSI, ports, systems 
summary: 'コントローラにiSCSIホスト接続が搭載されている場合は、[システム]ページからiSCSIポートを設定できます。' 
---
= iSCSIポートの設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラにiSCSIホスト接続が搭載されている場合は、[システム]ページからiSCSIポートを設定できます。

.開始する前に
* コントローラにiSCSIポートが搭載されている必要があります。そうでない場合、iSCSI設定は使用できません。
* ネットワーク速度（ポートとホストの間のデータ転送率）を把握しておく必要があります。


[NOTE]
====
iSCSIの設定と機能は、ストレージアレイがiSCSIをサポートしている場合にのみ表示されます。

====
.手順
. メニューを選択します。[設定][システム]。
. [* iSCSI設定*]で、[* iSCSIポートの設定*]を選択します。
+
[NOTE]
====
Configure iSCSI ports（iSCSIポートの設定）オプションは、System ManagerがコントローラでiSCSIポートを検出した場合にのみ表示されます。

====
. iSCSIポートを設定するコントローラを選択します。
. ドロップダウンリストで、設定するポートを選択し、 * Next * をクリックします。
. 構成ポートの設定を選択し、 * 次へ * をクリックします。
+
すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more port settings * リンクをクリックします。

+
.フィールドの詳細
[%collapsible]
====
[cols="1a,1a"]
|===
| ポート設定 | 製品説明 


 a| 
設定されているイーサネットポート速度（特定のタイプのホストインターフェイスカードでのみ表示されます）
 a| 
ポートのSFPの速度と同じ速度を選択します。



 a| 
Forward Error Correction（FEC）モード（特定のタイプのホストインターフェイスカードでのみ表示されます）
 a| 
必要に応じて、指定したホストポートのいずれかのFECモードを選択します。


NOTE: Reed Solomonモードでは、25Gbpsのポート速度はサポートされません。



 a| 
IPv4を有効にする/ IPv6を有効にする
 a| 
IPv4およびIPv6ネットワークのサポートを有効にするには、一方または両方のオプションを選択します。


NOTE: ポートアクセスをディセーブルにする場合は、両方のチェックボックスをオフにします。



 a| 
TCP リスニングポート（ [Show more port settings] をクリックすると使用可能）
 a| 
必要に応じて、新しいポート番号を入力します。

リスニングポートは、コントローラがホストiSCSIイニシエータからのiSCSIログインをリスンするために使用するTCPポート番号です。デフォルトのリスニングポートは3260です。3260または49152~65535の値を入力する必要があります。



 a| 
MTU サイズ（ * Show more port settings* をクリックすると使用可能）
 a| 
必要に応じて、Maximum Transmission Unit（MTU；最大転送単位）の新しいサイズをバイト単位で入力します。

デフォルトのMaximum Transmission Unit（MTU；最大伝送ユニット）サイズは1500バイト/フレームです。1500 ~ 9000の値を入力する必要があります。



 a| 
ICMP PING応答をイネーブルにする
 a| 
Internet Control Message Protocol（ICMP）を有効にするには、このオプションを選択します。ネットワーク接続されたコンピュータのオペレーティングシステムは、このプロトコルを使用してメッセージを送信します。これらのICMPメッセージは、ホストに到達できるかどうか、およびそのホストとのパケットの送受信にかかる時間を決定します。

|===
====
+
[*IPv4 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv4 設定を選択するためのダイアログボックスが開きます。[*IPv6 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv6 設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、 IPv4 設定のダイアログボックスが最初に開き、 * 次へ * をクリックすると、 IPv6 設定のダイアログボックスが開きます。

. IPv4 / IPv6を自動または手動で設定します。すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more settings * リンクをクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="1a,1a"]
|===
| ポート設定 | 製品説明 


 a| 
設定を自動的に取得
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的設定を手動で指定する
 a| 
このオプションを選択し、フィールドに静的アドレスを入力します。（必要に応じて、カット アンド ペーストでアドレスをフィールドに貼り付けることもできます）。IPv4の場合は、ネットワークのサブネットマスクとゲートウェイを指定します。IPv6の場合は、ルーティング可能なIPアドレスとルータのIPアドレスを指定します。



 a| 
VLAN サポートを有効にします（ * Show more settings * をクリックして使用可能）。
 a| 
VLANを有効にしてそのIDを入力するには、このオプションを選択します。VLANは、同じスイッチ、同じルータ、またはその両方でサポートされる他の物理LANや仮想LANから物理的に分離されているかのように動作する論理ネットワークです。



 a| 
イーサネットの優先順位を有効にする（ [ 詳細設定を表示する *] をクリックして使用可能）。
 a| 
ネットワークアクセスの優先度を決定するパラメータを有効にするには、このオプションを選択します。スライダを使用して優先度を1（最も低い）から7（最も高い）の間で選択します。

イーサネットなどの共有ローカルエリアネットワーク（LAN）環境では、多くのステーションがネットワークへのアクセスを争う場合があります。アクセスは先に行われたものから順に処理されます。2つのステーションが同時にネットワークにアクセスしようとすると、両方のステーションがオフになり、再試行する前に待機します。このプロセスは、スイッチポートに1つのステーションだけが接続されているスイッチドイーサネットでは最小限に抑えられます。

|===
====
. [ 完了 ] をクリックします。

