---
permalink: sm-settings/configure-snmp-mib-variables.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, mib, variables, 
summary: SNMPアラートの場合、必要に応じて、SNMPトラップに表示される管理情報ベース（MIB）変数を設定できます。これらの変数は、ストレージアレイ名、アレイの場所、および担当者を返すことができます。 
---
= SNMP MIB変数の設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMPアラートの場合、必要に応じて、SNMPトラップに表示される管理情報ベース（MIB）変数を設定できます。これらの変数は、ストレージアレイ名、アレイの場所、および担当者を返すことができます。

.開始する前に
MIBファイルは、SNMPサービスアプリケーションがインストールされたサーバにコピーしてコンパイルする必要があります。

MIBファイルがない場合は、次の方法で入手できます。

* に進みます https://mysupport.netapp.com/site/global/dashboard["NetAppのサポート"^]。
* [* Downloads（ダウンロード）]をクリックし、[* Downloads（ダウンロード）]を選択します。
* EシリーズSANtricity OSコントローラソフトウェア*をクリックします。
* [最新リリースのダウンロード]を選択します。
* ログインします。
* 注意事項と使用許諾契約書に同意します。
* コントローラタイプのMIBファイルが表示されるまで下にスクロールし、リンクをクリックしてファイルをダウンロードします。


.タスクの内容
このタスクでは、SNMPトラップのMIB変数を定義する方法について説明します。これらの変数は、SNMP GetRequestsへの応答として次の値を返すことができます。

* `sysName`（ストレージアレイの名前）
* `sysLocation`（ストレージアレイの場所）
* `sysContact`（管理者の名前）


.手順
. メニューを選択します。Settings [Alerts]（設定[Alerts]）。
. SNMP *タブを選択します。
. [Configure SNMP MIB Variables]を選択します。
+
SNMP MIB変数の設定ダイアログボックスが開きます。

. 次の値を1つ以上入力し、*保存*をクリックします。
+
** *Name*-- MIB変数の値 `sysName`。たとえば、ストレージアレイの名前を入力します。
** *Location*-- MIB変数の値 `sysLocation`。たとえば、ストレージアレイの場所を入力します。
** *Contact*-- MIB変数の値 `sysContact`。たとえば、ストレージアレイを担当する管理者を入力します。




.結果
これらの値は、ストレージアレイのアラートのSNMPトラップメッセージに表示されます。
