---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: ドライブセキュリティ機能を使用するには、ストレージアレイのコントローラとセキュリティ対応ドライブで共有される内部セキュリティキーを作成します。内部キーは、コントローラの永続的メモリに保持されます。 
---
= 内部セキュリティキーの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブセキュリティ機能を使用するには、ストレージアレイのコントローラとセキュリティ対応ドライブで共有される内部セキュリティキーを作成します。内部キーは、コントローラの永続的メモリに保持されます。

.開始する前に
* ストレージアレイにセキュリティ対応ドライブが搭載されている必要があります。対応するドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。
* ドライブセキュリティ機能が有効になっている必要があります。そうしないと、このタスクの実行中に[セキュリティキーを作成できません]ダイアログボックスが開きます。ドライブセキュリティ機能を有効にする手順については、必要に応じてストレージベンダーにお問い合わせください。


[NOTE]
====
ストレージアレイにFDEドライブとFIPSドライブの両方が搭載されている場合は、すべてのドライブで同じセキュリティキーが共有されます。

====
.タスクの内容
このタスクでは、内部セキュリティキーに関連付ける識別子とパスフレーズを定義します。

[NOTE]
====
ドライブセキュリティのパスフレーズは、ストレージアレイの管理者パスワードとは別のものです。

====
.手順
. メニューを選択します。[設定][システム]。
. セキュリティキー管理*で、*内部キーの作成*を選択します。
+
まだセキュリティキーを生成していない場合は、セキュリティキーの作成ダイアログボックスが開きます。

. 次のフィールドに情報を入力します。
+
** *セキュリティキー識別子を定義*--デフォルト値(コントローラファームウェアによって生成されたストレージアレイ名とタイムスタンプ)をそのまま使用するか'独自の値を入力することができます入力できる文字数は最大189文字です。使用できるのは英数字のみで、スペース、句読点、記号は使用できません。
+
[NOTE]
====
入力した文字列の前後に追加の文字が自動的に生成されて付加されます。文字が追加されることで識別子が一意であることが保証されます。

====
** *パスフレーズを定義/パスフレーズを再入力*--パスフレーズを入力して確認します値は8~32文字で、次の文字をそれぞれ含める必要があります。
+
*** 大文字のアルファベット（1文字以上）。パスフレーズでは大文字と小文字が区別されることに注意してください。
*** 数字（1文字以上）。
*** !、*、@などの英数字以外の文字（1文字以上）。




+
[CAUTION]
====
*後で使用するために、必ず入力を記録しておいてください*。セキュリティ有効ドライブをストレージアレイから移動する必要がある場合は、ドライブデータのロックを解除するために識別子とパスフレーズが必要です。

====
. [ 作成（ Create ） ] をクリックします。
+
セキュリティキーは、コントローラのアクセスできない場所に格納されています。実際のキーと一緒に、ブラウザからダウンロードされる暗号化されたキーファイルがあります。

+
[NOTE]
====
ダウンロードしたファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。

====
. キー識別子、パスフレーズ、ダウンロードしたキーファイルの場所を記録し、*閉じる*をクリックします。


.結果
これで、セキュリティ有効のボリュームグループまたはプールを作成したり、既存のボリュームグループおよびプールでセキュリティを有効にしたりできます。

[NOTE]
====
ドライブの電源をオフにして再度オンにすると、すべてのセキュリティ有効ドライブがセキュリティロック状態に変わります。この状態のデータには、ドライブの初期化時にコントローラが正しいセキュリティキーを適用するまでアクセスできません。第三者がロックされたドライブを物理的に取り外して別のシステムに取り付けた場合でも、データへの不正アクセスを防止することができます。

====
.終了後
セキュリティキーを検証して、キーファイルが破損していないことを確認する必要があります。
