---
permalink: sm-settings/drive-security-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, security, terms, 
summary: ストレージアレイに関連するドライブセキュリティの用語を次に示します。 
---
= ドライブセキュリティの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するドライブセキュリティの用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 製品説明 


 a| 
ドライブセキュリティ機能
 a| 
ドライブセキュリティは、 Full Disk Encryption （ FDE ）ドライブまたは連邦情報処理標準（ FIPS ）ドライブを使用してセキュリティを強化するストレージアレイの機能です。これらのドライブをドライブセキュリティ機能と組み合わせて使用すると、データにアクセスするためのセキュリティキーが必要になります。ドライブをアレイから物理的に取り外した場合、別のアレイに取り付けるまでドライブは動作しません。別のアレイに取り付けると、正しいセキュリティキーを指定するまでセキュリティロック状態になります。



 a| 
FDEトライフ
 a| 
Full Disk Encryption（FDE）ドライブは、ハードウェアレベルでディスクドライブの暗号化を実行します。ハードドライブには、書き込み時にデータを暗号化し、読み取り時に復号化するASICチップが搭載されています。



 a| 
FIPSトライフ
 a| 
FIPSドライブは、連邦情報処理標準（FIPS）140-2レベル2に準拠しています。基本的な概念はFDEドライブと同じですが、米国政府の基準に従って強力な暗号化アルゴリズムと暗号化方式を実装しています。FIPSドライブにはFDEドライブよりも高度なセキュリティ基準が採用されています。



 a| 
管理クライアント
 a| 
System Managerにアクセスするためのブラウザを含むローカルシステム（コンピュータやタブレットなど）。



 a| 
パスフレーズ
 a| 
パスフレーズは、バックアップ用にセキュリティキーを暗号化するために使用します。ドライブの移行またはヘッドの交換によってバックアップされたセキュリティキーをインポートする場合は、セキュリティキーの暗号化に使用したパスフレーズを指定する必要があります。パスフレーズは8~32文字で指定できます。

[NOTE]
====
ドライブセキュリティのパスフレーズは、ストレージアレイの管理者パスワードとは別のものです。

====


 a| 
セキュリティ対応ドライブ
 a| 
セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。これらのドライブでは、書き込み時にデータが暗号化され、読み取り時に復号化されます。ドライブセキュリティ機能を使用したセキュリティの強化に使用できるため、これらのドライブはsecured_capable_とみなされます。これらのドライブを使用するボリュームグループやプールでドライブセキュリティ機能を有効にすると、ドライブはsecure-_enabled_になります。



 a| 
セキュリティ有効ドライブ
 a| 
セキュリティ有効ドライブは、ドライブセキュリティ機能で使用されます。ドライブセキュリティ機能を有効にし、かつsecured_caped_drivesのプールまたはボリュームグループにドライブセキュリティを適用すると、ドライブはsecure__enable__になります。読み取り/書き込みアクセスは、正しいセキュリティキーが設定されたコントローラからのみ実行できます。この追加のセキュリティ機能により、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。



 a| 
セキュリティキー
 a| 
セキュリティキーは、ストレージアレイのセキュリティ有効ドライブとコントローラで共有される文字列です。ドライブの電源をオフにしてオンにするたびに、コントローラがセキュリティキーを適用するまでセキュリティ有効ドライブはセキュリティロック状態になります。セキュリティ有効ドライブをストレージアレイから取り外すと、ドライブのデータはロックされます。ドライブを別のストレージアレイに取り付け直すと、データへのアクセスを再開する前にセキュリティキーが検索されます。データのロックを解除するには、元のセキュリティキーを適用する必要があります。セキュリティキーは、次のいずれかの方法で作成および管理できます。

* 内部キー管理--セキュリティキーをコントローラの永続的メモリに作成して保持します。
* 外部キー管理--セキュリティキーを外部キー管理サーバに作成して保管します。




 a| 
セキュリティキー識別子
 a| 
セキュリティキー識別子は、キーの作成時にセキュリティキーに関連付けられる文字列です。識別子は、コントローラとセキュリティキーに関連付けられたすべてのドライブに格納されます。

|===