---
permalink: sm-settings/enable-or-disable-resource-provisioning-for-new-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, resource, provisioning, 
summary: 以前にリソースプロビジョニングのデフォルト機能を無効にしていた場合は、設定に移動して、作成した新しいSSDボリュームグループまたはプールに対して再度有効にすることができます。設定を再度無効にすることもできます。 
---
= 新しいボリュームグループまたはプールのリソースプロビジョニングを有効または無効にする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースプロビジョニングのデフォルト機能を無効にしていた場合は、作成する新しいSSDボリュームグループまたはプールに対して再度有効にすることができます。設定を再度無効にすることもできます。

リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。ボリュームに割り当てられているドライブブロックはすべて割り当て解除（マッピング解除）されるため、SSDの摩耗度が向上し、最大書き込みパフォーマンスが向上します。


NOTE: デフォルトでは、ドライブがDULBEをサポートするシステムでリソースプロビジョニングが有効になっています。

.開始する前に
* EF300またはEF600ストレージアレイが必要です。
* NVMeのDeallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能がすべてのドライブでサポートされているSSDボリュームグループまたはプールが必要です。


.タスクの内容
新しいボリュームグループまたはプールのリソースプロビジョニングを再度有効にすると、新しく作成したボリュームグループとプールのみが影響を受けます。リソースプロビジョニングが有効になっている既存のボリュームグループおよびプールは変更されません。

.手順
. メニューを選択します。[設定][システム]。
. 下にスクロールして「* Additional Settings *」(追加設定*)を選択し、「*リソースプロビジョニングボリュームの有効化/無効化」をクリックします。
+
設定の説明には、リソースプロビジョニングが現在有効になっているか無効になっているかが示されます。

. ダイアログボックスで、処理を確認します。


.結果
リソースプロビジョニングの有効化と無効化は、作成した新しいSSDプールまたはボリュームグループにのみ影響します。既存のプールまたはボリュームグループは変更されません。
