---
permalink: sm-settings/enable-feature-pack.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, feature, pack, 
summary: 機能パックは、ストレージアレイの属性を変更する（プロトコルをFibre ChannelからiSCSIに変更するなど）バンドルです。機能パックを有効にするには特別なキーが必要です。 
---
= 機能パックの有効化
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
機能パックは、ストレージアレイの属性を変更する（プロトコルをFibre ChannelからiSCSIに変更するなど）バンドルです。機能パックを有効にするには特別なキーが必要です。

.開始する前に
* ストレージアレイの新しい属性の変換と準備について説明した適切な手順に従います。ホストプロトコルの変換手順については、コントローラモデルのハードウェアメンテナンスガイドを参照してください。
* ストレージアレイがオフラインであるため、ホストやアプリケーションがアクセスしていません。
* すべてのデータがバックアップされます。
* 機能パックファイルを入手しておきます。
+
機能パックファイルは管理クライアント（System Managerにアクセスするためのブラウザを備えたシステム）上にロードされます。



[NOTE]
====
ダウンタイムのメンテナンス時間をスケジュールし、ホストとコントローラの間のI/O処理をすべて停止する必要があります。また、変換が完了するまではストレージアレイのデータにアクセスできないことに注意してください。

====
.タスクの内容
このタスクでは、System Managerを使用して機能パックを有効にする方法について説明します。完了したら、ストレージアレイを再起動する必要があります。

.手順
. メニューを選択します。[設定][システム]。
. [ * アドオン * ] で、 [ * 機能パックの変更 * ] を選択します。
. [*Browse*](参照)をクリックし、キーファイルを選択します。
+
ファイル名がダイアログボックスに表示されます。

. フィールドにと入力し `change`ます。
. [ 変更（ Change ） ] をクリックします。
+
機能パックの移行が開始され、コントローラがリブートします。書き込み前のキャッシュデータが削除されるため、I/Oアクティビティが発生しません。両方のコントローラが自動的にリブートし、新しい機能パックが有効になります。リブートが完了すると、ストレージアレイは応答可能な状態に戻ります。


