---
permalink: sm-settings/how-alerts-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, alarm, alerts, 
summary: アラートは、ストレージアレイで発生した重要なイベントについて管理者に通知します。Eメール、SNMPトラップ、syslogを使用してアラートを送信できます。 
---
= アラートの仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラートは、ストレージアレイで発生した重要なイベントについて管理者に通知します。Eメール、SNMPトラップ、syslogを使用してアラートを送信できます。

アラートプロセスは次のように機能します。

. 管理者がSystem Managerで、次のうち1つ以上のアラート方法を設定します。
+
** *電子メール*--電子メールアドレスにメッセージが送信されます。
** *snmp *-- SNMPトラップがSNMPサーバに送信されます。
** *syslog *--メッセージがsyslogサーバに送信される。


. ストレージアレイのイベントモニタが問題 を検出すると、その問題 に関する情報をイベントログに書き込みます（メニュー：サポート[イベントログ]から選択できます）。これには、バッテリの障害、最適からオフラインへのコンポーネントの状態の変化、コントローラの冗長性の問題などが含まれます。
. イベントモニタがイベントが「アラート対象」であると判断すると、設定されているアラート方法（Eメール、SNMP、syslog）を使用して通知が送信されます。重大イベントはすべて「アラート対象」とみなされるほか、一部の警告イベントと情報イベントも「アラート対象」とみなされます。




== アラートの設定

アラートは、初期セットアップウィザード（Eメールアラートのみ）または[アラート]ページから設定できます。現在の設定を確認するには、メニューから「Settings [Alerts]」に移動します。

[アラート]タイルには、次のいずれかのアラート設定が表示されます。

* 未設定
* 設定：少なくとも1つのアラート方法が設定されています。どのアラート方法が設定されているかを確認するには、カーソルでタイルをポイントします。




== アラート情報

アラートには次の種類の情報を含めることができます。

* ストレージアレイの名前。
* イベントログエントリに関連するイベントエラータイプ。
* イベントが発生した日時。
* イベントの簡単な説明。


[NOTE]
====
syslogアラートはRFC 5424のメッセージング標準に準拠します。

====