---
permalink: sm-settings/how-certificates-work-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, certificates, 
summary: 証明書は、Webサイトやサーバなどのオンラインエンティティを識別するデジタルファイルで、インターネット上のセキュアな通信を実現します。 
---
= 証明書の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
証明書は、Webサイトやサーバなどのオンラインエンティティを識別するデジタルファイルで、インターネット上のセキュアな通信を実現します。

証明書を使用すると、Web通信が、指定されたサーバとクライアントの間でのみ、非公開かつ変更されずに暗号化された形式で送信されることが保証されます。System Managerを使用すると、ホスト管理システムのブラウザ（クライアントとして機能）とストレージシステムのコントローラ（サーバとして機能）の間の証明書を管理できます。

証明書には信頼できる認証局が署名した証明書と自己署名の証明書があります。「署名」とは、誰かが所有者のIDを検証し、自分のデバイスが信頼できると判断したことを意味します。ストレージアレイには、自動生成された自己署名証明書が各コントローラに付属しています。自己署名証明書を引き続き使用することも、CA署名証明書を取得してコントローラとホストシステムの間のよりセキュアな接続を確立することもできます。

[NOTE]
====
CA署名証明書はセキュリティ保護に優れていますが（中間者攻撃を防止するなど）、大規模なネットワークの場合はコストがかかる可能性があります。一方、自己署名証明書は安全性は低くなりますが、無料です。したがって、自己署名証明書は本番環境ではなく内部テスト環境で最もよく使用されます。

====


== 署名済み証明書

署名済み証明書は、信頼できる第三者機関である認証局（CA）によって検証されます。署名済み証明書には、エンティティ（通常はサーバまたはWebサイト）の所有者に関する詳細、証明書の発行日と有効期限、エンティティの有効なドメイン、およびアルファベットと数字で構成されるデジタル署名が含まれます。

ブラウザを開いてWebアドレスを入力すると、証明書のチェックプロセスがバックグラウンドで実行され、有効なCA署名証明書を含むWebサイトに接続しているかどうかが確認されます。通常、署名済み証明書で保護されたサイトのアドレスには、南京錠のアイコンとhttpsの指定が含まれます。CA署名証明書が含まれていないWebサイトに接続しようとすると、サイトがセキュアでないことを示す警告がブラウザに表示されます。

CAは、申請プロセス中にユーザーの身元を確認するための手順を実行します。登録済みの会社にEメールを送信し、会社の住所を確認して、HTTPまたはDNSの検証を実行する場合があります。アプリケーションプロセスが完了すると、CAからホスト管理システムにロードするデジタルファイルが送信されます。通常、これらのファイルには次のような信頼チェーンが含まれます。

* *ルート*--階層の最上位にあるのはルート証明書です。この証明書には、他の証明書への署名に使用する秘密鍵が含まれています。ルートは特定のCA組織を識別します。すべてのネットワークデバイスで同じCAを使用する場合、必要なルート証明書は1つだけです。
* *Intermediate *--ルートからの分岐は中間証明書です。CAは、保護されたルート証明書とサーバ証明書の間の証明書として機能する、1つ以上の中間証明書を発行します。
* *サーバー*--チェーンの下部にあるサーバー証明書は、Webサイトやその他のデバイスなど、特定のエンティティを識別するサーバー証明書です。ストレージアレイの各コントローラには、個別のサーバ証明書が必要です。




== 自己署名証明書

ストレージアレイの各コントローラには、自己署名証明書が事前にインストールされています。自己署名証明書はCA署名証明書と似ていますが、第三者ではなくエンティティの所有者によって検証される点が異なります。CA署名証明書と同様に、自己署名証明書には独自の秘密鍵が含まれており、サーバとクライアントの間のHTTPS接続を介してデータが暗号化されて送信されることも保証されます。ただし、自己署名証明書はCA署名証明書と同じ信頼チェーンを使用しません。

自己署名証明書はブラウザでは「信頼されている」ものではありません。自己署名証明書のみが含まれているWebサイトに接続しようとするたびに、ブラウザに警告メッセージが表示されます。Webサイトに進むには、警告メッセージ内のリンクをクリックする必要があります。これにより、基本的には自己署名証明書が受け入れられます。



== キー管理サーバに使用される証明書

ドライブセキュリティ機能を備えた外部キー管理サーバを使用している場合は、そのサーバとコントローラの間の認証用の証明書も管理できます。
