---
permalink: sm-settings/obtain-a-feature-key-file.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, obtain, feature, key, file, 
summary: ストレージアレイでプレミアム機能または機能パックを有効にするには、まず機能キーファイルを取得する必要があります。キーは1つのストレージアレイにのみ関連付けられます。 
---
= 機能キーファイルの取得
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイでプレミアム機能または機能パックを有効にするには、まず機能キーファイルを取得する必要があります。キーは1つのストレージアレイにのみ関連付けられます。

.タスクの内容
このタスクでは、機能に必要な情報を収集し、機能キーファイルの要求を送信する方法について説明します。必要な情報は次のとおりです。

* シャーシのシリアル番号
* 機能有効識別子
* 機能のアクティブ化コード


.手順
. System Managerで、シャーシのシリアル番号を確認して記録します。このシリアル番号は、[サポートセンター]タイルの上にマウスを置くと表示されます。
. System Managerで、機能有効識別子を確認します。[設定]、[システム]の順に移動し、下にスクロールして*アドオン*を表示します。機能有効識別子*を探します。機能有効識別子の番号を記録します。
. 機能を有効にするためのコードを見つけて記録します。機能パックの場合、このコードは変換の実行手順に記載されています。
+
NetAppの手順については、を参照して https://www.netapp.com/support-and-training/documentation/eseries-santricity/["NetApp Eシリーズシステムのドキュメントセンター"^]ください。

+
プレミアム機能の場合は、サポートサイトから次の手順でアクティベーションコードにアクセスできます。

+
.. にログインし https://mysupport.netapp.com/site/global/dashboard["NetAppのサポート"^]ます。
.. お使いの製品の「*ソフトウェアライセンス*」にアクセスします。
.. ストレージアレイシャーシのシリアル番号を入力し、* Go *をクリックします。
.. [*License Key*]列で、Feature Activation Codeを探します。
.. 必要な機能のFeature Activation Codeを記録します。


. 機能キーファイルをリクエストするには、シャーシのシリアル番号、有効識別子、機能のアクティブ化のコードを記載したEメールまたはテキストドキュメントをストレージサプライヤに送信してください。
+
に移動して必要な情報を入力し、機能パックまたは機能パックを入手することもできます http://partnerspfk.netapp.com["ネットアップライセンスのアクティブ化：ストレージアレイプレミアム機能のアクティブ化"^]。（このサイトの手順はプレミアム機能用であり、機能パック用ではありません）。



.終了後
機能キーファイルがある場合は、プレミアム機能または機能パックを有効にすることができます。
