---
permalink: sm-settings/overview-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Alerts, 
summary: System Managerでは、ストレージアレイのアラートをEメール、SNMPトラップ、およびsyslogメッセージで送信するように設定できます。 
---
= アラートの概要
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Managerでは、ストレージアレイのアラートをEメール、SNMPトラップ、およびsyslogメッセージで送信するように設定できます。



== アラートとは

_アラート_ストレージアレイで発生した重要なイベントについて管理者に通知します。イベントには、バッテリの障害、最適からオフラインへのコンポーネントの移動、コントローラの冗長性の問題などが含まれます。重大イベントはすべて「アラート対象」とみなされるほか、一部の警告イベントと情報イベントも「アラート対象」とみなされます。

詳細：

* link:how-alerts-work.html["アラートの仕組み"]
* link:alerts-terminology.html["アラートの用語"]




== アラートの設定方法

アラートは、メッセージとして1つ以上のEメールアドレスに送信するか、SNMPサーバにSNMPトラップとして送信するか、syslogサーバにメッセージとして送信するように設定できます。アラート設定はメニューから選択できます。Settings [Alerts]

詳細：

* link:configure-mail-server-and-recipients-for-alerts.html["メールサーバとアラートの受信者の設定"]
* link:configure-syslog-server-for-alerts.html["アラート用のsyslogサーバの設定"]
* link:configure-snmp-alerts.html["SNMPアラートの設定"]




== 関連情報

アラートに関連する概念の詳細については、以下を参照してください。

* link:../sm-support/overview-event-log.html["イベントログの概要"]
* link:why-are-timestamps-inconsistent-between-the-array-and-alerts.html["一貫性のないタイムスタンプ"]

