---
permalink: sm-settings/overview-drive-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, system, security, key, management, 
summary: セキュリティキー管理は、System（システム）ページから使用できます。 
---
= ドライブセキュリティの概要
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[セキュリティキー管理]ページで、ドライブセキュリティとキー管理を設定できます。



== ドライブセキュリティとは

_Drive Security_は、セキュリティ有効ドライブをストレージアレイから取り外したときに、そのドライブ上のデータへの不正アクセスを防止する機能です。対応するドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。FDEドライブまたはFIPSドライブをアレイから物理的に取り外した場合は、別のアレイに取り付けるまで動作できません。別のアレイに取り付けると、正しいセキュリティキーを指定するまでドライブはセキュリティロック状態になります。a_security key_は、ストレージアレイ内のこれらのタイプのドライブおよびコントローラで共有される文字列です。

詳細：

* link:how-the-drive-security-feature-works.html["ドライブセキュリティ機能の仕組み"]
* link:how-security-key-management-works.html["セキュリティキー管理の仕組み"]
* link:drive-security-terminology.html["ドライブセキュリティの用語"]




== キー管理の設定方法

ドライブセキュリティを実装するには、アレイにFDEドライブまたはFIPSドライブを取り付ける必要があります。これらのドライブのキー管理を設定するには、メニューから次のいずれかを選択します。Settings [ System > Security key management ]コントローラの永続的メモリから内部キーを作成するか、キー管理サーバから外部キーを作成できます。最後に、ボリューム設定で[セキュリティ対応]を選択して、プールおよびボリュームグループのドライブセキュリティを有効にします。

詳細：

* link:create-internal-security-key.html["内部セキュリティキーの作成"]
* link:create-external-security-key.html["外部セキュリティキーの作成"]
* link:../sm-storage/create-pool-manually.html["プールの手動作成"]
* link:../sm-storage/create-volume-group.html["ボリュームグループの作成"]




== ドライブのロックを解除する方法を教えてください。

キー管理を設定したあとにセキュリティ有効ドライブをストレージアレイ間で移動した場合、ドライブ上の暗号化データにアクセスできるようにするには、セキュリティキーを新しいストレージアレイに再割り当てする必要があります。

詳細：

* link:unlock-drives-using-an-internal-security-key.html["内部キー管理の使用時のドライブのロック解除"]
* link:unlock-drives-using-an-external-security-key.html["外部キー管理の使用時のドライブのロック解除"]




== 関連情報

キー管理に関連するタスクの詳細については、以下を参照してください。

* link:use-ca-signed-certificates-for-authentication-with-a-key-management-server.html["キー管理サーバでの認証にCA署名証明書を使用する"]
* link:back-up-security-key.html["セキュリティキーのバックアップ"]

