---
permalink: sm-settings/save-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, save, storage array, configuration, 
summary: ストレージアレイの構成情報をスクリプトファイルに保存すると、追加のストレージアレイをセットアップする時間を同じ構成で節約できます。 
---
= ストレージアレイの構成の保存
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイの構成情報をスクリプトファイルに保存すると、追加のストレージアレイをセットアップする際に同じ構成を使用するための時間を節約できます。

.開始する前に
論理構成の設定を変更する処理がストレージアレイで行われていないことを確認してください。このような処理の例としては、ボリュームの作成または削除、コントローラファームウェアのダウンロード、ホットスペアドライブの割り当てまたは変更、ボリュームグループへの容量（ドライブ）の追加などがあります。

.タスクの内容
ストレージアレイの構成を保存すると、ストレージアレイの設定、ボリュームの構成、ホストの構成、またはストレージアレイに対するホストとボリュームの割り当てを含むコマンドラインインターフェイス（CLI）スクリプトが生成されます。生成されたこのCLIスクリプトを使用して、ハードウェア構成がまったく同じ別のストレージアレイに構成をレプリケートできます。

ただし、ディザスタリカバリにはこのCLIスクリプトを使用しないでください。システムをリストアするには、代わりに、手動で作成する構成データベースのバックアップファイルを使用するか、テクニカルサポートに問い合わせて最新のAutoSupportデータからこのデータを取得してください。

この操作では、次の設定は保存されません。

* バッテリーの寿命
* コントローラの時刻
* Nonvolatile Static Random Access Memory（NVSRAM；不揮発性静的ランダムアクセスメモリ）の設定
* すべてのプレミアム機能
* ストレージアレイのパスワード
* ハードウェアコンポーネントの動作ステータスと状態
* ボリュームグループの動作ステータス（最適を除く）と状態
* ミラーリングやボリュームコピーなどのコピーサービス


[CAUTION]
====
*アプリケーションエラーのリスク*-論理構成の設定を変更する処理をストレージアレイで実行中の場合は、このオプションを使用しないでください。このような処理の例としては、ボリュームの作成または削除、コントローラファームウェアのダウンロード、ホットスペアドライブの割り当てまたは変更、ボリュームグループへの容量（ドライブ）の追加などがあります。

====
.手順
. メニューを選択します。[設定][システム]。
. 「ストレージアレイ構成の保存」を選択します。
. 保存する構成の項目を選択します。
+
** ストレージアレイの設定
** ボリューム構成
** ホストの設定
** ホスト/ボリューム間の割り当て


+
[NOTE]
====
［*ホスト/ボリューム間の割り当て*］項目を選択した場合、［*ボリューム構成*］項目と［*ホスト構成*］項目もデフォルトで選択されます。「ホスト/ボリューム間の割り当て」は、「ボリューム構成」と「ホスト構成」も保存しないと保存できません。

====
. [ 保存（ Save ） ] をクリックします。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `storage-array-configuration.cfg`。



.終了後
保存したストレージアレイの構成を別のストレージアレイにロードするには、SANtricityコマンドラインインターフェイス（SMcli）でオプションを指定して `-f`ファイルを適用し `.cfg`ます。

[NOTE]
====
Unified Managerインターフェイスを使用して、ストレージアレイの構成を他のストレージアレイにロードすることもできます（選択メニュー：管理[設定のインポート]）。

====