---
permalink: sm-settings/synchronize-storage-array-clocks.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronize, storage, array, clocks, 
summary: ネットワークタイムプロトコル（NTP）が無効な場合は、コントローラのクロックを手動で設定して、管理クライアント（SANtricity System Managerにアクセスするブラウザの実行に使用されるシステム）と同期されるようにすることができます。 
---
= ストレージアレイのクロックの同期
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークタイムプロトコル（NTP）が有効になっていない場合は、コントローラのクロックを手動で設定して、管理クライアント（System Managerにアクセスするブラウザの実行に使用されるシステム）と同期されるようにすることができます。

.タスクの内容
同期により、イベントログ内のイベントタイムスタンプがホストログファイルに書き込まれたタイムスタンプと一致するようになります。同期プロセス中も、コントローラは引き続き使用可能で動作します。

[NOTE]
====
System ManagerでNTPが有効になっている場合は、このオプションを使用してクロックを同期しないでください。代わりに、NTPはSNTP（Simple Network Time Protocol）を使用してクロックを外部ホストと自動的に同期します。

====
[NOTE]
====
同期後に、パフォーマンス統計が失われたり歪んだりしたり、スケジュールが影響を受けたり（ASUP、Snapshotなど）、ログデータのタイムスタンプが歪んだりすることがあります。NTPを使用すると、この問題を回避できます。

====
.手順
. メニューを選択します。[設定][システム]。
. [*General]で'[*ストレージ・アレイ・クロックの同期化*]をクリックします
+
[ストレージアレイクロックの同期]ダイアログボックスが開きます。コントローラと管理クライアントとして使用されているコンピュータの現在の日時が表示されます。

+
[NOTE]
====
シンプレックスストレージアレイの場合は、1台のコントローラのみが表示されます。

====
. ダイアログボックスに表示された時間が一致しない場合は、*同期化*をクリックします。


.結果
同期が成功すると、イベントのタイムスタンプはイベントログとホストログで同じになります。
