---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, drives, internal, key, management, 
summary: 内部キー管理を設定したあとにセキュリティ有効ドライブをストレージアレイ間で移動した場合、ドライブ上の暗号化されたデータにアクセスできるようにするには、セキュリティキーを新しいストレージアレイに再割り当てする必要があります。 
---
= 内部キー管理の使用時のドライブのロック解除
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
内部キー管理を設定したあとにセキュリティ有効ドライブをストレージアレイ間で移動した場合、ドライブ上の暗号化されたデータにアクセスできるようにするには、セキュリティキーを新しいストレージアレイに再割り当てする必要があります。

.開始する前に
* ソースアレイ（ドライブを取り外すアレイ）で、ボリュームグループをエクスポートし、ドライブを取り外しておきます。ターゲットアレイにドライブを取り付け直しておきます。
+

NOTE: エクスポート/インポート機能はSystem Managerユーザインターフェイスではサポートされていません。ボリュームグループを別のストレージアレイにエクスポート/インポートするには、コマンドラインインターフェイス（CLI）を使用する必要があります。

+
ボリュームグループの移行の詳細な手順については、を参照して https://kb.netapp.com/["NetAppナレッジベース"^]ください。System Managerで管理している新しいアレイや従来型システムのアレイについては、該当する手順に従ってください。

* ドライブセキュリティ機能が有効になっている必要があります。そうしないと、このタスクの実行中に[セキュリティキーを作成できません]ダイアログボックスが開きます。ドライブセキュリティ機能を有効にする手順については、必要に応じてストレージベンダーにお問い合わせください。
* ロックを解除するドライブに関連付けられているセキュリティキーを確認しておく必要があります。
* セキュリティキーファイルは管理クライアント（System Managerへのアクセスに使用するブラウザを備えたシステム）にあります。別のシステムで管理されているストレージアレイにドライブを移動する場合は、その管理クライアントにセキュリティキーファイルを移動する必要があります。


.タスクの内容
内部キー管理を使用する場合、セキュリティキーはストレージアレイにローカルに格納されます。セキュリティキーは、読み取り/書き込みアクセス用にコントローラとドライブで共有される文字列です。ドライブをアレイから物理的に取り外して別のドライブに取り付けた場合、正しいセキュリティキーを指定するまでドライブは動作しません。

[NOTE]
====
コントローラの永続的メモリから内部キーを作成するか、キー管理サーバから外部キーを作成できます。ここでは、_INTERNAL _KEY管理を使用する場合のデータのロック解除について説明します。外部キー管理を使用した場合は、を参照してくださいlink:unlock-drives-using-an-external-security-key.html["外部キー管理の使用時のドライブのロック解除"]。コントローラのアップグレードを実行し、すべてのコントローラを最新のハードウェアに交換する場合は、のEシリーズおよびSANtricityドキュメントセンターに記載されている手順に従う必要があります。link:https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html["ドライブのロック解除"]

====
セキュリティ有効ドライブを別のアレイに取り付けると、そのアレイでドライブが検出され、「要対応」状態となって「セキュリティ キーが必要です」というステータスが表示されます。ドライブ データのロックを解除するには、セキュリティ キー ファイルを選択し、キーのパス フレーズを入力します（このパスフレーズはストレージアレイの管理者パスワードとは異なります）。

新しいストレージアレイに取り付けられている他のセキュリティ有効ドライブでは、インポートするセキュリティキーとは異なるセキュリティキーが使用される場合があります。インポートプロセスでは、取り付けようとしているドライブのデータのロックを解除するためにのみ古いセキュリティキーが使用されます。ロック解除プロセスが完了すると、新しく取り付けたドライブのキーがターゲットストレージアレイのセキュリティキーに変更されます。

.手順
. メニューを選択します。[設定][システム]。
. セキュリティキー管理*で、*セキュアドライブのロック解除*を選択します。
+
[セキュアドライブのロック解除]ダイアログボックスが開きます。セキュリティキーを必要とするドライブが表に表示されます。

. *オプション：ドライブ番号にカーソルを合わせると、ドライブの場所（シェルフ番号とベイ番号）が表示されます。
. [*参照]をクリックし、ロックを解除するドライブに対応するセキュリティキーファイルを選択します。
+
選択したキーファイルがダイアログボックスに表示されます。

. このキーファイルに関連付けられているパスフレーズを入力します。
+
入力した文字はマスクされます。

. [ロック解除]をクリックします。
+
ロック解除処理が成功すると、ダイアログボックスに「The associated secure drives have been unlocked」と表示されます。



.結果
すべてのドライブがロックされてロックが解除されると、ストレージアレイ内の各コントローラがリブートされます。ただし、ターゲットストレージアレイ内にロック解除されたドライブがすでにある場合、コントローラはリブートされません。

.終了後
デスティネーションアレイ（新しくドライブを取り付けたアレイ）で、ボリュームグループをインポートできるようになりました。


NOTE: エクスポート/インポート機能はSystem Managerユーザインターフェイスではサポートされていません。ボリュームグループを別のストレージアレイにエクスポート/インポートするには、コマンドラインインターフェイス（CLI）を使用する必要があります。

ボリュームグループの移行の詳細な手順については、を参照して https://kb.netapp.com/["NetAppナレッジベース"^]ください。
