---
permalink: sm-settings/use-ca-signed-certificates-for-controllers.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ca-signed, certificates, controllers, 
summary: コントローラとSystem Managerへのアクセスに使用されるブラウザとの間のセキュアな通信を確立するために、CA署名証明書を取得できます。 
---
= コントローラのCA署名証明書の使用
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラとSystem Managerへのアクセスに使用されるブラウザとの間のセキュアな通信を確立するために、CA署名証明書を取得できます。

.開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書機能は表示されません。
* 各コントローラのIPアドレスまたはDNS名を確認しておく必要があります。


.タスクの内容
CA署名証明書の使用は、3つの手順で構成されます。



== 手順1：コントローラのCSRを作成します

最初に、ストレージアレイの各コントローラの証明書署名要求（CSR）ファイルを生成する必要があります。

.タスクの内容
このタスクでは、System ManagerからCSRファイルを生成する方法について説明します。CSRは、組織に関する情報、およびコントローラのIPアドレスまたはDNS名を提供します。このタスクでは、ストレージアレイにコントローラが1つある場合は1つ、コントローラが2つある場合は2つのCSRファイルが生成されます。

[NOTE]
====
または、OpenSSLなどのツールを使用してCSRファイルを生成し、に進みます。<<手順2：CSRファイルを送信する>>

====
.手順
. メニューから[設定][証明書]を選択します。
. [Array Management]タブで、[*Complete CSR*]を選択します。
+
[NOTE]
====
2台目のコントローラの自己署名証明書を受け入れるよう求めるダイアログボックスが表示された場合は、*自己署名証明書を受け入れる*をクリックして続行します。

====
. 次の情報を入力し、[次へ*]をクリックします。
+
** *組織*--会社または組織の正式名称。Inc.やCorp.などのサフィックスを含めます。
** *組織単位（オプション）*--証明書を処理している組織の部門。
** *市区町村*--ストレージアレイまたは事業の所在地である市区町村。
** *都道府県（オプション）*-ストレージアレイまたは事業の所在地である都道府県。
** *国のISOコード*--自国を表す2桁のISO（国際標準化機構）コード（USなど）。


+
[CAUTION]
====
一部のフィールドには、コントローラのIPアドレスなどの適切な情報があらかじめ入力されています。事前入力された値は、明らかな間違いでないかぎり変更しないでください。たとえば、CSRをまだ作成していない場合、コントローラのIPアドレスは「localhost」に設定されます。 この場合は、「localhost」をコントローラのDNS名またはIPアドレスに変更する必要があります。

====
. ストレージアレイ内のコントローラAに関する次の情報を確認または入力します。
+
** *コントローラAの共通名*--コントローラAのIPアドレスまたはDNS名がデフォルトで表示されますこのアドレスが正しいことを確認してください。ブラウザでSystem Managerにアクセスする際に入力したアドレスと正確に一致している必要があります。DNS名の1文字目をワイルドカードにすることはできません。
** *コントローラAの代替IPアドレス*--共通名がIPアドレスの場合は、コントローラAの追加のIPアドレスまたはエイリアスをオプションで入力できます。複数のエントリを入力する場合は、カンマで区切って指定します。
** *コントローラAの代替DNS名*--共通名がDNS名の場合は、コントローラAの追加のDNS名を入力します。複数のエントリを入力する場合は、カンマで区切って指定します。代替DNS名がない場合は、最初のフィールドに入力したDNS名をここにコピーします。DNS名の1文字目をワイルドカードにすることはできません。ストレージアレイにコントローラが1台しかない場合は、「完了」ボタンを使用できます。
+
ストレージアレイにコントローラが2台ある場合は、* Next *ボタンを使用できます。



+
[NOTE]
====
CSR要求を最初に作成するときは、[この手順をスキップ]リンクをクリックしないでください。このリンクは、エラーリカバリの状況で提供されます。CSR要求が一方のコントローラで失敗し、もう一方のコントローラで失敗することがあります。このリンクを使用すると、コントローラAでCSRがすでに定義されている場合はその作成をスキップし、コントローラBでCSRを再作成する次の手順に進むことができます

====
. コントローラが1台しかない場合は、[完了]をクリックします。コントローラが2台ある場合は、[次へ]をクリックしてコントローラBの情報を入力し（上記と同じ）、[完了]をクリックします。
+
シングルコントローラの場合は、1つのCSRファイルがローカルシステムにダウンロードされます。デュアルコントローラの場合は、2つのCSRファイルがダウンロードされます。ダウンロードのフォルダの場所は、ブラウザによって異なります。

. にアクセスします。




== 手順2：CSRファイルを送信する

証明書署名要求（CSR）ファイルを作成したら、ファイルを認証局（CA）に送信します。Eシリーズシステムでは、署名済み証明書のPEM形式（Base64 ASCIIエンコード）が必要です。PEM、.crt、.cer、または.keyのファイルタイプが含まれます。

.手順
. ダウンロードしたCSRファイルの場所を確認します。
. CSRファイルをCA（VerisignやDigiCertなど）に送信し、PEM形式の署名付き証明書を要求します。
+
[CAUTION]
====
* CSRファイルをCAに送信した後は、別のCSRファイルを再生成しないでください。*CSRを生成すると、秘密鍵と公開鍵のペアが作成されます。公開鍵はCSRの一部であり、秘密鍵はシステムのキーストアに保持されます。署名済み証明書を受け取ってインポートすると、秘密鍵と公開鍵の両方が元のペアになります。キーが一致しないと署名済み証明書は機能せず、CAに新しい証明書を要求する必要があります。

====
. CAから署名済み証明書が返されたら、に進みます<<手順3：コントローラの署名済み証明書をインポートする>>。




== 手順3：コントローラの署名済み証明書をインポートする

認証局（CA）から署名済み証明書を受け取ったら、コントローラのファイルをインポートします。

.開始する前に
* 署名済み証明書ファイルをCAから受け取っておきます。これらのファイルには、ルート証明書、1つ以上の中間証明書、およびサーバ証明書が含まれます。
* CAからチェーン証明書ファイル（.p7bファイルなど）が提供された場合は、チェーンファイルを個 々 のファイル（ルート証明書、1つ以上の中間証明書、コントローラを識別するサーバ証明書）に展開する必要があります。Windowsユーティリティを使用してファイルを展開でき `certmgr`ます(右クリックしてメニューを選択します:すべてのタスク[エクスポート])。Base-64エンコードを推奨します。エクスポートが完了すると、チェーン内の証明書ファイルごとに1つのCERファイルが表示されます。
* System Managerにアクセスするホストシステムに証明書ファイルをコピーしておきます。


.手順
. 選択メニュー：設定[証明書]
. Array Management（アレイ管理）タブで、* Import（インポート）*を選択します。
+
証明書ファイルをインポートするためのダイアログボックスが開きます。

. 「*参照」ボタンをクリックして、最初にルート証明書と中間証明書ファイルを選択してから、コントローラの各サーバ証明書を選択します。ルートファイルと中間ファイルは両方のコントローラで同じです。サーバ証明書のみコントローラごとに一意です。外部ツールからCSRを生成した場合は、CSRと一緒に作成された秘密鍵ファイルもインポートする必要があります。
+
ファイル名がダイアログボックスに表示されます。

. [* インポート * ] をクリックします。
+
ファイルがアップロードされて検証されます。



.結果
セッションは自動的に終了します。証明書を有効にするには、再度ログインする必要があります。再度ログインすると、新しいCA署名証明書がセッションに使用されます。
