---
permalink: sm-settings/view-iscsi-statistics-packages-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, statistics, packages, 
summary: ストレージアレイへのiSCSI接続に関するデータを表示できます。 
---
= iSCSI統計パッケージの表示
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのiSCSI接続に関するデータを表示できます。

.タスクの内容
System Managerには、次のタイプのiSCSI統計が表示されます。すべての統計は読み取り専用であり、設定することはできません。

* *イーサネットMAC統計*--メディアアクセス制御(MAC)の統計情報を提供します。MACは、物理アドレスまたはMACアドレスと呼ばれるアドレス指定メカニズムも提供します。MACアドレスは、各ネットワークアダプタに割り当てられる一意のアドレスです。MACアドレスは、データパケットをサブネットワーク内の宛先に配信するのに役立ちます。
* *イーサネットTCP/IP統計*-- iSCSIデバイスのTCP (Transmission Control Protocol)とIP (Internet Protocol)のTCP/IPの統計情報を提供しますTCPを使用すると、ネットワーク接続されたホスト上のアプリケーションが相互に接続を作成し、その上でパケットでデータを交換できます。IPは、パケット交換されたネットワーク間でデータを通信するデータ指向プロトコルです。IPv4統計とIPv6統計は個別に表示されます。
* *ローカル・ターゲット/イニシエータ（プロトコル）統計*：ストレージ・メディアへのブロック・レベルのアクセスを提供するiSCSIターゲットの統計情報を表示します非同期ミラーリング処理でイニシエータとして使用される場合は'ストレージ・アレイのiSCSI統計情報を表示します
* *DCBXの運用状態統計*--さまざまなData Center Bridging Exchange（DCBX）機能の運用状態を表示します。
* *LLDP TLV statistics *-- Link Layer Discovery Protocol (LLDP) Type Length Value (TLTLV )統計を表示します。
* *DCBX TLV統計*-- Data Center Bridging（DCB）環境内のストレージアレイのホストポートを識別する情報が表示されます。この情報は、識別および機能の目的でネットワークピアと共有されます。


これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。統計の生データは、コントローラの起動以降に収集されたすべての統計です。ベースライン統計は、ベースライン時間の設定以降に収集されたポイントインタイムの統計です。

.手順
. メニューを選択します。[設定][システム]。
. [View iSCSI Statistics Packages]を選択します。
. タブをクリックして、さまざまな統計を表示します。
. *オプション：*ベースラインを設定するには、*新しいベースラインの設定*をクリックします。
+
ベースラインを設定すると、統計を収集するための新しい開始ポイントが設定されます。すべてのiSCSI統計に同じベースラインが使用されます。



各種統計の詳細については、次の項を参照してください。



== MAC送信統計とMAC受信統計

イーサネットMAC統計を選択すると、受信統計と送信統計の両方が表示されます。これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。

.MAC送信統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
F
 a| 
フレーム数



 a| 
B
 a| 
バイト数



 a| 
MF
 a| 
マルチキャストフレーム数



 a| 
BF
 a| 
ブロードキャストフレーム数



 a| 
PF
 a| 
ポーズフレーム数



 a| 
CF
 a| 
制御フレーム数



 a| 
FDF
 a| 
フレーム遅延数



 a| 
FED
 a| 
フレーム遅延の多発数



 a| 
FLC
 a| 
フレームレイトコリジョン数



 a| 
FA
 a| 
フレームの中断数



 a| 
FSC
 a| 
フレームの単一コリジョン数



 a| 
FMC
 a| 
フレームの複数コリジョン数



 a| 
FC
 a| 
フレームのコリジョン数



 a| 
FDR
 a| 
フレーム破棄数



 a| 
JF
 a| 
ジャンボフレーム数

|===
====
.MAC受信統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
F
 a| 
フレーム数



 a| 
B
 a| 
バイト数



 a| 
MF
 a| 
マルチキャストフレーム数



 a| 
BF
 a| 
ブロードキャストフレーム数



 a| 
PF
 a| 
ポーズフレーム数



 a| 
CF
 a| 
制御フレーム数



 a| 
FLE
 a| 
フレーム長エラー数



 a| 
FD
 a| 
フレーム破棄数



 a| 
FCRCE
 a| 
フレームCRCエラー数



 a| 
料金
 a| 
フレームエンコードエラー数



 a| 
LFE
 a| 
ラージフレームエラー数



 a| 
SFE
 a| 
スモールフレームエラー数



 a| 
J
 a| 
ジャバー数



 a| 
UCC
 a| 
不明な制御フレーム数



 a| 
CSE
 a| 
キャリア検知エラー数

|===
====


== イーサネットTCP/IP統計

イーサネットTCP/IP統計を選択すると、TCP統計とIP統計の両方が表示されます。これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。

.イーサネットTCP統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
TXS
 a| 
送信セグメント数



 a| 
TXB
 a| 
送信バイト数



 a| 
RTxTE
 a| 
再送信タイマー期限切れ数



 a| 
TxDACK
 a| 
送信遅延ACK数



 a| 
TxACK
 a| 
送信ACK数



 a| 
受信数
 a| 
受信セグメント数



 a| 
RxB
 a| 
受信バイト数



 a| 
RxDACK
 a| 
受信重複ACK数



 a| 
RxACK
 a| 
受信ACK数



 a| 
RxSEC
 a| 
受信セグメントエラー数



 a| 
RxSOOC
 a| 
受信セグメント順不同数



 a| 
RxWP
 a| 
受信ウィンドウプローブ数



 a| 
RxWU
 a| 
受信ウィンドウ更新数

|===
====
.イーサネットIP統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
TXP
 a| 
送信パケット数



 a| 
TXB
 a| 
送信バイト数



 a| 
TxF
 a| 
送信フラグメント数



 a| 
RXP
 a| 
受信パケット数。[*Show IPv4*]を選択して、IPv4パケット受信数を表示します。[*Show IPv6*]を選択して、IPv6パケット受信数を表示します。



 a| 
RxB
 a| 
受信バイト数



 a| 
RxF
 a| 
受信フラグメント数



 a| 
RxPE
 a| 
受信パケットエラー数



 a| 
DR
 a| 
データグラム再構築数



 a| 
DRE-OLFC
 a| 
データグラム再構築エラー、重複フラグメント数



 a| 
DRE-OOFC
 a| 
データグラム再構築エラー、順不同フラグメント数



 a| 
DRE-TOC
 a| 
データグラム再構築エラー、タイムアウト数

|===
====


== iSCSIターゲット統計およびローカルイニシエータ統計

ターゲット（プロトコル）統計またはローカルイニシエータ（プロトコル）統計を選択すると、iSCSI統計が表示されます。これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。

.iSCSI統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
SL
 a| 
成功したiSCSIログイン数



 a| 
UL
 a| 
失敗したiSCSIログイン数



 a| 
SA
 a| 
成功したiSCSI認証数（認証が有効な場合）



 a| 
UA
 a| 
失敗したiSCSI認証数（認証が有効な場合）



 a| 
PDU
 a| 
正しいiSCSI PDU処理数



 a| 
HDE
 a| 
ヘッダーダイジェストエラーがあるiSCSI PDUの数



 a| 
DDE
 a| 
データダイジェストエラーのあるiSCSI PDUの数



 a| 
PE
 a| 
iSCSIプロトコルエラーのあるPDUの数



 a| 
必要
 a| 
予期しないiSCSIセッション終了数



 a| 
UCT
 a| 
予期しないiSCSI接続終了数

|===
====


== DCBX動作状態統計

[Data Center Bridging Exchange（DCBX）Operational State Statistics]を選択すると、DCBX統計が表示されます。

.DCBX統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
iSCSIホストポート
 a| 
検出されたホストポートの場所をコントローラ番号、ポート番号の形式で示します。



 a| 
優先度グループ
 a| 
優先度グループ（PG）アプリケーションの動作状態を示します。「有効」または「無効」のいずれかです。



 a| 
優先度ベースのフロー制御
 a| 
優先度ベースフロー制御（PFC）機能の動作状態を示します。「有効」または「無効」のいずれかです。



 a| 
iSCSI機能
 a| 
Internet Small Computer System Interface（iSCSI）アプリケーションの動作状態を示します。「有効」または「無効」のいずれかです。



 a| 
FCoE帯域幅
 a| 
Fibre Channel over Ethernet（FCoE）帯域幅の状態を示します。「True」または「False」のいずれかになります。



 a| 
FCoE / FIPでマッピングの不一致なし
 a| 
FCoEとFCoE Initialization Protocol（FIP）の間にマッピングの不一致がないかどうかを示します。値はTrueまたはFalseのいずれかです。

|===
====

NOTE: その他のDCBX動作状態統計は、状態キャプチャファイルで確認できます。



== LLDP TLV統計

Link Layer Discovery Protocol（LLDP）Type Length Value（TLV）Statisticsを選択すると、ローカルデバイス用とリモートデバイス用の2つの統計セットが表示されます。ローカルデバイスはコントローラを参照します。リモートデバイスとは、コントローラが接続されているピアデバイス（通常はスイッチ）のことです。

.LLDP TLV統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
iSCSIホストポート
 a| 
検出されたホストポートの場所をコントローラ番号、ポート番号の形式で示します。



 a| 
シャーシID
 a| 
シャーシIDを示します。



 a| 
シャーシIDサブタイプ
 a| 
シャーシIDのサブタイプを示します。



 a| 
ポートID
 a| 
ポートIDを示します。



 a| 
ポートIDサブタイプ
 a| 
ポートIDのサブタイプを示します。



 a| 
Time-To-Live
 a| 
受信者LLDPエージェントが情報を有効とみなす秒数を示します。

|===
====

NOTE: その他のLLDP TLV統計は、状態キャプチャファイルで確認できます。



== DCBX TLV統計

Data Center Bridging Exchange（DCBX）Type Length Value（TLV）Statisticsを選択すると、次の統計が表示されます。

* *ローカル統計*-コントローラ出荷時に設定されたDCBXパラメータ。
* *動作統計*-- DCBXネゴシエーション後のDCBXパラメータ。
* *リモート統計*--コントローラが接続されているピアデバイス（通常はスイッチ）からのDCBXパラメータ。


.DCBX TLV統計：
[%collapsible]
====
[cols="25h,~"]
|===
| 統計 | 定義 


 a| 
iSCSIホストポート
 a| 
検出されたホストポートの場所をコントローラ番号、ポート番号の形式で示します。



 a| 
フロー制御モード
 a| 
ポート全体のフロー制御モード。有効な値は、「無効」、「標準」、「優先度別」、「不確定」です。



 a| 
プロトコル
 a| 
通信プロトコル。有効な値は、「FCoE」、「FIP」、「iSCSI」、「不明」です。



 a| 
優先度
 a| 
通信の優先順位を示す整数値。



 a| 
優先度グループ
 a| 
プロトコルが割り当てられている優先度グループを表す整数値。



 a| 
優先度グループの帯域幅
 a| 
プライオリティグループに割り当てられた帯域幅の量を示すパーセンテージ値。



 a| 
DCBX PFCステータス
 a| 
特定のポートの優先度ベースフロー制御（PFC）ステータス。「有効」または「無効」のいずれかになります。

|===
====

NOTE: その他のDCBX TLV統計は、状態キャプチャファイルで確認できます。
