---
permalink: sm-settings/what-is-cache-flushing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, flushing, 
summary: キャッシュ内の書き込み前のデータの量が一定のレベルに達すると、コントローラはキャッシュされたデータを定期的にドライブに書き込みます。この書き込みプロセスはフラッシュと呼ばれます。 
---
= キャッシュフラッシュとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キャッシュ内の書き込み前のデータの量が一定のレベルに達すると、コントローラはキャッシュされたデータを定期的にドライブに書き込みます。この書き込みプロセスは「フラッシュ」と呼ばれます。

コントローラは、デマンドベースと経過時間ベースの2つのアルゴリズムを使用してキャッシュをフラッシュします。キャッシュされたデータの量がキャッシュフラッシュしきい値を下回るまで、コントローラはデマンドベースのアルゴリズムを使用します。デフォルトでは、キャッシュの80%が使用中になるとフラッシュが開始されます。

System Managerでは、「デマンド・キャッシュ・フラッシュの開始」しきい値を、環境で使用されるI/Oのタイプに最も適した値に設定できます。書き込み操作が主な環境では'新しい書き込み要求をディスクに移動せずにキャッシュで処理できる可能性を高めるために'デマンド・キャッシュ・フラッシュの開始パーセントを高く設定する必要があります割合を高く設定すると、キャッシュフラッシュの回数が制限され、キャッシュに残っているデータが増えるため、キャッシュヒット率が高くなります。

I/Oが不安定な（データバーストが発生する）環境では、キャッシュフラッシュを低くすることで、データバースト間でキャッシュが頻繁にフラッシュされるようにすることができます。さまざまな負荷を処理する多様なI/O環境や、負荷のタイプが不明な環境では、このしきい値を中間の50%に設定します。80%未満に設定した場合、ホスト読み取りに必要なデータがキャッシュにないためにパフォーマンスが低下する可能性があります。割合を低くすると、キャッシュレベルを維持するために必要なディスク書き込みの数も増加し、システムオーバーヘッドが増加します。

経過時間ベースのアルゴリズムでは、書き込みデータがディスクにフラッシュされるまでのキャッシュでの保持期間を指定します。キャッシュフラッシュしきい値に達するまで、経過時間ベースのアルゴリズムが使用されます。デフォルトは10秒ですが、この期間は非アクティブな期間にのみカウントされます。System Managerではフラッシュのタイミングを変更できません。代わりに、コマンドラインインターフェイス（CLI）で* Set Storage Array *コマンドを使用する必要があります。

[CAUTION]
====
*データ損失の可能性*--バッテリなしの書き込みキャッシュ*オプションを有効にして保護用のユニバーサル電源装置を持たないと、データが失われる可能性があります。また、コントローラのバッテリがない場合に*バッテリなしの書き込みキャッシュ*オプションを有効にすると、データが失われる可能性があります。

====