---
permalink: sm-settings/what-do-i-need-to-know-before-backing-up-a-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, backing up, security, key, 
summary: バックアップがない状態で元のセキュリティキーが破損した場合、ドライブ上のデータをストレージアレイ間で移行すると、ドライブ上のデータにアクセスできなくなります。 
---
= セキュリティキーをバックアップするときは、どのような点に注意する必要がありますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップがない状態で元のセキュリティキーが破損した場合、ドライブ上のデータをストレージアレイ間で移行すると、ドライブ上のデータにアクセスできなくなります。

セキュリティキーをバックアップする前に、次のガイドラインに注意してください。

* 元のキーファイルのセキュリティキー識別子とパスフレーズを確認しておきます。
+
[NOTE]
====
識別子を使用するのは内部キーのみです。識別子を作成すると、追加の文字が自動的に生成され、識別子文字列の両端に追加されます。文字が追加されることで識別子が一意であることが保証されます。

====
* バックアップ用の新しいパスフレーズを作成します。このパスフレーズは、元のキーの作成時または最後の変更時に使用されたパスフレーズと一致する必要はありません。このパスフレーズは、作成するバックアップにのみ適用されます。
+
[NOTE]
====
ドライブセキュリティのパスフレーズをストレージアレイの管理者パスワードと混同しないでください。ドライブセキュリティのパスフレーズは、セキュリティキーのバックアップを保護します。管理者パスワードは、ストレージアレイ全体を不正アクセスから保護します。

====
* バックアップセキュリティキーファイルが管理クライアントにダウンロードされます。ダウンロードしたファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。セキュリティキー情報が格納されている場所を必ず記録しておいてください。

