---
permalink: sm-settings/what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, resource-provisioned, volumes, feature, 
summary: リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。 
---
= リソースプロビジョニングボリューム機能について、どのような点に注意する必要がありますか？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。この機能を使用すると、ボリュームをバックグラウンドの初期化プロセスなしですぐに使用できるようになります。

リソースプロビジョニングボリュームは、SSDボリュームグループまたはプール内のシックボリュームで、ボリュームの作成時にドライブ容量が割り当てられますが（ボリュームに割り当てられます）、ドライブブロックは割り当て解除されます（マッピング解除されます）。一方、従来のシックボリュームでは、Data Assurance保護の情報フィールドを初期化し、各RAIDストライプでデータとRAIDパリティを整合させるために、すべてのドライブブロックがバックグラウンドのボリューム初期化処理でマッピングまたは割り当てられます。リソースプロビジョニングボリュームの場合、バックグラウンドの初期化は時間に制限されません。代わりに、各RAIDストライプは、ストライプ内のボリュームブロックへの最初の書き込み時に初期化されます。

リソースプロビジョニングボリュームはSSDボリュームグループおよびプールでのみサポートされ、グループまたはプール内のすべてのドライブでNVMeのDeallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能がサポートされます。リソースプロビジョニングボリュームを作成すると、そのボリュームに割り当てられているすべてのドライブブロックの割り当てが解除されます（マッピングが解除されます）。また、ホストではNVMe Dataset ManagementコマンドまたはSCSI Unmapコマンドを使用して、ボリューム内の論理ブロックの割り当てを解除できます。ブロックの割り当てを解除すると、SSDの消耗度が向上し、最大書き込みパフォーマンスが向上します。どの程度向上するかは、ドライブのモデルや容量によって異なります。

リソースプロビジョニングは、ドライブがDULBEをサポートするシステムではデフォルトで有効になっています。このデフォルト設定は、* Pools & Volume Groups *で無効にできます。
