---
permalink: sm-settings/what-is-controller-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, cache, 
summary: コントローラキャッシュは、コントローラとホスト間、およびコントローラとディスク間の2種類のI/O（入出力）処理を合理化する物理メモリスペースです。 
---
= コントローラキャッシュとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラキャッシュは、コントローラとホスト間、およびコントローラとディスク間の2種類のI/O（入出力）処理を合理化する物理メモリスペースです。

読み取りおよび書き込みのデータ転送では、ホストとコントローラは高速な接続を介して通信します。ただし、ディスクは比較的低速なデバイスであるため、コントローラのバックエンドからディスクへの通信は低速です。

コントローラキャッシュがデータを受信すると、コントローラはデータを保持していることをホストアプリケーションに確認応答します。これにより、ホストアプリケーションはI/Oがディスクに書き込まれるのを待つ必要がなくなります。代わりに、アプリケーションは処理を続行できます。また、キャッシュされたデータにサーバアプリケーションから簡単にアクセスできるため、データにアクセスするためにディスクを読み取る必要がありません。

コントローラキャッシュは、ストレージアレイの全体的なパフォーマンスにいくつかの点で影響します。

* キャッシュはバッファとして機能するため、ホストとディスクのデータ転送を同期する必要がありません。
* ホストからの読み取りまたは書き込み処理のデータは、以前の処理でキャッシュに格納されている場合があるため、ディスクにアクセスする必要はありません。
* 書き込みキャッシュを使用している場合、ホストは以前の書き込み処理がディスクに書き込まれる前に後続の書き込みコマンドを送信できます。
* キャッシュプリフェッチを有効にすると、シーケンシャルリードアクセスが最適化されます。読み取り処理ではデータがディスクから読み取られるのではなく、キャッシュ内のデータが使用される可能性が高くなります。


[CAUTION]
====
*データ損失の可能性*--バッテリなしの書き込みキャッシュ*オプションを有効にして保護用のユニバーサル電源装置を持たないと、データが失われる可能性があります。また、コントローラのバッテリがない場合に*バッテリなしの書き込みキャッシュ*オプションを有効にすると、データが失われる可能性があります。

====