---
permalink: sm-support/activate-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, activate, controller, software, firmware 
summary: アップグレードファイルはすぐにアクティブ化することも、都合の良いタイミングでアクティブ化することもできます。 
---
= コントローラのソフトウェアとファームウェアのアクティブ化
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードファイルはすぐにアクティブ化することも、都合の良いタイミングでアクティブ化することもできます。

.タスクの内容
アクティブ化せずにファイルをダウンロードして転送できます。あとでアクティブ化する理由は次のとおりです。

* *時間帯*--ソフトウェアとファームウェアのアクティブ化には時間がかかることがあるため、I/O負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


ソフトウェアまたはファームウェアの転送は完了していてもアクティブ化されていない場合は、System Managerのホームページの通知領域とアップグレードセンターのページに通知が表示されます。

[CAUTION]
====
起動後にアクティブ化プロセスを停止することはできません。

====
.手順
. メニューを選択します。Support [Upgrade Center]を選択します。
. SANtricity OS Controller Software upgrade（OSコントローラソフトウェアのアップグレード）というラベルの付いた領域で、* Activate（アクティブ化）*をクリックし、操作を実行することを確認します。
+
アップグレード前の健常性チェックの段階で処理をキャンセルすることはできますが、アクティブ化の実行中はキャンセルできません。

+
アップグレード前の健常性チェックが開始されます。アップグレード前の健常性チェックに合格すると、アップグレードプロセスはファイルのアクティブ化に進みます。アップグレード前の健常性チェックに失敗した場合は、Recovery Guruを使用するかテクニカルサポートに連絡して問題を解決してください。一部の種類の条件では、*アップグレードを許可*チェックボックスを選択してエラーが発生しても、テクニカルサポートからアップグレードを続行するようにアドバイスされる場合があります。

+
アップグレード前の健常性チェックが正常に完了すると、アクティブ化が実行されます。アクティブ化にかかる時間は、ストレージアレイの構成とアクティブ化するコンポーネントによって異なります。

. *オプション：*アップグレードされた内容のリストを表示するには、*ログの保存*をクリックします。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `drive_upgrade_log-timestamp.txt`。



.終了後
* ハードウェアページにすべてのコンポーネントが表示されていることを確認します。
* [Software and Firmware Inventory] ダイアログボックスをチェックして、新しいソフトウェアとファームウェアのバージョンを確認します（ [Menu] ： [Upgrade Center] を選択し、 [* Software and Firmware Inventory] のリンクをクリックします）。
* コントローラNVSRAMをアップグレードした場合、既存のNVSRAMに適用したカスタム設定はアクティブ化のプロセスで失われます。アクティブ化のプロセスが完了したら、NVSRAMにカスタム設定を再度適用する必要があります。

