---
permalink: sm-support/autosupport-feature-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, autosupport, ASUP 
summary: AutoSupport機能は、ストレージアレイの健常性を監視し、テクニカルサポートに自動ディスパッチを送信します。 
---
= AutoSupport機能の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport機能は、ストレージアレイの健常性を監視し、テクニカルサポートに自動ディスパッチを送信します。

テクニカルサポートは、AutoSupportデータをリアクティブに使用してお客様の問題の診断と解決を迅速化し、潜在的な問題をプロアクティブに検出して回避します。

AutoSupportデータには、ストレージアレイの構成、ステータス、パフォーマンス、およびシステムイベントに関する情報が含まれます。AutoSupport データにユーザデータが含まれることはありません。ディスパッチはすぐに送信することも、スケジュールに従って送信することもできます（日次および週次）。



== 主なメリット

AutoSupport機能の主なメリットは次のとおりです。

* ケースの解決時間の短縮
* 高度な監視でインシデント管理を迅速化
* スケジュールに基づく自動レポート、および重大イベントに関する自動レポート
* 選択したコンポーネント（ドライブなど）のハードウェア交換要求を自動化
* 問題が発生した場合は、お客様の邪魔にならない方法で通知し、テクニカルサポートが修正措置を講じるための情報を提供します。
* ディスパッチを監視して構成に関する既知の問題を検出するAutoSupport分析ツール




== 個 々 のAutoSupport機能

AutoSupport 機能は、個別に有効にする3つの機能で構成されています。

* *Basic AutoSupport *--ストレージ・アレイが自動的にデータを収集してテクニカル・サポートに送信することを可能にします
* * AutoSupport OnDemand*--問題 のトラブルシューティングに必要なときに、テクニカルサポートが以前のAutoSupport ディスパッチの再送信を要求できるようにします。転送はすべて、AutoSupportサーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupportサーバに定期的にコンタクトし、保留中の再送信要求がないかどうかをチェックし、適切に応答します。
* *リモート診断*--問題 のトラブルシューティングに必要な場合に、テクニカルサポートが最新のAutoSupport ディスパッチをリクエストできるようにします。転送はすべて、AutoSupportサーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupportサーバに定期的にコンタクトし、保留中の新しい要求がないかどうかをチェックし、適切に応答します。




== AutoSupportとサポートデータの収集の違い

ストレージアレイでは、次の2つの方法でサポートデータを収集できます。

* * AutoSupport 機能*--データが自動的に収集されます。
* *サポートデータの収集オプション*--データを収集して手動で送信する必要があります。


データが自動的に収集されて送信されるため、AutoSupport機能の方が簡単です。AutoSupportデータをプロアクティブに使用して、問題を未然に防止できます。AutoSupport機能を使用すると、テクニカルサポートがデータにアクセスできるため、トラブルシューティングにかかる時間が短縮されます。このような理由から、AutoSupport機能を使用することを推奨します。
