---
permalink: sm-support/review-the-possible-software-and-firmware-upgrade-errors.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, software, firmware, upgrade, errors 
summary: エラーは、コントローラソフトウェアのアップグレード中またはドライブファームウェアのアップグレード中に発生する可能性があります。 
---
= 考えられるソフトウェアとファームウェアのアップグレードエラーを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エラーは、コントローラソフトウェアのアップグレード中またはドライブファームウェアのアップグレード中に発生する可能性があります。

[cols="25h,~,~"]
|===
| ファームウェアのダウンロードエラーです | 製品説明 | 推奨される対処方法 


 a| 
割り当て済みドライブで障害が発生
 a| 
ストレージアレイに割り当てられているドライブをアップグレードできませんでした。
 a| 
障害の原因の1つとして、ドライブに適切な署名がないことが考えられます。該当するドライブが認証済みドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。

ドライブを交換する場合は、交換用ドライブの容量が障害が発生したドライブと同じかそれよりも大きいことを確認してください。

障害が発生したドライブの交換は、ストレージアレイでI/Oを受信中に実行できます。



 a| 
統合ホットスペアドライブ
 a| 
ホットスペアとしてマークされたドライブがボリュームグループに使用されている場合は、ファームウェアのアップグレードプロセスが失敗します。
 a| 
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
ボリュームグループに不備がある
 a| 
ボリュームグループに含まれるドライブがバイパスされた、削除された、または応答しない場合、そのドライブは不完全なボリュームグループとみなされます。ボリュームグループが不完全な場合、ファームウェアのアップグレードは実行できません。
 a| 
1つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前にこのエラーを修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
いずれかのボリュームグループで実行中の排他的な処理（バックグラウンドメディア/パリティスキャンを除く）
 a| 
ボリュームで排他的な処理を実行中の場合は、ファームウェアをアップグレードできません。
 a| 
同時に実行できない処理が1つ以上実行中の場合は、その処理が完了してからファームウェアをアップグレードする必要があります。System Managerを使用して処理の進捗状況を監視します。



 a| 
ボリュームが見つからない
 a| 
いずれかのボリュームが見つからない場合は、ファームウェアをアップグレードできません。
 a| 
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
いずれかのコントローラが最適以外の状態です
 a| 
いずれかのコントローラの状態が最適以外の場合は、ファームウェアをアップグレードできません。
 a| 
いずれかのストレージアレイコントローラで対応が必要です。ファームウェアをアップグレードする前に、この状態を修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
SPM Verify Database Controllerチェックが失敗する
 a| 
ストレージパーティションマッピングデータベースが破損しているため、ファームウェアをアップグレードできません。
 a| 
コントローラでストレージパーティションのマッピングデータベースエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
構成データベースの検証（ストレージアレイのコントローラバージョンでサポートされている場合）
 a| 
構成データベースが破損しているため、ファームウェアをアップグレードできません。
 a| 
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
MEL関連チェック
 a| 
イベントログにエラーが含まれているため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に10件を超えるDDE情報イベントまたは重大MELイベントが報告されました
 a| 
10個を超えるDDE情報または重大MELイベントが過去7日以内に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に2つ以上のPage 2C重大MELイベントが報告されました
 a| 
2個を超えるページ2C重大MELイベントが過去7日以内に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に、ドライブチャネルのデグレード重大MELイベントが2つ以上報告されました
 a| 
2つを超えるデグレードドライブチャネルの重大MELイベントが過去7日間に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に4件を超える重要なMELエントリ
 a| 
4個を超える重大イベントログエントリが過去7日間に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
有効な管理IPアドレスが必要です。
 a| 
この処理を実行するには、有効なコントローラIPアドレスが必要です。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
コマンドでは、各コントローラのアクティブな管理IPアドレスを指定する必要があります。
 a| 
この処理には、ストレージアレイに関連付けられている各コントローラのコントローラIPアドレスが必要です。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
未処理のダウンロードファイルタイプが返されました。
 a| 
指定したダウンロードファイルはサポートされていません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
ファームウェアダウンロードのアップロード手順中にエラーが発生しました。
 a| 
コントローラが要求を処理できないため、ファームウェアのダウンロードに失敗しました。ストレージアレイが最適な状態であることを確認してから、処理を再試行してください。
 a| 
ストレージアレイが最適な状態であることを確認したあとにこのエラーが再び発生する場合は、テクニカルサポートに連絡して問題を解決してください。



 a| 
ファームウェアのアクティブ化手順中にエラーが発生しました。
 a| 
コントローラが要求を処理できないため、ファームウェアのアクティブ化に失敗しました。ストレージアレイが最適な状態であることを確認してから、処理を再試行してください。
 a| 
ストレージアレイが最適な状態であることを確認したあとにこのエラーが再び発生する場合は、テクニカルサポートに連絡して問題を解決してください。



 a| 
コントローラ｛0｝のリブートを待機中にタイムアウトしました。
 a| 
リブート後に管理ソフトウェアがコントローラ\{0\}に再接続できません。ストレージアレイへの動作中の接続パスがあることを確認し、正常に完了しなかった場合は処理を再試行してください。
 a| 
ストレージアレイが最適な状態であることを確認したあとにこのエラーが再び発生する場合は、テクニカルサポートに連絡して問題を解決してください。

|===
System ManagerのRecovery Guruを使用して、上記の一部の状態を修正できます。ただし、一部の状況については、テクニカルサポートへの連絡が必要になる場合があります。最新のコントローラファームウェアのダウンロードに関する情報は、ストレージアレイから入手できます。この情報は、ファームウェアのアップグレードとダウンロードを妨げているエラー状態をテクニカルサポートが把握するのに役立ちます。
