---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: ストレージアレイのソフトウェア、およびオプションでIOMファームウェアと不揮発性ランダムアクセスメモリ（NVSRAM）をアップグレードして、最新の機能とバグ修正をすべて適用できます。 
---
= コントローラのソフトウェアとファームウェアのアップグレード
:allow-uri-read: 


[role="lead"]
ストレージアレイのソフトウェア、および必要に応じてIOMファームウェアと不揮発性静的ランダムアクセスメモリ（NVSRAM）をアップグレードして、最新の機能とバグ修正をすべて適用することができます。

.開始する前に
* IOMファームウェアをアップグレードするかどうかを決めます。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、 IOM ファームウェアを SANtricity OS ソフトウェアアップグレードの一部としてアップグレードしない場合や、テクニカルサポートから IOM ファームウェアをダウングレードするよう依頼された場合は（ファームウェアのダウングレードにはコマンドラインインターフェイスを使用する必要があります）、アップグレードを中止することもできます。

* コントローラNVSRAMファイルをアップグレードするかどうかを決めます。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、コントローラのNVSRAMファイルにパッチを適用している場合や、ファイルがカスタムバージョンであり、上書きしたくない場合は、アップグレードしないこともできます。

* OSのアップグレードを今すぐアクティブ化するかあとでアクティブ化するかを決めておきます。
+
あとでアクティブ化する理由は次のとおりです。

+
** *時間帯*--ソフトウェアとファームウェアのアクティブ化には時間がかかることがあるため、I/O負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


* セキュリティ保護されていないドライブまたは内部で保護されたドライブから切り替えて、ドライブセキュリティに外部キー管理サーバ（KMS）を使用するかどうかを確認します。
* ストレージアレイでロールベースアクセス制御を使用するかどうかを確認しておきます。


.タスクの内容
OSソフトウェアファイルのみをアップグレードするか、コントローラNVSRAMファイルのみをアップグレードするか、両方のファイルをアップグレードするかを選択できます。

この処理は、テクニカルサポートから指示があった場合にのみ実行してください。

[CAUTION]
====
* データ損失のリスク、ストレージアレイの損傷のリスク * -- アップグレードの実行中にストレージアレイを変更しないでください。ストレージアレイへの電源を維持します。

====
.手順
. ストレージアレイにコントローラが1台しかない場合やマルチパスドライバがインストールされていない場合は、アプリケーションエラーを回避するためにストレージアレイへのI/Oアクティビティを停止します。ストレージアレイにコントローラが2台あり、マルチパスドライバがインストールされている場合は、I/Oアクティビティを停止する必要はありません。
. メニューを選択します。Support [Upgrade Center]を選択します。
. 新しいファイルをサポートサイトから管理クライアントにダウンロードします。
+
.. ネットアップサポートをクリックして、サポートWebサイトを起動します。
.. サポートWebサイトで、* Downloads *（ダウンロード）タブをクリックし、* Downloads *（ダウンロード）を選択します。
.. EシリーズSANtricity OSコントローラソフトウェア*を選択します。
.. 残りの手順に従います。


+
[NOTE]
====
バージョン8.42以降では、デジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。

====
. この時点でIOMファームウェアをアップグレードしない場合は、* IOMの自動同期を中断*をクリックします。
+
ストレージアレイにコントローラが1台しかない場合、IOMファームウェアはアップグレードされません。

. SANtricity OSソフトウェアアップグレードで、*アップグレードの開始*をクリックします。
+
[Upgrade SANtricity OS Software]ダイアログボックスが表示されます。

. アップグレードプロセスを開始するファイルを1つ以上選択します。
+
.. SANtricity OSソフトウェアファイルを選択するには、「*参照」をクリックし、サポートWebサイトからダウンロードしたOSソフトウェアファイルを選択します。
.. 参照 * をクリックし、サポートサイトからダウンロードした NVSRAM ファイルに移動して、コントローラ NVSRAM ファイルを選択します。コントローラNVSRAMファイルの名前は、のようになります。 `N2800-830000-000.dlp`


+
次のアクションが実行されます。

+
** デフォルトでは、現在のストレージアレイ構成と互換性のあるファイルのみが表示されます。
** アップグレードするファイルを選択すると、ファイルの名前とサイズが表示されます。


. *オプション：*アップグレードするSANtricity OSソフトウェアファイルを選択した場合、*ファイルを今すぐ転送するが、アップグレードしない（後でアップグレードをアクティブ化する）*チェックボックスをオンにして、ファイルをコントローラに転送することができます。
. [ * スタート * ] をクリックし、操作を確定します。
+
アップグレード前の健常性チェックの実行中は処理をキャンセルできますが、転送中またはアクティブ化中はキャンセルできません。

. *オプション：*アップグレードされた内容のリストを表示するには、*ログの保存*をクリックします。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `drive_upgrade_log-timestamp.txt`。



.終了後
* ハードウェアページにすべてのコンポーネントが表示されていることを確認します。
* [Software and Firmware Inventory] ダイアログボックスをチェックして、新しいソフトウェアとファームウェアのバージョンを確認します（ [Menu] ： [Upgrade Center] を選択し、 [* Software and Firmware Inventory] のリンクをクリックします）。
* コントローラNVSRAMをアップグレードした場合、既存のNVSRAMに適用したカスタム設定はアクティブ化のプロセスで失われます。アクティブ化のプロセスが完了したら、NVSRAMにカスタム設定を再度適用する必要があります。

