---
permalink: sm-support/upgrade-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, drive, firmware 
summary: ドライブのファームウェアをアップグレードして、最新の機能とバグ修正をすべて利用できます。 
---
= ドライブファームウェアのアップグレード
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブファームウェアをアップグレードして、最新の機能とバグ修正をすべて適用することができます。

.開始する前に
* ディスクツーディスクバックアップ、（計画的なファームウェアアップグレードの影響を受けないボリュームグループへの）ボリュームコピー、またはリモートミラーを使用してデータをバックアップしておきます。
* ストレージアレイのステータスが「最適」である。
* すべてのドライブのステータスが「最適」である。
* ストレージアレイで設定の変更が実行されていません。
* ドライブのオフラインアップグレードのみが可能な場合は、ドライブに関連付けられているすべてのボリュームへのI/Oアクティビティが停止します。


.手順
. メニューを選択します。Support [Upgrade Center]を選択します。
. サポートサイトから管理クライアントに新しいファイルをダウンロードします。
+
.. Drive Firmware upgrade（ドライブファームウェアのアップグレード）で、*NetApp Support*（ネットアップサポート）をクリック
.. ネットアップサポートWebサイトで、「* Downloads *」タブをクリックします。
.. 「* Disk Drive & Firmware Matrix *」を選択します。
.. 残りの手順に従います。


. ドライブファームウェアのアップグレードで、*アップグレードの開始*をクリックします。
+
ダイアログボックスが表示され、使用中のドライブファームウェアファイルが表示されます。

. サポートサイトからダウンロードしたファイルを展開（解凍）します。
. [* Browse] をクリックし、サポートサイトからダウンロードした新しいドライブファームウェアファイルを選択します。
+
ドライブファームウェアファイルのファイル名は、のようになり `D_HUC101212CSS600_30602291_MS01_2800_0002`、拡張子はに `.dlp`なります。

+
一度に1つずつ、最大4つのドライブファームウェアファイルを選択できます。同じドライブに互換性があるドライブファームウェアファイルが複数ある場合は、ファイル競合エラーが発生します。アップグレードに使用するドライブファームウェアファイルを決定し、もう一方のファイルを削除します。

. 「 * 次へ * 」をクリックします。
+
ドライブの選択*（* Select Drives *）ダイアログボックスが表示され、選択したファイルでアップグレードできるドライブがリストされます。

+
互換性があるドライブのみが表示されます。

+
ドライブに対して選択したファームウェアが、推奨されるファームウェア情報領域に表示されます。ファームウェアを変更する必要がある場合は、 ［ * 戻る ］ をクリックして前のダイアログに戻ります。

. 実行するアップグレードのタイプを選択します。
+
** * オンライン（デフォルト） * - ストレージ・アレイが I/O を処理している間に ' ファームウェア・ダウンロードをサポートできるドライブを表示しますこのアップグレード方式を選択した場合、これらのドライブを使用している関連ボリュームへのI/Oを停止する必要はありません。これらのドライブは、ストレージアレイがドライブへのI/Oを処理している間に一度に1つずつアップグレードされます。
** * オフライン（並行処理） * -- ドライブを使用するすべてのボリュームですべての I/O アクティビティが停止されている間に ' ファームウェアのダウンロードのみをサポートできるドライブを表示しますこのアップグレード方式を選択した場合は、アップグレード対象のドライブを使用するすべてのボリュームでI/Oアクティビティをすべて停止する必要があります。冗長性のないドライブはオフライン処理として処理する必要があります。これには、SSDキャッシュ、RAID 0ボリュームグループ、またはデグレード状態のプールやボリュームグループに関連付けられているドライブが含まれます。通常、オフライン（並行）アップグレードはオンライン（デフォルト）アップグレードよりも高速です。


. テーブルの最初の列で、アップグレードするドライブを選択します。
. [ * スタート * ] をクリックし、操作を確定します。
+
アップグレードを停止する必要がある場合は、 * 停止 * をクリックします。実行中のファームウェアのダウンロードは完了します。開始されていないファームウェアのダウンロードはキャンセルされます。

+
[CAUTION]
====
ドライブファームウェアのアップグレードを停止すると、データが失われたり、ドライブを使用できなくなったりする可能性があります。

====
. *オプション：*アップグレードされた内容のリストを表示するには、*ログの保存*をクリックします。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `drive_upgrade_log-timestamp.txt`。

. 手順のアップグレード中に次のいずれかのエラーが発生した場合は、推奨される対処方法を実行してください。


.エラーと推奨される対処方法
[%collapsible]
====
[cols="40h,~"]
|===
| ファームウェアのダウンロードエラー | 対処方法 


 a| 
割り当て済みドライブで障害が発生
 a| 
障害の原因の1つとして、ドライブに適切な署名がないことが考えられます。該当するドライブが認証済みドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。

ドライブを交換する場合は、交換用ドライブの容量が障害が発生したドライブと同じかそれよりも大きいことを確認してください。

障害が発生したドライブの交換は、ストレージアレイでI/Oを受信中に実行できます。



 a| 
ストレエシアレイノカクニン
 a| 
* 各コントローラにIPアドレスが割り当てられていることを確認します。
* コントローラに接続されているすべてのケーブルが破損していないことを確認します。
* すべてのケーブルがしっかりと接続されていることを確認します。




 a| 
統合ホットスペアドライブ
 a| 
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
ボリュームグループに不備がある
 a| 
1つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前にこのエラーを修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
いずれかのボリュームグループで排他的な処理\（バックグラウンドメディア/パリティスキャン\を除く）を実行中
 a| 
同時に実行できない処理が1つ以上実行中の場合は、その処理が完了してからファームウェアをアップグレードする必要があります。System Managerを使用して処理の進捗状況を監視します。



 a| 
ボリュームが見つからない
 a| 
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
いずれかのコントローラが最適以外の状態です
 a| 
いずれかのストレージアレイコントローラで対応が必要です。ファームウェアをアップグレードする前に、この状態を修正する必要があります。System Managerを起動し、Recovery Guruを使用して問題を解決します。



 a| 
コントローラオブジェクトグラフ間でストレージパーティション情報が一致しません
 a| 
コントローラ上のデータの検証中にエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
SPM Verify Database Controllerチェックが失敗する
 a| 
コントローラでストレージパーティションのマッピングデータベースエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
構成データベースの検証\（ストレージアレイのコントローラバージョンでサポートされている場合\）
 a| 
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
MEL関連チェック
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に10件を超えるDDE情報イベントまたは重大MELイベントが報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に2つ以上のPage 2C重大MELイベントが報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に、ドライブチャネルのデグレード重大MELイベントが2つ以上報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去7日間に4件を超える重要なMELエントリ
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。

|===
====
.終了後
これでドライブファームウェアのアップグレードは完了です。通常の運用を再開することができます。
