---
permalink: sm-support/view-storage-array-profile.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, storage, array, profile 
summary: ストレージアレイプロファイルには、ストレージアレイのすべてのコンポーネントとプロパティの説明が表示されます。 
---
= ストレージアレイプロファイルの表示
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイプロファイルには、ストレージアレイのすべてのコンポーネントとプロパティの説明が表示されます。

.タスクの内容
ストレージアレイプロファイルは、リカバリ時の補助として、またはストレージアレイの現在の構成の概要として使用できます。ストレージアレイプロファイルのコピーを管理クライアントに保存したり、ストレージアレイプロファイルのハードコピーをストレージアレイとともに保管したりできます。構成を変更する場合は、ストレージアレイプロファイルの新しいコピーを作成します。

.手順
. メニューを選択します。Support [サポートセンター]>[サポートリソース]タブ。
. 下にスクロールして「 Launch detailed storage array information 」 * と進み、「 * Storage Array Profile 」を選択します。
+
レポートが画面に表示されます。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| セクション | 製品説明 


 a| 
ストレージアレイ
 a| 
ストレージアレイに対して設定可能なすべてのオプションとシステムの静的オプションが表示されます。これらのオプションには、コントローラ、ドライブシェルフ、ドライブ、ディスクプール、ボリュームグループ、ボリューム、ホットスペアドライブの数、許可されるドライブシェルフ、ドライブ、ソリッドステートディスク（SSD）、ボリュームの最大数、Snapshotグループ、Snapshotイメージ、Snapshotボリューム、整合性グループの数、機能に関する情報、ファームウェアバージョンに関する情報、シャーシのシリアル番号に関する情報、AutoSupportステータスとAutoSupportスキャンスケジュール情報、自動サポートデータ収集とスケジュールの設定（WWID）、ストレージID）が含まれます。



 a| 
ストレージ
 a| 
ストレージアレイ内のすべてのストレージデバイスのリストが表示されます。ストレージアレイの構成によっては、[Storage]セクションに次のサブセクションが表示される場合があります。

** *ディスク・プール*--ストレージ・アレイ内のすべてのディスク・プールのリストを表示します
** *ボリュームグループ*--ストレージアレイ内のすべてのボリュームグループのリストを表示しますボリュームと空き容量は作成順に表示されます。
** * Volumes *--ストレージアレイ内のすべてのボリュームのリストを表示します表示される情報には、ボリューム名、ボリュームステータス、容量、RAIDレベル、ボリュームグループまたはディスクプール、ドライブタイプ、およびその他の詳細があります。
** *見つからないボリューム*--ストレージアレイ内で現在ステータスが不明なすべてのボリュームのリストを表示します表示される情報には、見つからない各ボリュームのWorld Wide Identifier（WWID）があります。




 a| 
コピーサービス
 a| 
ストレージアレイに使用されているすべてのコピーサービスのリストが表示されます。ストレージアレイの構成によっては、[Copy Services]セクションに次のサブセクションが表示される場合があります。

** *ボリュームコピー*--ストレージアレイ内のすべてのコピーペアのリストを表示します表示される情報には、コピーの数、コピーペア名、ステータス、開始タイムスタンプ、およびその他の詳細があります。
** *スナップショット・グループ*--ストレージ・アレイ内のすべてのスナップショット・グループのリストを表示します
** *スナップショット・イメージ*--ストレージ・アレイ内のすべてのスナップショットのリストを表示します
** *スナップショット・ボリューム*--ストレージ・アレイ内のすべてのスナップショット・ボリュームのリストを表示します
** *コンシステンシ・グループ*--ストレージ・アレイ内のすべてのコンシステンシ・グループのリストを表示します
** *メンバーボリューム*--ストレージアレイ内のすべてのコンシステンシグループメンバーボリュームのリストを表示します
** *ミラーグループ*--すべてのミラーボリュームのリストを表示します
** *リザーブ容量*-ストレージアレイ内のすべてのリザーブ容量ボリュームのリストが表示されます




 a| 
ホストの割り当て
 a| 
ストレージアレイ内のホスト割り当てのリストが表示されます。表示される情報には、ボリューム名、論理ユニット番号（LUN）、コントローラID、ホスト名またはホストクラスタ名、およびボリュームステータスがあります。トポロジ定義とホストタイプ定義などの追加情報が表示されます。



 a| 
ハードウェア
 a| 
ストレージアレイ内のすべてのハードウェアのリストが表示されます。ストレージアレイの構成によっては、[ハードウェア]セクションに次のサブセクションが表示される場合があります。

** *コントローラ*--ストレージアレイ内のすべてのコントローラのリストを表示しますコントローラの場所'ステータス'構成が含まれますまた、ドライブチャネル情報、ホストチャネル情報、イーサネットポート情報も含まれます。
** *ドライブ*--ストレージアレイ内のすべてのドライブのリストを表示しますシェルフID、ドロワーID、スロットIDの順にドライブが表示されます。表示される情報には、シェルフID、ドロワーID、スロットID、ステータス、物理容量、メディアタイプ、インターフェイスタイプ、現在のデータ速度、製品ID、および各ドライブのファームウェアバージョンがあります。[ドライブ]セクションには、ドライブチャネル情報、ホットスペアの対象情報、および消耗度情報（SSDドライブの場合のみ）も表示されます。消耗度情報には、使用済み寿命の割合が含まれます。これは、これまでにSSDドライブに書き込まれたデータ量を、ドライブの理論上の合計書き込み制限で割った値です。
** *ドライブチャネル*--ストレージアレイ内のすべてのドライブチャネルの情報を表示します表示される情報には、チャネルステータス、リンクステータス（該当する場合）、ドライブ数、および累積エラー数があります。
** * shelves *--ストレージアレイ内のすべてのシェルフの情報を表示します。表示される情報には、ドライブタイプとシェルフの各コンポーネントのステータス情報があります。シェルフコンポーネントには、バッテリパック、Small Form-factor Pluggable（SFP）トランシーバ、電源/ファンキャニスター、入出力モジュール（IOM）キャニスターなどがあります。ストレージアレイでセキュリティキーが使用されている場合は、[ハードウェア]セクションにセキュリティキー識別子も表示されます。




 a| 
特徴
 a| 
インストールされている機能パックのリストと、ホストまたはホストクラスタあたりのSnapshotグループ、Snapshot（レガシー）、ボリュームの最大許容数が表示されます。[機能]セクションの情報には、ドライブセキュリティ（ストレージアレイでセキュリティが有効になっているか無効になっているか）も含まれます。

|===
====
. ストレージアレイプロファイルを検索するには、検索キーワードを*検索*テキストボックスに入力し、*検索*をクリックします。
+
一致するすべての用語が強調表示されます。すべての結果を一度に 1 つずつスクロールするには、 * 検索 * をクリックします。

. ストレージアレイプロファイルを保存するには、* Save *をクリックします。
+
ブラウザのDownloadsフォルダにという名前でファイルが保存されます `storage-array-profile.txt`。


