---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-the-santricity-os-software.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrading, santricity, os, software 
summary: コントローラのソフトウェアとファームウェアをアップグレードする前に、次の項目を確認しておきます。 
---
= SANtricity OSソフトウェアをアップグレードするときは、どのような点に注意する必要がありますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラのソフトウェアとファームウェアをアップグレードする前に、次の項目を確認しておきます。

* ドキュメントとファイルを読み、 `readme.txt`アップグレードを実行することを決定しておきます。
* IOMファームウェアをアップグレードするかどうかを決めます。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、SANtricity OSコントローラソフトウェアのアップグレードの一環としてIOMファームウェアをアップグレードしない場合や、テクニカルサポートからIOMファームウェアのダウングレードを指示された場合（ファームウェアをダウングレードするにはコマンドラインインターフェイスを使用する必要があります）は、IOMファームウェアをアップグレードしないこともできます。

* コントローラNVSRAMファイルをアップグレードするかどうかを決めます。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、コントローラのNVSRAMファイルにパッチを適用している場合や、ファイルがカスタムバージョンであり、上書きしたくない場合は、アップグレードしないこともできます。

* すぐにアクティブ化するかあとでアクティブ化するかを決めます。
+
あとでアクティブ化する理由は次のとおりです。

+
** *時間帯*--ソフトウェアとファームウェアのアクティブ化には時間がかかることがあるため、I/O負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします




SANtricity OSコントローラソフトウェアのアップグレードに含まれるコンポーネントは次のとおりです。

* *管理ソフトウェア*-- System Managerはストレージ・アレイを管理するソフトウェアです
* * コントローラファームウェア * -- コントローラファームウェアは、ホストとボリューム間の I/O を管理します。
* * コントローラ NVSRAM * -- コントローラ NVSRAM は、コントローラのデフォルト設定を指定するコントローラファイルです。
* * IOM ファームウェア * - I/O モジュール（ IOM ）ファームウェアは、コントローラとドライブシェルフの間の接続を管理します。また、コンポーネントのステータスも監視します。
* * スーパーバイザー・ソフトウェア * -- スーパーバイザー・ソフトウェアは、ソフトウェアが実行されるコントローラ上の仮想マシンです。


アップグレードプロセスの一環として、ホストがコントローラと正しく連携できるように、ホストのマルチパス/フェイルオーバードライバやHBAドライバのアップグレードも必要になる場合があります。

[NOTE]
====
該当するかどうかを確認するには、を参照してください https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool"^]。

====
ストレージアレイにコントローラが1台しかない場合やマルチパスドライバがインストールされていない場合は、アプリケーションエラーを回避するためにストレージアレイへのI/Oアクティビティを停止します。ストレージアレイにコントローラが2台あり、マルチパスドライバがインストールされている場合は、I/Oアクティビティを停止する必要はありません。


CAUTION: アップグレードの実行中はストレージアレイに変更を加えないでください。
