---
permalink: sm-support/what-type-of-data-is-collected-through-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, data, collected, autosupport, ASUP 
summary: AutoSupport機能には、イベントディスパッチ、スケジュールディスパッチ、オンデマンドおよびリモート診断ディスパッチの3つの標準ディスパッチタイプが含まれています。 
---
= AutoSupport機能を使用して収集されるデータの種類を教えてください。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport機能には、イベントディスパッチ、スケジュールディスパッチ、オンデマンドおよびリモート診断ディスパッチの3つの標準ディスパッチタイプが含まれています。

AutoSupport データにユーザデータが含まれることはありません。

* *イベントディスパッチ*
+
テクニカルサポートへのプロアクティブな通知が必要なシステムでイベントが発生すると、AutoSupport機能によってイベントトリガー型ディスパッチが自動的に送信されます。

+
** 管理対象のストレージアレイでサポートイベントが発生したときに送信されます。
** イベント発生時にストレージアレイで発生していた状況の包括的なスナップショットが含まれます。


* *スケジュールディスパッチ*
+
AutoSupport機能は、定期的に複数のディスパッチを自動的に送信します。

+
** *日次ディスパッチ*--ユーザーが設定可能な時間間隔内に毎日1回送信されます最新のシステムイベントログとパフォーマンスデータが含まれます。
** *週次ディスパッチ*--ユーザーが設定可能な時間間隔と日の間に毎週1回送信されます構成とシステムの状態の情報が含まれます。


* * AutoSupport OnDemandおよびRemote Diagnosticsディスパッチ*
+
** * AutoSupport OnDemand*--問題 のトラブルシューティングに必要なときに、テクニカルサポートが以前のAutoSupport ディスパッチの再送信を要求できるようにします。転送はすべて、AutoSupportサーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupportサーバに定期的にコンタクトし、保留中の再送信要求がないかどうかをチェックし、適切に応答します。
** *リモート診断*--問題 のトラブルシューティングに必要な場合に、テクニカルサポートが最新のAutoSupport ディスパッチをリクエストできるようにします。転送はすべて、AutoSupportサーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupportサーバに定期的にコンタクトし、保留中の新しい要求がないかどうかをチェックし、適切に応答します。



