---
permalink: um-certificates/certificate-terminology-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, certificate, terminology 
summary: 証明書管理に関連する用語を次に示します。 
---
= 証明書の用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
証明書管理に関連する用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 製品説明 


 a| 
カリフォルニア州
 a| 
認証局（CA）は、インターネットセキュリティのためにデジタル証明書と呼ばれる電子ドキュメントを発行する信頼されたエンティティです。証明書でWebサイトの所有者を識別することにより、クライアントとサーバの間のセキュアな接続が確立されます。



 a| 
CSR
 a| 
証明書署名要求（CSR）は、申請者から認証局（CA）に送信されるメッセージです。CSRは、CAが証明書を発行するために必要な情報を検証します。



 a| 
証明書
 a| 
証明書はセキュリティ上の目的でサイトの所有者を識別するもので、攻撃者による偽装を防止します。証明書には、サイトの所有者に関する情報と、この情報を証明（署名）する信頼されたエンティティのIDが含まれています。



 a| 
証明書チェーン
 a| 
証明書にセキュリティレイヤを追加するファイルの階層。通常、チェーンには階層の最上位にある1つのルート証明書、1つ以上の中間証明書、およびエンティティを識別するサーバ証明書が含まれます。



 a| 
中間証明書
 a| 
証明書チェーンのルートから1つ以上の中間証明書が分岐します。CAは、保護されたルート証明書とサーバ証明書の間の証明書として機能する、1つ以上の中間証明書を発行します。



 a| 
キーストア
 a| 
キーストアはホスト管理システム上のリポジトリであり、秘密鍵とそれに対応する公開鍵および証明書が格納されています。これらのキーと証明書によって、コントローラなどの独自のエンティティが識別されます。



 a| 
ルート証明書
 a| 
ルート証明書は、証明書チェーンの階層の最上位にあります。この証明書には、他の証明書への署名に使用する秘密鍵が含まれています。ルートは特定のCA組織を識別します。すべてのネットワークデバイスで同じCAを使用する場合、必要なルート証明書は1つだけです。



 a| 
署名済み証明書
 a| 
認証局（CA）によって検証される証明書。このデータファイルには秘密鍵が含まれており、HTTPS接続を介してサーバとクライアントの間でデータが暗号化された形式で送信されるようにします。また、署名済み証明書には、エンティティ（通常、サーバまたはWebサイト）の所有者に関する詳細およびアルファベットと数字で構成されるデジタル署名が含まれています。署名済み証明書は信頼チェーンを使用するため、本番環境で最もよく使用されます。「CA署名証明書」または「管理証明書」とも呼ばれます。



 a| 
自己署名証明書
 a| 
自己署名証明書は、エンティティの所有者によって検証されます。このデータファイルには秘密鍵が含まれており、HTTPS接続を介してサーバとクライアントの間でデータが暗号化された形式で送信されるようにします。また、文字と数字で構成されるデジタル署名も含まれています。自己署名証明書はCA署名証明書と同じ信頼チェーンを使用しないため、テスト環境で最もよく使用されます。「事前にインストールされている」証明書とも呼ばれます。



 a| 
サーバ証明書
 a| 
サーバ証明書は、証明書チェーンの最下位にあります。Webサイトやその他のデバイスなど、特定のエンティティを識別します。ストレージシステムの各コントローラには、個別のサーバ証明書が必要です。



 a| 
信頼ストア
 a| 
信頼ストアは、CAなどの信頼できるサードパーティの証明書を格納するリポジトリです。

|===