---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: すべての新規または更新されるローカルユーザパスワードに必要な最小文字数を設定できます。また、ローカルユーザがパスワードを入力せずにシステムにアクセスできるようにすることもできます。 
---
= ローカルユーザのパスワード設定の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての新規または更新されるローカルユーザパスワードに必要な最小文字数を設定できます。また、ローカルユーザがパスワードを入力せずにシステムにアクセスできるようにすることもできます。

.開始する前に
Root Adminの権限が割り当てられたローカル管理者としてログインする必要があります。

.タスクの内容
ローカルユーザパスワードの最小文字数を設定する際は、次のガイドラインに注意してください。

* 設定を変更しても、既存のローカルユーザパスワードには影響しません。
* ローカルユーザパスワードの最小文字数は0~30文字に設定する必要があります。
* 新しいローカルユーザパスワードは、現在の最小文字数の設定以上にする必要があります。
* ローカルユーザがパスワードを入力せずにシステムにアクセスできるようにする場合は、パスワードの最小文字数を設定しないでください。


.手順
. アクセス管理*を選択します。
. [ローカルユーザー役割*（Local User Roles *）]タブを選択します。
. 「*表示/設定の編集*」を選択します。
+
[ローカルユーザーパスワードの設定]ダイアログボックスが開きます。

. 次のいずれかを実行します。
+
** ローカルユーザがパスワードを入力せずにsystem_に アクセスできるようにするには、「すべてのローカルユーザパスワードを最低必要とする」チェックボックスをオフにします。
** すべてのローカルユーザパスワードに対してパスワードの最小文字数を設定するには、[Require all local user passwords to be at least]チェックボックスをオンにし、スピンボックスですべてのローカルユーザパスワードの最小文字数を設定します。
+
新しいローカルユーザパスワードは現在の設定以上にする必要があります。



. [ 保存（ Save ） ] をクリックします。

