---
permalink: um-certificates/what-do-i-need-to-know-before-configuring-and-enabling-saml.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, configuring, enabling, SAML, 
summary: 認証のためにSecurity Assertion Markup Language（SAML）の機能を設定して有効にする前に、次の要件を満たしていることを確認し、SAMLの制限事項を理解しておきます。 
---
= SAMLを設定して有効にするときは、どのような点に注意する必要がありますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
認証のためにSecurity Assertion Markup Language（SAML）の機能を設定して有効にする前に、次の要件を満たしていることを確認し、SAMLの制限事項を理解しておきます。



== 要件

開始する前に、次のことを確認してください。

* ネットワークにアイデンティティプロバイダ（IdP）を設定しておきます。IdPは、ユーザにクレデンシャルを要求して認証されたユーザかどうかを確認するための外部システムです。IdPの保守はセキュリティチームが行います。
* IdP管理者が、IdPシステムでユーザ属性とユーザグループを設定しておきます。
* IdP管理者が、認証時に名前IDを返す機能がIdPでサポートされていることを確認しておく必要があります。
* IdPサーバとコントローラのクロックが同期されていることを確認しておきます（NTPサーバを使用するかコントローラのクロックの設定を調整します）。
* IdPのメタデータファイルをIdPシステムからダウンロードし、Unified Managerへのアクセスに使用するローカルシステムで使用できるようにしておきます。
* ストレージアレイのコントローラのIPアドレスまたはドメイン名を確認しておきます。




== 制限事項

上記の要件に加えて、次の制限事項を理解していることを確認してください。

* SAMLを有効にすると、ユーザインターフェイスで無効にしたり、IdP設定を編集したりすることはできなくなります。SAMLの設定を無効にしたり編集したりする必要がある場合は、テクニカルサポートにお問い合わせください。最後の設定手順でSAMLを有効にする前に、SSOログインをテストすることを推奨します。（SAMLを有効にする前にSSOログインのテストも実行されます）。
* あとでSAMLを無効にすると、以前の設定（ローカルユーザロールまたはディレクトリサービス）が自動的にリストアされます。
* 現在ユーザ認証用にディレクトリサービスが設定されている場合は、SAMLによって上書きされます。
* SAMLが設定されている場合、次のクライアントはストレージアレイリソースにアクセスできません。
+
** Enterprise Management Window（EMW）
** コマンドラインインターフェイス（CLI）
** ソフトウェア開発キット（SDK）クライアント
** インバンドクライアント
** HTTPベーシック認証REST APIクライアント
** 標準のREST APIエンドポイントを使用したログイン



