---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: SANtricity Unified Managerには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。 
---
= 管理者パスワード保護の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。



== 管理者パスワードとユーザプロファイル

Unified Managerの初回起動時に、管理者パスワードを設定するように求められます。adminパスワードを持つユーザなら誰でも、ストレージアレイの設定を変更できます。

Unified Managerインターフェイスには、管理パスワードに加えて、1つ以上のロールがマッピングされた設定済みのユーザプロファイルが含まれています。詳細については、を参照してください link:../um-certificates/how-access-management-works-unified.html["アクセス管理の仕組み"]。

ユーザとマッピングは変更できません。変更できるのはパスワードのみです。パスワードの変更については、次を参照してください。

* link:change-admin-password-unified.html["管理者パスワードの変更"]
* link:../um-certificates/change-passwords-unified.html["ローカルユーザプロファイルのパスワードの変更"]




== セツシヨンタイムアウト

1つの管理セッションでパスワードの入力を求められるのは1回のみです。デフォルトでは操作がない状態が30分続くとセッションがタイムアウトし、パスワードをもう一度入力する必要があります。セッション中に別の管理クライアントから同じソフトウェアにアクセスしている別のユーザがパスワードを変更した場合は、次回の設定処理や表示処理でパスワードの入力を求められます。

セキュリティ上の理由から、パスワードの入力を試行できるのは5回までとなっており、この回数を超えると、ソフトウェアは「ロックアウト」状態になります。この状態では、ソフトウェアは以降のパスワード試行を拒否します。パスワードを再度入力するには、10分待ってから「通常」の状態にリセットする必要があります。

セッションタイムアウトを調整したり、セッションタイムアウトを完全に無効にしたりできます。詳細については、を参照してください link:manage-session-timeouts-unified.html["セッションタイムアウトの管理"]。
