---
permalink: um-admin/overview-interface-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, interface, GUI 
summary: Unified ManagerはWebベースのインターフェイスであり、1つのビューで複数のストレージアレイを管理することができます。 
---
= Unified Managerインターフェイスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified ManagerはWebベースのインターフェイスであり、1つのビューで複数のストレージアレイを管理することができます。



== メインページ

Unified Managerにログインすると、メインページが開き、* Manage-All *が表示されます。このページでは、ネットワーク内で検出されたストレージアレイのリストをスクロールしてステータスを表示し、単一のアレイまたはアレイのグループに対して処理を実行できます。



== ナビゲーションサイドバー

Unified Managerの機能には、ナビゲーションサイドバーからアクセスできます。

[cols="25h,~"]
|===
| 面積 | 製品説明 


 a| 
管理
 a| 
ネットワーク内のストレージアレイを検出し、アレイのSANtricity System Managerを起動し、1つのアレイから複数のアレイに設定をインポートし、アレイグループを管理します。設定のインポートやアレイグループの作成などの処理を実行するには、アレイ名の横にあるチェックボックスをオンにします。各行の最後にある省略記号は、アレイ名の変更など、単一のアレイに対する操作のインラインメニューを提供します。



 a| 
運用
 a| 
アレイ間での設定のインポートなど、バッチ処理の進捗状況を表示します。

[NOTE]
====
ストレージアレイのステータスが最適でない場合は、一部の処理を実行できません。

====


 a| 
証明書管理
 a| 
ブラウザとクライアントの間で認証する証明書を管理します。



 a| 
アクセス管理
 a| 
Unified Managerインターフェイスのユーザ認証を確立します。



 a| 
サポート
 a| 
テクニカルサポートのオプション、リソース、連絡先を表示します。

|===


== インターフェイスの設定とヘルプ

インターフェイスの右上にあるヘルプやその他のドキュメントにアクセスできます。ログイン名の横にあるドロップダウンから管理オプションにアクセスすることもできます。



== ユーザログインとパスワード

システムにログインしている現在のユーザがインターフェイスの右上に表示されます。

ユーザとパスワードの詳細については、次を参照してください。

* link:administrator-password-protection-unified.html["管理者パスワード保護の設定"]
* link:change-admin-password-unified.html["管理者パスワードの変更"]
* link:../um-certificates/change-passwords-unified.html["ローカルユーザプロファイルのパスワードの変更"]

